<?php
function deportes_perm() {
  return array();
}
function deportes_menu() {
  $items=array();
  return $items;
}
function deportes_get_menu_primary_links($result_in){
  $result=array();
  if(!empty($result_in)){
      foreach($result_in as $id=>$row){
          if(deportes_is_tab_deportes($row)){
              $result[$id]=$row;
          }
      }
  }
  return $result;        
}
function deportes_is_tab_deportes($row){
    if(red_visualizador_is_visualizador_pantalla()){
        return 1;
    }else{    
        $tab_title_in=$row['title'];
        $in_array=array('Monitoring','Bulletins');
        $href_array=array('vigilancia/pendientes','vigilancia/validados','vigilancia/ultimas','alerta_user/inicio');
        foreach($in_array as $i=>$value){
            $konp=strtoupper(t($value));
            $tab_title=strtoupper($tab_title_in);
            if($tab_title==$konp){
                return 1;
            }else if(in_array($row['href'],$href_array)){
                return 1;
            }
        }
    }    
    return 0;
}  