<?php
function deportes_perm() {
  return array();
}
function deportes_menu() {
  $items=array();
  return $items;
}
function deportes_get_menu_primary_links($result_in){
  $result=array();
  if(!empty($result_in)){
      foreach($result_in as $id=>$row){
          if(deportes_is_tab_deportes($row)){
              $result[$id]=$row;
          }
      }
  }
  return $result;        
}
function deportes_is_tab_deportes($row){
    if(deportes_is_menu_deportes()){    
        $tab_title_in=$row['title'];
        $in_array=array('Monitoring','Bulletins');
        $href_array=array('vigilancia/pendientes','vigilancia/validados','vigilancia/ultimas','alerta_user/inicio');
        foreach($in_array as $i=>$value){
            $konp=strtoupper(t($value));
            $tab_title=strtoupper($tab_title_in);
            if($tab_title==$konp){
                return 1;
            }else if(in_array($row['href'],$href_array)){
                return 1;
            }
        }
    }else{
        return 1;
    }    
    return 0;
}
function deportes_is_menu_deportes(){
    if(red_visualizador_is_visualizador_pantalla()){
        return 0;
    }
    if(hontza_canal_rss_is_visualizador_activado()){
        if(hontza_is_user_anonimo()){
            return 0;
        }
    }
    return 1;
}