<?php
function usuario_basico_perm() {
  return array();
}
function usuario_basico_menu() {
  $items=array();
  $items['basico/inicio']=array(
    'title'=>'Home',
    'page callback' => 'usuario_basico_inicio_callback',
    'access callback' => 'usuario_basico_inicio_access',
  );
  return $items;
}
function usuario_basico_is_usuario_basico(){
    global $user;
    if(usuario_basico_is_activado()){
        if(isset($user->roles) && !empty($user->roles)){
           $values=array_values($user->roles);
           if(count($values)==2){
              if(in_array('Basico',$values)){
                  return 1;
              } 
           }
        }
    }
    return 0;
}
function usuario_basico_is_activado(){
    if(defined('_IS_USUARIO_BASICO')){
        if(_IS_USUARIO_BASICO){
            return 1;
        }
    }
    return 0;
}
function usuario_basico_get_usuario_basico_menu_primary_links($links){
    $my_array=array('dashboard','vigilancia/pendientes','alerta_user/inicio');
    $result=array();
    if(!empty($my_array) && !empty($links)){
        foreach($links as $id=>$row){
            if(in_array($row['href'],$my_array)){
                $result[$id]=$row;
                if($row['href']=='dashboard'){
                   $result[$id]['href']='basico/inicio'; 
                }
            }
        }
        return $result;
    }else{
        return $links;
    }
}
function usuario_basico_inicio_callback(){
    $node=usuario_basico_inicio_get_grupo_inicio_node();
    if(isset($node->nid) && !empty($node->nid)){
        drupal_set_title($node->title);
        $output=node_view($node,FALSE,1);
        $output=hontza_canal_rss_unset_node_view_links($output);
        return $output;
    }
    return '';
}
function usuario_basico_inicio_access(){
    if(!hontza_is_user_anonimo()){
        return TRUE;
    }
    return FALSE;
}
function usuario_basico_panel_admin_grupos_get_url_inicio($r){
    $result='';
    $grupo_inicio_row=usuario_basico_get_grupo_inicio_row($r->nid,$r->node_vid);
    if(isset($grupo_inicio_row->id) && !empty($grupo_inicio_row->id)){
        $result='node/'.$grupo_inicio_row->grupo_inicio_nid.'/edit';
    }else{
        $result='node/add/grupo-inicio/'.$r->nid;
    }    
    return $result;
}
function usuario_basico_get_grupo_inicio_row($nid,$vid){
    $res=db_query('SELECT * FROM {usuario_basico_grupo_inicio_texto} WHERE nid=%d AND vid=%d',$nid,$vid);
    while($row=db_fetch_object($res)){
        $node=node_load($row->grupo_inicio_nid);
        if(isset($node->nid) && !empty($node->nid)){
            return $row;
        }    
    }
    $my_result=new stdClass();
    return $my_result;
}
function usuario_basico_grupo_inicio_node_form_alter(&$form,&$form_state,$form_id){
    $nid=hontza_get_nid_by_form($form);
    if(empty($nid)){
        $grupo_inicio_grupo_nid=arg(3);
        $form['grupo_inicio_grupo_nid']=array(
            '#type'=>'hidden',
            '#value'=>$grupo_inicio_grupo_nid,
        );
    }
}
function usuario_basico_on_grupo_inicio_save(&$node,$op){
    if(isset($node->grupo_inicio_grupo_nid) && !empty($node->grupo_inicio_grupo_nid)){
        $grupo=node_load($node->grupo_inicio_grupo_nid);
        if(isset($grupo->nid) && !empty($grupo->nid)){
            $grupo_inicio_row=usuario_basico_get_grupo_inicio_row($grupo->nid,$grupo->vid);
            if(isset($grupo_inicio_row->id) && !empty($grupo_inicio_row->id)){
                //
            }else{
                usuario_basico_delete_usuario_basico_grupo_inicio_texto($grupo->nid);
                db_query('INSERT INTO {usuario_basico_grupo_inicio_texto}(vid,nid,grupo_inicio_nid) VALUES(%d,%d,%d)',$grupo->vid,$grupo->nid,$node->nid);
            }
        }
    }
}
function usuario_basico_inicio_get_grupo_inicio_node(){
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $grupo_inicio_row=usuario_basico_get_grupo_inicio_row($my_grupo->nid,$my_grupo->vid);
        if(isset($grupo_inicio_row->id) && !empty($grupo_inicio_row->id)){
            $result=hontza_node_load_by_lang($grupo_inicio_row->grupo_inicio_nid);
            return $result;
        }
    }
    $my_result=new stdClass();
    return $my_result;
}
function usuario_basico_panel_admin_grupos_get_link_inicio($r,$destination){
    $icono=my_get_icono_action('inicio',t('Home'));
    $url_inicio=usuario_basico_panel_admin_grupos_get_url_inicio($r);
    return l($icono,$url_inicio,array('query'=>$destination,'html'=>true));
}
function usuario_basico_delete_usuario_basico_grupo_inicio_texto($grupo_nid,$grupo_inicio_nid=''){
    if(!empty($grupo_nid)){
        db_query('DELETE FROM {usuario_basico_grupo_inicio_texto} WHERE nid=%d',$grupo_nid);
    }else if(!empty($grupo_inicio_nid)){
        db_query('DELETE FROM {usuario_basico_grupo_inicio_texto} WHERE grupo_inicio_nid=%d',$grupo_inicio_nid);
    }
}
function usuario_basico_on_grupo_inicio_delete(&$node){
    if($node->type=='grupo_inicio'){
        usuario_basico_delete_usuario_basico_grupo_inicio_texto('',$node->nid);
    }
}
function usuario_basico_access_denied(){
    if(usuario_basico_is_usuario_basico()){
        drupal_access_denied();
        exit();
    }
}
function  usuario_basico_is_show_debate_collaboration_idea(){
    if(usuario_basico_is_usuario_basico()){
        return 0;
    }
    return 1;
}