<?php
require_once('facilitador.validados.inc.php');
function facilitador_perm() {
  return array();
}
function facilitador_menu() {
    $items=array();
    $items['facilitador/facilitadores'] = array(
    'title' => 'Experts',
    'page callback' => 'facilitador_facilitadores_callback',
    'access callback'=>'facilitador_admin_access',    
  );
    $items['facilitador/validar/%'] = array(
    'title' => 'Validate',
    'page callback' => 'facilitador_validar_callback',
    'access callback'=>'facilitador_admin_access',    
  );
    $items['facilitador/rechazar/%'] = array(
    'title' => 'Reject',
    'page callback' => 'facilitador_rechazar_callback',
    'access callback'=>'facilitador_admin_access',    
  );
    $items['facilitador/facilitadores_publicados'] = array(
    'title' => 'Experts',
    'page callback' => 'facilitador_validados_facilitadores_publicados_callback',
    'access callback'=>'facilitador_custom_access',    
  );
     $items['facilitador/simulando_convertir_facilitadores'] = array(
    'title' => 'Experts',
    'page callback' => 'facilitador_simulando_convertir_facilitadores_callback',
    'access callback'=>'facilitador_admin_access',    
  );
     $items['facilitador/enviar_peticion_facilitador/%']= array(
    'title' => 'Send',
    'page callback' => 'facilitador_enviar_peticion_facilitador_callback',
    'access callback'=>'facilitador_custom_access',    
  );
      $items['facilitador/tarea']= array(
    'title' => 'Experts',
    'page callback' => 'facilitador_tarea_callback',
    'access arguments'=>array('root'),    
  );
    return $items;
}
function facilitador_is_facilitador_activado(){
    $my_array=array('ROOT');
    if(!empty($my_array)){
        foreach($my_array as $i=>$sareko_id){
            if(hontza_is_sareko_id($sareko_id)){
                return 1;
            }
        }
    }
    if(defined('_IS_FACILITADOR_WITH_USER') && _IS_FACILITADOR_WITH_USER==1){
        return 1;
    }
    return 0;
}
function facilitator_save($form_state_values,$account,$category){
    if($category=='Consultoria_en_gestion_de_la_informacion'){
        $is_facilitator=$form_state_values['is_facilitator'];
        $facilitador_row=facilitador_get_users_facilitators_row($account->uid);
        $servicios_experto=facilitator_get_servicios_experto_form_state($form_state_values);
        $servicios_experto=facilitador_servicios_experto_encode($servicios_experto);
        if(isset($facilitador_row->id) && !empty($facilitador_row->id)){
            $validate=0;
            if($is_facilitator){
                $validate=1;
            }
            $is_facilitator_bakup=facilitador_get_is_facilitador_value($uid);
            facilitador_update($account->uid,$validate,$servicios_experto);
            if($validate){
                if($is_facilitator_bakup==0){
                    facilitador_avisar_admin($account->uid);
                }    
            }
        }else{
            if($is_facilitator){
                facilitador_insert($account->uid,1,$servicios_experto);
                facilitador_avisar_admin($account->uid);
            }
        }
    }
}
function facilitador_get_users_facilitators_row($uid){
    $res=db_query('SELECT * FROM {users_facilitators} WHERE uid=%d ORDER BY id ASC',$uid);
    while($row=db_fetch_object($res)){
        return $row;
    }
    //
    $my_result=new stdClass();
    return $my_result;
}
function facilitador_insert($uid,$value,$servicios_experto=''){
    $timestamp=time();
    if(db_column_exists('users_facilitators','servicios_experto')){
        db_query('INSERT INTO {users_facilitators}(uid,timestamp,validate,servicios_experto) VALUES(%d,%d,%d,"%s")',$uid,$timestamp,$value,$servicios_experto);
    }else{
        db_query('INSERT INTO {users_facilitators}(uid,timestamp,validate) VALUES(%d,%d,%d)',$uid,$timestamp,$value);
    }    
}
function facilitador_update($uid,$value,$servicios_experto=''){
    //validate
    //0=desapuntado
    //1=apuntado
    //2=validado
    if(db_column_exists('users_facilitators','servicios_experto')){
        db_query('UPDATE {users_facilitators} SET validate=%d,servicios_experto="%s" WHERE uid=%d',$value,$servicios_experto,$uid);        
    }else{
        db_query('UPDATE {users_facilitators} SET validate=%d WHERE uid=%d',$value,$uid);    
    }    
}
function facilitador_get_is_facilitador_value($uid){
    $facilitador_row=facilitador_get_users_facilitators_row($uid);
    if(isset($facilitador_row->id) && !empty($facilitador_row->id)){
        return $facilitador_row->validate;
    }
    return 0;
}
function facilitador_facilitadores_callback(){
    $headers=array();
    $headers[0]=t('Expert');
    $headers[1]=t('Services');
    $headers[2]='Motivo de rechazo del facilitador';
    $headers[3]=t('Actions');
    //        
    $where=array();
    $where[]='1';
    $where[]='users_facilitators.validate!=0';
    $sql='SELECT users_facilitators.*
    FROM {users}
    LEFT JOIN {users_facilitators} ON users_facilitators.uid=users.uid
    WHERE '.implode(' AND ',$where).' 
    GROUP BY users.uid     
    ORDER BY users_facilitators.id DESC';
    $res=db_query($sql);        
    $rows=array();
    $kont=0;
    $faktore=50;
    $my_limit=20;
    while ($r = db_fetch_object($res)) {
      $rows[$kont]=array();
      $user_image=hontza_grupos_mi_grupo_get_user_img($r->uid,$faktore);
      $my_user=user_load($r->uid);
      $user_link='';
      if(isset($my_user->uid) && !empty($my_user->uid)){
        $name=facilitador_get_name($my_user);
        $user_link=l($name,'user/'.$r->uid,array('attributes'=>array('target'=>'_blank'),'html'=>true));
      }
      $user_image=$user_link.'<div>'.$user_image.'</div>';
      $rows[$kont][0]=$user_image;
      //$rows[$kont][1]=facilitador_get_services_html($my_user);
      $rows[$kont][1]=facilitador_get_servicios_experto_html($r->servicios_experto);
      $rows[$kont][2]=facilitador_set_resumen($r->description_reject);
      $rows[$kont][3]=array('data'=>facilitador_define_facilitadores_acciones($r),'style'=>'white-space:nowrap;');
      $kont++;
    }
    //
    $rows=my_set_estrategia_pager($rows, $my_limit);    
    if (count($rows)>0) {
        $output .= theme('table',$headers,$rows,array('class'=>'table_facilitador_facilitadores'));
        $output .= theme('pager', NULL, $my_limit);    
    }else {
        $output.= '<div id="first-time">' .t('There are no contents'). '</div>';
    }
    //intelsat-2016
    drupal_set_title(t('Management of Experts'));
    //
    return $output;
}
function facilitador_admin_access(){
    if(red_facilitador_user_access()){
        if(is_super_admin()){
            return TRUE;
        }
    }    
    return FALSE;
}
function facilitador_define_facilitadores_acciones($r){
    $html=array();
    $destination=drupal_get_destination();
    if($r->validate==2){
        //$icono='delete';
        $icono='rechazar_checkbox';
        $html[]=l(my_get_icono_action($icono,t('Reject')),'facilitador/rechazar/'.$r->uid,array('query'=>$destination,'html'=>true));
    }else{
        //$icono='validar_facilitador';
        $icono='validar_checkbox';
        $html[]=l(my_get_icono_action($icono,t('Validate')),'facilitador/validar/'.$r->uid,array('query'=>$destination,'html'=>true));
    }
    return implode('&nbsp;',$html);
}
function facilitador_validar_callback(){
    facilitador_validar(2);    
}
function facilitador_rechazar_callback(){
    //facilitador_validar(1);
    drupal_set_title(t('Reject Facilitator'));
    return drupal_get_form('facilitador_rechazar_form');
}
function facilitador_validar($validate,$uid_in='',$description_reject=''){
    global $user;
    if(empty($uid_in)){
        $uid=arg(2);
    }else{
        $uid=$uid_in;
    }
    $timestamp_validate=time();
    $rejected=0;
    if($validate==1){
        $rejected=1;
    }
    db_query('UPDATE {users_facilitators} SET validate=%d,uid_validate=%d,timestamp_validate=%d,description_reject="%s",rejected=%d WHERE uid=%d',$validate,$user->uid,$timestamp_validate,$description_reject,$rejected,$uid); 
    $url='facilitador/facilitadores';
    if(isset($_REQUEST['destination']) && !empty($_REQUEST['destination'])){
        $url=$_REQUEST['destination'];
    }
    if($validate==2){
        facilitador_avisar_facilitador_validado($uid);
    }else{
        facilitador_avisar_facilitador_rechazado($uid);
    }
    drupal_goto($url);    
}
function facilitador_avisar_admin($uid){
    $my_user=user_load(1);
    $mail_to=$my_user->mail;
    $subject=t('There is an expert asking for validation of his/her profile');
    $url=$base_url.'facilitador/facilitadores';
    $user_url=$base_url.'user/'.$uid;
    $br='<br><br>';
    $message=t('There is an expert asking for validation of his/her profile').$br;     
    $message.=l(t('Expert/facilitator profile'),$user_url,array('absolute'=>TRUE)).$br;    
    $message.=l(t('Experts/Facilitators'),$url,array('absolute'=>TRUE));
    //intelsat-2016
    red_copiar_send_mail($mail_to,$subject,$message,'mimemail','');   
}
function facilitador_add_facilitator_select_js($edit){
    $uid=$edit['uid'];
    $validate=facilitador_get_is_facilitador_value($uid);
    $js='is_facilitador='.$validate.';
    $(document).ready(function()
    {
        if(is_facilitador==0){
            show_facilitador_fieldsets(false);
        }
        $("#edit-is-facilitator").change(function(){
            var is_txeked=$(this).attr("checked");
            if(is_txeked){
                show_facilitador_fieldsets(true);
            }else{
                show_facilitador_fieldsets(false);
            }
        });
        function show_facilitador_fieldsets(visible){
            /*var my_array=new Array("id_Consultoria_en_gestion_de_la_informacion","id_Consultoria_en_innovacion","id_Consultoria_estrategica","id_Optimizacion_tics",
            "id_Servicios");*/
            var my_array=new Array("id_Servicios","id_servicios_experto");
            var field="";
            for (i = 0; i < my_array.length;i++) {
                field=my_array[i];
                if(visible){
                    $("#"+field).css("display","block");
                }else{
                    $("#"+field).css("display","none");
                }
            }
        }
    });';
    drupal_add_js($js,'inline');
}
function facilitador_avisar_facilitador_validado($uid){
    $my_user=user_load($uid);
    $mail_to=$my_user->mail;
    $subject=t('You have been validated as an expert/facilitator');
    $br='<br><br>';
    $message=t('You have been validated as an expert/facilitator').$br;         
    $message.=t('Please go to your profile to continue adding more details').$br;
    $user_url=$base_url.'user/'.$uid;
    $message.=l(t('My profile'),$user_url,array('absolute'=>TRUE));   
    //intelsat-2016
    red_copiar_send_mail($mail_to,$subject,$message,'mimemail','');
}
function facilitador_avisar_facilitador_rechazado($uid){
    $my_user=user_load($uid);
    $mail_to=$my_user->mail;
    $subject=t('You have been rejected as an expert/facilitator');
    $br='<br><br>';    
    $message=t('You have been rejected as an expert/facilitator').$br;         
    $message.=t('Please go to your profile to see the reasons and to add/correct data in order to get the validation').$br;
    $user_url=$base_url.'user/'.$uid;
    $message.=l(t('My profile'),$user_url,array('absolute'=>TRUE));   
    //intelsat-2016
    red_copiar_send_mail($mail_to,$subject,$message,'mimemail','');
}
function facilitador_custom_access(){
    if(red_facilitador_user_access()){
        if(!hontza_is_user_anonimo()){
            return TRUE;
        }
    }
    return FALSE;
}
function facilitador_facilitador_view($account){
    $html=array();
    $faktore=100;
    $user_image=hontza_grupos_mi_grupo_get_user_img($account->uid,$faktore);
    $html[]=$user_image;
    $html[]='<table class="table_node_view" style="clear:both;">';
    $is_facilitador=facilitador_get_is_facilitador_value($account->uid);
    if(is_super_admin()){
        if($is_facilitador){        
            $html[]=facilitador_get_facilitador_tr_view(t('Validate'),facilitador_get_validar_link($account,$is_facilitador));
        }
    }    
    $html[]=facilitador_get_facilitador_tr_view(t('Organisation'),red_crear_usuario_get_empresa_value($row,$account));
    $html[]=facilitador_get_facilitador_tr_view(t('Username'),$account->name);
    $html[]=facilitador_get_facilitador_tr_view(t('Name'),$account->profile_nombre);
    $html[]=facilitador_get_facilitador_tr_view(t('Surname'),$account->profile_apellidos);
    if(!hontza_is_user_anonimo()){
        $html[]=facilitador_get_facilitador_tr_view(t('Email'),$account->mail);
        $html[]=facilitador_get_facilitador_tr_view(t('Status'),red_crear_usuario_get_user_status_label($account));
        $html[]=facilitador_get_facilitador_tr_view(t('Roles'),hontza_get_user_roles_li($account->uid));    
    }
    $html[]=facilitador_get_facilitador_tr_view(t('Language'),red_crear_usuario_get_user_language_label($account));
    if(!hontza_is_user_anonimo()){
        $html[]=facilitador_get_facilitador_tr_view(t('Start page'),red_crear_usuario_get_user_start_page_html($user));        
        $html[]=facilitador_get_facilitador_tr_view(t('Member for'),$account->content['summary']['member_for']['#value']);
    }
    
    //$html[]=facilitador_get_facilitador_tr_view(t('Subscriptions'),'<div class="item-list">'.$account->content['summary']['notifications']['#value'].'</div>');
    $html[]=facilitador_get_facilitador_tr_view(t('Groups'),facilitador_get_user_groups_html($account));
    $html[]=facilitador_get_facilitador_tr_view(t('Facebook URL'),$account->profile_perfil_en_twitter);
    $html[]=facilitador_get_facilitador_tr_view(t('Twitter URL'),$account->profile_perfil_en_linkedln);
    $html[]=facilitador_get_facilitador_tr_view(t('Linkedln URL'),$account->profile_perfil_en_facebook);
    $html[]=facilitador_get_facilitador_tr_view(t('Expert'),facilitador_get_is_facilitador_html($account,$is_facilitador));
    if(!hontza_is_user_anonimo()){
        if($is_facilitador){
            $html[]=facilitador_get_information_management_consultancy_tr_view($account);
            $html[]=facilitador_get_innovation_consultancy_tr_view($account);
            $html[]=facilitador_get_strategic_consultancy_tr_view($account);
            $html[]=facilitador_get_icts_optimisation_tr_view($account);
            $html[]=facilitador_get_services_view($account);
        }
    }
    //intelsat-2015
    /*if(!red_movil_is_activado()){
        $html[]=facilitador_get_facilitador_tr_view('Vcard',l(t('Download vcard'), 'user/' . $account->uid . '/vcard', array('absolute' => FALSE, 'html' => TRUE)));        
    }*/
    $html[]='</table>';
    /*if(hontza_canal_rss_is_vcard_activado()){
        $html[]=red_vcard_view($account);
    }*/
    return implode('',$html);
}
function facilitador_get_facilitador_tr_view($label,$value){
    return canal_usuario_get_canal_usuario_tr_view($label,$value);
}
function facilitador_get_user_groups_html($account){
    $html=array();
    if(isset($account->og_groups)){
        $html[]='<div class="item-list">';
        $html[]='<ul>';
        foreach($account->og_groups as $group_nid=>$row){
            //intelsat-2016
            if(red_facilitador_is_grupo_colaborativo_publico($row['nid'])){
                $url='node/'.$row['nid'];
                //intelsat-2015
                if(red_movil_is_activado()){
                    $url=movil_grupo_get_url_default($row['nid']);
                }
                $grupo_link=l($row['title'],$url);
                if(hontza_is_user_anonimo()){
                    $grupo_link=$row['title'];
                }
                $html[]='<li>'.$grupo_link.'</li>';
            }    
        }
        $html[]='</ul>';
        $html[]='</div>';
    }
    return implode('',$html);
}
function facilitador_get_is_facilitador_html($account,&$validate){
    $validate=facilitador_get_is_facilitador_value($account->uid);
    if($validate==2){
        return t('Yes');
    }else if($validate==1){
        return t('Pending');
    }
    return t('No');
}
function facilitador_get_facilitador_tr_checkbox_view($field,$account,$is_value=0){
    $label=hontza_canal_rss_user_translate_profile_value('','','class="profile-'.$field.'"');
    $value=t('No');
    $result=0;
    if(isset($account->$field) && !empty($account->$field)){
        $value=t('Yes');
        $result=1;
    }
    if($is_value){
        if($result){
            //return '<b>'.$label.'</b>: '.$value;
            return $label;
        }    
    }else{
        return facilitador_get_facilitador_tr_view($label,$value);
    }    
}
function facilitador_get_information_management_consultancy_tr_view($account){
    $html=array();
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_gestion_buscar_fuentes',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_gestion_optimizacion_busquedas',$account,1);
    $html=facilitador_unset_empty_array($html);
    return facilitador_get_facilitador_tr_view(t('Information Management Consultancy'),implode('<br>',$html));
}
function facilitador_get_innovation_consultancy_tr_view($account){
    $html=array();
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_creatividad',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_seleccion_de_ideas',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_construccion',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_evaluacion',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_redaccion',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_busqueda',$account,1);
    $html=facilitador_unset_empty_array($html);
    return facilitador_get_facilitador_tr_view(t('Innovation Consultancy'),implode('<br>',$html));
}
function facilitador_get_strategic_consultancy_tr_view($account){
    $html=array();
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_estrategica_ayuda',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_estrategica_despliegue_estrategico',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_estrategica_despliegue_fcv',$account,1);
    $html=facilitador_unset_empty_array($html);
    return facilitador_get_facilitador_tr_view( t('Strategic Consultancy'),implode('<br>',$html));
}
function facilitador_get_icts_optimisation_tr_view($account){
    $html=array();
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_optimizacion_tics_html_rss',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_optimizacion_tics_adaptacion',$account,1);
    $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_optimizacion_tics_crear_modulo',$account,1);
    $html=facilitador_unset_empty_array($html);
    return facilitador_get_facilitador_tr_view(t('ICTs Optimisation'),implode('<br>',$html));    
}
function facilitador_unset_empty_array($html){
    $result=array();
    if(!empty($html)){
        foreach($html as $i=>$value){
            if(!empty($value)){
                $result[]=$value;
            }
        }
    }
    return $result;
}
function facilitador_get_services_view($account){
    $html=array();
    //$html[]=facilitador_get_facilitador_tr_view(t('Your Consultancy services'),$account->profile_servicios_ofrece,1);
    //$profile_servicios_proveedores_vtic_value=facilitador_get_facilitador_tr_checkbox_view('profile_servicios_proveedores_vtic',$account,0);    
    //$html[]=facilitador_get_facilitador_tr_view(t('Do your company have commercial relations with other CI software providers?'),$profile_servicios_proveedores_vtic_value);
    return implode('',$html);
}
function facilitador_get_services_html($account,$html_in=''){
    $html=array();
    if(!empty($account)){
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_gestion_buscar_fuentes',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_gestion_optimizacion_busquedas',$account,1);
        //
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_creatividad',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_seleccion_de_ideas',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_construccion',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_evaluacion',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_redaccion',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_innovacion_busqueda',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_estrategica_ayuda',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_estrategica_despliegue_estrategico',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_consultoria_estrategica_despliegue_fcv',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_optimizacion_tics_html_rss',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_optimizacion_tics_adaptacion',$account,1);
        $html[]=facilitador_get_facilitador_tr_checkbox_view('profile_optimizacion_tics_crear_modulo',$account,1);
    }else{
        $html=$html_in;
    }
    $html=facilitador_unset_empty_array($html);    
    $num=count($html);
    $max=9;
    if($num>$max){
        $html=array_slice($html,0,$max);
        $html[]='...';
    }
    //
    return implode('<br>',$html);
}
function facilitador_get_validar_link($account,$validate){
    $result='';
    $destination=drupal_get_destination();
    if($validate==2){
        $result=l(my_get_icono_action('delete',t('Reject')),'facilitador/rechazar/'.$account->uid,array('query'=>$destination,'html'=>true));
    }else{
        $result=l(my_get_icono_action('validar_facilitador',t('Validate')),'facilitador/validar/'.$account->uid,array('query'=>$destination,'html'=>true));
    }
    return $result;
}
function facilitador_simulando_convertir_facilitadores_callback(){    
    $facilitador_array=facilitador_get_facilitadores_role_array();
    if(!empty($facilitador_array)){
        foreach($facilitador_array as $i=>$facilitador){
            $uid=$facilitador->uid;
            $timestamp=time();
            $uid_validate=1;
            $timestamp_validate=$timestamp;
            $validate=2;
            $users_facilitators_row=facilitador_get_users_facilitators_row($uid);
            if(!isset($users_facilitators_row->uid) || empty($users_facilitators_row->uid)){
                db_query('INSERT INTO users_facilitators(uid,timestamp,uid_validate,timestamp_validate,validate) VALUES(%d,%d,%d,%d,%d)',$uid,$timestamp,$uid_validate,$timestamp_validate,$validate);        
            }    
        }
    }
}
function facilitador_get_facilitadores_role_array(){
    $result=array();
    $sql='SELECT users.* 
    FROM {users}
    LEFT JOIN {users_roles} ON users.uid=users_roles.uid
    WHERE users_roles.rid=9';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function facilitador_rechazar_form(){
    $form=array();
    $uid=arg(2);
    $form['uid_reject']=array(
        '#type'=>'hidden',
        '#value'=>$uid,
    );
    $form['description_reject']=array(
        '#title'=>'Motivo de rechazo del facilitador',
        '#type'=>'textarea',
    );
    $form['reject_btn']=array(
        '#type'=>'submit',
        '#value'=>t('Reject'),
    );
    $form['return_btn']=array(
        '#value'=>l(t('Cancel'),'facilitador/facilitadores'),
    );
    return $form;
}
function facilitador_rechazar_form_submit($form,&$form_state){
    $uid=$form_state['values']['uid_reject'];
    $description_reject=$form_state['values']['description_reject'];
    facilitador_validar(1,$uid,$description_reject);    
}
function facilitador_user_add_facilitator_tab_fields(&$form,$account, $edit){
        $users_facilitators_row=facilitador_get_users_facilitators_row($account->uid);
        $description_reject='';
        if(isset($users_facilitators_row->rejected) && !empty($users_facilitators_row->rejected)){
            $description_reject=$users_facilitators_row->description_reject;
            $form['facilitator_fieldset']['description_reject_readonly']=array(
            '#title'=>'Motivo de rechazo del facilitador',
            '#type'=>'textarea',
            '#value'=>$description_reject,
            '#attributes' => array('readonly' => 'readonly')
            );
            $form['facilitator_fieldset']['enviar_peticion_facilitador_btn_description']['#value']='<p><i>Una vez corregido el motivo del rechazo, puedes enviar otra vez la petición de faciltador al administrador</i></p>';
            $form['facilitator_fieldset']['enviar_peticion_facilitador_btn']=array(
                '#type'=>'button',
                '#value'=>'Enviar otra vez la petición para ser facilitador',                
            );
            facilitador_user_add_facilitator_tab_fields_add_js($account->uid);
        }
}
function facilitador_user_add_facilitator_tab_fields_add_js($uid){
    $js='$(document).ready(function()
    {
        var enviar_peticion_facilitador_url="'.url('facilitador/enviar_peticion_facilitador/'.$uid).'"
        $("#edit-enviar-peticion-facilitador-btn").click(function(){
            window.location.href=enviar_peticion_facilitador_url;
            return false;
        });        
    });';
    drupal_add_js($js,'inline');
}
function facilitador_enviar_peticion_facilitador_callback(){
    $html=array();
    $uid=arg(2);
    facilitador_avisar_admin($uid);
    $html[]='<p>La peticion para ser facilitador ha sido enviada al administrador</p>';
    $html[]=l(t('Return'),'user/'.$uid.'/edit/Consultoria_en_gestion_de_la_informacion');
    return implode('',$html);
}
function facilitador_set_resumen($result_in,$max=150){
    $result=$result_in;    
    $len=strlen($result_in);
    if($len>$max){
        $result=substr($result_in,0,$max).' ...';
    }
    return $result;
}
function facilitador_get_name($my_user){
    $result=$my_user->name.'<BR>';  
    $result.=$my_user->profile_nombre.' '.$my_user->profile_apellidos;
    return $result;
}
function facilitador_servidor_central_users_facilitators_row_save($u,$u_in){
    if(isset($u_in->users_facilitators_row->id) && !empty($u_in->users_facilitators_row->id)){
        $row=$u_in->users_facilitators_row;
        $row->uid=$u->uid;
        $users_facilitators_row=facilitador_get_users_facilitators_row($u->uid);
        $servicios_experto='';
        if(isset($row->servicios_experto) && !empty($row->servicios_experto)){
            $servicios_experto=$row->servicios_experto;
        }            
        if(!isset($users_facilitators_row->uid) || empty($users_facilitators_row->uid)){
            db_query('INSERT INTO {users_facilitators}(uid,timestamp,uid_validate,timestamp_validate,validate,description_reject,rejected,servicios_experto) VALUES(%d,%d,%d,%d,%d,"%s",%d,"%s")',$row->uid,$row->timestamp,$row->uid_validate,$row->timestamp_validate,$row->validate,$row->description_reject,$row->rejected,$servicios_experto);        
        }else{
            db_query('UPDATE {users_facilitators} SET servicios_experto="%s" WHERE uid=%d',$servicios_experto,$users_facilitators_row->uid);
        }  
    }
}
function facilitador_user_profile_form_alter(&$form,&$form_state,$form_id){
    facilitador_user_profile_unset_form_fields($form);
    $form['servicios_experto_fieldset']=array(
        '#type'=>'fieldset',
        '#title'=>t('Services'),
        '#attributes'=>array('id'=>'id_servicios_experto'),
    );
    $servicios_experto_options=facilitador_get_servicios_experto_network_options();
    //echo print_r($servicios_experto_options,1);exit();
    $servicios_experto=facilitador_get_servicios_experto($form);    
    $form['servicios_experto_fieldset']['servicios_experto']=array(
        '#type'=>'select',
        '#title'=>t('Services'),
        '#options'=>$servicios_experto_options,
        '#multiple'=>TRUE,
        '#size'=>25,
        '#default_value'=>$servicios_experto,
    );
     $form['servicios_experto_fieldset']['servicios_experto_textarea'] = array(
    '#type' => 'textarea',
    '#title' => t('Select other services'),  
    '#rows' => 5,
    '#cols' => 70,
    '#description' => t('Add one or more services. Multiple services should be separated by a comma.'),
  );
  $form['Servicios']['#title']=t('CI software providers');   
  unset($form['Servicios']['profile_servicios_ofrece']);
  unset($form['Servicios']['profile_servicios_documento']);  
  //echo print_r($form,1);exit();   
}
function facilitador_user_profile_unset_form_fields(&$form){
    $unset_array=array('Consultoria_en_innovacion','Consultoria_en_gestion_de_la_informacion','Consultoria_estrategica','Optimizacion_tics');
    if(!empty($unset_array)){
        foreach($unset_array as $i=>$field){
            if(isset($form[$field]) && !empty($form[$field])){
                unset($form[$field]);
            }
        }
    }
}
function facilitador_cron(){
    facilitador_tarea();
}
function facilitador_tarea(){
    facilitador_set_servicios_experto_by_network();
}
function facilitador_tarea_callback(){
    facilitador_tarea();
}
function facilitador_set_servicios_experto_by_network(){
    facilitador_get_servicios_experto_network();
}
function facilitador_get_servicios_experto_network(){
    $servidor_central_url=red_get_servidor_central_url();
    $url=$servidor_central_url.'/red_servidor/facilitador/download_servicios_experto';
    $content=file_get_contents($url);
    variable_set('servicios_experto_network',$content);
}
function facilitador_get_servicios_experto_network_options(){
    $result=array();
    //simulando
    variable_set('servicios_experto_network','');
    $servicios_experto_network=variable_get('servicios_experto_network','');    
    if(empty($servicios_experto_network)){
        facilitador_get_servicios_experto_network();      
        $servicios_experto_network=variable_get('servicios_experto_network','');
    }
    if(!empty($servicios_experto_network)){
        $servicios_experto_network=json_decode($servicios_experto_network);
        $servicios_experto_options=red_compartir_grupo_decrypt_text($servicios_experto_network->servicios_experto_options);
        $servicios_experto_options=base64_decode($servicios_experto_options);
        $result=unserialize($servicios_experto_options);        
    }
    $result=facilitador_unset_traduccion_servicios_experto_options($result);
    return $result;
}
function facilitador_servicios_experto_encode($servicios_experto){
    $result=serialize($servicios_experto);
    $result=base64_encode($result);
    return $result;
}
function facilitador_get_servicios_experto($form){    
    $result=array();
    $uid=$form['_account']['#value']->uid;
    $facilitador_row=facilitador_get_users_facilitators_row($uid);
    if(isset($facilitador_row->id) && !empty($facilitador_row->id)){
        $result=facilitador_get_users_facilitators_servicios_experto_decode($facilitador_row->servicios_experto);       
    }
    return $result;
}
function facilitador_get_servicios_experto_html($servicios_experto){
    $html=array();
    $servicios_experto=facilitador_get_users_facilitators_servicios_experto_decode($servicios_experto);
    if(!empty($servicios_experto)){
        foreach($servicios_experto as $tid=>$value){
            $servicio=taxonomy_get_term($tid);
            if(isset($servicio->tid) && !empty($servicio->tid)){
               //$html[]=t($servicio->name);
               $html[]=$servicio->name; 
            }    
        }
    }
    $result=facilitador_get_services_html('',$html);
    return $result;
}
function facilitador_get_users_facilitators_servicios_experto_decode($servicios_experto){
    $result=base64_decode($servicios_experto);
    $result=unserialize($result);
    return $result;
}
function facilitator_get_servicios_experto_form_state($form_state_values){
    $result=$form_state_values['servicios_experto'];
    $servicios_experto_textarea=$form_state_values['servicios_experto_textarea'];
    facilitador_save_servicios_experto_textarea_network($servicios_experto_textarea);
    $servicios_experto_array=facilitador_get_servicios_experto_network_options();
    /*echo print_r($servicios_experto_array,1);
    exit();*/
    if(!empty($servicios_experto_textarea)){
        $servicios_experto_textarea=explode(',',$servicios_experto_textarea);  
        foreach($servicios_experto_textarea as $i=>$servicio_name){
            $tid=facilitator_get_tid_servicios_experto_textarea($servicio_name,$servicios_experto_array);
            //print $tid.'='.$servicio_name;exit();
            if(!empty($tid)){
                if(isset($result[$tid]) && !empty($result[$tid])){
                    continue;
                }else{
                    $result[$tid]=$tid;
                }
            }
        }
    }    
    /*echo print_r($result,1);
    exit();*/
    return $result;
}
function facilitador_save_servicios_experto_textarea_network($servicios_experto_textarea){
    if(!empty($servicios_experto_textarea)){
        $servidor_central_url=red_get_servidor_central_url();
        $url=$servidor_central_url.'/red_servidor/facilitador/save_servicios_experto';
        $servicios_experto_textarea=explode(',',$servicios_experto_textarea);
        $postdata=array();
        $postdata['servicios_experto_textarea']=red_compartir_grupo_encrypt_text(base64_encode(serialize($servicios_experto_textarea)));
        facilitador_save_servicios_experto_textarea_network_postapi($url,$postdata);
    }
}
function facilitador_save_servicios_experto_textarea_network_postapi($url,$postdata)
{
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_RETURNTRANSFER,TRUE);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_POST, 1);
    curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query( $postdata ) );
    $data=curl_exec($curl);
    //print $data;exit();
    //$result=unserialize(trim($data));
    curl_close($curl);    
    if(isset($result['servicios_experto_options'])){
        return 1;
    }
    return 0;
}
function facilitator_get_tid_servicios_experto_textarea($servicio_name,$servicios_experto_array){
    if(!empty($servicios_experto_array)){
        //echo print_r($servicios_experto_array,1);exit();
        foreach($servicios_experto_array as $tid=>$value){
            $konp=red_facilitador_unset_traduccion($value);
            if($konp==$servicio_name){
                return $tid;
            }
        }
    }
    return '';
}
function facilitador_unset_traduccion_servicios_experto_options($result_in){
    $result=$result_in;
    if(!empty($result)){
        foreach($result as $tid=>$servicio_name){    
            $result[$tid]=red_facilitador_unset_traduccion($servicio_name);
        }    
    }
    return $result;    
}       