<?php
function calendario_perm() {
  return array('View calendar');
}
function calendario_menu() {
  $items=array();
  $items['calendario/next_prev/%'] = array(
    'title' => t('View Customised Bulletin on the web'),
    'page callback' => 'calendario_next_prev_callback',
    'access arguments' => array('View calendar'),
  );
  $items['calendario/dia_tabla/%'] = array(
    'title' => t('Events'),
    'page callback' => 'calendario_dia_tabla_callback',
    'access arguments' => array('View calendar'),
  );
  $items['calendario/year_tabla/%'] = array(
    'title' => t('Events'),
    'page callback' => 'calendario_year_tabla_callback',
    'access arguments' => array('View calendar'),
  );
  return $items;
}
function calendario_get_title(){
  return t('Calendar');  
}
function calendario_get_content(){
    //gemini-2014
    if(!hontza_grupo_shared_active_tabs_access(1)){
        return '';
    }
        $delta=51;
        $help_block='';
        $help_block=calendario_help_popup_block();    
        $html.='<div class="block block-hontza block-odd region-odd clearfix " id="block-hontza-'.$delta.'">';
        //intelsat-2015
        $icono=my_get_icono_action('calendario', t('Calendar'),'calendario').'&nbsp;';
        //
        $html.='<h3 class="title">'.$icono.calendario_get_title().$help_block.'</h3>';
        $html.='<div class="content">';
        $result=calendario_create_html();
        //intelsat-2015
        $url_year=calendario_get_url_year($result['info_botones']['year_link']);
        $html.=$result['output'];
        //intelsat-2015
        $html.=hontza_inicio_view_all($url_year,t('View Annual Calendar'));
        $html.='</div>';
        $html.='</div>';   
        return $html;
    
}
function calendario_get_region(){
  $style='';
  /*if(!hontza_is_sareko_id('ROOT')){
    $style=' style="display:none;width:0%;"';
  }*/  
  $html=array();
  //$html[]='<div id="c_calendario"'.$style.'><div class="page-region">';
  $html[]=calendario_get_content();
  //$html[]="</div></div>";
  return implode("",$html);
}
function calendario_create_html($time_in='',$year_in='',$mes_in='',$is_year_tabla=0){      
//AVISO:::: bergara.module función makeMonthCalendar
    global $language;
    //gemini-2014
    $result=array();
    $result['info_botones']='';
    $result['output']='';
    if(!hontza_grupo_shared_active_tabs_access(1)){
        return $result;
    }
    //
    $columns=7;
    if($is_year_tabla){
        $date=mktime(0,0,0,$mes_in,1,$year_in);
    }else{    
        if(empty($time_in)){
            $date=time();
        }else{
            $date=$time_in;
        }
    }
    $hoy=date('Y-m-d');
    $num_of_days = date('t',$date);
    $current_day = date('j',$date);
    $current_month_in = date('n',$date);
    $current_year = date('Y',$date);
    $start_day = date('w', mktime(0,0,0,$current_month_in,1, $current_year));
    if($start_day>0){
       $start_day=$start_day-1; 
    }else{
       $start_day=6; 
    }
    $is_dashboard=calendario_is_dashboard();
    if($is_dashboard){
        //$is_dashboard=1;
        $is_reto=1;
        $is_response=1;
    }else{
        $is_reto=calendario_is_reto();
        $is_response=calendario_is_response();    
    }
    $events=calendario_get_events($current_month_in,$current_year,$is_dashboard,$is_reto,$is_response);
    //
    $rows = 1;
    $cells = array();
    if($start_day > 0){
        $cells = array_fill(0, $start_day, '&nbsp;');
    }
    
    for($i = 1; $i <= $num_of_days; $i++)	{
      $day_classes = array();
      $day = mktime(0, 0, 0, $current_month_in, $i, $current_year);
      $day_classes[] = 'month' . date('n', $day);

      $w=date('w', $day);
      
      switch($w){
        case 1:
          $day_classes[] = 'astelehen'; 
          $day_classes[] = 'astegun';
          
          break;
        case 2:
          $day_classes[] = 'astearte'; 
          $day_classes[] = 'astegun';
          break;
        case 3:
          $day_classes[] = 'asteazken'; 
          $day_classes[] = 'astegun';
          break;
        case 4:
          $day_classes[] = 'ostegun'; 
          $day_classes[] = 'astegun';
          break;
        case 5;
          $day_classes[] = 'ostiral'; 
          $day_classes[] = 'astegun';
          break;
        case 6: 
          $day_classes[] = 'larunbat'; 
          $day_classes[] = 'asteburu';
          break;
        case 0: 
          $day_classes[] = 'igande'; 
          $day_classes[] = 'asteburu';
          break;
      }

      if($i == $current_day && $current_month_in == date('n')){
				$day_classes[] = 'current-day';
      }
      
      $key = date('Y-m-d', $day);
      
      /*if(isset($this->notes[$key])){
				$day_classes[] = 'oharduna';
      }*/
      /*if(user_access('root')){
          print 'key='.$key.'<BR>';
      }*/
      $cell = array(
          'id' => $key, 
          'class' => $day_classes, 
          'data' => $i,
      );
      if(isset($events[$key]) && isset($legend_items[$events[$key]])){
            //$cell['rel'] = 'tooltip'; 
            //$cell['title'] = $legend_items[$events[$key]]['safe_value'];
            //$cell['class'][] = drupal_html_class($legend_items[$events[$key]]['safe_value']);
      }
      
      // print date('Y-m-d');
      if(isset($events[$key])){
        //$cell['style'] = 'background-color:' . $colors[$events[$key]];
        //$cell['style'] = 'background-color:red';
        $dia_color=calendario_get_dia_color($key);
        if(!empty($dia_color)){
            $cell['style'] = 'background-color:'.$dia_color;
            $cell['data']=calendario_get_dia_link($i,$is_dashboard,$is_reto,$is_response,$key);
        }
      }else if($key==$hoy){
        $cell['style'] = 'background-color:grey';    
      }
      
      $cells[] = $cell;
    }
    
    //echo print_r($cells,1);
    
    $rest = ($columns * $rows) - ($num_of_days + $start_day);
    if($rest > 0){
      $weeks = array_merge($cells, array_fill(0, ($columns * $rows) - ($num_of_days + $start_day), '&nbsp;'));
    }
    $weeks = array_chunk($cells, 7);
    
    $output = '';
    $month_name = date('F', mktime(NULL, NULL, NULL, $current_month_in, 1, NULL));
    $maiatza = array('eu' => 'Maiatza', 'es' => 'Mayo');
    $caption = $month_name == 'May' && isset($maiatza[$language->language]) ? $maiatza[$language->language] : t($month_name);
    $caption=calendario_add_caption_botones($caption,$is_dashboard,$is_reto,$is_response,$key,$is_year_tabla,$info_botones);
    // setlocale(LC_TIME, "{$language->language}_ES");
    // $caption = strftime('%B', mktime(NULL, NULL, NULL, $this->current_month_in, 1, NULL));
    // setlocale(LC_TIME, 'en_EN');
    $headers = array(t('Mon'), t('Tue'), t('Wed'), t('Thu'), t('Fri'), t('Sat'), t('Sun'));
    $output .= theme('table',$headers,$weeks,array('class' => 'hilabete'),$caption);
    //return $output;
    $result=array();
    $result['info_botones']=$info_botones;
    $result['output']=$output;
    
    return $result;
}
function calendario_get_events($current_month_in,$current_year,$is_dashboard,$is_reto,$is_response,$day_in=0){
    $events=array();
    if(empty($day_in)){
        $ultimo=date("d",(mktime(0,0,0,$current_month_in+1,1,$current_year)-1));
        $time_ini=mktime(0,0,0,$current_month_in,1,$current_year);
        $time_end=mktime(23,59,59,$current_month_in,$ultimo,$current_year);    
    }else{
        $time_ini=mktime(0,0,0,$current_month_in,$day_in,$current_year);
        $time_end=mktime(23,59,59,$current_month_in,$day_in,$current_year);        
    }
    //simulando
    //$time_ini=0;    
    //$time_end+=$time_end;
    
    if($is_reto || !$is_response){
        //
        $estrategia_events=calendario_get_estrategia_events($time_ini,$time_end);
        $events=calendario_events_merge($events,$estrategia_events);
        //
        $despliegue_events=calendario_get_despliegue_events($time_ini,$time_end);
        $events=calendario_events_merge($events,$despliegue_events);
        //
        $decision_events=calendario_get_decision_events($time_ini,$time_end);
        $events=calendario_events_merge($events,$decision_events);
        //
        $informacion_events=calendario_get_informacion_events($time_ini,$time_end);
        $events=calendario_events_merge($events,$informacion_events);
    }
    if($is_response || !$is_reto){
        $idea_events=calendario_get_idea_events($time_ini,$time_end);
        $events=calendario_events_merge($events,$idea_events,'plazo_del_reto');
        //
        $oportunidad_events=calendario_get_oportunidad_events($time_ini,$time_end);
        $events=calendario_events_merge($events,$oportunidad_events,'plazo_del_reto');
        //
        $proyecto_events=calendario_get_proyecto_events($time_ini,$time_end);
        $events=calendario_events_merge($events,$proyecto_events,'plazo_del_reto');
    }
    //       
    return $events;
}
function calendario_get_estrategia_events($time_ini,$time_end){
    global $user;
    //AVISO::::copy paste estrategia_list_callback
    $estrategia_events=array();
    $where=array();
    //
    $where[]='n.promote = 1';
    $where[]='n.status = 1';
    $where[]='n.type="estrategia"'; 
    $where[]='e.fecha_cumplimiento>='.$time_ini.' AND e.fecha_cumplimiento<='.$time_end.' AND e.no_control_date!=1';    
    //
    if(is_where_estrategia_por_grupo()){
        $where_grupo=get_where_estrategia_por_grupo("e","estrategia");
        //
        if(!empty($where_grupo)){
            $where[]=$where_grupo;
        }
        $order_by=' ORDER BY n.sticky DESC, n.created ASC';
        //
        $sql='SELECT n.nid, n.sticky, n.created
        FROM {node} n
        LEFT JOIN {estrategia} e ON n.vid=e.vid
        LEFT JOIN {despliegue} d ON e.nid=d.estrategia_nid
        WHERE '.implode(' AND ',$where)." GROUP BY n.nid ".$order_by;
        //
        $res=db_query($sql);
        while($row=db_fetch_object($res)){
          $estrategia_events[]=node_load($row->nid);
        }
    }
    return $estrategia_events;
}
function calendario_simulando_key($node,$key){
    if($node->type=='estrategia'){
        return '2013-11-12';
    }else if($node->type=='despliegue'){
        return '2013-11-15';
    }else if($node->type=='decision'){
        return '2013-11-18';
    }else if($node->type=='idea'){
        return '2013-11-21';
    }else if($node->type=='oportunidad'){
        return '2013-11-25';
    }
    return $key;
}    
function calendario_events_merge($events,$estrategia_events,$field='fecha_cumplimiento'){
    if(!empty($estrategia_events)){
        $result=$events;
        foreach($estrategia_events as $i=>$node){
            if(isset($node->$field) && !empty($node->$field)){
                $fecha=$node->$field;            
                $fecha_array=hontza_convertir_fecha_doble_digito($fecha);
                $key=implode('-',$fecha_array);
                //simulando
                //$key=calendario_simulando_key($node,$key);
                //
                if(!isset($events[$key])){
                    $result[$key]=array();
                    $result[$key]['node_array']=array();
                }
                //
                $result[$key]['node_array'][]=$node;
            }    
        }
        return $result;
    }
    return $events;
}
function calendario_get_despliegue_events($time_ini,$time_end){
  global $user;
  //AVISO::::copy paste despliegue_list_callback
  $result=array();
  $where=array();
  //
  $where[]='n.promote = 1';
  $where[]='n.status = 1';
  $where[]='n.type="despliegue"'; 
  $where[]='d.fecha_cumplimiento>='.$time_ini.' AND d.fecha_cumplimiento<='.$time_end.' AND d.no_control_date!=1';   
  //
  if(is_where_estrategia_por_grupo()){
      $where_grupo=get_where_estrategia_por_grupo("d","despliegue");
      if(!empty($where_grupo)){
          $where[]=$where_grupo;
      }
      $estrategia_nid=my_get_despliegue_estrategia_nid();
      if(!empty($estrategia_nid) && $estrategia_nid!='todas'){
            $where[]='d.estrategia_nid='.$estrategia_nid;
      }
      $order_by=' ORDER BY d.importancia_despliegue ASC,n.sticky DESC, n.created ASC';
      //
      $sql='SELECT n.nid, n.sticky, n.created
      FROM {node} n
      LEFT JOIN {despliegue} d ON n.vid=d.vid
      WHERE '.implode(' AND ',$where)." GROUP BY n.nid ".$order_by;
      $res=db_query($sql);
      while($row=db_fetch_object($res)){
          $result[]=node_load($row->nid);
      }
  }
  return $result;
}
function calendario_get_decision_events($time_ini,$time_end){
global $user;
  //
  $where=array();
  //
  $where[]='n.promote = 1';
  $where[]='n.status = 1';
  $where[]='n.type="decision"';
  $where[]='d.fecha_cumplimiento>='.$time_ini.' AND d.fecha_cumplimiento<='.$time_end.' AND d.no_control_date!=1';  
  //
  $num_rows = FALSE;
  if(is_where_estrategia_por_grupo()){
      $where_grupo=get_where_estrategia_por_grupo("de","decision");
      if(!empty($where_grupo)){
          $where[]=$where_grupo;
      }
      //
      $despliegue_nid=my_get_decision_despliegue_nid();
      if(!empty($despliegue_nid) && $despliegue_nid!='todas'){
            $where[]='d.despliegue_nid='.$despliegue_nid;
      }
      $order_by=' ORDER BY d.valor_decision ASC,n.sticky DESC, n.created ASC';
      //
      $sql='SELECT n.nid, n.sticky, n.created
      FROM {node} n
      LEFT JOIN {decision} d ON n.vid=d.vid
      LEFT JOIN {despliegue} de ON d.despliegue_nid=de.nid
      WHERE '.implode(' AND ',$where)." GROUP BY n.nid ".$order_by;
      $res=db_query($sql);
      while($row=db_fetch_object($res)){
          $result[]=node_load($row->nid);
      }
  }
  return $result;
}
function calendario_get_idea_events($time_ini,$time_end){
  $result=array();
  $where=array();
  //
  $where[]='n.promote = 1';
  $where[]='n.status = 1';
  $where[]='n.type="idea"';
  $where[]='idea.plazo_del_reto>='.$time_ini.' AND idea.plazo_del_reto<='.$time_end; 
  //
  $my_grupo=og_get_group_context();
  if(!empty($my_grupo) && isset($my_grupo->nid) && !empty($my_grupo->nid)){
      $where[]='idea.grupo_nid='.$my_grupo->nid;  
      $order_by=' ORDER BY n.sticky DESC, n.created ASC';
      $sql='SELECT n.nid, n.sticky, n.created
      FROM {node} n
      LEFT JOIN {idea} idea ON n.vid=idea.vid
      WHERE '.implode(' AND ',$where)." GROUP BY n.nid ".$order_by;
      //print $sql;
      $res=db_query($sql);
      while($row=db_fetch_object($res)){
          $result[]=node_load($row->nid);
      }
  }
  //echo print_r($result,1);
  return $result;
}
function calendario_get_oportunidad_events($time_ini,$time_end){
  $result=array();
  $where=array();
  //
  $where[]='n.promote = 1';
  $where[]='n.status = 1';
  $where[]='n.type="oportunidad"';
  $where[]='o.plazo_del_reto>='.$time_ini.' AND o.plazo_del_reto<='.$time_end; 
  //
  $my_grupo=og_get_group_context();
  if(!empty($my_grupo) && isset($my_grupo->nid) && !empty($my_grupo->nid)){
	$where[]='o.grupo_nid='.$my_grupo->nid;
  
      $order_by=' ORDER BY n.sticky DESC, n.created ASC';
      $sql='SELECT n.nid, n.sticky, n.created
      FROM {node} n
      LEFT JOIN {oportunidad} o ON n.vid=o.vid
      WHERE '.implode(' AND ',$where)." GROUP BY n.nid ".$order_by;
      //print $sql;
      $res=db_query($sql);
      while($row=db_fetch_object($res)){
          $result[]=node_load($row->nid);
      }
  }
  //echo print_r($result,1);
  return $result;
}
function calendario_get_proyecto_events($time_ini,$time_end){
  $result=array();
  $where=array();
  //
  $where[]='n.promote = 1';
  $where[]='n.status = 1';
  $where[]='n.type="proyecto"';
  $where[]='p.plazo_del_reto>='.$time_ini.' AND p.plazo_del_reto<='.$time_end; 
  //
  $my_grupo=og_get_group_context();
  if(!empty($my_grupo) && isset($my_grupo->nid) && !empty($my_grupo->nid)){
	$where[]='p.grupo_nid='.$my_grupo->nid;
  
      $order_by=' ORDER BY n.sticky DESC, n.created ASC';
      $sql='SELECT n.nid, n.sticky, n.created
      FROM {node} n
      LEFT JOIN {proyecto} p ON n.vid=p.vid
      WHERE '.implode(' AND ',$where)." GROUP BY n.nid ".$order_by;
      //print $sql;
      $res=db_query($sql);
      while($row=db_fetch_object($res)){
          $result[]=node_load($row->nid);
      }
  }
  //echo print_r($result,1);
  return $result;
}
function calendario_block($op = 'list', $delta = 0, $edit = array()) {
 	switch ($op) {
    	case 'list':
 			$blocks[1500]['info'] = t('Calendar left');
			return $blocks;
			break;
		case 'view':
			$block=calendario_view_block($delta);
   			return $block;
		default:
			break;
	}
}
function calendario_view_block($delta){
	$block=array();
	switch($delta){
		case 1500:
                        if(user_access('View calendar')){
                            //intelsat-2015
                            $title=t('Calendar');
                            $icono=my_get_icono_action('calendario', t('Calendar'),'calendario').'&nbsp;';
                            //
                            $help_block=calendario_help_popup_block();
                            $block['subject'] = $icono.$title.$help_block;
                            $result=calendario_create_html();
                            $block['content'] = $result['output'];
                        }
			break;
		default:
			break;	 
 	}
    return $block;
}
function calendario_is_reto(){
    if(isset($_REQUEST['is_reto'])){
        return $_REQUEST['is_reto'];
    }
    //if(is_estrategia() || is_despliegue() || is_decision() || is_informacion()){
    if(estrategia_is_arbol_estrategico()){
        return 1;
    }
    return 0;
}
function calendario_is_response(){
    if(isset($_REQUEST['is_response'])){
        return $_REQUEST['is_response'];
    }
    //if(is_idea() || is_oportunidad() || is_proyecto()){
    if(idea_is_arbol()){
        return 1;        
    }
    return 0;
}
function calendario_is_show_left(){
    //if(is_estrategia_left() || is_despliegue_left() || is_decision_left() || is_informacion_left()){
    if(estrategia_is_arbol_estrategico()){
        return 1;
    }
    //if(is_idea() || is_oportunidad() || is_proyecto()){
    if(idea_is_arbol()){
        return 1;
    }
    return 0;
}
function calendario_add_caption_botones($caption,$is_dashboard,$is_reto,$is_response,$key,$is_year_tabla,&$info){
    if($is_year_tabla){
        return '<b>'.$caption.'</b>';
    }
    $next_arg=calendario_get_next_arg();
    $next_param=calendario_define_next_param($next_arg);
    $prev_param=calendario_define_next_param($next_arg,1);
    $next_year=calendario_define_next_param($next_arg,0,1);
    $prev_year=calendario_define_next_param($next_arg,1,1);
    //
    $info=array();
    $info['next_param']=$next_param;
    $info['prev_param']=$prev_param;
    $info['next_year']=$next_year;
    $info['prev_year']=$prev_year;    
    //
    $year=calendario_define_next_param($next_arg,0,0,1);
    $current_day = date('j',$date);
    $current_month_in = date('n',$date);    
    $next=l('>','calendario/next_prev/'.$next_param,array('attributes'=>array('id'=>'a_next_month')));
    $prev=l('<','calendario/next_prev/'.$prev_param,array('attributes'=>array('id'=>'a_prev_month')));
    //if(is_dashboard()){
        $next_year=l('>>','calendario/next_prev/'.$next_year,array('attributes'=>array('id'=>'a_next_year')));
        $prev_year=l('<<','calendario/next_prev/'.$prev_year,array('attributes'=>array('id'=>'a_prev_year')));
    /*}else{
        $next_year='';
        $prev_year='';
    }*/
    $year_link=calendario_define_year_link($year,$is_dashboard,$is_reto,$is_response,$key);
    //intelsat-2015
    $info['year_link']=$year_link;
    return $prev_year.$prev.'<b>'.$year_link.' '.$caption.'</b>'.$next.$next_year;
}
function calendario_add_ajax_navegacion(){ 
   if(calendario_in_pantalla_add_ajax_navegacion()){       
   global $base_url;
   $next_arg=calendario_get_next_arg();
   $next_param=calendario_define_next_param($next_arg);
   $prev_param=calendario_define_next_param($next_arg,1);
   $next_year=calendario_define_next_param($next_arg,0,1);
   $prev_year=calendario_define_next_param($next_arg,1,1);
   $year=calendario_define_next_param($next_arg,0,0,1);
   $is_dashboard=is_dashboard();
   $my_grupo=og_get_group_context();
   $purl='';
   if(isset($my_grupo->purl) && !empty($my_grupo->purl)){
       $purl=$my_grupo->purl;
   }
   //    
   $js='$(document).ready(function()
   {
        var next_param="'.$next_param.'";
        var prev_param="'.$prev_param.'";
        var next_year="'.$next_year.'";
        var prev_year="'.$prev_year.'";
        var is_dashboard='.$is_dashboard.';
        var is_reto='.calendario_is_reto().';
        var is_response='.calendario_is_response().';    
        //
            calendario_a_clicks(false,"");
            function call_calendario_next_prev_month_ajax(calendario_next_prev){
             jQuery.ajax({
				//type: "POST",
                                type:"GET",
				url: "'.$base_url.'/'.$purl.'/calendario/next_prev/"+calendario_next_prev+"?my_time="+new Date().getTime(),
				data:{is_dashboard:is_dashboard,is_reto:is_reto,is_response:is_response},
                                dataType:"json",
				success: function(my_result){
                                    if(is_dashboard){
                                        $("#block-hontza-51 .content").html(my_result.calendario_html);
                                        calendario_a_clicks(true,my_result.info_botones);
                                    }else{
                                        $("#block-calendario-1500 .content").html(my_result.calendario_html);
                                        calendario_a_clicks(true,my_result.info_botones);
                                    }
				}
			});
            }
            function calendario_a_clicks(is_info_botones,info_botones){
                if(is_info_botones){
                    next_param=info_botones.next_param;
                    prev_param=info_botones.prev_param;
                    next_year=info_botones.next_year;
                    prev_year=info_botones.prev_year;
                }
                //
                $("#a_next_month").click(function(){
                call_calendario_next_prev_month_ajax(next_param);
                return false;
                });
                $("#a_prev_month").click(function(){
                   call_calendario_next_prev_month_ajax(prev_param);
                   return false;
                });
                $("#a_next_year").click(function(){
                   call_calendario_next_prev_month_ajax(next_year);
                   return false;
                });
                $("#a_prev_year").click(function(){
                   call_calendario_next_prev_month_ajax(prev_year);
                   return false;
                });
            }
   });';
   drupal_add_js($js,'inline');
   }
}
function calendario_next_prev_callback(){
    $next=arg(2);
    $my_array=explode('-',$next);
    $year='';
    $mes='';
    if(count($my_array)>=2){
        if(isset($my_array[0])){
            $year=$my_array[0];
        }
        if(isset($my_array[1])){
            $mes=$my_array[1];
        }
    }
    //
    $time='';
    if(!empty($year) && !empty($mes)){
        $time=mktime(0,0,0,$mes,1,$year);        
    }
    $calendario_html=calendario_create_html($time);
    $result=array();
    $result['calendario_html']=$calendario_html['output'];
    $result['info_botones']=$calendario_html['info_botones'];
    /*print $result['calendario_html'];
    exit();*/
    print json_encode($result);
    exit();
}
function calendario_get_next_arg(){
    if(calendario_is_arg('next_prev')){
        $param2=arg(2);
        return $param2;
    }else{
        $date=time();
        $current_month_in = date('n',$date);
        $current_year = date('Y',$date);
        return $current_year.'-'.$current_month_in;
    }
    return '';
}
function calendario_is_arg($konp){
    $param0=arg(0);
    if($param0=='calendario'){
        $param1=arg(1);
        if(empty($konp)){
            return 1;
        }else if(!empty($param1) && $param1==$konp){
            return 1;
        }
    }
    return 0;
}
function calendario_define_next_param($next_arg,$is_prev=0,$is_year=0,$only_year=0){
    $my_array=explode('-',$next_arg);    
    $year='';
    $mes='';
    if(count($my_array)>=2){
        if(isset($my_array[0])){
            $year=$my_array[0];
        }
        if(isset($my_array[1])){
            $mes=$my_array[1];
        }
    }
    if($only_year){
        return $year;
    }
    if($is_prev){
        if($is_year){
            $year=$year-1;
            $mes=1;
        }else{
            if($mes==1){
                $mes=12;
                $year=$year-1;
            }else{
                $mes=$mes-1;
            }
        }
    }else{
        if($is_year){
            $year=$year+1;
            $mes=1;
        }else{
            if($mes==12){
                $mes=1;
                $year=$year+1;
            }else{
                $mes=$mes+1;
            }
        }    
    }
    return $year.'-'.$mes;
}
function calendario_define_year_link($year,$is_dashboard,$is_reto,$is_response,$key){
    return l($year,'calendario/year_tabla/'.$year,array('query'=>'is_dashboard='.$is_dashboard.'&is_reto='.$is_reto.'&is_response='.$is_response,'attributes'=>array('style'=>'padding:0;')));
}
function calendario_get_dia_color($fecha){
    return estrategia_get_status_fecha_control_color($fecha);
}
function calendario_get_dia_link($dia,$is_dashboard,$is_reto,$is_response,$key){
    $destination='';
    /*if(calendario_is_arg('year_tabla')){
        $dest_url='calendario/year_tabla/'.arg(2);
        $destination='&destination='.$dest_url;
    }*/
    return l($dia,'calendario/dia_tabla/'.$key,array('query'=>'is_dashboard='.$is_dashboard.'&is_reto='.$is_reto.'&is_response='.$is_response.$destination));
}
function calendario_dia_tabla_callback(){
    $output='';
    $date=arg(2);
    drupal_set_title(t('Control Date').': '.$date);
    boletin_report_no_group_selected_denied();
    //
    $events=array();
    $my_array=explode('-',$date);
    if(count($my_array)>=3){
        $current_year=$my_array[0];
        $current_month_in=$my_array[1];
        $day=$my_array[2];
    }
    
    $sort='asc';
    $field='title';
    if(isset($_REQUEST['sort']) && !empty($_REQUEST['sort'])){
        $sort=$_REQUEST['sort'];
    }
    if(isset($_REQUEST['order']) && !empty($_REQUEST['order'])){
        $order=$_REQUEST['order'];
        if($order==t('Title')){
            $field='title';
        }        
    }
    
    $is_dashboard=calendario_is_dashboard();
    $is_reto=calendario_is_reto();
    $is_response=calendario_is_response();
    
    $events=calendario_get_events($current_month_in,$current_year,$is_dashboard,$is_reto,$is_response,$day);
    if(!empty($events) && isset($events[$date]) && isset($events[$date]['node_array'])){
        $node_array=$events[$date]['node_array'];
        $headers=calendario_define_dia_tabla_headers();
        $rows=array();
        $my_limit=100;        
        if(!empty($node_array)){
            foreach($node_array as $i=>$r){
                $rows[$i][0]=calendario_define_event_link($r);
                $rows[$i][1]=calendario_get_status_color($r);
                $rows[$i]['title']=$r->title;
            }
        }
        
        if($field=='title'){
            $rows=array_ordenatu($rows,$field,strtolower($sort),0);
        }
        $rows=hontza_unset_array($rows,array('title')); 
        $rows=my_set_estrategia_pager($rows, $my_limit);
        if (count($rows)>0) {
          $output .= theme('table',$headers,$rows);
          $output .= theme('pager', NULL, $my_limit);
        }else {
            $output.= '<div id="first-time">' .t('There are no events'). '</div>';
        }
    }else {
        $output.= '<div id="first-time">' .t('There are no events'). '</div>';
    }
    $output.=calendario_define_dia_tabla_cancel_link();
    return $output;
}
function calendario_define_dia_tabla_headers(){
    $headers=array();
    $headers[0]=array('data'=>t('Title'),'field'=>'title');
    $headers[1]=t('Status');
    return $headers;
}
function calendario_define_event_link($r){
    return calendario_get_content_type_img($r->type).l($r->title,'node/'.$r->nid);                        
}
function calendario_get_content_type_img($type){
    $result='';
    switch($type){
        case 'estrategia';
            $result=get_estrategia_simbolo_img();
            break;
        case 'despliegue';
            $result=get_despliegue_simbolo_img();
            break;
        case 'decision';
            $result=get_decision_simbolo_img();
            break;
        case 'informacion';
            $result=get_informacion_simbolo_img();
            break;
        case 'idea';
            $result=get_idea_bombilla_img();
            break;
        case 'oportunidad';
            $result=get_oportunidad_simbolo_img();
            break;
        case 'proyecto';
            $result=get_proyecto_simbolo_img();
            break;
        default:
            break;    
    }
    return $result;
}
function calendario_define_dia_tabla_cancel_link(){
    $html=array();
    $url='dashboard';
    if(isset($_REQUEST['is_dashboard']) && !empty($_REQUEST['is_dashboard'])){
        $url='dashboard';
    }else if(calendario_is_reto()){
        $url='estrategias/arbol_estrategico';
    }else if(calendario_is_response()){
        $url='ideas/arbol';
    }
    $html[]='<div>';
    $html[]=l(t('Cancel'),$url);
    $html[]='</div>';
    return implode('',$html);
}
function calendario_get_status_color($r){
    if(in_array($r->type,array('estrategia','despliegue','decision','informacion'))){
        return estrategia_get_status_color($r);
    }else if(in_array($r->type,array('idea','oportunidad','proyecto'))){
        return estrategia_get_status_color($r,'plazo_del_reto');
    }    
    return '';
}
function calendario_is_pantalla(){
    $param0=arg(0);
    if(!empty($param0) && $param0=='calendario'){
        return 1;
    }
    return 0;
}
function calendario_year_tabla_callback(){
    $year=arg(2);
    drupal_set_title(t('Events').': '.$year);
    boletin_report_no_group_selected_denied();
    $months = array();
    for($i = 1; $i<=12; $i++){
      $info_mes=calendario_create_html('',$year,$i,1);  
      $months[]=$info_mes['output'];
    }
    $tres_meses = array_chunk($months, 3);
    $html=array();
    $cancel_div=calendario_define_dia_tabla_cancel_link();
    //$html[]=$cancel_div;
    $html[]=calendario_year_next_prev_div_link();
    $html[]='<table>';
    foreach($tres_meses as $mes_array){
      $html[]='<tr>';  
      foreach($mes_array as $k=>$v){
          $html[]='<td>'.$v.'</td>';
      }
      $html[]='</tr>'; 
    }
    $html[]='</table>';
    $html[]=$cancel_div;
    return implode('',$html);
}
function calendario_is_dashboard(){
    if(isset($_REQUEST['is_dashboard'])){
        return $_REQUEST['is_dashboard'];
    }
    if(is_dashboard()){
        return 1;
    }
    return 0;
}
function calendario_in_pantalla_add_ajax_navegacion(){
    if(is_dashboard() || estrategia_is_arbol_estrategico() || idea_is_arbol()){
        return 1;
    }
    return 0;
}
function calendario_year_next_prev_div_link(){
    $html=array();
    $next_arg=arg(2);
    $next_year=$next_arg+1;
    $prev_year=$next_arg-1;
    $is_dashboard=calendario_is_dashboard();
    $is_reto=calendario_is_reto();
    $is_response=calendario_is_response();
    $query=array('is_dashboard'=>$is_dashboard,'is_reto'=>$is_reto,'is_response'=>$is_response);
    $html[]='<div class="year_next_prev_main_div">';
    $html[]='<div class="year_prev_div">';
    $html[]=l('<<','calendario/year_tabla/'.$prev_year,array('query'=>$query));
    $html[]='</div>';
    $html[]='<div class="year_next_div">';
    $html[]=l('>>','calendario/year_tabla/'.$next_year,array('query'=>$query));
    $html[]='</div>';
    $html[]='</div>';
    return implode('',$html);
}
function calendario_get_informacion_events($time_ini,$time_end){
    $result=array();
    $sql=informacion_define_list_sql(1,$time_ini,$time_end);
    
     $res=db_query($sql);
      while($row=db_fetch_object($res)){
          $result[]=node_load($row->nid);
      }
  
    return $result;
}
function calendario_get_url_year($year_link){
    $find='href="';
    $pos=strpos($year_link,$find);
    if($pos===FALSE){
        return $year_link;
    }
    $s=substr($year_link,$pos+strlen($find));
    $pos2=strpos($s,'"');
    $result=substr($s,0,$pos2);
    $result=hontza_solr_search_prepare_redirect_url($result);
    $result=html_entity_decode($result);        
    return $result;
}
function calendario_help_popup_block(){
    return help_popup_block(468291);
}