; This file was auto-generated by drush_make
core = 6.x

projects[] = "drupal"
; Modules

projects[cck][install_path] = sites/all
projects[cck][version] = 6.x-2.8

projects[chart][install_path] = sites/all
projects[chart][version] = 6.x-1.2

projects[coder][install_path] = sites/all
projects[coder][version] = 6.x-2.0-beta1

projects[comment_upload][install_path] = sites/all
projects[comment_upload][version] = 6.x-1.0-alpha5

projects[community_tags][install_path] = sites/all
projects[community_tags][version] = 6.x-1.0-beta3

projects[content_taxonomy][install_path] = sites/all
projects[content_taxonomy][version] = 6.x-1.0-rc2

projects[context][install_path] = sites/all
projects[context][version] = 6.x-3.0

projects[ctools][install_path] = sites/all
projects[ctools][version] = 6.x-1.7

projects[date][install_path] = sites/all
projects[date][subdir] = date
projects[date][version] = 6.x-2.6

projects[devel][install_path] = sites/all
projects[devel][version] = 6.x-1.22

projects[faq][install_path] = sites/all
projects[faq][version] = 6.x-1.11

projects[features][install_path] = sites/all
projects[features][version] = 6.x-1.0

projects[feeds][install_path] = sites/all
projects[feeds][version] = 6.x-1.0-beta9

projects[filefield][install_path] = sites/all
projects[filefield][version] = 6.x-3.7

projects[fivestar][install_path] = sites/all
projects[fivestar][version] = 6.x-1.19

projects[flag][install_path] = sites/all
projects[flag][version] = 6.x-1.3

projects[imageapi][install_path] = sites/all
projects[imageapi][version] = 6.x-1.8

projects[imagecache][install_path] = sites/all
projects[imagecache][version] = 6.x-2.0-beta10

projects[imagefield][install_path] = sites/all
projects[imagefield][version] = 6.x-3.7

projects[imce][install_path] = sites/all
projects[imce][version] = 6.x-2.0-rc1

projects[imce_wysiwyg][install_path] = sites/all
projects[imce_wysiwyg][version] = 6.x-1.1

projects[job_scheduler][install_path] = sites/all
projects[job_scheduler][version] = 6.x-1.0-beta3


projects[jquery_ui][install_path] =  sites/all
projects[jquery_ui][version] = 6.x-1.3

projects[link][install_path] = sites/all
projects[link][version] = 6.x-2.9

projects[og][install_path] = sites/all
projects[og][version] = 6.x-2.1

projects[og_vocab][install_path] = sites/all
projects[og_vocab][version] = 6.x-1.x-dev

projects[pathauto][install_path] = sites/all
projects[pathauto][version] = 6.x-1.4

projects[purl][install_path] = sites/all
projects[purl][version] = 6.x-1.0-beta13

projects[quant][install_path] = sites/all
projects[quant][version] = 6.x-1.0

projects[spaces][install_path] = sites/all
projects[spaces][version] = 6.x-3.0

projects[stored_views][install_path] = sites/all
projects[stored_views][version] = 6.x-1.0-beta2

projects[strongarm][install_path] = sites/all
projects[strongarm][version] = 6.x-2.0

projects[tagadelic][install_path] = sites/all
projects[tagadelic][version] = 6.x-1.2

projects[tagadelic_views][install_path] = sites/all
projects[tagadelic_views][version] = 6.x-1.2

projects[token][install_path] = sites/all
projects[token][version] = 6.x-1.14

projects[views][install_path] = sites/all
projects[views][version] = 6.x-2.11

projects[views_bulk_operations][install_path] = sites/all
projects[views_bulk_operations][version] = 6.x-1.10-beta3

projects[views_or][install_path] = sites/all
projects[views_or][version] = 6.x-1.x-dev

projects[votingapi][install_path] = sites/all
projects[votingapi][version] = 6.x-2.3

projects[wysiwyg][install_path] = sites/all
projects[wysiwyg][version] = 6.x-2.1

; Themes
projects[sky][install_path] = sites/all
projects[sky][version] = 6.x-3.10
