<?php
require_once('compartir_documentos.usuario.inc.php');
require_once('compartir_documentos.fuente.inc.php');
require_once('compartir_documentos.proyecto.inc.php');
function compartir_documentos_perm() {
  return array();
}
function compartir_documentos_menu() {
  $items=array();
 $items['compartir_documentos/copiar/%/enviar_mail']=array(
    'title'=>'Send',
    'page arguments'=>array('compartir_documentos_copiar_enviar_mail_form'), 
   'page callback'=>'drupal_get_form',
    'access callback'=>'compartir_documentos_custom_access',
  );
  $items['compartir_documentos/importar_documento']=array(
    'title'=>'Import',
    //'page arguments'=>array('compartir_documentos_importar_documento_form'),
    //'page callback'=>'drupal_get_form',
    'page callback'=>'compartir_documentos_importar_documento_callback',
    'access callback'=>'compartir_documentos_import_custom_access',  
  );
  $items['compartir_documentos/download_documento/%']=array(
    'title'=>'Download',
    'page callback'=>'compartir_documentos_download_documento_callback',
    'access callback'=>TRUE,  
  );
  $items['compartir_documentos/simular_tarea']=array(
    'title'=>'Download',
    'page callback'=>'compartir_documentos_simular_tarea_callback',
    'access arguments'=>array('root'),  
  );
  $items['compartir_documentos/update/%']=array(
    'title'=>'Import',
    'page callback'=>'compartir_documentos_update_callback',
    'access callback'=>'compartir_documentos_import_custom_access',  
  );
  $items['compartir_documentos_news/importar_documento_news']=array(
    'title'=>'Import',
    //'page arguments'=>array('compartir_documentos_importar_documento_form'),
    //'page callback'=>'drupal_get_form',
    'page callback'=>'compartir_documentos_importar_documento_callback',  
    'access callback'=>'compartir_documentos_import_custom_access',  
  );
  $items['compartir_documentos_news/copiar_news/%/enviar_mail']=array(
    'title'=>'Send',
    'page arguments'=>array('compartir_documentos_copiar_enviar_mail_form'),
    'page callback'=>'drupal_get_form',
    'access callback'=>'compartir_documentos_custom_access',
  );
  $items['compartir_documentos_usuario/copiar_usuario/%/enviar_mail']=array(
    'title'=>'Send',
    'page arguments'=>array('compartir_documentos_usuario_copiar_usuario_enviar_mail_form'),
    'page callback'=>'drupal_get_form',
    'access callback'=>'compartir_documentos_custom_access',
  );
  $items['compartir_documentos/import_todos_tarea']=array(
    'title'=>'Download',
    'page callback'=>'compartir_documentos_import_todos_tarea_callback',
    'access callback'=>TRUE,  
  );
  $items['compartir_documentos/reset/%']=array(
    'title'=>'Import',
    'page callback'=>'compartir_documentos_reset_callback',
    'access callback'=>'compartir_documentos_import_custom_access',  
  );
  return $items;
}
function compartir_documentos_is_compartir_documentos_activado(){
    //if(is_super_admin()){
        if(defined('_IS_COMPARTIR_DOCUMENTOS') && _IS_COMPARTIR_DOCUMENTOS==1){
            return 1;
        }
    //}
    return 0;
}
function compartir_documentos_copiar_link($node,$is_icono=0){
    $destination=drupal_get_destination();
    $copiar='';
    $title='';
    $icono='';
    compartir_documentos_get_export_info($node->type,$copiar,$title,$compartir_documentos);
    $class='jqm-trigger-compartir_documentos_enviar_mail_'.$node->nid;
    $options=array('query'=>$destination,'attributes'=>array('title'=>$title,'class'=>$class));        
    if($is_icono){
        //$title=compartir_documentos_get_popup_title($node->nid);
        $icono=my_get_icono_action('copiar_nodo',$title);
        $options['html']=true;
    }        
    $result=l($icono,$compartir_documentos.'/'.$copiar.'/'.$node->nid.'/enviar_mail',$options);
    $result.='<div id="excompartir_documentos_enviar_mail_'.$node->nid.'" class="jqmWindow jqmID2000"></div>'; 
    compartir_documentos_enviar_mail_add_js($node->nid);
    return $result;
}
function compartir_documentos_enviar_mail_callback(){
    return drupal_get_form('compartir_documentos_copiar_enviar_mail_form');
}
function compartir_documentos_copiar_enviar_mail_form($form_state,$nid_in='',$my_grupo_nid=''){
    $is_popup=0;
    if(!empty($nid_in)){
        $nid=$nid_in;
        $is_popup=1;
    }else{
        $nid=arg(2);
    }
    //hontza_solr_clear_cache_content($nid,1);
    $node=node_load($nid);
    //print $node->nid.'='.$node->vid;exit();
    $form['nid']=array(
        '#type'=>'hidden',
        '#default_value'=>$nid,
    );
    $form['my_grupo_nid']=array(
        '#type'=>'hidden',
        '#default_value'=>$my_grupo_nid,
    );
    $enviar_mail_message=compartir_documentos_get_enviar_mail_message($node);
    $form['enviar_mail_message']=array(
        '#value'=>$enviar_mail_message,
    );
    $form['email']=array(
        '#type'=>'textfield',
        '#title'=>t('To'),
        //'#required'=>true,
    );
    $form['rss_name']=array(
        '#type'=>'hidden',
        '#default_value'=>compartir_documentos_get_rss_name($node),
    );
    $form['message_text']=array(
        '#type'=>'textarea',
        '#title'=>t('Message'),
        //'#required'=>true,
    );
    if(compartir_documentos_is_node_frecuencia_fields($node)){
        compartir_documentos_add_frecuencia_form_fields($form,$node);
    }
    $form['send_btn']=array(
        '#type'=>'submit',
        '#value'=>t('Send'),
    );
    //$_SESSION['enviar_mail_destination']=request_uri();
    $url_cancel='vigilancia/pendientes';
    if(isset($_REQUEST['destination']) && !empty($_REQUEST['destination'])){
        $url_cancel=$_REQUEST['destination'];
    }
    $url_cancel=compartir_documentos_copiar_on_enviar_mail_drupal_goto($node,$my_grupo_nid,$url_cancel,1);
    //$url_cancel=l(t('Cancel'),$url_cancel);
    $url_cancel=red_copiar_get_cancel_link($url_cancel,0,$is_popup);    
    $form['cancel_btn']['#value']=$url_cancel; 
    compartir_documentos_get_export_info($node->type,$copiar,$export_title,$compartir_documentos);
    drupal_set_title(t($export_title));
    return $form;
}
function compartir_documentos_is_enviar_mail($type=''){
    $param0=arg(0);
    if(!empty($param0) && $param0=='compartir_documentos'){
        $param1=arg(1);
        if(!empty($param1) && $param1=='copiar'){
            $param2=arg(2);
            if(!empty($param2) && is_numeric($param2)){
                $node=node_load($param2);
                if(isset($node->nid) && !empty($node->nid)){
                    if(isset($node->type) && !empty($node->type)){
                        //if($node->type=='wiki'){
                        if(in_array($node->type,array('my_report','wiki','item','noticia','proyecto'))){    
                            $param3=arg(3);
                            if(!empty($param3) && $param3=='enviar_mail'){
                                return 1;
                            }   
                        }
                    }
                }
            }
        }
    }
    return 0;
}
function compartir_documentos_custom_access(){
    global $user;
    if(!hontza_is_red_hoja()){
        return FALSE;
    }
    if(is_super_admin()){
        return TRUE;
    }
    $modo_estrategia=1;
    if(is_administrador_grupo($modo_estrategia)){
        return TRUE;
    }
    if(isset($user->roles[CREADOR]) && isset($user->roles[ADMINISTRADOR_DE_GRUPO])){
        return TRUE;
    }
    return FALSE;
}
function compartir_documentos_copiar_enviar_mail_form_submit($form,&$form_state){
    global $base_url;
    global $user;
    $values=$form_state['values'];
    $nid=$form_state['values']['nid'];
    $node=node_load($nid);
    $mail=$form_state['values']['email'];
    $rss_name=$form_state['values']['rss_name'];
    $my_grupo_nid=$form_state['values']['my_grupo_nid'];
    $message_text=$form_state['values']['message_text'];
    $frecuencia='';
    $hora='';
    if(compartir_documentos_is_node_frecuencia_fields($node)){    
        $frecuencia=$form_state['values']['frecuencia'];
        $hora=str_pad($values['hora_array']['hour'], 2, '0', STR_PAD_LEFT).':'.str_pad($values['hora_array']['minute'], 2, '0', STR_PAD_LEFT);
    }
    $is_shared=1;
    compartir_documentos_update_on_send($rss_name,$frecuencia,$hora,$is_shared,$nid);
    //Al borrar la cache, hay que hacer otra vez node_load 
    //$node=node_load($nid);
    if($node->type=='wiki'){
        $node->field_wiki_frecuencia[0]['value']=$frecuencia;
        $node->field_wiki_frecuencia_hora[0]['value']=$hora;        
    }        
    $rss_url=$base_url.'/compartir_documentos/download_documento/'.$rss_name;
    /*if($node->type=='my_report'){
        $rss_url.='/my_report';
    }*/
    $rss_url.='/'.$node->type;
    $html=$rss_url;
    //print $html;exit();
    $servidor_central_url=red_get_servidor_central_url();
    $is_validar_usuario_network=red_copiar_validar_usuario_mail_network_para_compartir($mail);
    if($is_validar_usuario_network){
        $caducidad=red_copiar_get_caducidad();
        $mail_from=base64_encode($user->mail);
        $compartir_servidor_url=$servidor_central_url.'/compartir_servidor_documentos/'.$node->type.'/'.base64_encode($rss_url).'/'.$caducidad.'/'.$mail_from;
    }else{
        $compartir_servidor_url=$rss_url;
    }    
    //print $compartir_servidor_url;exit();
    //$html=l($compartir_servidor_url,$compartir_servidor_url);
    //$html=l(my_get_icono_action('copiar_nodo'),$compartir_servidor_url,array('html'=>TRUE));
    //$html=my_get_icono_action('copiar_nodo');
    $html=compartir_documentos_get_email_message($mail,$compartir_servidor_url,$node,'',$is_validar_usuario_network,$message_text);
    //print $html;exit();
    red_copiar_send_mail($mail,$node->title,$html,'mimemail','',0);
    //drupal_set_message(t('The message has been sent.'));
    $document_type=red_copiar_get_document_type($node,'document');
    $message_user=red_copiar_get_enviar_mail_message_user($node,$is_validar_usuario_network,$mail);
    drupal_set_message($message_user);
    //print $rss_url;exit();    
    compartir_documentos_copiar_on_enviar_mail_drupal_goto($node,$my_grupo_nid);
}
function compartir_documentos_get_rss_name($node){
    $result=compartir_documentos_get_node_rss_name($node);
    if(empty($result)){
        if($node->type=='user'){
            $id=$node->uid;
        }else{
            $id=$node->nid;
        }
        $result=md5('documento_nid_'.$id.'_'.time());
    }
    return $result;
}
function compartir_documentos_update_on_send($rss_name,$frecuencia,$hora,$is_shared,$nid){
    $node=node_load($nid);
    if($node->type=='wiki'){
        //puede haber versionado
        $content_type_wiki_array=compartir_documentos_get_content_type_wiki_array($nid);
        if(!empty($content_type_wiki_array)){
            foreach($content_type_wiki_array as $i=>$row){
                db_query($sql=sprintf('UPDATE {content_type_wiki} SET field_wiki_rss_name_value="%s",field_wiki_frecuencia_value="%s",field_wiki_frecuencia_hora_value="%s",field_wiki_is_shared_value=%d WHERE nid=%d AND vid=%d',$rss_name,$frecuencia,$hora,$is_shared,$node->nid,$node->vid));
                //print $sql;exit();
                //hontza_solr_clear_cache_content($nid,1);
            }
        }
    }else if($node->type=='my_report'){
        //puede haber versionado
        $content_type_my_report_array=compartir_documentos_get_content_type_my_report_array($nid);
        if(!empty($content_type_my_report_array)){
            foreach($content_type_my_report_array as $i=>$row){
                db_query('UPDATE {content_type_my_report} SET field_report_rss_name_value="%s" WHERE nid=%d AND vid=%d',$rss_name,$node->nid,$node->vid);
            }
        }else{
            db_query('INSERT INTO {content_type_my_report}(vid,nid,field_report_rss_name_value) VALUES(%d,%d,"%s")',$node->vid,$node->nid,$rss_name);
        }
    }else if(in_array($node->type,array('item','noticia'))){
        $content_type_item_array=compartir_documentos_get_content_type_item_array($nid);
        if(!empty($content_type_item_array)){
            foreach($content_type_item_array as $i=>$row){
                //db_query('UPDATE {content_type_item} SET field_item_rss_name_value="%s" WHERE nid=%d AND vid=%d',$rss_name,$node->nid,$node->vid);
                db_query('UPDATE {content_field_item_rss_name} SET field_item_rss_name_value="%s" WHERE nid=%d AND vid=%d',$rss_name,$node->nid,$node->vid);
            }
        }else{
            //db_query('INSERT INTO {content_type_item}(vid,nid,field_item_rss_name_value) VALUES(%d,%d,"%s")',$node->vid,$node->nid,$rss_name);
            db_query('INSERT INTO {content_field_item_rss_name}(vid,nid,field_item_rss_name_value) VALUES(%d,%d,"%s")',$node->vid,$node->nid,$rss_name);            
        }
    }else if($node->type=='estrategia'){
        $content_type_estrategia_array=compartir_documentos_get_content_type_estrategia_array($nid);
        if(!empty($content_type_estrategia_array)){
            foreach($content_type_estrategia_array as $i=>$row){
                db_query('UPDATE {content_type_estrategia} SET field_estrategia_rss_name_value="%s" WHERE nid=%d AND vid=%d',$rss_name,$node->nid,$node->vid);
            }
        }else{
            db_query('INSERT INTO {content_type_estrategia}(vid,nid,field_estrategia_rss_name_value) VALUES(%d,%d,"%s")',$node->vid,$node->nid,$rss_name);
        }
    }else if($node->type=='supercanal'){
        compartir_documentos_fuente_supercanal_update_on_send($rss_name,$frecuencia,$hora,$is_shared,$node);
    }else if($node->type=='proyecto'){
        compartir_documentos_proyecto_update_on_send($rss_name,$frecuencia,$hora,$is_shared,$node);
    }
    hontza_solr_clear_cache_content($nid,1);    
}
function compartir_documentos_get_content_type_wiki_array($nid,$field_wiki_rss_name_value=''){
    $result=array();
    if(!empty($nid)){
        $res=db_query('SELECT * FROM {content_type_wiki} WHERE nid=%d',$nid);
    }else if(!empty($field_wiki_rss_name_value)){
        $res=db_query('SELECT * FROM {content_type_wiki} WHERE field_wiki_rss_name_value="%s" ORDER BY vid DESC',$field_wiki_rss_name_value);
    }else{
        return $result;
    }
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function compartir_documentos_get_importar_wiki_link(){
    return l(t('Import Wiki'),'compartir_documentos/importar_documento');
}
function compartir_documentos_importar_documento_form(){
    $form=array();
    boletin_report_no_group_selected_denied();
    compartir_documentos_is_conectado_red_access_denied();    
    $type=arg(2);
    $title=t('Import Wiki');
    if($type=='my_report'){
        $title=t('Import Report');
    }else if(in_array($type,array('item','noticia'))){
        $title=t('Import News');
    }else if($type=='proyecto'){
        $title=t('Import Project');
    }
    drupal_set_title($title);
    boletin_report_no_group_selected_denied(); 
    $form['documento_type']=array(
        '#type'=>'hidden',
        '#default_value'=>$type,
    );
    $mail_from=arg(4);
    $form['mail_from']=array(
        '#type'=>'hidden',
        '#default_value'=>$mail_from,
    );
    $rss_url=compartir_documentos_get_rss_url_by_arg(arg(3));
    $form['rss_url']=array(
        '#type'=>'textfield',
        '#title'=>t('Url'),
        '#required'=>TRUE,
        '#default_value'=>$rss_url,
    );
    $form['import_btn']=array(
        '#type'=>'submit',
        '#value'=>t('Import'),
    );
    return $form;
}
function compartir_documentos_download_documento_callback(){
    $type=arg(3);
    if($type=='user'){
        compartir_documentos_usuario_download_documento();
    }else{
        $node=compartir_documentos_get_node_download($type);
        //echo print_r($node,1);exit();
        //simulando
        //$node=node_load(140825);
        if(isset($node->nid) && !empty($node->nid)){
            unset($node->nid);
            unset($node->vid);
            unset($node->uid);
            unset($node->og_groups);
            unset($node->og_groups_both);
            unset($node->name);
            unset($node->taxonomy);
            unset($node->path);
            //echo print_r($node,1);exit();
            $result=array();
            $result['node']=compartir_documentos_encrypt_text(base64_encode(serialize($node)));
            $result=json_encode($result);
            print $result;
            exit();
        }
    }    
}
function compartir_documentos_encrypt_text($value) {
   if(!$value ) return false;
 
   $crypttext = mcrypt_encrypt(MCRYPT_RIJNDAEL_256,compartir_documentos_define_encrypt_key1(), $value, MCRYPT_MODE_ECB,compartir_documentos_define_encrypt_key2());
   return trim(base64_encode($crypttext));
}
function compartir_documentos_define_encrypt_key1(){
    $result=md5('kfshsdkhdsfhsdfkl vckviucvovciobvihsjkdfhdjkdjfhdfjdfhdfjf');
    return $result;
}
function compartir_documentos_define_encrypt_key2(){
    return md5(date('Y-m-d'));
}
function compartir_documentos_decrypt_text($value) {
   if(!$value ) return false;
 
   $crypttext = base64_decode($value);
   $decrypttext = mcrypt_decrypt(MCRYPT_RIJNDAEL_256,compartir_documentos_define_encrypt_key1(), $crypttext, MCRYPT_MODE_ECB, compartir_documentos_define_encrypt_key2() );
   return trim($decrypttext);
}
function compartir_documentos_importar_documento_form_submit($form,&$form_state){
   /*if(compartir_documentos_existe_documento_grupo($form_state['values']['rss_url'])){
       print 'existe';exit();
   }else{*/ 
    $node=compartir_documentos_importar_documento_file_get_contents($form_state['values']['rss_url'],0,1);
   //}
   //$url='area-trabajo';
   if($node->type=='user' || (isset($node->name) && isset($node->mail))){
    $url='user/'.$node->uid;
    $node_title=$node->name;
    if(!isset($node->type)){
        $node->type='user';
    }
   }else{ 
    $url='node/'.$node->nid;
    $node_title=$node->title;
   }
   if($node->type=='estrategia'){
       $url='estrategias/arbol_estrategico';
   }
   drupal_set_message(t('%node_title has been imported successfully',array('%node_title'=>$node_title)));
   compartir_documentos_importar_enviar_mail_from($form_state['values']['mail_from'],$node_title,$node);
   drupal_goto($url);
}
function compartir_documentos_importar_documento_file_get_contents($rss_url,$is_save_today=0,$is_new=0,$nid_in=''){
   $content=file_get_contents($rss_url);
   //print $rss_url;exit();
   //compartir_documentos_encrypt_text(base64_encode(serialize($node)));
   $content=json_decode($content);
   $node=unserialize(base64_decode(compartir_documentos_decrypt_text($content->node)));
   //$local_node=compartir_documentos_importar_get_local_node($node,$rss_url);
   if($node->type=='estrategia'){
       return compartir_documentos_importar_estrategia($node);
   }else if($node->type=='user'){
       $my_user=$node;
       return compartir_documentos_usuario_importar($my_user);
   }
   $local_node='';
   if(!empty($nid_in)){
       $local_node=node_load($nid_in);
   }
   $frecuencia='';
   $frecuencia_hora='';
   $import_frecuencia='';
   $import_frecuencia_hora='';
   $is_shared=0;
   $rss_name='';
   if(isset($local_node->nid) && !empty($local_node->nid)){
       /*
       //intelsat-2016
       if(empty($node)){
           return;
       }*/
       $node->nid=$local_node->nid;
       $node->vid=$local_node->vid;
       $rss_name=$local_node->field_wiki_rss_name[0]['value'];
       $is_shared=$local_node->field_wiki_is_shared[0]['value'];
       $frecuencia=$local_node->field_wiki_frecuencia[0]['value'];
       $frecuencia_hora=$local_node->field_wiki_frecuencia_hora[0]['value'];       
       $import_frecuencia=$local_node->field_wiki_import_frecuencia[0]['value'];
       $import_frecuencia_hora=$local_node->field_wiki_import_frecuenci_hora[0]['value'];
       $node->created=$local_node->created;
       $node->changed=$local_node->changed;
       $node->og_groups=$local_node->og_groups;
       $node->og_groups_both=$local_node->og_groups_both;
       $node->uid=$local_node->uid;
   }else{
       unset($node->created);
       unset($node->changed);
   }
   compartir_documentos_add_field_is_imported($node);
   if($node->type=='wiki'){
    $node->field_wiki_import_rss_url[0]['value']=$rss_url;    
    if(isset($local_node->nid) && !empty($local_node->nid)){
        $node->field_wiki_rss_name[0]['value']=$rss_name;
        $node->field_wiki_is_shared[0]['value']=$is_shared;
        $node->field_wiki_frecuencia[0]['value']=$frecuencia;
        $node->field_wiki_frecuencia_hora[0]['value']=$frecuencia_hora; 
        $node->field_wiki_import_frecuencia[0]['value']=$import_frecuencia;
        $node->field_wiki_import_frecuenci_hora[0]['value']=$import_frecuencia_hora;
    }else{
        $node->field_wiki_rss_name[0]['value']='';    
        $node->field_wiki_is_shared[0]['value']=0;    
        $node->field_wiki_import_frecuencia[0]['value']=$node->field_wiki_frecuencia[0]['value'];
        $node->field_wiki_import_frecuenci_hora[0]['value']=$node->field_wiki_frecuencia_hora[0]['value'];
        $node->field_wiki_frecuencia[0]['value']='';
        $node->field_wiki_frecuencia_hora[0]['value']='';        
    }
    $node->field_wiki_import_links[0]['value']=base64_encode(serialize($node->compartir_documentos_enlaces));
   }else if(in_array($node->type,array('item','noticia'))){
    compartir_documentos_import_convert_noticia($node);
   }
   node_save($node);
   if($node->type=='wiki'){
    if($is_save_today){
        compartir_documentos_import_wiki_today_save($node);
    }
   } 
   return $node;
}
function compartir_documentos_get_node_download($type){
    $node=new stdClass();
    if($type=='my_report'){
        $field_report_rss_name_value=arg(2);    
        $content_type_my_report_array=compartir_documentos_get_content_type_my_report_array('',$field_report_rss_name_value);
        if(isset($content_type_my_report_array[0])){
            $row=$content_type_my_report_array[0];
            $node=node_load($row->nid);
        }
    }else if(in_array($type,array('item','noticia'))){    
        $field_item_rss_name_value=arg(2);    
        $content_type_item_array=compartir_documentos_get_content_type_item_array('',$field_item_rss_name_value);
        if(isset($content_type_item_array[0])){
            $row=$content_type_item_array[0];
            $node=node_load($row->nid);
        }
    }else if($type=='estrategia'){    
        $field_estrategia_rss_name_value=arg(2);    
        $content_type_estrategia_array=compartir_documentos_get_content_type_estrategia_array('',$field_estrategia_rss_name_value);
        if(isset($content_type_estrategia_array[0])){
            $row=$content_type_estrategia_array[0];
            $node=node_load($row->nid);
            $node->estrategia_tabla_csv=compartir_documentos_get_estrategia_tabla_csv($row->nid);
            /*echo print_r($node->estrategia_tabla_csv,1);
            exit();*/
        }
    }else if($type=='supercanal'){ 
        $node=compartir_documentos_fuente_supercanal_get_node_download($type);
    }else if($type=='proyecto'){
        $node=compartir_documentos_proyecto_get_node_download($type);
    }else{
        $field_wiki_rss_name_value=arg(2);    
        $content_type_wiki_array=compartir_documentos_get_content_type_wiki_array('',$field_wiki_rss_name_value);
        if(isset($content_type_wiki_array[0])){
            $row=$content_type_wiki_array[0];
            $node=node_load($row->nid);
        }
        if($node->type=='wiki'){
            $node->compartir_documentos_enlaces=compartir_documentos_get_wiki_enlaces_array($node);
        }
    }
    /*echo print_r($node,1);
    exit();*/
    return $node;
}
function compartir_documentos_get_content_type_my_report_array($nid,$field_report_rss_name_value=''){
    $result=array();
    if(!empty($nid)){
        $res=db_query('SELECT * FROM {content_type_my_report} WHERE nid=%d',$nid);
    }else if(!empty($field_report_rss_name_value)){
        $res=db_query('SELECT * FROM {content_type_my_report} WHERE field_report_rss_name_value="%s" ORDER BY vid DESC',$field_report_rss_name_value);
    }else{
        return $result;
    }
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function compartir_documentos_get_importar_my_report_link(){
    return l(t('Import Report'),'compartir_documentos/importar_documento/my_report');
}
function compartir_documentos_wiki_node_form_alter(&$form,&$form_state,$form_id){
    //compartir_documentos_add_frecuencia_form_fields($form);
    $unset_array=array('field_wiki_rss_name','field_wiki_import_rss_url','field_wiki_is_shared','field_wiki_is_imported','field_wiki_frecuencia'
    ,'field_wiki_frecuencia_hora','field_wiki_import_frecuencia','field_wiki_import_frecuenci_hora','field_wiki_import_links');
    $node=$form['#node'];
    /*if(compartir_documentos_import_is_imported_type($node)){
        $unset_array=array_diff($unset_array,array('field_wiki_import_frecuencia','field_wiki_import_frecuenci_hora'));        
    }*/
    compartir_documentos_unset_form_field_form_alter($form,$form_state, $form_id, $unset_array);
    $frecuencia=compartir_documentos_get_wiki_import_frecuencia($node);
    /*if(compartir_documentos_import_is_imported_type($node)){
        $form['field_wiki_import_frecuencia_post']=array(
            '#type'=>'select',
            '#title'=>t('Import frequency'),
            '#options' => get_frecuencia_options(1),
            '#default_value' => $frecuencia,
            '#required' => TRUE
        );
    }*/    
}
function compartir_documentos_add_frecuencia_form_fields(&$form,$node){    
    //$nid=arg(2);
    //$node=node_load($nid);
    //echo print_r($node,1);exit();
    $frecuencia=compartir_documentos_get_wiki_frecuencia($node);
    $hora=compartir_documentos_get_wiki_frecuencia_hora($node);
    $form['frecuencia_fs']=array(
    '#type'=>'fieldset',
    '#title'=>t('Update'),
    '#collapsible'=>TRUE,
    '#attributes'=>array('class'=>'enviar_mail_frecuencia_fs'),    
    );
    $form['frecuencia_fs']['frecuencia'] = array(
            '#type' => 'select',
            '#title' => t('Update'),
            '#options' => get_frecuencia_options(1,1),
            '#default_value' => $frecuencia,
            //'#required' => TRUE
          );
    $style='';
    if(empty($frecuencia) || $frecuencia=='manual'){
        $style=' style="display:none;"';
    }
    $prefix='<div id="id_div_hora_array"'.$style.'>';    
    $form['frecuencia_fs']['hora_array'] = array(
          '#type' => 'alerta_time',
            '#title' => t('Time'),
            '#default_value' => $hora,
            //'#required' => TRUE,
            '#prefix'=>$prefix,
            '#suffix'=>'</div>',
    );
    $form['frecuencia_fs']['value_js'] = array(
          '#value'=>compartir_documentos_add_frecuencia_form_fields_js(),
    );
    //compartir_documentos_add_frecuencia_form_fields_js();
}
function compartir_documentos_get_wiki_frecuencia($node,$is_label=0){
    $result=compartir_documentos_get_field_value($node,'field_wiki_frecuencia');
    if($is_label){
        return alerta_inc_get_frecuencia_label($result,1);
    }
    return $result;
}
function compartir_documentos_get_wiki_frecuencia_hora($node){
    $frecuencia=compartir_documentos_get_wiki_frecuencia($node);
    if($frecuencia!='manual'){
        return compartir_documentos_get_field_value($node,'field_wiki_frecuencia_hora');
    }
    return '';
}
function compartir_documentos_get_field_value($node,$field){
    if(isset($node->$field)){
        $row=$node->$field;
        if(isset($row[0]['value'])){
            return $row[0]['value'];
        }
    }
    return '';
}
function compartir_documentos_unset_form_field_form_alter(&$form,&$form_state, $form_id, $unset_array_in){
    $unset_array=$unset_array_in;
    $unset_array[]='field_documento_is_imported';
    red_movil_unset_form_field_form_alter($form, $form_state, $form_id, $unset_array);
}
function compartir_documentos_is_wiki_compartir_fields_show(){
    if(is_super_admin()){
        return 1;
    }
    return 0;
}
function compartir_documentos_get_wiki_rss_name($node){
    return compartir_documentos_get_field_value($node,'field_wiki_rss_name');
}
function compartir_documentos_get_wiki_import_rss_url($node){
    return compartir_documentos_get_field_value($node,'field_wiki_import_rss_url');
}
function compartir_documentos_get_wiki_is_shared_string($node){
    $value=compartir_documentos_get_field_value($node,'field_wiki_is_shared');
    if(!empty($value)){
        return t('Yes');
    }
    return t('No');
}
function compartir_documentos_get_wiki_is_imported_string($node){
    $value=compartir_documentos_get_field_value($node,'field_wiki_is_imported');
    if(!empty($value)){
        return t('Yes');
    }
    return t('No');
}
function compartir_documentos_get_wiki_import_frecuencia($node,$is_label=0){
    $result=compartir_documentos_get_field_value($node,'field_wiki_import_frecuencia');
    if($is_label){
        return alerta_inc_get_frecuencia_label($result,1);
    }
    return $result;
}
function compartir_documentos_get_wiki_import_frecuencia_hora($node){
    $frecuencia=compartir_documentos_get_wiki_import_frecuencia($node);
    if($frecuencia!='manual'){
        return compartir_documentos_get_field_value($node,'field_wiki_import_frecuenci_hora');
    }
    return '';
}
function compartir_documentos_importar_get_local_node($node,$rss_url){
    //$value=$node->field_wiki_import_rss_url_value;
    $value=$rss_value;
    $res=db_query('SELECT * FROM {content_type_wiki} WHERE field_wiki_import_rss_url_value="%s"',$rss_url);
    while($row=db_fetch_object($res)){
        $node=node_load($row->nid);
        return $node;
    }
    $my_result=new stdClass();
    return $my_result;
}
function compartir_documentos_import_is_in_frecuencia($frecuencia,$nombre_dia,$hora,$node){
    $not_hora=0;
    //simulando
    //return 1;
    if(strcmp($frecuencia,'manual')==0){
        return 0;
    }
    if(strcmp($frecuencia,'diaria')==0){
        //return 1;
        if(compartir_documentos_import_is_in_hora($hora,$node)){
            return 1;
        }else{
            $not_hora=1;
        }
    }
    //
    if(strcmp($frecuencia,'semanal_'.$nombre_dia)==0){
        //return 1;
        if(compartir_documentos_import_is_in_hora($hora,$node)){
            return 1;
        }else{
            $not_hora=1;
        }
    }
    /*
    if($not_hora){
        $my_message=t('Is not in the time');
    }else{
        $my_message=t('Is not in the frequency');
    }*/
    
    return 0;
}
function compartir_documentos_import_is_in_hora($hora,$node){
        $hora_array=explode(':',$hora);
        $h=0;
        $minute=0;
        if(count($hora_array)>1){
            $h=(int) $hora_array[0];
            $minute=(int) $hora_array[1];
        }
        $my_time=time();
        $import_time=mktime($h,$minute,0);
        if(!compartir_documentos_import_is_procesed_today($param,$node) && $import_time<=$my_time){
            return 1;
        }
    return 0;
}
function compartir_documentos_simular_tarea_callback(){
    compartir_documentos_import_todos();
    return date('Y-m-d H:i:s');
}
function compartir_documentos_get_import_wiki_array(){
    $result=array();
    $res=db_query('SELECT * FROM {content_type_wiki} WHERE field_wiki_is_imported_value=1');
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function compartir_documentos_import_todos($with_frecuencia=1){
    $dia=date('N');
    $nombre_dia=get_nombre_dia($dia);
    $wiki_array=compartir_documentos_get_import_wiki_array();
    if(!empty($wiki_array)){
        foreach($wiki_array as $i=>$row){
            $node=node_load($row->nid);
            /*$frecuencia=$row->field_wiki_import_frecuencia_value;
            $frecuencia_hora=$row->field_wiki_import_frecuenci_hora_value;*/
            $frecuencia=$node->field_wiki_import_frecuencia[0]['value'];
            $frecuencia_hora=$node->field_wiki_import_frecuenci_hora[0]['value'];
            if(!$with_frecuencia || compartir_documentos_import_is_in_frecuencia($frecuencia,$nombre_dia,$frecuencia_hora,$node)){
                /*print $frecuencia.'<br>';
                print $frecuencia_hora;
                exit();*/
                /*$rss_url=$node->field_wiki_import_rss_url[0]['value'];
                if(!empty($rss_url)){
                    compartir_documentos_importar_documento_file_get_contents($rss_url,1);
                }*/
                compartir_documentos_importar_documento_node($node,1,0);
            }           
        }
    }
}
function compartir_documentos_import_is_procesed_today($param,$node){
    if($node->type=='wiki'){
        $import_wiki_today_array=compartir_documentos_import_get_import_wiki_today_array($node);
        if(count($import_wiki_today_array)>0){
            return 1;
        }
        return 0;
    }
    return 0;
}
function compartir_documentos_import_get_import_wiki_today_array($node){
    $result=array();
    $where=array();
    $where[]="1";
    $where[]="t.nid=".$node->nid;    
    //$where[]="t.vid=".$node->vid;    
    $where[]="t.fecha='".date('Y-m-d')." 00:00:00'";
    $sql="SELECT t.* FROM {import_wiki_today} t WHERE ".implode(" AND ",$where);
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;    
}
function compartir_documentos_import_wiki_today_save($node){
    $fecha=date('Y-m-d')." 00:00:00'";
    $created=time();
    db_query('INSERT INTO {import_wiki_today(nid,vid,fecha,created)} VALUES(%d,%d,"%s",%d)',$node->nid,$node->vid,$fecha,$created);
}
function compartir_documentos_get_node_update_link($node,$result_in){
    $result=$result_in;
    if(compartir_documentos_import_is_imported_type($node)){
        $result.='<li>'.l(t('Update'),'compartir_documentos/update/'.$node->nid,array('attributes'=>array('id'=>'my_volver_js'))).'</li>';
    }
    return $result;
}
function compartir_documentos_import_is_imported_type($node){
    if($node->type=='user'){
        $my_user=$node;
        return compartir_documentos_usuario_is_imported($my_user->uid);
    }else{
        $field=compartir_documentos_get_field_is_imported_type($node);   
        if(isset($node->{$field}) && isset($node->{$field}[0]) && isset($node->{$field}[0]['value'])){
            if($node->{$field}[0]['value']==1){
                return 1;
            }    
        } 
    }    
    return 0;
}
function compartir_documentos_update_callback(){
    $nid=arg(2);
    $node=node_load($nid);
    compartir_documentos_importar_documento_node($node,0,0);
    drupal_set_message(t('Updated'));
    drupal_goto('node/'.$nid);
}
function compartir_documentos_importar_documento_node($node,$is_save_today=0,$is_new=0){
    if($node->type=='wiki'){
        $rss_url=$node->field_wiki_import_rss_url[0]['value'];
        if(!empty($rss_url)){
            compartir_documentos_importar_documento_file_get_contents($rss_url,$is_save_today,$is_new,$node->nid);
        }
    }
}
function compartir_documentos_cron(){
    compartir_documentos_import_todos();
}
function compartir_documentos_on_wiki_save($op,&$node){
    /*echo 'compartir_documentos===='.print_r($node,1);
    exit();*/
}
function compartir_documentos_get_rss_url_by_arg($rss_url){
    $result='';
    if(!empty($rss_url)){
        $result=base64_decode($rss_url);
    }    
    return $result;    
}
function compartir_documentos_is_node_frecuencia_fields($node){
    if(in_array($node->type,array('wiki'))){
        return 1;
    }
    return 0;
}
function compartir_documentos_existe_documento_grupo($rss_url){
    print $rss_url;
    exit();
}
function compartir_documentos_get_email_message($mail,$compartir_servidor_url,$node,$document_type,$is_validar_usuario_network,$message_text){
    return red_copiar_get_email_message($mail,$compartir_servidor_url,$node,$document_type,$is_validar_usuario_network,$message_text);
}
function compartir_documentos_get_content_type_item_array($nid,$field_item_rss_name_value=''){
    $result=array();
    if(!empty($nid)){
        //$res=db_query('SELECT * FROM {content_type_item} WHERE nid=%d',$nid);
        $res=db_query('SELECT * FROM {content_field_item_rss_name} WHERE nid=%d',$nid);
    }else{
        //$res=db_query('SELECT * FROM {content_type_item} WHERE field_item_rss_name_value="%s" ORDER BY vid DESC',$field_item_rss_name_value);
        $res=db_query('SELECT * FROM {content_field_item_rss_name} WHERE field_item_rss_name_value="%s" ORDER BY vid DESC',$field_item_rss_name_value);
    }
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function compartir_documentos_get_export_info($node_type,&$copiar,&$title,&$compartir_documentos){
    $title=t('Export wiki');
    $copiar='copiar';
    $compartir_documentos='compartir_documentos';
    if($node_type=='my_report'){
        $title=t('Export report');
    }else if(in_array($node_type,array('item','noticia'))){
        $title=t('Export news');
        $copiar='copiar_news';
        $compartir_documentos='compartir_documentos_news';
    }else if($node_type=='estrategia'){
        $title=t('Export challenge');
    }else if(in_array($node_type,array('supercanal'))){
        $title=t('Export source');
    }else if($node_type=='user'){
        $title=t('Export user');
    }else if($node_type=='proyecto'){
        $title=t('Export project');
    } 
}
function compartir_documentos_import_convert_noticia(&$node){
    if($node->type=='item'){
        $url=hontza_item_web_link($node,1);  
        $node->field_enlace_noticia[0]['url']=$url;
        $node->field_cuando[0]['value']=time();    
        $node->type='noticia';
    }
    $term=red_solr_inc_taxonomy_get_term_by_name_vid_row('Noticias de usuario',1);    
    $node->taxonomy[$term->tid]=$term;    
}
function compartir_documentos_enviar_mail_add_js($nid){
    global $base_path;
    $my_base_path=hontza_canal_rss_get_base_path_help_popup();
    $my_grupo=og_get_group_context();
    $my_grupo_nid='';
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $my_grupo_nid=$my_grupo->nid;
    }    
    $destination=red_copiar_get_popup_destination();
    $js="$(document).ready(function()
     {               
         $('#excompartir_documentos_enviar_mail_".$nid."').jqm({ajax:'".$my_base_path."help_popup.php?nid=compartir_documentos&w=500&h=400&compartir_documentos_nid=".$nid."&my_grupo_nid=".$my_grupo_nid.$destination."', trigger: 'a.jqm-trigger-compartir_documentos_enviar_mail_".$nid."',modal:true, toTop: true, overlay: 0});
         
     });";
     drupal_add_js($js,'inline');
}
function compartir_documentos_copiar_on_enviar_mail_drupal_goto($node,$my_grupo_nid_in,$url_in='',$is_url=0){
    global $base_url;
    global $language;
    $result=$url_in;
    $my_lang='';
    if($language->language!='en'){
        $my_lang='/'.$language->language;
    }
    $my_grupo_nid=$my_grupo_nid_in;
    if(empty($my_grupo_nid)){
        if(isset($_REQUEST['my_grupo_nid']) && !empty($_REQUEST['my_grupo_nid'])){
            $my_grupo_nid=$_REQUEST['my_grupo_nid'];
        }
    }
    if(!empty($my_grupo_nid)){
        $grupo_node=node_load($my_grupo_nid);
        $url='area-trabajo';
        if(in_array($node->type,array('item','noticia'))){
            $url='vigilancia/validados';
        }
        /*if(isset($_SESSION['enviar_mail_destination'])){
            $destination=str_replace('destination=','',$_SESSION['enviar_mail_destination']);
            if(!empty($destination)){
                $url=$destination;
            }
            unset($_SESSION['enviar_mail_destination']);
        }*/
        if(isset($_REQUEST['destination']) && !empty($_REQUEST['destination'])){
            $url=$_REQUEST['destination'];
        }        
        $url=$base_url.$my_lang.'/'.$grupo_node->purl.'/'.$url;
        if($is_url){
            return $url;
        }else{
            $_REQUEST['destination']='';
            drupal_goto($url);
        }
    }
    if($is_url){
        return $result;
    }    
}
function compartir_documentos_get_popup_title($nid){
    $result='Export document';
    $node=node_load($nid);
    if($node->type=='my_report'){
        $result='Export report';
    }else if($node->type=='wiki'){
        $result='Export wiki';
    }else if($node->type=='item'){
        $result='Export news';
    }else if($node->type=='noticia'){
        $result='Export news';
    }else if($node->type=='estrategia'){
        $result='Export challenge';
    }else if(in_array($node->type,array('supercanal'))){
        $result='Export source';
    }else if($node->type=='proyecto'){
        $result='Export project';
    } 
    $result=t($result);
    return $result;    
}
function compartir_documentos_get_enviar_mail_message($node){
    /*$result='<p><i>Exporting <b>@node_title</b></i><p>';
    $result.='<p><i>Please indicate a valid email</i></p>';
    $result=t($result,array('@node_title'=>$node->title));
    return $result;*/
    return red_copiar_get_enviar_mail_message($node);
}
function compartir_documentos_import_custom_access(){
    if(hontza_is_user_anonimo()){
        return FALSE;
    }
    return TRUE;
}
function compartir_documentos_importar_enviar_mail_from($mail_from,$node_title,$node=''){
    red_copiar_importar_enviar_mail_from($mail_from,$node_title,$node);
}
function compartir_documentos_add_importar_noticia_link(&$html){
    /*if(!red_copiar_is_grupo_conectado()){
        $html[]='<br>'.l(t('Import News'),'compartir_documentos_news/importar_documento_news/noticia');
    }*/
}
function compartir_documentos_item_node_form_alter(&$form,&$form_state, $form_id){
    compartir_documentos_unset_field_item_rss_name_form_field($form,$form_state, $form_id);
}
function compartir_documentos_unset_field_item_rss_name_form_field(&$form,&$form_state, $form_id){
    $unset_array=array('field_item_rss_name');
    compartir_documentos_unset_form_field_form_alter($form,$form_state, $form_id, $unset_array);
}
function compartir_documentos_noticia_node_form_alter(&$form,&$form_state, $form_id){
    compartir_documentos_unset_field_item_rss_name_form_field($form,$form_state, $form_id);
}
function compartir_documentos_importar_documento_callback(){
   $rss_url=arg(3);
   $mail_from=arg(4);
   if(!empty($rss_url) && !empty($mail_from)){
       $rss_url=compartir_documentos_get_rss_url_by_arg($rss_url);    
       compartir_documentos_create_compartir_documentos_importar_documento_form_submit($rss_url,$mail_from);
   }else{
       return drupal_get_form('compartir_documentos_importar_documento_form');
   } 
}
function compartir_documentos_create_compartir_documentos_importar_documento_form_submit($rss_url,$mail_from){
   $form=array();
   $form_state=array();
   $form_state['values']=array();
   //$rss_url=compartir_documentos_get_rss_url_by_arg(arg(3));
   //$mail_from=arg(4);    
   $form_state['values']['rss_url']=$rss_url;
   $form_state['values']['mail_from']=$mail_from;
   compartir_documentos_importar_documento_form_submit($form,$form_state);
}
function compartir_documentos_import_todos_tarea_callback(){
   compartir_documentos_import_todos(0);
   return date('Y-m-d H:i');
}
function compartir_documentos_get_wiki_enlaces_array($node){
    $result=array();
    if(isset($node->nid) && !empty($node->nid)){
        $enlaces=array();
        if($node->type=='wiki'){
            $wiki_nid=$node->nid;
            $enlazar_wiki_array=hontza_get_all_enlazar_wiki_array($wiki_nid,'');
            $enlaces=$enlazar_wiki_array;
        }
        if(!empty($enlaces)){
            foreach($enlaces as $i=>$row){
                $nid=$row->item_nid;
                $my_node=node_load($nid);
                if(isset($my_node->nid) && !empty($my_node->nid)){
                    $enlace_row=new stdClass();
                    $url=hontza_get_item_url_enlace($item_nid,$my_node);
                    $enlace_row->fecha=date('d/m/Y',$my_node->created);
                    $my_node->votingapi_cache_node_average_value=boletin_report_get_votingapi_cache_node_average_value($my_node->nid);
                    $enlace_row->stars_value=my_get_stars_idea($my_node);
                    $enlace_row->link=l($my_node->title,$url,array('absolute'=>TRUE,'attributes'=>array('target'=>'_blank')));
                    $result[]=$enlace_row;
                }    
            }            
        }
    }
    return $result;
}
function compartir_documentos_get_wiki_import_links($node,$enlaces){
    $result=$enlaces;
    if(isset($node->field_wiki_import_links[0]['value'])){
       $import_links=unserialize(base64_decode($node->field_wiki_import_links[0]['value']));
       if(!empty($import_links)){
           foreach($import_links as $i=>$row){
               $enlace_row=new stdClass();
               $enlace_row=clone $row;
               $enlace_row->is_wiki_import=1;
               $result[]=$enlace_row;
           }
       }
    }
    return $result;
}
function compartir_documentos_add_wiki_import_enlaces_html(&$html,$row,$is_view,$con_fecha){
    $html[]='<tr>';
    if($is_view && user_access('Enlazar wiki')){
        $html[]='<td>';
        $html[]='&nbsp;';
        $html[]='</td>';                    
    }
    if($con_fecha){
        $html[]='<td>';
        $html[]=$row->fecha;
        $html[]='</td>';
    }
    $html[]=red_copiar_get_enlaces_stars_td();
    $html[]=$row->stars_value;
    $html[]='</td>';    
    $html[]='<td>';
    $html[]=$row->link;
    $html[]='</td>';
    $html[]='</tr>';
}
function compartir_documentos_add_frecuencia_form_fields_js(){
    $js='<script>';
    $js.='$(document).ready(function()
     {               
         $("#edit-frecuencia").change(function(){
            var my_value=$(this).attr("value");
            compartir_documentos_set_visible_hora_array(my_value);
         });
         function compartir_documentos_set_visible_hora_array(my_value){
            var div_display="block";
            if(my_value=="manual"){
                div_display="none";
            }
            $("#id_div_hora_array").css("display",div_display);
         }
     });';
    $js.='</script>';
     //drupal_add_js($js,'inline');
    return $js;
}
function compartir_documentos_is_show_update_link($node){
    $value=compartir_documentos_get_field_value($node,'field_wiki_is_imported');
    if(!empty($value)){
        return 1;
    }
    return 0;
}
function compartir_documentos_update_link($node){
    $destination=drupal_get_destination();
    $title=t('Update');
    $result=l('','compartir_documentos/update/'.$node->nid,array('query'=>$destination,'attributes'=>array('title'=>$title)));
    return $result;
}
function compartir_documentos_copiar_enviar_mail_form_validate(&$form,&$form_state){
    $mail=$form_state['values']['email'];
    $message_text=$form_state['values']['message_text'];
    if(empty($mail) || empty($message_text)){
        if(empty($mail)){
            drupal_set_message(t('!field field is required.', array('!field' =>t('To'))),'error');
        }
        if(empty($message_text)){
            drupal_set_message(t('!field field is required.', array('!field' =>t('Message'))),'error');
        }
        drupal_goto($_REQUEST['destination']);
    }
}
function compartir_documentos_is_show_reset_link($node){
    if($node->type=='wiki'){
        $value=compartir_documentos_get_field_value($node,'field_wiki_is_shared');
        if(!empty($value)){
            return 1;
        }
    }else{
        $rss_name=compartir_documentos_get_node_rss_name($node);
        if(!empty($rss_name)){
            return 1;
        }    
    }
    return 0;
}
function compartir_documentos_reset_link($node){
    $destination=drupal_get_destination();
    $title=t('Reset');
    $result=l('','compartir_documentos/reset/'.$node->nid,array('query'=>$destination,'attributes'=>array('title'=>$title)));
    return $result;
}
function compartir_documentos_reset_callback(){
    $nid=arg(2);
    $node=node_load($nid);
    if($node->type=='wiki'){    
        $content_type_wiki_array=compartir_documentos_get_content_type_wiki_array($nid);
        if(!empty($content_type_wiki_array)){
            foreach($content_type_wiki_array as $i=>$row){
                db_query('UPDATE {content_type_wiki} SET field_wiki_rss_name_value="",field_wiki_is_shared_value=0 WHERE nid=%d AND vid=%d',$node->nid,$node->vid);                                
            }
        }
    }else if($node->type=='estrategia'){
        $content_type_estrategia_array=compartir_documentos_get_content_type_estrategia_array($nid);
        if(!empty($content_type_estrategia_array)){
            foreach($content_type_estrategia_array as $i=>$row){
                db_query('UPDATE {content_type_estrategia} SET field_estrategia_rss_name_value="" WHERE nid=%d AND vid=%d',$node->nid,$node->vid);                                
            }
        }
    }else if($node->type=='supercanal'){
        compartir_documentos_fuente_supercanal_reset($node);
    }else if($node->type=='proyecto'){
        compartir_documento_proyecto_reset($node);
    }    
    hontza_solr_clear_cache_content($nid,1);
    $url='node/'.$nid;
    if(isset($_REQUEST['destination']) && !empty($_REQUEST['destination'])){
        $url=$_REQUEST['destination'];
    }
    drupal_goto($url);
}
function compartir_documentos_get_content_type_estrategia_array($nid,$field_estrategia_rss_name_value=''){
    $result=array();
    if(!empty($nid)){
        $res=db_query('SELECT * FROM {content_type_estrategia} WHERE nid=%d',$nid);
    }else if(!empty($field_estrategia_rss_name_value)){
        $res=db_query('SELECT * FROM {content_type_estrategia} WHERE field_estrategia_rss_name_value="%s" ORDER BY vid DESC',$field_estrategia_rss_name_value);
    }else{
        return $result;
    }
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function compartir_documentos_get_estrategia_tabla_csv($nid){
    return estrategia_tabla_csv_download($nid,1);
}
function compartir_documentos_get_node_rss_name($node){
    $result='';
    if($node->type=='my_report'){
        $result=compartir_documentos_get_field_value($node,'field_report_rss_name');
    }else if(in_array($node->type,array('item','noticia'))){     
        $result=compartir_documentos_get_field_value($node,'field_item_rss_name');
    }else if($node->type=='estrategia'){
        $result=compartir_documentos_get_field_value($node,'field_estrategia_rss_name');
    }else if($node->type=='wiki'){
        $result=compartir_documentos_get_wiki_rss_name($node);
    }else{
        $result=compartir_documentos_get_field_value($node,'field_'.$node->type.'_rss_name');    
    }    
    return $result;
}
function compartir_documentos_importar_estrategia($node){
    $form_state=array();
    $form_state['values']=array();
    $form_state['values']['import_type']=0;
    $lineas=$node->estrategia_tabla_csv;
    array_shift($lineas);
    estrategia_crear_retos_csv($lineas,$form_state,1);
    return $node;
}
function compartir_documentos_estrategia_node_form_alter(&$form,&$form_state,$form_id){
    $unset_array=array('field_estrategia_rss_name');
    compartir_documentos_unset_form_field_form_alter($form,$form_state, $form_id, $unset_array);
}
function compartir_documentos_get_title_imported_class($node_in='',$title_in=''){
    $result='';
    /*if(!empty($title_in) && ($title_in=='Importing' || $title_in==t('Importing'))){
        return $result;
    }*/
    if(isset($node_in->nid) && !empty($node_in->nid)){
        $node=$node_in;
    }else{
        if(is_mi_perfil(0,0)){
            $node=new stdClass();
            $node->uid=arg(1);
            $node->type='user';
        }else{
            $node=my_get_node();
        }    
    }
    if(compartir_documentos_import_is_imported_type($node)){
        if(in_array($node->type,array('canal_de_yql'))){
            $param=arg(2);
            if($param=='import'){
                return $result;
            }
        }
        $class='documento_importado';
        if(isset($node_in->nid) && !empty($node_in->nid)){
            $result=' class="'.$class.'"';
        }else{
            $result=' '.$class;
        }
    }
    return $result;
}
function compartir_documentos_add_field_is_imported(&$node){
    $field=compartir_documentos_get_field_is_imported_type($node);    
    //$node->$field[0]=array();
    $node->{$field}[0]['value']=1;
}
function compartir_documentos_get_field_is_imported_type($node){
    $field='field_documento_is_imported';
    if($node->type=='wiki'){
        $field='field_wiki_is_imported';        
    }
    return $field;
}
function compartir_documentos_canal_node_form_alter(&$form,&$form_state,$form_id){
    $unset_array=array('field_is_usuario_exportado');
    compartir_documentos_unset_form_field_form_alter($form,$form_state, $form_id, $unset_array);
}
function compartir_documentos_get_estrategia_link($node){
    $result='';
    if(compartir_documentos_custom_access()){
        $result=compartir_documentos_copiar_link($node,1);
        if(!empty($result)){
            $result.='&nbsp;';
        }
    }                                                
    return $result;
}
function compartir_documentos_my_report_node_form_alter(&$form,&$form_state,$form_id){
    $unset_array=array('field_report_rss_name');
    compartir_documentos_unset_form_field_form_alter($form,$form_state,$form_id,$unset_array);
}
function compartir_documentos_is_conectado_red(){
    /*if(hontza_is_sareko_id_red()){
        if(hontza_is_red_hoja()){
            return 1;
        }
    }*/
    if(red_copiar_is_grupo_conectado()){
        return 1;
    }
    return 0;
}
function compartir_documentos_is_conectado_red_access_denied(){
    if(!compartir_documentos_is_conectado_red()){
        drupal_access_denied();
        exit();
    }
}
function compartir_documentos_is_canal_usuario_exportado_save($source,$xml){
    /*if(isset($xml->channel->is_canal_usuario_exportado) && !empty($xml->channel->is_canal_usuario_exportado)){
        $is_canal_usuario_exportado=trim($xml->channel->is_canal_usuario_exportado);
        if($is_canal_usuario_exportado==1){
            if(db_table_exists('content_field_is_usuario_exportado')){*/
            if(compartir_documentos_is_canal_usuario_exportado($xml)){
                $node=node_load($source->feed_nid);
                if(isset($node->nid) && !empty($node->nid)){
                    compartir_documentos_is_canal_usuario_exportado_update($node->nid,$node->vid,$is_canal_usuario_exportado);
                }
            }    
            /*}
        }
    }*/    
}
function compartir_documentos_is_canal_usuario_exportado_update($nid,$vid,$is_canal_usuario_exportado){
    db_query('UPDATE {content_field_is_usuario_exportado} SET field_is_usuario_exportado_value=%d WHERE nid=%d AND vid=%d',$is_canal_usuario_exportado,$nid,$vid);
    hontza_solr_clear_cache_content($nid,1);
}
function compartir_documentos_is_canal_usuario_exportado_add(&$canal,$xml){
     if(compartir_documentos_is_canal_usuario_exportado($xml)){
        $canal->field_is_usuario_exportado[0]['value']=1;            
     }    
}
function compartir_documentos_is_canal_usuario_exportado_add_img($canal_nid,$result_in){
    $result=$result_in;
    if(compartir_documentos_is_canal_usuario_exportado_node($canal_nid)){
        $result.=my_get_icono_action('is_canal_usuario_exportado',t('User'));
    }
    return $result;
}
function compartir_documentos_is_canal_usuario_exportado_node($canal_nid){
    $canal=node_load($canal_nid);
    if(isset($canal->nid) && !empty($canal->nid)){
        if(isset($canal->field_is_usuario_exportado[0]['value']) && !empty($canal->field_is_usuario_exportado[0]['value'])){
            return 1;
        }
    }
    return 0;
}
function compartir_documentos_is_canal_usuario_exportado($xml){
    if(isset($xml->channel->is_canal_usuario_exportado) && !empty($xml->channel->is_canal_usuario_exportado)){
        $is_canal_usuario_exportado=trim($xml->channel->is_canal_usuario_exportado);
        if($is_canal_usuario_exportado==1){
            if(db_table_exists('content_field_is_usuario_exportado')){
                return 1;
            }
        }
    }    
    return 0;
}