<?php
function custom_dashboard_perm() {
  return array();
}
function custom_dashboard_menu() {
  $items=array();
  $items['custom_dashboard/searches']=array(
    '#title'=>t('Searches'),
    'page callback' => 'custom_dashboard_searches_callback',
    'access callback'=>'custom_dashboard_searches_access',    
  );
  $items['custom_dashboard/search/%/activar']=array(
    '#title'=>t('Activate search'),
    'page callback' => 'custom_dashboard_search_activar_callback',
    'access callback'=>'custom_dashboard_searches_access',    
  );
  return $items;
}
function custom_dashboard_is_searches(){
    //$custom_dashboard_type=panel_admin_dashboard_get_custom_dashboard_type();
    $custom_dashboard_type=custom_dashboard_get_grupo_dashboard_type();
    if($custom_dashboard_type=='searches'){
        return 1;
    }
    return 0;
}
function custom_dashboard_get_content_html(){
    $groups=array();
    $html=array();
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $groups[]=$my_grupo->nid;
        $canales=hontza_get_all_nodes(array('canal_busqueda'),$groups);
        if(!empty($canales)){
            foreach($canales as $i=>$canal){
                if(hontza_canal_rss_is_canal_busqueda_solr($canal->nid)){
                    if(custom_dashboard_is_mostrar_dashboard($canal)){
                        $content_block=custom_dashboard_get_content_block($canal->nid);
                        $html[]=$content_block;
                    }    
                }else{
                    //busqueda_rss_exportar_busqueda_rss($canal->nid);
                }    
            }
        }
    }
    return implode('',$html);
}
function custom_dashboard_get_busqueda_nid_array($canal_nid_in,&$canal_busqueda){
    $result=array();
        if(hontza_canal_rss_is_canal_busqueda_solr($canal_nid_in)){
            $canal_busqueda=node_load($canal_nid_in);
            $result=alerta_solr_get_canal_busqueda_nid_array($canal_busqueda);
            return $result;
        }
    return $result;    
}
function custom_dashboard_get_content_block($canal_nid_in){
    $html=array();
    $block_style=' style="float:left;width:31%;margin-left:16px;"';
    $html[]='<div id="block-hontza-dashboard-search-'.$canal_nid_in.'" class="block block-hontza block-odd region-odd clearfix"'.$block_style.'>';    
    //$html[]='<div id="block-views-dashboard-search-'.$canal_nid_in.'" class="block block-views block-odd region-odd clearfix "'.$block_style.'>';  
    $nid_array=custom_dashboard_get_busqueda_nid_array($canal_nid_in,$canal_busqueda);
    $url=red_dashboard_get_url_solr_search($canal_busqueda);
    $info_url=parse_url($url);
    $html[]='<h3 class="title">'.l($canal_busqueda->title,$info_url['path'],array('query'=>$info_url['query'])).'</h3>';
    $html[]='<div class="content" style="height:300px;">';
    //$html[]='<div class="view view-og-home-noticiasvalidadas-dash view-id-og-home-noticiasvalidadas-dash view-display-id-block-1 view-dom-id-6 ">';
    //$html[]='<div class="view-content">';
    $max=5;
    if(!empty($nid_array)){
        foreach($nid_array as $i=>$nid){
            if($i<$max){
                $node=node_load($nid);
                if(isset($node->nid) && !empty($node->nid)){
                    //$html[]='<div class="views-row views-row-2 views-row-even">';
                    $html[]='<div style="padding-left:0px;width:100%;">';
                    //$html[]='<div class="views-field-nothing">';
                    //$html[]='<span class="field-content">';
                    //$node_title=custom_dashboard_unset_hound_id_item_title($node);
                    $node_title=custom_dashboard_fix_hound_id_node_title($node->title);                    
                    if(!hontza_solr_search_is_usuario_lector()){
                        $node=red_dashboard_add_node_links($node);
                        $html[]='<div class="f-interesante">'.hontza_canal_rss_set_flag_link($node->links['flag-leido_interesante']['title']).'</div>';
                        $html[]='<div class="f-no-interesante">'.hontza_canal_rss_set_flag_link($node->links['flag-leido_no_interesante']['title']).'</div>';
                    }    	                    
                    $html[]=l($node_title,'node/'.$nid);
                    //$html[]='</span>';
                    //$html[]='</div>';
                    $html[]='</div>';
                }
            }else{
                break;
            }
        }
    }
    $html[]='</div>';
    $html[]='</div>';
    return implode('',$html);
}
function custom_dashboard_unset_hound_id_item_title($node){
    $result=$node->title;
        $result=ltrim($result);
        //Quitar hound id que tiene en el title entre corchetes        
        $result=preg_replace('/^\[[^\]]*\]/','',$result);
        $result=ltrim($result);
    return $result;    
}
function custom_dashboard_fix_hound_id_node_title($node_title){
    $result=explode(']',$node_title);
    if(count($result)>1){
        foreach($result as $i=>$value){
            if($i>0){
                $result[$i]=' '.trim($value);
            }
        }
    }
    return implode(']',$result);
}
function custom_dashboard_get_grupo_dashboard_type(){
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        if(isset($my_grupo->field_grupo_dashboard_type[0]['value'])){
            return $my_grupo->field_grupo_dashboard_type[0]['value'];
        }
    }
    return '';
}
function custom_dashboard_searches_access(){
    if(is_administrador_grupo()){
        return TRUE;
    }
    return FALSE;
}
function custom_dashboard_searches_callback(){

    $headers=array();
    $headers[0]=t('Search');
    $headers[1]=t('Actions');
    
    $my_limit=30;

    $where=array();
    $where[]='1';
    $where[]='node.type="canal_busqueda"';

    $rows=array();
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $where[]='og_ancestry.group_nid='.$my_grupo->nid;
        $sql='SELECT node.title,content_type_canal_busqueda.* 
        FROM {node} node
        LEFT JOIN {content_type_canal_busqueda} ON node.vid=content_type_canal_busqueda.vid
        LEFT JOIN {og_ancestry} ON og_ancestry.nid=content_type_canal_busqueda.nid
        WHERE '.implode(' AND ',$where).'
        ORDER BY node.title ASC';

        $res=db_query($sql);        
        $rows=array();
        $kont=0;
        while ($r = db_fetch_object($res)) {
          $rows[$kont]=array();
          $rows[$kont][0]=$r->title;
          $rows[$kont][1]= custom_dashboard_searches_define_acciones($r);
          $kont++;
        }
    }    
    //
    $rows=my_set_estrategia_pager($rows, $my_limit);
    if (count($rows)>0) {
        $output .= theme('table',$headers,$rows,array('class'=>'table_panel_admin_noticias'));
        $output .= theme('pager', NULL, $my_limit);    
    }else {
        $output.= '<div id="first-time">' .t('There are no contents'). '</div>';
    }
    drupal_set_title(t('Searches'));
    //
    //return panel_admin_noticias_define_gestion_noticias_header().drupal_get_form('panel_admin_noticias_gestion_noticias_bulk_form',array($output));
    return $output;
}
function custom_dashboard_searches_define_acciones($r){
    $html=array();
    $destination='destination=custom_dashboard/searches';
    if(isset($r->field_is_mostrar_dashboard_value) && $r->field_is_mostrar_dashboard_value==1){
         $html[]=l(my_get_icono_action('validar_facilitador_deshacer',t('Reject')),'custom_dashboard/search/'.$r->nid.'/activar',array('query'=>$destination,'html'=>true)); 
    }else{
        $html[]=l(my_get_icono_action('validar_facilitador_gris',t('Validate')),'custom_dashboard/search/'.$r->nid.'/activar',array('query'=>$destination,'html'=>true));    
    }
    return implode('&nbsp;',$html);
}
function custom_dashboard_search_activar_callback(){
    $nid=arg(2);
    $node=node_load($nid);
    $value=1;
    //if(isset($node->field_is_mostrar_dashboard[0]['value']) && $node->field_is_mostrar_dashboard[0]['value']==1){
    if(custom_dashboard_is_mostrar_dashboard($node)){    
        $value=0;
    }
    db_query($sql=sprintf('UPDATE {content_type_canal_busqueda} SET field_is_mostrar_dashboard_value=%d WHERE nid=%d AND vid=%d',$value,$node->nid,$node->vid));
    //print $sql;
    hontza_solr_clear_cache_content($node->nid,1);   
    drupal_goto('custom_dashboard/searches');
}
function custom_dashboard_is_mostrar_dashboard($canal){
    if(isset($canal->field_is_mostrar_dashboard[0]['value']) && $canal->field_is_mostrar_dashboard[0]['value']==1){
        return 1;
    }
    return 0;    
}