<?php
function custom_dashboard_perm() {
  return array();
}
function custom_dashboard_menu() {
  $items=array();
  
  return $items;
}
function custom_dashboard_is_searches(){
    $custom_dashboard_type=panel_admin_dashboard_get_custom_dashboard_type();
    if($custom_dashboard_type=='searches'){
        return 1;
    }
    return 0;
}
function custom_dashboard_get_content_html(){
    $groups=array();
    $html=array();
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $groups[]=$my_grupo->nid;
        $canales=hontza_get_all_nodes(array('canal_busqueda'),$groups);
        if(!empty($canales)){
            foreach($canales as $i=>$canal){
                if(hontza_canal_rss_is_canal_busqueda_solr($canal->nid)){
                    $content_block=custom_dashboard_get_content_block($canal->nid);
                    $html[]=$content_block;
                }else{
                    //busqueda_rss_exportar_busqueda_rss($canal->nid);
                }    
            }
        }
    }
    return implode('',$html);
}
function custom_dashboard_get_busqueda_nid_array($canal_nid_in,&$canal_busqueda){
    $result=array();
        if(hontza_canal_rss_is_canal_busqueda_solr($canal_nid_in)){
            $canal_busqueda=node_load($canal_nid_in);
            $result=alerta_solr_get_canal_busqueda_nid_array($canal_busqueda);
            return $result;
        }
    return $result;    
}
function custom_dashboard_get_content_block($canal_nid_in){
    $html=array();
    $block_style=' style="float:left;width:31%;margin-left:16px;"';
    $html[]='<div id="block-hontza-dashboard-search-'.$canal_nid_in.'" class="block block-hontza block-odd region-odd clearfix"'.$block_style.'>';    
    //$html[]='<div id="block-views-dashboard-search-'.$canal_nid_in.'" class="block block-views block-odd region-odd clearfix "'.$block_style.'>';  
    $nid_array=custom_dashboard_get_busqueda_nid_array($canal_nid_in,$canal_busqueda);
    $url=red_dashboard_get_url_solr_search($canal_busqueda);
    $info_url=parse_url($url);
    $html[]='<h3 class="title">'.l($canal_busqueda->title,$info_url['path'],array('query'=>$info_url['query'])).'</h3>';
    $html[]='<div class="content" style="height:300px;">';
    //$html[]='<div class="view view-og-home-noticiasvalidadas-dash view-id-og-home-noticiasvalidadas-dash view-display-id-block-1 view-dom-id-6 ">';
    //$html[]='<div class="view-content">';
    $max=5;
    if(!empty($nid_array)){
        foreach($nid_array as $i=>$nid){
            if($i<$max){
                $node=node_load($nid);
                if(isset($node->nid) && !empty($node->nid)){
                    //$html[]='<div class="views-row views-row-2 views-row-even">';
                    $html[]='<div style="padding-left:0px;width:100%;">';
                    //$html[]='<div class="views-field-nothing">';
                    //$html[]='<span class="field-content">';
                    //$node_title=custom_dashboard_unset_hound_id_item_title($node);
                    $node_title=custom_dashboard_fix_hound_id_node_title($node->title);
                    $html[]=l($node_title,'node/'.$nid);
                    //$html[]='</span>';
                    //$html[]='</div>';
                    $html[]='</div>';
                }
            }else{
                break;
            }
        }
    }
    $html[]='</div>';
    $html[]='</div>';
    return implode('',$html);
}
function custom_dashboard_unset_hound_id_item_title($node){
    $result=$node->title;
        $result=ltrim($result);
        //Quitar hound id que tiene en el title entre corchetes        
        $result=preg_replace('/^\[[^\]]*\]/','',$result);
        $result=ltrim($result);
    return $result;    
}
function custom_dashboard_fix_hound_id_node_title($node_title){
    $result=explode(']',$node_title);
    if(count($result)>1){
        foreach($result as $i=>$value){
            if($i>0){
                $result[$i]=' '.trim($value);
            }
        }
    }
    return implode(']',$result);
}