<?php
require_once('diccionario.exportar.csv.inc.php');
require_once('diccionario.portugues.inc.php');
require_once('diccionario.alerta.inc.php');
require_once('diccionario.red_alerta.inc.php');
require_once('diccionario.drupal_locales.inc.php');
require_once('diccionario.traducir.import.errores.inc.php');
require_once('diccionario.importar.csv.inc.php');
require_once('diccionario.fix.inc.php');
require_once('diccionario.compartir_documentos.inc.php');
function diccionario_perm() {
  return array('Access to Dictionnary');
}
function diccionario_menu() {
    $items=array();
    $items['diccionario']=array(
    'title'=>t('Migrate dictionary'),
    'page callback' => 'drupal_get_form',    
    'page arguments'   => array('diccionario_form'),
    'access arguments' => array('Access to Dictionnary'),
    );
    $items['diccionario/migrar']=array(
    'title'=>t('Migrate dictionary result'),
    'page callback' => 'diccionario_migrar',    
    'access arguments' => array('Access to Dictionnary'),
    );
    $items['diccionario/exportar_csv']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_exportar_csv_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
    $items['diccionario/guardar_para_traducir']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_guardar_para_traducir_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
    $items['diccionario/crear_para_traducir_todo']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_crear_para_traducir_todo_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
    $items['diccionario/traer_portugues']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_traer_portugues_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/traer_alerta']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_traer_alerta_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/traer_red_alerta']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_traer_red_alerta_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/traer_drupal_locales_source']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_traer_drupal_locales_source_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/exportar_drupal_locales_source_by_modulo']=array(
    'title'=>t('Export'),
    'page callback' => 'diccionario_exportar_drupal_locales_source_by_modulo_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/traducir_import_errores']=array(
    'title'=>t('Import'),
    'page callback' => 'diccionario_traducir_import_errores_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/importar_csv']=array(
    'title'=>t('Import'),
    'page callback' => 'drupal_get_form',      
    'page arguments' => array('diccionario_importar_csv_form'),    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/importar_csv_print']=array(
    'title'=>t('Import'),
    'page callback' => 'diccionario_importar_csv_print_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/undo_traducciones_permisos']=array(
    'title'=>'Import',
    'page callback' => 'diccionario_undo_traducciones_permisos_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/importar_csv_print_permisos']=array(
    'title'=>'Permissions',
    'page callback' => 'diccionario_importar_csv_print_permisos_callback',    
    'access arguments' => array('Access to Dictionnary'),
    );
     $items['diccionario/probar_actualizar_diccionarios'] = array(
    'title' => 'Text',
    'page callback' => 'diccionario_probar_actualizar_diccionarios_callback',
    'access arguments' => array('root'),
    );
     $items['diccionario/diccionario_custom_cron']=array(
    'title'=>t('Migrate dictionary'),
    'page callback' => 'diccionario_custom_cron_callback',    'access callback' => TRUE,
    );
     $items['diccionario/fix']=array(
    'title'=>t('Migrate dictionary'),
    'page callback' => 'diccionario_fix_callback',    
    'access arguments' => array('root'),
    );
     $items['diccionario/compartir_documentos']=array(
    'title'=>t('Translate'),
    'page callback' => 'diccionario_compartir_documentos_callback',    
    'access arguments' => array('root'),
    );
     $items['diccionario/compartir_documentos/%/edit_locales_source']=array(
    'title'=>t('Translate'),
    'page arguments' => array('diccionario_compartir_documentos_locales_source_form'),
    'page callback' => 'drupal_get_form',    
    'access arguments' => array('root'),
    );
     $items['diccionario/compartir_documentos/%/edit_locales_target']=array(
    'title'=>t('Translate'),
    'page arguments' => array('diccionario_compartir_documentos_locales_target_form'),
    'page callback' => 'drupal_get_form',    
    'access arguments' => array('root'),
    );
    return $items;
}
function diccionario_form(){
    $form=array();    
    $form['funcion_desactivada']=array(
        '#value'=>'Funcion desactivada',
    );
    return $form;
    $options=array(
        'hontza_blanco'=>'hontza_blanco', 
    );
    $form['my_db']=array(
        '#type'=>'select',
        '#title'=>t('Database'),
        '#options'=>$options
    );
    $form['migrate_btn']=array('#type'=>'submit','#name'=>'migrate_btn','#value'=>t('Migrate'));
    //$form['cancel_btn']=array('#value'=>l(t('Cancel'),'node/'.$nid.'/enlazar_debate'));
    return $form;
}
function diccionario_form_submit($form, &$form_state){
    if(isset($form_state['clicked_button']) && !empty($form_state['clicked_button'])){
        $my_name=$form_state['clicked_button']['#name'];
        if($my_name=='migrate_btn'){            
            $_SESSION['diccionario']['my_db']=$form_state['values']['my_db'];
        }                
    }
   drupal_goto('diccionario/migrar');    
}
function diccionario_migrar(){
    
    $html=array();
    $my_db=$_SESSION['diccionario']['my_db'];
    //$my_db="hontza_icbroseta";
    $root_locales_source=diccionario_get_locales_source_array();
    db_set_active($my_db);
    $sub_locales_source=diccionario_get_locales_source_array();    
    $prev_db_name=db_set_active();
    //print $prev_db_name;exit();
    $html[]=count($root_locales_source).'='.count($sub_locales_source).'<BR>';
    //
    $insert_source_array=array();
    $update_source_array=array();
    $kont_update=0;
    if(!empty($root_locales_source)){
        foreach($root_locales_source as $i=>$row){
            db_set_active($my_db);

            $sub_row=diccionario_get_locales_source_row($row->source);
            if(isset($sub_row->lid) && !empty($sub_row->lid)){
                $update_source_array[$kont_update]=$sub_row;
                $update_source_array[$kont_update]->hontza3_lid=$row->lid;
                $kont_update++;
            }else{
                $insert_source_array[]=$row;

            }
            db_set_active();
        }
    }
    

    $html[]=count($insert_source_array).'<BR>';
    $html[]=count($update_source_array).'<BR>';
    $html[]=(count($insert_source_array)+count($update_source_array)).'<BR>';
    //
    $html[]=diccionario_migrar_update_output($update_source_array);
    $html[]='##########################################################<BR>';
    $html[]=diccionario_migrar_insert_output($insert_source_array);
    return implode('',$html);
}
function diccionario_get_locales_source_output(){
    $locales_source_array=diccionario_get_locales_source_array();
    if(!empty($locales_source_array)){
        foreach($locales_source_array as $i=>$row){
            echo print_r($row,1);
            exit();
        }
    }
}
function diccionario_get_locales_source_array($source=''){
    $result=array();
    if(empty($source)){
        $res=db_query('SELECT ls.* FROM {locales_source} ls WHERE ls.textgroup="default" ORDER BY ls.lid ASC');   
    }else{
        $res=db_query('SELECT ls.* FROM {locales_source} ls WHERE ls.textgroup="default" AND ls.source="%s" ORDER BY ls.lid ASC',$source);
    }
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function diccionario_get_locales_source_row($source){
    $result=diccionario_get_locales_source_array($source);
    if(count($result)>0){
        return $result[0];
    }
    $my_result=new stdClass();
    return $my_result;
}
function diccionario_migrar_update_output($update_source_array){
    $html=array();
    if(!empty($update_source_array)){
        foreach($update_source_array as $i=>$row){
            $locales_target_array=diccionario_get_locales_target_array($row->hontza3_lid);
            if(!empty($locales_target_array)){
                $my_db=$_SESSION['diccionario']['my_db'];
                db_set_active($my_db);
                $sub_locale_row=diccionario_get_locales_source_row($row->source);
                if(isset($sub_locale_row->lid) && !empty($sub_locale_row->lid)){
                    foreach($locales_target_array as $k=>$locale_target_row){
                        $sub_target_row=diccionario_get_locales_target_row($sub_locale_row->lid,$locale_target_row->language);
                        if(isset($sub_target_row->lid) && !empty($sub_target_row->lid)){
                            $sql=sprintf('UPDATE {locales_target} SET translation="%s" WHERE lid=%d AND language="%s" AND plural=%d',$locale_target_row->translation,$sub_locale_row->lid,$locale_target_row->language,$locale_target_row->plural);
                            $html[]=$sql.'<BR>';
                            db_query('UPDATE {locales_target} SET translation="%s" WHERE lid=%d AND language="%s" AND plural=%d',$locale_target_row->translation,$sub_locale_row->lid,$locale_target_row->language,$locale_target_row->plural);
                        }else{
                            $sql=sprintf('INSERT INTO {locales_target}(lid,translation,language,plid,plural,l10n_status,i18n_status) VALUES(%d,"%s","%s",%d,%d,%d,%d)',$sub_locale_row->lid,$locale_target_row->translation,$locale_target_row->language,$locale_target_row->plid,$locale_target_row->plural,$locale_target_row->l10n_status,$locale_target_row->i18n_status);
                            $html[]=$sql.'<BR>';
                            db_query('INSERT INTO {locales_target}(lid,translation,language,plid,plural,l10n_status,i18n_status) VALUES(%d,"%s","%s",%d,%d,%d,%d)',$sub_locale_row->lid,$locale_target_row->translation,$locale_target_row->language,$locale_target_row->plid,$locale_target_row->plural,$locale_target_row->l10n_status,$locale_target_row->i18n_status);
                        }
                    }
                }
                db_set_active();                
            }
        }
    }
    return implode('',$html);
}
function diccionario_get_locales_target_array($lid='',$language='',$is_all=0){
    $result=array();
    if($is_all){
        $res=db_query('SELECT lt.* FROM {locales_target} lt WHERE lt.lid=%d ORDER BY lt.lid ASC',$lid);
    }else if(empty($lid) && empty($language)){
        $res=db_query('SELECT lt.* FROM {locales_target} lt WHERE lt.language IN('.diccionario_define_languages_where().') ORDER BY lt.lid ASC');
    }else if(!empty($lid) && empty($language)){    
        $res=db_query('SELECT lt.* FROM {locales_target} lt WHERE lt.lid=%d AND lt.language IN('.diccionario_define_languages_where().') ORDER BY lt.lid ASC',$lid);
    }else if(empty($language) && !empty($language)){    
        $res=db_query('SELECT lt.* FROM {locales_target} lt WHERE lt.language="%s" ORDER BY lt.lid ASC',$language);
    }else{
        $res=db_query('SELECT lt.* FROM {locales_target} lt WHERE lt.lid=%d AND lt.language="%s" ORDER BY lt.lid ASC',$lid,$language);
    }
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function diccionario_get_locales_target_row($lid,$language){
    $result=diccionario_get_locales_target_array($lid,$language);
    if(count($result)>0){
        return $result[0];
    }
    $my_result=new stdClass();
    return $my_result;
}
function diccionario_migrar_insert_output($insert_source_array){
    $html=array();
    if(!empty($insert_source_array)){
        foreach($insert_source_array as $i=>$row){
            $my_db=$_SESSION['diccionario']['my_db'];
            db_set_active($my_db);
            $location='';
            $sql=sprintf('INSERT INTO {locales_source}(location,textgroup,source,version) VALUES("%s","%s","%s","%s")',$location,$row->textgroup,$row->source,$row->version);
            $html[]=$i.'='.$sql.'<BR>';
            db_query('INSERT INTO {locales_source}(location,textgroup,source,version) VALUES("%s","%s","%s","%s")',$location,$row->textgroup,$row->source,$row->version);
            $new_lid=db_last_insert_id('locales_source','lid');
            db_set_active();
            //
            $locales_target_array=diccionario_get_locales_target_array($row->lid);
            if(!empty($locales_target_array)){
                $my_db=$_SESSION['diccionario']['my_db'];
                db_set_active($my_db);
                if(!empty($new_lid)){
                    foreach($locales_target_array as $k=>$locale_target_row){
                        $sql=sprintf('INSERT INTO {locales_target}(lid,translation,language,plid,plural,l10n_status,i18n_status) VALUES(%d,"%s","%s",%d,%d,%d,%d)',$new_lid,$locale_target_row->translation,$locale_target_row->language,$locale_target_row->plid,$locale_target_row->plural,$locale_target_row->l10n_status,$locale_target_row->i18n_status);
                        $html[]=$sql.'<BR>';
                        db_query('INSERT INTO {locales_target}(lid,translation,language,plid,plural,l10n_status,i18n_status) VALUES(%d,"%s","%s",%d,%d,%d,%d)',$new_lid,$locale_target_row->translation,$locale_target_row->language,$locale_target_row->plid,$locale_target_row->plural,$locale_target_row->l10n_status,$locale_target_row->i18n_status);
                    }
                }
                db_set_active();                
            }
        }
    }
    return implode('',$html);
}
function diccionario_define_languages_where(){
    return '"eu","es","fr","pt-pt"';
}
function diccionario_cron(){
    //diccionario_actualizar_diccionarios();
}
function diccionario_actualizar_diccionarios(){
    $sareko_id_array=array('LOKALA','ROOT');
    if(hontza_in_sareko_id($sareko_id_array)){
        if(diccionario_is_actualizar_diccionarios()){
            $conexiones=diccionario_define_subdominios_conexiones();
            if(!empty($conexiones)){
                $kont=0;
                $max=3;
                foreach($conexiones as $key=>$value){
                    if($kont>=$max){
                        break;
                    }
                    if(diccionario_is_actualizar_diccionario_hoy($value)){
                        $_SESSION['diccionario']['my_db']=$value;
                        diccionario_migrar();                    
                        variable_set('diccionario_migrar_fecha_'.$value,date('Y-m-d'));
                        print $value.'<BR>';
                        $kont++;
                    }
                }                
            }
        }
    }
}
function diccionario_is_actualizar_diccionarios(){
    /*if(hontza_is_sareko_id('LOKALA')){
        return 1;
    }*/
            /*$fecha_konp=date('Y-m-d').' 02:00';
            $time_konp=strtotime($fecha_konp);
            $now=time();
            $now=strtotime('2014-08-03 02:45');
            $suma=$now-$time_konp;
            if($suma>=0 && $suma<=3600){
                return 1;
            }*/
    return 1;
    //return 0;
}
function diccionario_probar_actualizar_diccionarios_callback(){
    //diccionario_actualizar_diccionarios();
    return date('Y-m-d H:i');
}
function diccionario_define_subdominios_conexiones(){ 
    //intelsat-2016
    $result=diccionario_get_subdominios_conexiones_database_name_array();
    $result=array_combine($result,$result);
    return $result;
}
function diccionario_is_actualizar_diccionario_hoy($value){
    $konp=variable_get('diccionario_migrar_fecha_'.$value,'');
    if(empty($konp)){
        return 1;
    }
    $hoy=date('Y-m-d');
    if($hoy==$konp){
        return 0;
    }
    return 1;
}
function diccionario_custom_cron_callback(){
    diccionario_actualizar_diccionarios();
    return date('Y-m-d H:i');
}
function diccionario_get_subdominios_conexiones_database_name_array(){
    $result=array();
    if(db_table_exists('diccionario_db_conexiones')){
        $sql='SELECT * FROM {diccionario_db_conexiones} WHERE 1 ORDER BY id ASC';
        $res=db_query($sql);
        while($row=db_fetch_object($res)){
            $result[]=trim($row->database_name);
        }
    }
    return $result;
}