<?php
require_once('sites/all/libraries/MCAPI-PHP-master/examples/inc/MCAPI.class.php');
function hontza_mcapi_perm() {
  return array();
}
function hontza_mcapi_menu() {
  $items=array();
  $items['hontza_mcapi/settings'] = array(
    'title' => 'MailChimp Settings',
    'page arguments'=>array('hontza_mcapi_settings_form'),  
    'page callback' => 'drupal_get_form',
    'access callback' => 'hontza_mcapi_custom_admin_access',
  );
  return $items;
}
function hontza_mcapi_my_send_mail($mail_to_in,$subject,$body_in,$send_method,$is_recibir,$historico_nid,$is_mail_externo,$br_in){
    $campaignId=hontza_mcapi_campaignCreate($subject,$body_in,$br_in);
    hontza_mcapi_campaignSendNow($campaignId);
}
function hontza_mcapi_campaignCreate($subject,$body_in,$br_in){
$api=hontza_mcapi_create_api();


$type = 'regular';
    
//$opts['list_id'] = '23c961e1b4';
$opts['list_id'] = $br_in->mailchimp_list_id;
$opts['subject'] = $subject;
//$opts['from_email'] = 'bulegoa@netkam.com';
$opts['from_email'] = variable_get('my_from_default_mail','hontza@hontza.es');

$opts['from_name'] = 'Hontza';

//$opts['tracking']=array('opens' => true, 'html_clicks' => true, 'text_clicks' => false);

$opts['authenticate'] = true;
//$opts['analytics'] = array('google'=>'my_google_analytics_key');
$opts['title'] = $subject;
//$opts['template_id']=74425;
//$opts['template_id']=75465;
//$opts['template_id']=75681;
$mailchimp_template_id=$br_in->mailchimp_template_id;
if(!empty($mailchimp_template_id)){
    $opts['template_id']=$mailchimp_template_id;
    $content = array('html_main'=>$body_in,
    //'text' => 'Texto'
    );
}else{
    $content = array('html'=>$body_in, 
		  //'text' => 'Texto'
    );
}


/** OR we could use this:
$content = array('html_main'=>'some pretty html content',
		 'html_sidecolumn' => 'this goes in a side column',
		 'html_header' => 'this gets placed in the header',
		 'html_footer' => 'the footer with an *|UNSUB|* message', 
		 'text' => 'text content text content *|UNSUB|*'
		);
$opts['template_id'] = "1";
**/

$retval = $api->campaignCreate($type, $opts, $content);

    if ($api->errorCode){
            $msg="Unable to Create New Campaign!";
            $msg.="<br>Code=".$api->errorCode;
            $msg.="<br>".$api->errorMessage;
            drupal_set_message($msg);
    } else {
            drupal_set_message("New Campaign ID:".$retval);
    }
    return $retval;
}
function hontza_mcapi_get_apikey(){
    //$result="4dc50eae734b6bb1e09a8afa36314053-us13";
    $result=variable_get('hontza_mcapi_apikey','');
    return $result;
}
function hontza_mcapi_campaignSendNow($campaignId){
    $api=hontza_mcapi_create_api();
    $retval = $api->campaignSendNow($campaignId);
    if ($api->errorCode){
            $msg="Unable to Send Campaign!";
            $msg.="<br>Code=".$api->errorCode;
            $msg.="<br>Msg=".$api->errorMessage;
            drupal_set_message($msg);
    } else {
            drupal_set_message("Campaign Sent!");
    }
}
function hontza_mcapi_custom_admin_access(){
    if(red_funciones_is_administrador_grupo()){
        return TRUE;
    }
    return FALSE;
}
function hontza_mcapi_settings_form(){
    $form=array();
    $form['apikey']=array(
        '#type'=>'textfield',
        '#title'=>t('MailChimp API Key'),
        '#default_value'=>hontza_mcapi_get_apikey(),
        '#required'=>TRUE,
    );
    $form['save_btn']=array(
        '#type'=>'submit',
        '#value'=>t('Save'),
        '#name'=>'save_btn',
    );
    return $form;
}
function hontza_mcapi_add_alerta_settings_block_links(&$html){
    $html[]=l('MailChimp settings','hontza_mcapi/settings',array('query'=>drupal_get_destination()));    
}
function hontza_mcapi_create_api(){
    $apikey=hontza_mcapi_get_apikey();
    $api = new MCAPI($apikey);
    return $api;
}

function hontza_mcapi_settings_form_submit($form, &$form_state){
    if(isset($form_state['clicked_button']) && !empty($form_state['clicked_button']) && $form_state['clicked_button']['#name']=='save_btn'){
        variable_set('hontza_mcapi_apikey',$form_state['values']['apikey']);
        drupal_set_message(t('Saved'));
    }
}
function hontza_mcapi_add_boletin_report_form_fields($row,&$form){
    $form['boletin_report_receptores_fs']['#prefix']='<div style="display:none;">';
    $form['boletin_report_receptores_fs']['#suffix']='</div>';
    $form['boletin_report_receptores_mcapi_fs']=array(
    '#type'=>'fieldset',
    '#title'=>t('Recipients'),
    '#collapsible'=>TRUE,
    '#attributes'=>array('id'=>'id_boletin_report_receptores_fs'),    
    );
    $form['boletin_report_receptores_mcapi_fs']['mailchimp_list_id']=array(
        '#type'=>'textfield',
        '#title'=>t('MailChimp List id'),
        '#default_value'=>$row->mailchimp_list_id,
    );
    $form['boletin_report_receptores_mcapi_fs']['mailchimp_template_id']=array(
        '#type'=>'textfield',
        '#title'=>t('MailChimp Template id'),
        '#default_value'=>$row->mailchimp_template_id,
    );
}
function hontza_mcapi_save_mailchimp_list_id($id,$values){
    $mailchimp_list_id='';
    if(isset($values['mailchimp_list_id']) && !empty($values['mailchimp_list_id'])){
        $mailchimp_list_id=$values['mailchimp_list_id'];
    }
    db_query('UPDATE {boletin_report_array} SET mailchimp_list_id="%s" WHERE id=%d',$mailchimp_list_id,$id);
}
function hontza_mcapi_get_forward_user_mail_array($user_mail_array_in){
    $result=$user_mail_array_in;
    if(empty($result)){
        $result[]='hontza@hontza.es';
    }
    return $result;
}
function hontza_mcapi_add_boletin_report_forward_form_fields($id,&$form){
    $row=boletin_report_get_row($id);
    $form['forward_receptores_fs']['#prefix']='<div style="display:none;">';
    $form['forward_receptores_fs']['#suffix']='</div>';
    $form['boletin_report_receptores_mcapi_fs']['mailchimp_list_id']=array(
        '#type'=>'textfield',
        '#title'=>t('MailChimp List id'),
        '#default_value'=>$row->mailchimp_list_id,
    );
    $form['boletin_report_receptores_mcapi_fs']['mailchimp_template_id']=array(
        '#type'=>'textfield',
        '#title'=>t('MailChimp Template id'),
        '#default_value'=>$row->mailchimp_template_id,
    );
}
function hontza_mcapi_save_mailchimp_fields($id,$values){
    hontza_mcapi_save_mailchimp_list_id($id,$values);
    hontza_mcapi_save_mailchimp_template_id($id,$values);
}
function hontza_mcapi_save_mailchimp_template_id($id,$values){
    $mailchimp_template_id='';
    if(isset($values['mailchimp_template_id']) && !empty($values['mailchimp_template_id'])){
        $mailchimp_template_id=$values['mailchimp_template_id'];
    }
    db_query('UPDATE {boletin_report_array} SET mailchimp_template_id="%s" WHERE id=%d',$mailchimp_template_id,$id);
}