<?php
function gestion_canales_perm(){
    return array('access gestion_canales');
}    
function gestion_canales_menu() {
  $items['gestion/gestion_canales'] = array(
    'title' => 'Management of Channels',
    'page callback' => 'gestion_canales_callback',
    //intelsat-2015  
    //'access arguments' => array('access gestion_canales'),
    'access callback' => 'gestion_canales_custom_access',  
  );
  //$items['gestion/gestion_canales/delete_items_confirm'] = array(
  $items['gestion/gestion_canales/delete_canales_confirm'] = array(  
  'title' => 'Management of Channels',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('gestion_canales_delete_canales_confirm_form'),
    //intelsat-2015  
    //'access arguments' => array('access gestion_canales'),
    'access callback' => 'gestion_canales_custom_access',   
  );
  $items['gestion/gestion_canales/activate_confirm']=array(
    'title'=>t('Activated channel'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('gestion_canales_activate_confirm_form'),
    //intelsat-2015  
    //'access arguments' => array('access activar_actualizacion_canal'),
    'access callback' => 'gestion_canales_activar_actualizacion_canal_custom_access',  
  );
  $items['gestion/gestion_canales/deactivate_confirm']=array(
    'title'=>t('Deactivate channel'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('gestion_canales_deactivate_confirm_form'),
    //intelsat-2015  
    //'access arguments' => array('access activar_actualizacion_canal'),
    'access callback' => 'gestion_canales_activar_actualizacion_canal_custom_access',  
    );
  return $items;
}
function gestion_canales_callback(){
    //intelsat-2015
    global $user;
    drupal_set_title(t('Management of Channels'));
    $output='';
    
    $headers=array();
    $headers[0]='<input type="checkbox" id="my_select_all" name="my_select_all" class="my_select_all"/>';    
    $headers[1]=array('data'=>t('Creator'),'field'=>'users_name');    
    $headers[2]=array('data'=>t('Channel'),'field'=>'node_title');
    $headers[3]=array('data'=>t('Group'),'field'=>'node_title');
    //$headers[4]=array('data'=>t('Source'),'field'=>'node_data_field_fuente_canal_field_fuente_canal_value');    
    //$headers[4]=array('data'=>t('Activated'),'field'=>'node_title');
    $headers[4]=array('data'=>t('Last download'),'field'=>'node_title','class'=>'gestion_canales_last_download');  
    $headers[5]=array('data'=>t('Last update'),'field'=>'node_title'); 
    $headers[6]=t('Actions');				    
    
    $my_limit=40;    
    $sort='asc';
    $field='node_title';
    if(isset($_REQUEST['sort']) && !empty($_REQUEST['sort'])){
        $sort=$_REQUEST['sort'];
    }
    //$is_numeric=0;
    $order='';
    if(isset($_REQUEST['order']) && !empty($_REQUEST['order'])){
        $order=$_REQUEST['order'];
        if($order==t('Channel')){
            $field='node_title';
        }else if($order==t('Group')){
            $field='grupo_title';
        }else if($order==t('Source')){
            $field='node_data_field_fuente_canal_field_fuente_canal_value';
        }else if($order==t('Creator')){
            $field='users_name';
        }
    }
    
    //intelsat-2016
    if(empty($order)){
        $order=t('Last download');
    }
    
    $filter_fields=gestion_canales_define_filter_fields();
    
   $where=array();
   $where[]='1';
   //intelsat-2016
   //$where[]='node.type in ("canal_de_supercanal","canal_de_yql","canal_busqueda")';
   $where[]='node.type in ("canal_de_supercanal","canal_de_yql")';
   
   //intelsat-2015
   if(!is_super_admin()){
        $grupo_nid_array=hontza_get_user_group_nid_array($uid='');
        if(!empty($grupo_nid_array)){
             $where[]='grupo.nid IN('.implode(',',$grupo_nid_array).')';
        }
   }
   
   if(!empty($filter_fields)){
       foreach($filter_fields as $k=>$f){
           $v=gestion_canales_get_filter_value($f);
           //intelsat-2016
           $v=gestion_canales_get_grupo_nid_any_value($v,$f);
           if(!empty($v)){
                switch($f){
                    case 'node_title':
                        $where[]='node.title LIKE "%'.$v.'%"';
                        break;
                    case 'grupo_nid':
                        //intelsat-2016
                        //$where[]='grupo.nid='.$v;
                        $grupo_nid_array=array_keys($v);
                        $where[]='grupo.nid IN('.implode(',',$grupo_nid_array).')';
                        break;
                    case 'hound_id':
                        $where[]='canal_hound_parametros.hound_id LIKE "%'.$v.'%"';
                        break;
                    case 'text':
                        //$where[]='(node.title LIKE "%%'.$v.'%%" OR node_revisions.body LIKE "%%'.$v.'%%")';
                        $where[]=contenidos_canales_get_text_where($v);
                        break;
                    //intelsat-2016
                    case 'is_activated':
                        $my_value=$v;
                        $or=array();
                        if($my_value==2){
                            $my_value=0;
                        }
                        $or[]='content_field_canal_active_refresh.field_canal_active_refresh_value='.$my_value;
                        if(empty($my_value)){
                            $or[]='content_field_canal_active_refresh.field_canal_active_refresh_value IS NULL';
                        }
                        $where[]='('.implode(' OR ',$or).')';
                        break;
                    default:
                        break;
                }
           } 
       }
   }
   
   $where[]=hontza_get_usuarios_acceso_where_time('content_field_last_import_time.field_last_import_time_value','gestion_canales','fecha_inicio','fecha_fin');
        
    $sql='SELECT node.nid AS nid,
    node.title AS node_title,
    node.language AS node_language,
    og_ancestry.nid AS og_ancestry_nid,
    node_data_field_fuente_canal.field_fuente_canal_value AS node_data_field_fuente_canal_field_fuente_canal_value,
    node.type AS node_type, node.vid AS node_vid,
    node_data_field_nombrefuente_canal.field_nombrefuente_canal_value AS node_data_field_nombrefuente_canal_field_nombrefuente_canal_value, 
    users.name AS users_name,
    node.status AS node_status,
    node.uid AS node_uid,
    node_revisions.format AS node_revisions_format,
    node.created AS node_created,
    grupo.title AS grupo_title,
    grupo.nid AS grupo_nid,
    node.created AS node_changed 
    FROM {node} node LEFT JOIN {og_ancestry} og_ancestry ON node.nid = og_ancestry.nid
    LEFT JOIN {content_field_fuente_canal} node_data_field_fuente_canal ON node.vid = node_data_field_fuente_canal.vid 
    LEFT JOIN {content_field_nombrefuente_canal} node_data_field_nombrefuente_canal ON node.vid = node_data_field_nombrefuente_canal.vid 
    LEFT JOIN {users} users ON node.uid = users.uid 
    LEFT JOIN {node_revisions} node_revisions ON node.vid = node_revisions.vid 
    LEFT JOIN {node} grupo ON grupo.nid=og_ancestry.group_nid
    LEFT JOIN {canal_hound_parametros} ON node.vid=canal_hound_parametros.vid 
    LEFT JOIN {content_field_last_import_time} content_field_last_import_time ON node.vid=content_field_last_import_time.vid 
    LEFT JOIN {feeds_source} feeds_source ON node.nid=feeds_source.feed_nid
    LEFT JOIN {content_field_canal_active_refresh} ON node.vid=content_field_canal_active_refresh.vid
    WHERE '.implode(' AND ',$where).'
    GROUP BY node.nid     
    ORDER BY '.$field.' '.strtoupper($sort);
    //print $sql;
    $rows=array();
    $res=db_query($sql);
    $kont=0;
    $faktore=50;
    while($r=db_fetch_object($res)){
        $node=node_load($r->nid);
        $rows[$kont]=array();
        $rows[$kont][0]='<input type="checkbox" id="txek_'.$r->nid.'" name="txek_nid['.$r->nid.']" class="bulk_txek" value="1">';
        $user_image=hontza_grupos_mi_grupo_get_user_img($r->node_uid,$faktore);
        $rows[$kont][1]=$user_image;        
        $rows[$kont][2]=l($r->node_title,'node/'.$r->nid);
        $rows[$kont][3]=l($r->grupo_title,gestion_canales_get_grupo_url_absolute($r->grupo_nid),array('absolute'=>TRUE));
        //$rows[$kont][4]=$r->node_data_field_fuente_canal_field_fuente_canal_value;
        //intelsat-2015
        //$rows[$kont][4]=$r->users_name;
        //
        $activated_label=gestion_canales_get_activated_value_label($node,1,1);
        //$rows[$kont][4]=$activated_label;
        //intelsat-2015
        /*$last_content_en=get_canal_last_update_date_format($r->nid,'en');
        $last_content=strtotime($last_content_en);
        //print $last_content;exit();
        if(empty($last_content)){
            $rows[$kont][4]='';
        }else{
            $rows[$kont][4]=date('d-m-Y H:i',$last_content);
        }*/
        //intelsat-2015
        $last_content=contenido_canales_get_last_download($r->nid,$last_content_time);
        //
        $rows[$kont][4]=$last_content;
        //intelsat-2015
        /*$last_update=get_canal_last_import_time_format($node,1);
        if(empty($last_update)){
            $rows[$kont][5]='';
        }else{
            $rows[$kont][5]=date('d-m-Y H:i',$last_update);
        }*/
        //intelsat-2015
        $rows[$kont][5]=contenido_canales_get_last_update($node,$r->node_changed,$last_update_time);
        //
        $rows[$kont][6]=array('data'=>gestion_canales_define_acciones($r->nid,$activated_label),'style'=>'white-space:nowrap');        
        $rows[$kont]['activated_label']=$activated_label;
        //intelsat-2015
        //$rows[$kont]['date_of_last_content']=$last_content;
        $rows[$kont]['date_of_last_content']=$last_content_time;
        //intelsat-2015
        //$rows[$kont]['date_of_last_update']=$last_update;
        $rows[$kont]['date_of_last_update']=$last_update_time;
        //
        $kont++;
    }
    
    if(!empty($order)){
        if($order==t('Activated')){
            $rows=array_ordenatu($rows,'activated_label',$sort,0);
        }else if($order==t('Last download')){
            $rows=array_ordenatu($rows,'date_of_last_content',$sort,1);
        }else if($order==t('Last update')){
            $rows=array_ordenatu($rows,'date_of_last_update',$sort,1);
        }         
    }
    $rows=hontza_unset_array($rows,array('activated_label','date_of_last_content','date_of_last_update'));
    
    $rows=my_set_estrategia_pager($rows, $my_limit);
    if (count($rows)>0) {
      $output .= theme('table',$headers,$rows,array('class'=>'table_gestion_canales'));
      $output .= theme('pager', NULL, $my_limit);    
    }
    else {

      $output.= '<div id="first-time">' .t('There are no contents'). '</div>';
    }
    //intelsat-2015
    $output=gestion_canales_define_header().drupal_get_form('gestion_canales_bulk_form',array($output));
    //
    return $output;
}
function gestion_canales_define_acciones($nid,$is_activated){
    $html=array();
    //$html[]=l(my_get_icono_action('viewmag', t('View')),'node/'.$nid,array('absolute'=>true,'html'=>true,'query'=>drupal_get_destination(),'attributes'=>array('title'=>t('View'),'alt'=>t('View'))));        
    $html[]=l(my_get_icono_action('edit', t('Edit')),'node/'.$nid.'/edit',array('absolute'=>true,'html'=>true,'query'=>drupal_get_destination(),'attributes'=>array('title'=>t('Edit'),'alt'=>t('Edit'))));    
    $html[]=l(my_get_icono_action('delete', t('Delete')),'node/'.$nid.'/delete',array('absolute'=>true,'html'=>true,'query'=>drupal_get_destination(),'attributes'=>array('title'=>t('Delete'),'alt'=>t('Delete'))));        
    //intelsat-2015
    $html[]=gestion_canales_get_activar_canal_link($nid,$is_activated);
    //
    //intelsat-2015
    $html[]='<br>'.gestion_canales_get_canal_noticias_link($nid);
    $html[]=gestion_canales_get_actualizar_noticias_link($nid,'destination=gestion/gestion_canales');
    return implode('&nbsp;',$html);
}
function gestion_canales_get_activated_value_label($node,$is_icono=0,$is_result=0){
    //intelsat-2015
    $result=0;
    //
    if($node->type=='canal_busqueda'){
        $value=t('Yes');
        //intelsat-2015
        $result=1;
    }else{
        if(gestion_canales_is_existe_campo_canal_active_refresh()){
            $value=hontza_canal_get_activated_string($node,$is_icono);
            //intelsat-2015
            if($is_icono){
                $result=$value;
            }
        }else{
            if($is_icono){
                $result=1;
            }else{
                $value=t('Yes');
                return $value;
            }    
        }
    }
    //intelsat-2015
    if($is_result){
        return $result;
    }
    if($is_icono){
        if($result){
            return my_get_icono_action('active_user',t('Activated'));
        }else{
            return my_get_icono_action('deactive_user',t('Deactivated'));
        }
    }
    //
    return $value;
}
function gestion_canales_get_grupo_url_absolute($grupo_nid){
    global $base_url;
    $grupo=node_load($grupo_nid);
    if(isset($grupo->purl) && !empty($grupo->purl)){
        return $base_url.'/'.$grupo->purl.'/dashboard';
    }
    return '';
}
function gestion_canales_define_filter_fields(){
    /*$filter_fields=array('node_title','grupo_nid','hound_id');
    return $filter_fields;*/
    $result=array('grupo_nid','text','fecha_inicio','fecha_fin');
    //intelsat-2016
    $result[]='is_activated';
    return $result;    
}
function gestion_canales_define_header(){
    $html=array();
    //$html[]='<div class="view-header">';
    if(hontza_canal_rss_is_show_volver_gestion()){
        $html[]=l(t('Back to management panel'),'gestion',array('attributes'=>array('class'=>'back')));
    }
    $html[]=gestion_canales_define_filtro();
    //$html[]='<div>';
    return implode('',$html);
}
function gestion_canales_define_filtro(){
    my_add_buscar_js();
    return drupal_get_form('gestion_canales_filtro_form');    
}
function gestion_canales_filtro_form(){
    $fs_title=t('Search');
    if(!gestion_canales_is_filter_activated()){
        $fs_title=t('Filter');
        $class='file_buscar_fs_vigilancia_class';
    }else{
        $fs_title=t('Filter Activated');
        $class='file_buscar_fs_vigilancia_class fs_search_activated';
    }
    //        
    $form=array();
    $form['file_buscar_fs']=array('#type'=>'fieldset','#title'=>$fs_title,'#attributes'=>array('id'=>'file_buscar_fs','class'=>$class));
    /*$form['file_buscar_fs']['node_title']=
        array('#type'=>'textfield',
        '#title'=>t('Channel'),
        "#default_value"=>gestion_canales_get_filter_value('node_title'));
    $form['file_buscar_fs']['grupo_nid'] = array(
  '#type' => 'select',
  '#title' => t('Group'),
  '#default_value' =>gestion_canales_get_filter_value('grupo_nid'),
  '#options'=>gestion_canales_define_grupo_options(),
  '#multiple'=>FALSE
);*/
    //intelsat-2016
    $with_grupo=1;
    $is_grupo_multiple=1;
    contenidos_add_filter_form_fields('gestion_canales',$form,$with_grupo,$is_grupo_multiple);
    //
    $form['file_buscar_fs']['hound_id']=
        array('#type'=>'textfield',
        '#title'=>t('Hound Channel Id'),
        "#default_value"=>gestion_canales_get_filter_value('hound_id'));
    //
    $form['file_buscar_fs']['submit']=array('#type'=>'submit','#value'=>t('Search'),'#name'=>'buscar');
    $form['file_buscar_fs']['reset']=array('#type'=>'submit','#value'=>t('Clean'),'#name'=>'limpiar');
    return $form;
}
function gestion_canales_filtro_form_submit($form_id,&$form){
    if(isset($form['clicked_button']) && !empty($form['clicked_button'])){
        $name=$form['clicked_button']['#name'];
        if(strcmp($name,'limpiar')==0){
            if(isset($_SESSION['gestion_canales']['filter']) && !empty($_SESSION['gestion_canales']['filter'])){
                unset($_SESSION['gestion_canales']['filter']);
            }
        }else{
            $_SESSION['gestion_canales']['filter']=array();
            $fields=gestion_canales_define_filter_fields();
            if(count($fields)>0){
                foreach($fields as $i=>$f){
                    $v=$form['values'][$f];
                    if(!empty($v)){
                        $_SESSION['gestion_canales']['filter'][$f]=$v;
                    }
                }
            }
        }
    } 
}
function gestion_canales_get_filter_value($f){
    return hontza_get_gestion_usuarios_filter_value($f,'gestion_canales');
}
function gestion_canales_define_grupo_options(){
    $result=array();
    $result[0]='';
    $max=custom_menu_define_grupo_title_max_len();    
    $grupo_array=my_get_og_grupo_list('',1);
    if(!empty($grupo_array)){
        foreach($grupo_array as $i=>$row){
            $grupo_title=$row->title;
            $len=strlen($grupo_title);      
            if($len>$max){
              $grupo_title=substr($grupo_title,0,$max)."...";
            }
            $result[$row->nid]=$grupo_title;
        }
    }
    return $result;
}
function gestion_canales_is_filter_activated(){
            $fields=gestion_canales_define_filter_fields();
            if(count($fields)>0){
                foreach($fields as $i=>$f){
                    if(isset($_SESSION['gestion_canales']['filter'][$f]) && !empty($_SESSION['gestion_canales']['filter'][$f])){
                        return 1;
                    }
                }
            }
            return 0;
}
function gestion_canales_is_existe_campo_canal_active_refresh(){
    return 1;
}
function gestion_canales_get_activar_canal_link($nid,$is_activated){
    $icono='';
    if($is_activated){        
        $icono=my_get_icono_action('deactive_user',t('Deactivate'));
    }else{        
        $icono=my_get_icono_action('active_user',t('Activate'));                
    }
    //intelsat-2015
    //$destination='destination=gestion/gestion_canales';
    $destination=drupal_get_destination();
    return l($icono,'activar_actualizacion_canal/'.$nid,array('query'=>$destination.'&is_gestion_canales=1','html'=>true));
    //
}
//intelsat-2015
function gestion_canales_bulk_form(){
    $vars=func_get_args();
    $table=$vars[1][0];
    return contenidos_canales_bulk($table);
}
//intelsat-2015
function gestion_canales_bulk_form_submit($form, &$form_state) {
    contenidos_canales_bulk_submit($form,$form_state,'gestion_canales');
}
//intelsat-2015
function gestion_canales_delete_canales_confirm_form(){
    $form=panel_admin_grupos_get_grupos_confirm('delete_node','block_gestion_canales_nid_array','gestion/gestion_canales');
    return $form;
}
//intelsat-2015
function gestion_canales_delete_canales_confirm_form_submit(&$form, &$form_state){
    global $base_url;
    $url=$base_url.'/gestion/gestion_canales';
    call_bulk_confirm_form_submit($form,$form_state,'delete_node',$url,true);
}
//intelsat-2015
function gestion_canales_activate_confirm_form(){
    $form=panel_admin_grupos_get_grupos_confirm('activate_channel','block_gestion_canales_nid_array','gestion/gestion_canales');
    return $form;
}
//intelsat-2015
function gestion_canales_activate_confirm_form_submit(&$form, &$form_state){
    global $base_url;
    $url=$base_url.'/gestion/gestion_canales';
    call_bulk_confirm_form_submit($form,$form_state,'activate_channel',$url,true);
}
//intelsat-2015
function gestion_canales_activar_canal($nid,$value){
    $new_value=hontza_activar_actualizacion_canal($nid,$value);
    $canal=node_load($nid);
    hontza_solr_search_clear_cache_content($canal);
}
//intelsat-2015
function gestion_canales_deactivate_confirm_form(){
    $form=panel_admin_grupos_get_grupos_confirm('deactivate_channel','block_gestion_canales_nid_array','gestion/gestion_canales');
    return $form;
}
//intelsat-2015
function gestion_canales_deactivate_confirm_form_submit(&$form, &$form_state){
    global $base_url;
    $url=$base_url.'/gestion/gestion_canales';
    call_bulk_confirm_form_submit($form,$form_state,'deactivate_channel',$url,true);
}
//intelsat-2015
function gestion_canales_custom_access(){
    //if(hontza_canal_rss_is_visualizador_activado()){
        if(red_is_administrador()){
            return TRUE;
        }
    //}
    if(user_access('access gestion_canales')){
        return TRUE;
    }
    return FALSE;
}
//intelsat-2015
function gestion_canales_activar_actualizacion_canal_custom_access(){
    if(hontza_canal_rss_is_visualizador_activado()){
        if(red_is_administrador()){
            return TRUE;
        }
    }
    if(user_access('access activar_actualizacion_canal')){
        return TRUE;
    }
    return FALSE;
}
//intelsat-2015
function gestion_canales_get_canal_noticias_link($canal_nid){
    $result=l(my_get_icono_action('ver_noticias',t('List of News')),'canales/'.$canal_nid.'/ultimas',array('html'=>true));
    return $result;
}
//intelsat-2015
function gestion_canales_get_actualizar_noticias_link($canal_nid,$destination_in=''){
    $title=t('Update Channel');
    $options=array('attributes'=>array('title'=>$title));
    if(!empty($destination_in)){
        $options['query']=$destination_in;
        $options['html']=true;
    }
    return l(my_get_icono_action('actualizar_noticias',$title),'node/'.$canal_nid.'/import',$options);
}
//intelsat-2016
function gestion_canales_get_grupo_nid_any_value($v,$f){
    $result=$v;
    if($f=='grupo_nid'){
        if(!empty($v)){
            $grupo_nid_array=array_keys($v);
            if(in_array(0,$grupo_nid_array)){
                return '';
            }
        }
    }
    return $result;
}