<?php
require_once('custom_menu.red.inc.php');
function custom_menu_perm(){
    $perm_array=array();    
    return $perm_array;
}
function custom_menu_menu(){
    $items=array();
    $items['custom_menu/red_grupos_subdominios'] = array(
    'title' => 'Groups',
    'page callback' => 'custom_menu_red_grupos_subdominios_callback',
    'access callback' => TRUE,
    );
    return $items;
}    
function custom_menu_get_menu_desplegable(){
    if(custom_menu_is_activado()){
        //$grupos_array=hontza_grupos_mis_grupos_form(1);
        //$grupos_array=custom_menu_get_grupos_array($rows);
        $grupos_array=custom_menu_red_get_grupos_db_array($rows,1);
        $html=array();
        /*$ul_style=custom_menu_get_ul_style();
        $html[]='<ul id="ul_ver_mas"'.$ul_style.'>';*/
        $ul_class=custom_menu_get_ul_class();
        $html[]='<ul id="ul_ver_mas" class="'.$ul_class.'">';
        //$style=' style="padding-top:0;padding-bottom:0;cursor:pointer;"';
        //$style=' style="cursor:pointer;"';
        $style='';
        $temp=0;
        if(!empty($grupos_array)){
            //intelsat-2015
            //if(red_crear_usuario_is_activado()){
                custom_menu_add_grupos_apuntarse_link($html,$temp,$style);
            //}
            $num=count($grupos_array);
            foreach($grupos_array as $i=>$row){
                //$html[]='<li>'.$row[0].'</li>';                
                if(custom_menu_is_grupo_local($row)){
                    $grupo_id='';
                    if(isset($rows[$i])){
                        $grupo_id=$rows[$i]->value;
                    }                    
                    $li_id=custom_menu_get_li_id($row,$grupo_id);
                    //$href=custom_menu_get_href($row);
                    $html[]='<li id="'.$li_id.'" class="li_grupo_custom_menu li_pointer" my_pos="'.$i.'" grupo_id="'.$grupo_id.'"'.$style.'>'.$row.'</li>';
                }else{
                    $id='';
                    $konp=custom_menu_get_all_my_groups_link();
                    if($konp==$row){
                        $id=' id="id_all_groups"';
                    }
                    $html[]='<li '.$id.'class="sin_menu_tabs li_pointer"'.$style.'>'.$row.'</li>';
                }    
            }
        }else{
            //intelsat-2015
            $html[]=custom_menu_get_menu_desplegable_get_usuario_sin_grupos($style);
        }
        $html[]='</ul>';
        if(custom_menu_is_menu_tabs_desplegable_activado()){
            $html[]=custom_menu_get_menu_tabs_desplegable();
        }
        $html=implode('',$html);
         $js=custom_menu_add_js_menu_desplegable($rows);
         return $js.$html;
    }     
}
function custom_menu_add_js_menu_desplegable($rows){
    global $base_path;
    global $base_url;
    $is_grupo_sel=0;
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){ 
       $is_grupo_sel=1;
    }
    $js='
        var base_path_js="'.$base_path.'";
        var base_url_js="'.$base_url.'/";
        var is_grupo_sel='.$is_grupo_sel.';
        $(document).ready(function()
        {
            var grupo_submenu_array=new Array();
            '.custom_menu_get_js_grupo_submenu_array($rows).'        
            $("#id_ver_mas").click(function(e){
                e.stopPropagation(); 
                show_custom_menu(true);
                return false;
            });
            //if(is_grupo_sel){
                $(".li_grupo_custom_menu").mouseover(function(e){
                //$(".li_grupo_custom_menu").click(function(e){
                    e.stopPropagation();
                    show_grupo_custom_menu(true,$(this).attr("id"),$(this).attr("my_pos"),$(this).find("a").attr("href"),$(this).attr("grupo_id"));                    
                    /*$(".li_tabs_desplegable").css("background-color","#D6E1E0");
                    $(".li_grupo_custom_menu").css("background-color","#D6E1E0");
                    $(".sin_menu_tabs").css("background-color","#D6E1E0");*/
                    //
                    $(".li_tabs_desplegable").removeClass("li_seleccionado");
                    $(".li_grupo_custom_menu").removeClass("li_seleccionado");
                    $(".sin_menu_tabs").removeClass("li_seleccionado");
                    $(".li_tabs_desplegable").removeClass("li_no_seleccionado");
                    $(".li_grupo_custom_menu").removeClass("li_no_seleccionado");
                    $(".sin_menu_tabs").removeClass("li_no_seleccionado");
                    //
                    $(".li_tabs_desplegable").addClass("li_no_seleccionado");
                    $(".li_grupo_custom_menu").addClass("li_no_seleccionado");
                    $(".sin_menu_tabs").addClass("li_no_seleccionado");
                    //$(this).css("background-color","#FFFFFF");
                    $(this).removeClass("li_no_seleccionado");
                    $(this).removeClass("li_seleccionado");
                    $(this).addClass("li_seleccionado");
                    return false;
                });
            //}
            li_grupo_custom_menu_click();
            /*$(".li_grupo_custom_menu").mouseout(function(e){
                //e.stopPropagation(); 
                //show_grupo_custom_menu(false,"","","","");
                //$(this).css("background-color","#D6E1E0");
                $(this).removeClass("li_seleccionado");
                $(this).removeClass("li_no_seleccionado");
                //
                $(this).addClass("li_no_seleccionado");
                return false;
            });*/
            $(".sin_menu_tabs").mouseover(function(e){
                e.stopPropagation();
                /*$(".li_grupo_custom_menu").css("background-color","#D6E1E0");
                $(".sin_menu_tabs").css("background-color","#D6E1E0");*/
                $(".li_grupo_custom_menu").removeClass("li_seleccionado");
                $(".li_grupo_custom_menu").removeClass("li_no_seleccionado");
                $(".sin_menu_tabs").removeClass("li_seleccionado");
                $(".sin_menu_tabs").removeClass("li_no_seleccionado");
                //
                $(".li_grupo_custom_menu").addClass("li_no_seleccionado");
                $(".sin_menu_tabs").addClass("li_no_seleccionado");
                //
                //$(this).css("background-color","#FFFFFF");
                $(this).removeClass("li_seleccionado");
                $(this).removeClass("li_no_seleccionado");
                //
                $(this).addClass("li_seleccionado");
                show_grupo_custom_menu(false,"","","","");
                return false;
            });
            $(document).click(function() { 
                show_custom_menu(false);
                show_grupo_custom_menu(false,"","","","");
            });
            $(document).mouseover(function() {
                //$(".li_grupo_custom_menu").css("background-color","#D6E1E0");
                //$(".li_tabs_desplegable").css("background-color","#D6E1E0");
                $(".li_tabs_desplegable").removeClass("li_seleccionado");
                $(".li_tabs_desplegable").removeClass("li_no_seleccionado");
                $(".li_tabs_desplegable").addClass("li_no_seleccionado");
            });            
            li_tabs_desplegable_mouseover();
            li_tabs_desplegable_click();
            $("#id_all_groups").click(function(){
                var url=$(this).find("a").attr("href");
                window.open(url);
                return false;
            });
            function show_custom_menu(show_type){
                //$(".li_grupo_custom_menu").css("background-color","#D6E1E0");
                $(".li_grupo_custom_menu").removeClass("li_seleccionado");
                $(".li_grupo_custom_menu").removeClass("li_no_seleccionado");
                $(".li_grupo_custom_menu").addClass("li_no_seleccionado");
                $(".sin_menu_tabs").removeClass("li_seleccionado");
                $(".sin_menu_tabs").removeClass("li_no_seleccionado");
                $(".sin_menu_tabs").addClass("li_no_seleccionado");
                var my_display=$("#ul_ver_mas").css("display");
                var my_value="none";
                //if(my_display=="none"){
                    if(show_type){
                        my_value="block";
                    }    
                //}
                $("#ul_ver_mas").css({display: my_value});
                if(my_value=="none"){
                    show_grupo_custom_menu(false,"","","","");
                }
                return false;
            }
            function show_grupo_custom_menu(show_type,li_id,my_pos,grupo_href,grupo_id){
                if(show_type){
                    if(li_id.length>0){
                        //alert("grupo_href="+grupo_href);
                        //update_url_grupo_custom_menu(li_id,grupo_href,my_pos,grupo_id);
                        update_url_grupo_custom_menu_html(li_id,grupo_href,my_pos,grupo_id);
                    }
                }    
                var my_display=$("#ul_tabs_desplegable").css("display");
                var my_value="none";
                var max_margin_top=442;
                max_margin_top=626;
                //if(my_display=="none"){
                    if(show_type){
                        margin_top=120+my_pos*45+my_pos*1;
                        if(margin_top>=max_margin_top){
                            margin_top=max_margin_top;
                        }
                        $("#ul_tabs_desplegable").css("margin-top",margin_top);
                        my_value="block";
                    }    
                //}
                $("#ul_tabs_desplegable").css({display: my_value});
                return false;
            }
            function update_url_grupo_custom_menu(li_id,grupo_href,my_pos,grupo_id){
                //var grupo_string=li_id.replace("li_grupo_string_","");
                var grupo_string=grupo_id;
                grupo_string=get_grupo_string_by_grupo_href(grupo_string,grupo_href);
                my_index=0;
                $(".a_tabs_desplegable").each(function() {
                    var href=$(this).attr("href");
                    //href=update_href_grupo_string(href,grupo_string,grupo_href,my_index);
                    if(grupo_submenu_array[grupo_string][my_index]){
                        href=grupo_submenu_array[grupo_string][my_index];
                    }else{
                        //alert(grupo_href);
                        if(grupo_submenu_array[grupo_string+"_remoto"][my_index]){    
                            href=grupo_submenu_array[grupo_string+"_remoto"][my_index];
                        }    
                    }
                    $(this).attr("href",href);
                    my_index++;
                });
                is_grupo_sel=1;
            }
            function update_href_grupo_string(href,grupo_string,grupo_href_in,my_index){
                var grupo_href=grupo_href_in;
                grupo_href=unset_red_destination(grupo_href);
                if(is_grupo_red(grupo_href)){                    
                    result=grupo_href+"&red_destination="+grupo_string+"/"+get_tab_url_by_pos(my_index);
                    return result;
                }else{
                    result=base_url_js+grupo_string+"/"+get_tab_url_by_pos(my_index);
                    return result;
                }
                var s=href.replace(base_url_js,"");
                var result="";
                var my_array="";
                if(base_path_js.length>1){
                    s=s.replace(base_path_js,"");                    
                    my_array=s.split("/");
                    if(is_grupo_sel==1){                        
                        my_array[0]=grupo_string;                    
                        //result=base_url_js+my_array.join("/");
                    }else{
                        new_array=new Array();
                        new_array.push(grupo_string);
                        my_array=new_array.concat(my_array);
                    }
                    result=base_url_js+my_array.join("/");
                    //result=result.replace(/\/\//g,"/");
                }else{
                    my_array=s.split("/");
                    my_array=unset_empty_array(my_array);
                    if(is_grupo_sel==1){  
                        my_array[0]=grupo_string;
                    }else{
                        new_array=new Array();
                        new_array.push(grupo_string);
                        my_array=new_array.concat(my_array);
                    }
                    result=base_url_js+my_array.join("/");
                    //alert(result);
                }
                return result;
            }
            function unset_empty_array(my_array){
                var result=new Array();
                var num=my_array.length;
                var i=0;
                for(i=0;i<num;i++){
                    if(my_array[i].length>0){
                        result.push(my_array[i]);
                    }
                }
                return result;
            }
            function is_grupo_red(grupo_href){
                var pos=grupo_href.indexOf("authenticate_local"); 
                if(pos>=0){
                    return 1;
                }
                pos=grupo_href.indexOf("authenticate_red_alerta"); 
                if(pos>=0){
                    return 1;
                }
                return 0;
            }
            function get_tab_url_by_pos(my_pos){
                if(my_pos==1){
                    return "estrategias/arbol_estrategico";
                }else if(my_pos==2){
                    return "mi-grupo";
                }else if(my_pos==3){
                    return "fuentes-pipes/todas";
                }else if(my_pos==4){
                    return "vigilancia/pendientes";
                }else if(my_pos==5){
                    return "area-debate";
                }else if(my_pos==6){
                    return "area-trabajo";
                }else if(my_pos==7){
                    return "alerta_user/inicio";
                 }else if(my_pos==8){
                    return "ideas";
                }
                
                return "dashboard";
            }
            function unset_red_destination(grupo_href){
                var pos=grupo_href.indexOf("&red_destination=");
                if(pos>=0){
                    var result=grupo_href.substring(0,pos);
                    //alert("result===="+result);
                    return result;
                }
                return grupo_href;
            }
            function update_url_grupo_custom_menu_html(li_id,grupo_href,my_pos,grupo_id){
                var grupo_string=grupo_id;
                grupo_string=get_grupo_string_by_grupo_href(grupo_string,grupo_href);
                my_index=0;
                var my_array=new Array();
                if(grupo_submenu_array[grupo_string]){
                    my_array=grupo_submenu_array[grupo_string];
                }else{
                    //alert(grupo_href);
                    if(grupo_submenu_array[grupo_string+"_remoto"]){
                        my_array=grupo_submenu_array[grupo_string+"_remoto"];
                    }
                }
                $("#ul_tabs_desplegable").html("");
                var result_html="";
                var href_value="";
                for(var i=0;i<my_array.length;i++){
                    //result_html+="<li class=\"li_tabs_desplegable\" style=\"padding-top:0;padding-bottom:0;width:80px;cursor:pointer;\"><a href=\""+my_array[i]["href"]+"\" class=\"a_tabs_desplegable\" target=\"_blank\">"+my_array[i]["label"]+"</a></li>";
                    href_value=my_array[i]["href"];
                    href_value=get_grupo_custom_menu_href(grupo_href,href_value);
                    result_html+="<li class=\"li_tabs_desplegable\"><a href=\""+href_value+"\" class=\"a_tabs_desplegable\" target=\"_blank\">"+my_array[i]["label"]+"</a></li>";                
                }
                $("#ul_tabs_desplegable").html(result_html);
                is_grupo_sel=1;
                li_tabs_desplegable_mouseover();
                li_tabs_desplegable_click();
            }
            function li_grupo_custom_menu_click(){
                $(".li_grupo_custom_menu").click(function(e){
                    var url=$(this).find("a").attr("href");
                    //window.location.href=url;
                    window.open(url);
                    show_custom_menu(false);
                    show_grupo_custom_menu(false,"","","","");
                    return false;
                });
            }
            function li_tabs_desplegable_mouseover(){
               $(".li_tabs_desplegable").mouseover(function(e){
                       e.stopPropagation();
                       //$(".li_tabs_desplegable").css("background-color","#D6E1E0");
                       $(".li_tabs_desplegable").removeClass("li_seleccionado");
                       $(".li_tabs_desplegable").removeClass("li_no_seleccionado");
                       $(".li_tabs_desplegable").addClass("li_no_seleccionado");
                       //$(this).css("background-color","#FFFFFF");
                       $(this).removeClass("li_seleccionado");
                       $(this).removeClass("li_no_seleccionado");
                       $(this).addClass("li_seleccionado");
                       return false;
               });
            }
            function li_tabs_desplegable_click(){
                $(".li_tabs_desplegable").click(function(e){
                    var url=$(this).find("a").attr("href");
                    //window.location.href=url;
                    window.open(url);
                    show_custom_menu(false);
                    show_grupo_custom_menu(false,"","","","");
                    return false;
                });
            }
            function get_grupo_custom_menu_href(grupo_href,href_value){
                var result="";
                var grupo_subdominio=get_subdominio_href(grupo_href);
                var href_subdominio=get_subdominio_href(href_value);
                var my_array;                   
                if(grupo_subdominio!=href_subdominio){
                    result=grupo_href;
                    my_array=href_value.split("/"); 
                    if(my_array.length>2){
                        my_array=my_array.slice(3);
                        red_destination=my_array.join("/");
                        result=result+"&red_destination="+red_destination;
                    }
                    return result;
                }
                return href_value;
            }
            function get_subdominio_href(href_value){
                var my_array=href_value.split("/");
                if(my_array.length>2){
                    return my_array[2];
                }
                return "";    
            }
            function get_grupo_string_by_grupo_href(grupo_string,grupo_href){
                return grupo_string;
                var base_url_konp=parse_url_js(grupo_href);
                var konp=base_url_konp.protocol+"//"+base_url_konp.host+"/";
                if(konp==base_url_js){
                    //alert("grupo_string="+grupo_string);
                    return grupo_string;
                }
                konp=base_url_konp.host;
                //alert("grupo_string="+grupo_string+"_"+konp);
                return grupo_string+"_"+konp;
            }
            function parse_url_js(url) {
                var a = document.createElement("a");
                  a.href = url;
                  return {
                    host: a.host,
                    hostname: a.hostname,
                    pathname: a.pathname,
                    port: a.port,
                    protocol: a.protocol,
                    search: a.search,
                    hash: a.hash
                  };
            }
        });';

    //drupal_add_js($js,'inline');
    $result='<script type="text/javascript">';
    $result.=$js;
    $result.='</script>';
    return $result;
}
function custom_menu_is_activado(){
    if(hontza_is_sareko_id('VISUALIZADOR','OBSERVATORIO')){
        return 0;
    }
    if(defined('_IS_CUSTOM_MENU') && _IS_CUSTOM_MENU!=1){
        return 0;
    }
    return 1;
}
function custom_menu_get_grupos_array(&$rows,$is_custom_menu_red=0){
    global $language,$base_url;
    $rows=array();
    $result=array();
    $my_lang='';
    if($language->language!='en'){
        $my_lang=$language->language.'/';
    }
    //
    	$html='';
        //$my_list=my_get_og_grupo_list();
	$my_grupo=og_get_group_context();
        if(!empty($my_grupo) && isset($my_grupo->nid) && !empty($my_grupo->nid)){
            $grupo_nid=$my_grupo->nid;
        }
        $is_resto_grupos=0;
        $is_visualizador_grupos_colaborativos=hontza_canal_rss_is_visualizador_grupos_colaborativos();        
        if(hontza_is_user_anonimo()){
            $is_resto_grupos=1;        
        }
        $my_list=my_get_og_grupo_list('',1,$grupo_nid,1,1,$is_resto_grupos,$is_visualizador_grupos_colaborativos);
        $my_list=red_funciones_unset_shared_group($my_list);
        //if(hontza_is_sareko_id_red(0)){
        //if(hontza_is_sareko_id_red()){
        if(hontza_is_sareko_user()){
            //echo print_r($my_list,1);
            //$grupos_red_alerta=red_get_user_grupos_red_alerta();
            if(hontza_is_servidor_red_alerta()){
                $grupos_red_alerta=red_servidor_grupo_get_grupos_red_alerta();
                //echo print_r($grupos_red_alerta,1);
            }else{
                $grupos_red_alerta=red_compartir_grupo_get_user_grupos_red_alerta();
                //echo print_r($grupos_red_alerta,1);
            }            
            $my_list=array_merge($my_list,$grupos_red_alerta);
            
        }
        $order_field='title';
        $sort='asc';
        /*if(isset($_REQUEST['sort']) && !empty($_REQUEST['sort'])){
            $sort=$_REQUEST['sort'];
        }*/
        $my_list=custom_menu_red_unset_grupos_locales_como_remotos($my_list);
        $my_list=array_ordenatu($my_list,$order_field,$sort,0);
        $my_list=custom_menu_set_max_title_tabs($my_list);
        //
	if(count($my_list)>0){
            $ul_my_resto_grupos_class=custom_menu_get_ul_my_resto_grupos_class();
            	$html.='<div id="div_my_resto_grupos"><ul id="ul_my_resto_grupos" class="ul_menu_desplegable'.$ul_my_resto_grupos_class.'">';
		//$kont=0;
		//for($k=0;$k<6;$k++){
		$barra='|';
		$hasi_orri=custom_menu_get_hasi_orri();
                if(is_user_invitado()){
                    $hasi_orri='/ideas';
                }
                $max=7;
                if(hontza_is_sareko_user()){
                    $max=6;
                }
                //gemini-2014                
                $max=red_funciones_get_grupo_menu_max($my_list,$max);
                //$max=2000;
                $max=14;
                /*if($is_custom_menu_red){
                    $max=custom_menu_red_get_max($max);
                }*/
                //                        
                foreach($my_list as $i=>$row){
                        if($i>=$max){
                            break;
                        }
                        /*if($i>=$max){
				//$my_link=l(utf8_encode('See more'),'mis-grupos');
                                //$my_link=l(t('See more'),'mis-grupos');
                                //intelsat-2015
                                $style=' style="margin-bottom:-23px;"';
                                $my_link=l(my_get_icono_action('ver_mas32',t('See more'),'ver_mas32','',$style),'mis-grupos',array('html'=>TRUE,'attributes'=>array('id'=>'id_ver_mas')));
				//intelsat-2015
                                $menu_desplegable=hontza_canal_rss_get_menu_desplegable();
                                //
                                $html.='<li id="li_menu_desplegable" class="li_menu_desplegable">'.$my_link.$menu_desplegable.'</li>';				
                                break;
			}*/
			if($i==(count($my_list)-1)){
				$barra='';
			}
			//$my_link=l($row->title,'dashboard');
			//$my_link='<a href="/hontza3/node/'.$row->nid.'">'.$row->title.'</a>';
			//$my_link='<a href="/hontza3/'.$row->value.'/dashboard">'.$row->title.'</a>';			
                        //if(isset($row->sareko_id)){
                        $my_action=$hasi_orri;
                        //intelsat-2015
                        $icono_red_alerta=hontza_get_icono_grupo_red_alerta($row);
                        //
                        if(isset($row->is_grupo_red_alerta)){
                            $subdominio='';
                            $user_login_enviar=hontza_define_user_login_enviar();
                            if(hontza_is_grupo_subdominio($row)){
                                $subdominio=$row->subdominio;
                                $my_url='http://'.$row->subdominio.'/';
                                $my_action='red_compartir/authenticate_local';
                            }else{    
                                $my_url=red_compartir_define_redalerta_servidor_url().'/';
                                $my_action='red_servidor/authenticate_red_alerta';
                            }
                            $subdominio=hontza_set_subdominio_id_name($subdominio);
                            $id_a=$subdominio.'login_red_alerta_'.$row->nid;
                            $login_red_alerta_url=$my_url.$my_lang.$my_action.'/'.$row->nid;
                            $privacidad_title=red_funciones_get_grupo_privacidad_name($row);
                            //$my_link='<a id="'.$id_a.'" class="a_login_red_alerta_class" href="'.$login_red_alerta_url.'?user_login_enviar_get='.base64_encode($user_login_enviar).'&red_idioma='.trim($my_lang,'/').'" title="'.$privacidad_title.'">'.hontza_get_icono_grupo_congelado($row,0,$is_congelado).custom_menu_get_icono_grupo_privacidad($row,$privacidad_title,0,$icono_red_alerta).hontza_get_icono_grupo_red_alerta($row).$row->title.'</a>';
                            $icono_privacidad=custom_menu_get_icono_grupo_privacidad($row,$privacidad_title,0,$icono_red_alerta,$title_popup);
                            $privacidad_title=$title_popup;
                            $my_link='<a id="'.$id_a.'" class="a_login_red_alerta_class" href="'.$login_red_alerta_url.'?user_login_enviar_get='.base64_encode($user_login_enviar).'&red_idioma='.trim($my_lang,'/').'" title="'.$privacidad_title.'" target="_blank">'.hontza_get_icono_grupo_congelado($row,0,$is_congelado).$icono_privacidad.$row->title.'</a>';                            
                            hontza_login_red_alerta_formulario($login_red_alerta_url.'&red_idioma='.trim($my_lang,'/'),$row->nid,1,$subdominio,$user_login_enviar);
                            $result[]=$my_link;
                            $rows[]=$row;
                        }else{
                            //intelsat-2015
                            //$my_url='http://'.$_SERVER['HTTP_HOST'].base_path();
                            $my_url=hontza_grupos_mi_grupo_get_grupo_url_by_alias($base_url).'/';
                            $my_action=$hasi_orri;
                            $privacidad_title=red_funciones_get_grupo_privacidad_name($row);
                            //$my_link='<a href="'.$my_url.$my_lang.$row->value.$my_action.'" title="'.$privacidad_title.'">'.hontza_get_icono_grupo_congelado($row,0,$is_congelado).custom_menu_get_icono_grupo_privacidad($row,$privacidad_title,0,$icono_red_alerta).hontza_get_icono_grupo_red_alerta($row).$row->title.'</a>';
                            $icono_privacidad=custom_menu_get_icono_grupo_privacidad($row,$privacidad_title,0,$icono_red_alerta,$title_popup);
                            $privacidad_title=$title_popup;
                            $my_link='<a href="'.$my_url.$my_lang.$row->value.$my_action.'" title="'.$privacidad_title.'" target="_blank">'.hontza_get_icono_grupo_congelado($row,0,$is_congelado).$icono_privacidad.$row->title.'</a>';                        
                            $result[]=$my_link;
                            $rows[]=$row;
                        }    
                        //                        
			$barra='';
                        //if($row->nid!=$grupo_nid || isset($row->sareko_id)){
                        if($row->nid!=$grupo_nid || isset($row->is_grupo_red_alerta)){
                            $html.='<li ><div class="gruponame tipo_grupo_'.$row->type_of_group.'"><div class="block block-hontza block-even region-odd clearfix " id="block-hontza-5"> <div class="content">'.$my_link.$barra.'</div></div></div></li>';
                            //$result[]=$my_link;
                            
                        }else{
                            $my_id='gruponame_no tipo_grupo_'.$row->type_of_group;
                            if($i>0){
                                $my_id='gruponame_no tipo_grupo_'.$row->type_of_group;
                            }
                            $html.='<li ><div class="'.$my_id.'">
                                    <a id="context-block-region-nombredelgrupo" class="context-block-region"></a>
                                    <div class="block block-hontza block-even region-odd clearfix " id="block-hontza-5">
                                            <div class="content">'.$my_link
                                                    .'<a class="context-block editable edit-vigilancia" id="context-block-hontza-5"></a>
                                            </div>
                                    </div>
                            </div></li>';
                            //$result[]=$my_link;
                        }
			//$kont++;
		}
                if(count($my_list)>$max){
                    $result[]=custom_menu_get_all_my_groups_link();
                }
		//}
		$html.='</ul></div>';
	}
	//return $html;
        return $result;
}
function custom_menu_get_icono_grupo_privacidad($row,$title,$is_tab,$icono_red_alerta,&$title_popup){
    if(custom_menu_is_activado()){
        $tid='';
        if(isset($row->type_of_group_tid) && !empty($row->type_of_group_tid)){
            $tid=$row->type_of_group_tid;
        }
        //intelsat-2015
        /*$icono_name='grupo_privado20.png';
        if($tid==27){
            $icono_name='grupo_colaborativo20';
        }else if($tid==28){
            $icono_name='grupo_privado20';
        }else if($tid==29){
            $icono_name='grupo_publico20';
        }
        $result=my_get_icono_action($icono_name,$title,'',array(),'','icono_grupo_red_alerta');*/
        $result=panel_admin_get_tipo_grupo_icono($row,$icono_red_alerta,$tid,$title_popup);
        //intelsat-2015
        //$title_popup=$row->title_orig."\r".$title_popup;
        return $result;
    }
    return '';
}
function custom_menu_is_user_grupo($grupo_nid){
    global $user;
    if(!empty($grupo_nid)){
        if(in_user_groups($grupo_nid)){
            return 1;
        }
        if(hontza_canal_rss_is_visualizador_grupos_colaborativos() && hontza_is_user_anonimo()){
            return 1;
        }
    }
    return 0;
}
function custom_menu_get_menu_tabs_desplegable(){
    $html=array();
    //$menutop=my_get_menutop('',0,1);
    //$tabs_array=custom_menu_get_tabs_desplegable_array($menutop);
    $tabs_array=custom_menu_get_tabs_array();
    /*$ul_style=custom_menu_get_ul_style(1);
    $html[]='<ul id="ul_tabs_desplegable"'.$ul_style.'>';*/
    $ul_class=custom_menu_get_ul_class(1);
    $html[]='<ul id="ul_tabs_desplegable" class="'.$ul_class.'">';
    //$style=' style="padding-top:0;padding-bottom:0;width:80px;cursor:pointer;"';
    if(!empty($tabs_array)){
        foreach($tabs_array as $i=>$value){
            //$html[]='<li class="li_tabs_desplegable"'.$style.'>'.$value.'</li>';
        }
    }
    $html[]='</ul>';
    return implode('',$html);
}
function custom_menu_get_tabs_desplegable_array($menutop){
    $result=array();
    $find='href="';
    $my_array=explode($find,$menutop);
    if(!empty($my_array)){
        foreach($my_array as $i=>$value){
            if($i>0){
                $my_value=$value;
                $my_value=str_replace(' class="active"','',$my_value);
                $pos=strpos($my_value,'"');
                if($pos===FALSE){
                    continue;
                }else{
                    $url=substr($my_value,0,$pos);
                    $url=hontza_solr_search_prepare_redirect_url($url);
                    $label=substr($my_value,$pos+2);
                    $pos2=strpos($label,'</a>');
                    if($pos2===FALSE){
                        continue;
                    }else{
                        $label=substr($label,0,$pos2);
                        $result[]=l($label,$url,array('attributes'=>array('class'=>'a_tabs_desplegable','target'=>'_blank')));
                    }    
                }
            }    
        }
    }
    return $result;
}
function custom_menu_get_li_id($value,$grupo_id){
    return 'li_grupo_string_'.$grupo_id;
    /*$find='href="';
    $pos=strpos($value,$find);
    if($pos===FALSE){
        return '';
    }else{
        $url=substr($value,$pos+strlen($find));
        $pos2=strpos($url,'"');
        if($pos2===FALSE){
            return '';
        }else{
            $url=substr($url,0,$pos2);
            $grupo_string=custom_menu_get_grupo_string($url);
            return 'li_grupo_string_'.$grupo_string;
        }    
    }
    return '';*/
}
function custom_menu_get_grupo_string($url){
    global $base_url;
    $result=str_replace($base_url.'/','',$url);
    $result=str_replace('/dashboard','',$result);
    return $result;
}
function custom_menu_set_max_title_tabs($my_list,$is_tab=0){
    $result=$my_list;
    $max=custom_menu_define_grupo_title_max_len($is_tab);
    if(!empty($result)){
        foreach($result as $i=>$row){
            $len=strlen($row->title);
            //intelsat-2015
            $result[$i]->title_orig=$row->title;
            if($len>$max){
                $result[$i]->title=substr($row->title,0,$max)."...";                
            }
        }
    }
    return $result;
}
function custom_menu_define_grupo_title_max_len($is_tab=0){
    //intelsat-2015
    if($is_tab){
        return 98;
    }else{
    //    
        //intelsat-2015
        //return 20;
        return 33;
    }
}
function custom_menu_is_menu_tabs_desplegable_activado(){
    return 1;    
}
function custom_menu_is_grupo_local($row){
    //$my_array=array('_gris','_verde');
    $my_array=array('_gris','_verde','_azul','_rojo');
    if(!empty($my_array)){
        foreach($my_array as $i=>$value){
            $pos=strpos($row,$value);
            if($pos===FALSE){
                continue;
            }else{
                return 1;
            }
        }    
    }
    return 0;
}
function custom_menu_get_href($row){
    $find='href="';
    $pos=strpos($row,$find);
    if($pos===FALSE){
        return '';
    }else{
        $url=substr($row,$pos+strlen($find));
        $pos2=strpos($url,'"');
        if($pos2===FALSE){
            return '';
        }else{
            $result=substr($url,0,$pos2);
            return $result;
        }    
    }
    return '';
}
function custom_menu_get_tabs_array(){
    $result=array();
    $attributes=array('attributes'=>array('class'=>'a_tabs_desplegable','target'=>'_blank'));
    $result[]=l(t('Home'),'dashboard',$attributes);
    //intelsat-2015
    $is_usuario_basico=hontza_canal_rss_is_usuario_basico();
    if(!$is_usuario_basico){
        if(hontza_grupos_is_activo_pestana('estrategia')){
            $result[]=l(t('Strategy'),'estrategias/arbol_estrategico',$attributes);
        }    
        $result[]=l(t('Group'),'mi-grupo',$attributes);
        //$result[]=l(t('Sources'),'fuentes-pipes/todas',$attributes);
    }
    $result[]=l(t('Monitoring'),'vigilancia/pendientes',$attributes);
    //intelsat-2015
    if(!$is_usuario_basico){
        if(hontza_grupos_is_activo_pestana('debate')){
            $result[]=l(t('Discussion'),'area-debate',$attributes);
        }
        if(hontza_grupos_is_activo_pestana('wiki')){
            $result[]=l(t('Collaboration'),'area-trabajo',$attributes);
        }
    }    
    $result[]=l(t('Bulletins'),'alerta_user/inicio',$attributes);
    //intelsat-2015
    if(!$is_usuario_basico){
        if(hontza_grupos_is_activo_pestana('idea','')){
            $result[]=l(t('Proposals'),'ideas',$attributes);
        }
    }    
    return $result;
}
function custom_menu_get_js_grupo_submenu_array($rows){
    $result=array();
    if(!empty($rows)){
        if(hontza_canal_rss_is_visualizador_grupos_colaborativos()){
            $result=custom_menu_get_js_grupo_submenu_visualizador_array($rows);
        }else{
            $result=custom_menu_get_js_grupo_submenu_no_visualizador_array($rows);
        }            
    }    
    return implode("\n",$result);
}
function custom_menu_get_ul_style($is_menu_tabs=0){
    $wa='';
    if($is_menu_tabs){
        $wa='width:80px;';
    }
    $top='-5';
    if(is_super_admin()){
        $top='15';
    }
    return ' style="'.$wa.'top:'.$top.'px;"';
}
function custom_menu_get_ul_class($is_menu_tabs=0){
    $class_array=array();
    if($is_menu_tabs){
        $class_array[]='is_menu_tabs';
    }
    $class_array[]='custom_top_menu_user';
    if(is_super_admin()){
        $class_array[]='custom_top_menu_superadmin';
    }
    return implode(' ',$class_array);
}
function custom_menu_get_all_my_groups_link(){    
    return l(t('All my groups'),'mis-grupos');
    //return l(t('All my groups'),'mis-grupos',array('attributes'=>array('target'=>'_blank')));
}
//intelsat-2015
function custom_menu_get_menu_desplegable_get_usuario_sin_grupos($style){
    if(hontza_is_user_anonimo()){
        return '';
    }
    $html=array();
    $i=0;
    if(red_crear_usuario_is_rol_administrador_creador_grupo()){
        $li_id='li_crear_grupo';
        $grupo_id='crear_grupo';
        $url=l(t('Create Group'),'node/add/grupo',array('attributes'=>array('target'=>'_blank')));
        $html[]='<li id="'.$li_id.'" class="li_grupo_custom_menu li_pointer" my_pos="'.$i.'" grupo_id="'.$grupo_id.'"'.$style.'>'.$url.'</li>';
        $i++;
    }
    //if(custom_menu_is_grupos_apuntarse()){
        custom_menu_add_grupos_apuntarse_link($html,$i,$style);
    //}
    return implode('',$html);
}
//intelsat-2015
function custom_menu_is_grupos_apuntarse(){
    $grupos_array=crear_usuario_get_grupos_assoc();
    if(!empty($grupos_array)){
        return 1;
    }
    return 0;
}
//intelsat-2015
function custom_menu_add_grupos_apuntarse_link(&$html,&$i,$style){
    if(hontza_is_user_anonimo()){
        return '';
    }
    $li_id='li_grupos_apuntarse';
    $grupo_id='grupos_apuntarse';
    //$url='crear_usuario/grupos_apuntarse';
    //intelsat-2016
    //$url='mis-grupos';
    $url='mis-grupos/este_servidor';
    //$label=t('List of groups');
    $label=t('My groups on this server');
    $url=l($label,$url,array('attributes'=>array('target'=>'_blank')));
    $html[]='<li id="'.$li_id.'" class="li_grupo_custom_menu li_pointer" my_pos="'.$i.'" grupo_id="'.$grupo_id.'"'.$style.'>'.$url.'</li>';
    $i++;
}
function custom_menu_get_hasi_orri(){
    $result='/dashboard';
    if(hontza_canal_rss_is_visualizador_grupos_colaborativos() && hontza_is_user_anonimo()){
        $result='/visualizador/inicio';
    }
    return $result;
}     
function custom_menu_get_ul_my_resto_grupos_class(){
    $result='';
    if(hontza_canal_rss_is_visualizador_grupos_colaborativos() && hontza_is_user_anonimo()){
        $result=' ul_my_resto_grupos_class';
    }
    return $result;
}
function custom_menu_get_js_grupo_submenu_no_visualizador_array($rows){
    global $base_url;    
    $result=array();
    if(!empty($rows)){
        foreach($rows as $i=>$row){
            /*if(user_access('root')){
                echo print_r($row,1);
            }*/
            //intelsat-2015
            $grupo_node='';
            $row_value=$row->value;
            /*if(isset($row->subdominio) && !empty($row->subdominio)){        
                $row_value.='_'.$row->subdominio;
            }*/
            if(empty($row) || hontza_grupos_mi_grupo_is_grupo_local($row)){
                $grupo_node=node_load($row->nid);
            }/*else{
                $row_value.='_remoto';
            }*/
            //intelsat-2015
            $is_usuario_basico=hontza_canal_rss_is_usuario_basico();            
            $result[]='var kont=0;';
            $result[]='grupo_submenu_array["'.$row_value.'"]=new Array();';
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Home').'";';
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/dashboard";';            
            $result[]='kont++;';
            //intelsat-2015
            if(!$is_usuario_basico){            
                if(hontza_grupos_is_activo_pestana('estrategia','',$grupo_node,$row)){
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Strategy').'";';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/estrategias/arbol_estrategico";';                
                    $result[]='kont++;';
                }
            }                
            //intelsat-2015
            if(!$is_usuario_basico){
                $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
                $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Group').'";';
                $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/mi-grupo";';            
                $result[]='kont++;';
                /*$result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
                $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Sources').'";';
                $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/fuentes-pipes/todas";';
                $result[]='kont++;';*/
            }
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Monitoring').'";';
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/vigilancia/pendientes";';
            $result[]='kont++;';
            //intelsat-2015
            if(!$is_usuario_basico){
                if(hontza_grupos_is_activo_pestana('debate','',$grupo_node,$row)){
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Discussion').'";';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/area-debate";';
                    $result[]='kont++;';
                }
                if(hontza_grupos_is_activo_pestana('wiki','',$grupo_node,$row)){
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Collaboration').'";';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/area-trabajo";';
                    $result[]='kont++;';
                }
            }    
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Bulletins').'";';
            $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/alerta_user/inicio";';
            $result[]='kont++;';
            //intelsat-2015
            if(!$is_usuario_basico){
                if(hontza_grupos_is_activo_pestana('idea','',$grupo_node,$row)){
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]=new Array();';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["label"]="'.t('Proposals').'";';
                    $result[]='grupo_submenu_array["'.$row_value.'"][kont]["href"]="'.$base_url.'/'.$row->value.'/ideas";';
                    $result[]='kont++;';
                }
            }    
        }
    }    
    return $result;    
}
function custom_menu_get_js_grupo_submenu_visualizador_array($rows){
    global $base_url;
    global $language;
    $my_lang='';
    if($language->language!='en'){
        $my_lang='/'.$language->language;
    }
    $result=array();
    if(!empty($rows)){
        foreach($rows as $i=>$row){
            $grupo_node=node_load($row->nid);
            $result[]='var kont=0;';
            $result[]='grupo_submenu_array["'.$row->value.'"]=new Array();';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]=new Array();';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["label"]="'.t('Home').'";';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["href"]="'.$base_url.$my_lang.'/'.$row->value.'/visualizador/inicio";';            
            $result[]='kont++;';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]=new Array();';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["label"]="'.t('The Project').'";';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["href"]="'.$base_url.$my_lang.'/'.$row->value.'/visualizador/project";';                  
            $result[]='kont++;';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]=new Array();';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["label"]="'.t('Latest News').'";';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["href"]="'.$base_url.$my_lang.'/'.$row->value.'/publico/vigilancia/ultimos";';                  
            $result[]='kont++;';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]=new Array();';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["label"]="'.t('Bulletins').'";';
            $result[]='grupo_submenu_array["'.$row->value.'"][kont]["href"]="'.$base_url.$my_lang.'/'.$row->value.'/publico/alerta_user/mis_boletines_grupo";';                  
            $result[]='kont++;';
        }
    }
    return $result;
}
function custom_menu_cron(){
    if(custom_menu_red_is_activado()){
        custom_menu_red_grupos_subdominios();
    }
}