<?php
//gemini-2013
require_once($_SERVER['DOCUMENT_ROOT'].base_path().'sites/all/libraries/datetimeselect/class.datetimeselect.php');
//gemini-2014
require_once('hontza_grupos.mi_grupo.inc.php');
/**
 * Implementation of hook_perm().
 */
function hontza_grupos_perm() {
  return array('Group selector');
}

function hontza_grupos_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':
      //Crear un vocabulario para cada grupo creado asociandolo.
      if ($node-> type=='grupo') {
         //create_grupo_chat($node);
		 $vocabulary = array(
            'name'  => $node->purl['value'],
            'description' => $node->og_description,
            'multiple'  => 1,
            'required'  => 0,
            'hierarchy' => 1,
            'relations' => 0,
             //intelsat-2015
             //se ha añadido my_report,debate,wiki        
            'nodes' => array('canal_busqueda' => 1, 'canal_de_supercanal' => 1, 'canal_de_yql' => 1,'my_report'=>1,'debate'=>1,'wiki'=>1),
            'weight'        => 0,
            'og' => $node->nid,
        );
        taxonomy_save_vocabulary($vocabulary);
        //gemini
	my_create_categoria_indefinida($vocabulary['vid']);
        //gemini-2013
        //hontza_grupos_on_save($node,$op);
        //intelsat-2016
        //hontza_grupos_mi_grupo_registrar_on_grupo_node_save($node,$op);
        hontza_grupos_mi_grupo_registrar_set_session_grupo_nid_saved($node,$op);
      }
    break;
    case 'presave':
        hontza_grupos_on_presave($node,$op);
        break;
    case 'delete':
          //gemini-2014
          //hontza_grupos_on_delete_grupo($node);  
          break;
	//gemini
	case 'update':
            if ($node-> type=='grupo') {
                create_grupo_chat($node);
                //gemini-2013
                //hontza_grupos_on_save($node,$op);
                 //intelsat-2016
                 //hontza_grupos_mi_grupo_registrar_on_grupo_node_save($node,$op);
                hontza_grupos_mi_grupo_registrar_set_session_grupo_nid_saved($node,$op);
            }
            break;	  
    case 'load':
      
    break;
  }
}

/**
 *Implementation of hook_form_alter
 */
function hontza_grupos_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    
    //gemini-2014
    if(strcmp($form_id,'contact_mail_user')==0){
        hontza_grupos_mi_grupo_contact_mail_user_form_alter($form, $form_state, $form_id);
    }else if(strcmp($form_id,'grupo_node_form')==0){
        //gemini-2014
        $form['title']['#title']=t('Title');
        //
        $node=my_get_node();
        $grupo_nid='';
        if(isset($node->nid) && !empty($node->nid)){
            $grupo_nid=$node->nid;
        }
        //
        $form['old_admin_uid']=array(
            '#type'=>'hidden',
            '#default_value'=>$node->field_admin_grupo_uid[0]['value'],
        );
        //gemini-2013
        $user_options=array();
        $user_options=get_usuarios_grupo_options($grupo_nid,1,1);
        if(!isset($user_options[1])){
            $user_options[1]='admin';
            asort($user_options);
        }
        //gemini-2014
        $user_options=hontza_grupos_set_creador_en_user_options($grupo_nid,$user_options);
        $admin_grupo_default=$user->uid;
        if(isset($node->field_admin_grupo_uid[0]['value']) && !empty($node->field_admin_grupo_uid[0]['value'])){
            $admin_grupo_default=$node->field_admin_grupo_uid[0]['value'];
        }
        $admin_grupo_default=hontza_grupos_set_admin_grupo_default_by_user_options($user_options,$admin_grupo_default);
        //gemini-2014
        //if(is_super_admin() || (hontza_grupos_mi_grupo_is_propietario_del_grupo($node))){
        $group_owner_uid=$user->uid;
        if(isset($node->nid) && !empty($node->nid)){
            $group_owner_uid=$node->uid;
        }
        
            $form['creator_uid']=array(
                  '#title'=>t('Group Owner'),                
                  '#type'=>'select',
                  '#options'=>$user_options,
                  '#default_value'=>$group_owner_uid,
                  '#description'=>t('Select a user to transfer your Group Ownership rights. This includes the exclusive rights of editing group settings and adding or subtracting members to the group.'),  
            );
        //}
        //if(isset($node->nid) && !empty($node->nid)){
            $form['field_admin_grupo_uid']=array(
              //gemini-2014  
              //'#title'=>t('Group Administrator'),              
              '#title'=>t('Editor in chief'),                
              '#type'=>'select',
              '#options'=>$user_options,
              '#default_value'=>$admin_grupo_default,
              '#description'=>t('Select a user as "Editor in chief". This includes the exclusive rights of launching Customised Bulletins.'),  
            );
        //}else{
            /*$form['field_admin_grupo_uid']=array(
              '#type'=>'hidden',
              '#default_value'=>0,
            );*/
          //  unset($form['field_admin_grupo_uid']);
        //}
        my_translate_taxonomy_in_form($form);
        if(is_node_add('grupo')){
            drupal_set_title(t('Create Group'));
        }
        hontza_grupos_publico_reto_form_alter($form,$form_state,$form_id);
        //gemini-2014
        if(isset($form['field_delete_rejected_news_time'])){
           $form['field_delete_rejected_news_time']['#title']=t('Time delay to delete rejected news');      
           //intelsat-2015
           //if(!is_super_admin()){
           if(!panel_admin_is_editar_tiempos_borrados_noticias_grupo($grupo_nid,$node)){
           //    
               unset($form['field_delete_rejected_news_time']);
               $form['field_delete_rejected_news_time_disabled']=array(
                '#title'=>t('Time delay to delete rejected news'),
                '#type'=>'textfield',
                '#default_value'=>hontza_grupos_get_delete_rejected_news_time_value_string($node),
                '#disabled'=>true,
                '#weight'=>15,   
               );
           }else{
               if(empty($grupo_nid)){
                   //intelsat-2015
                   $field_delete_rejected_news_time_default_value=2;
                   //$field_delete_rejected_news_time_default_value=1;
                   //
                   $form['field_delete_rejected_news_time']['#default_value'][0]['value']=$field_delete_rejected_news_time_default_value;
               }
           }                     
        }
        if(isset($form['field_delete_unread_news_time'])){
          $form['field_delete_unread_news_time']['#title']=t('Time delay to delete unread news'); 
          //intelsat-2015
          //if(!is_super_admin()){
          if(!panel_admin_is_editar_tiempos_borrados_noticias_grupo($grupo_nid)){
          //    
               unset($form['field_delete_unread_news_time']);
               $form['field_delete_unread_news_time_disabled']=array(
                '#title'=>t('Time delay to delete unread news'),   
                '#type'=>'textfield',
                '#default_value'=>hontza_grupos_get_delete_unread_news_time_value_string($node),
                '#disabled'=>true,
                '#weight'=>15,   
               );
           }else{
               if(empty($grupo_nid)){
                   $unread_default_value=6;
                   //$unread_default_value=3;
                   $form['field_delete_unread_news_time']['#default_value'][0]['value']=$unread_default_value;
               } 
           }    
        }
        if(!hontza_is_congelar_canal_sareko_id()){
            if(isset($form['field_group_active_refresh'])){
                unset($form['field_group_active_refresh']);
            }
        }else{
            //gemini-2014
            if(empty($grupo_nid)){
                //$form['field_group_active_refresh']['#attributes']=array('checked'=>'checked');
                $form['field_group_active_refresh']['#default_value'][0]['value']=1;
            }
        }
        //intelsat-2016
        hontza_grupos_mi_grupo_registrar_grupo_node_form_alter($form,$form_state, $form_id,$node);
        hontza_grupos_mi_grupo_registrar_add_grupo_node_form_js($node);
        //$form['buttons']['submit']['#submit'][]='hontza_grupos_mi_grupo_registrar_submit';
        hontza_grupos_mi_grupo_add_grupo_node_registrar_submit($form);
        if(isset($form['field_tematica'])){
            unset($form['field_tematica']);
        }
        if(isset($form['field_grupo_kimonolabs_api_key'])){
            unset($form['field_grupo_kimonolabs_api_key']);
        }
        //       
    }    
}

/**
 * Implementation of hook_menu
 */
function hontza_grupos_menu() {
  $items = array();
  $items['mis-grupos'] = array(
    //'page callback' => 'drupal_get_form',    
    //'page arguments'   => array('mis_grupos', 2),
    'page callback' => 'mis_grupos_callback',        
    'type' => MENU_CALLBACK,
    //intelsat-2015
    //'access callback' => TRUE,
    //'access arguments' => array('Group selector'),
    'access arguments' => array('access content'),  
  );
  //gemini-2014
  $items['mi-grupo'] = array(
    'title'=>'Group',  
    'type' => MENU_CALLBACK,
    'page callback' => 'hontza_grupos_mi_grupo_callback',            
    'access arguments' => array('access content'),
  );  
  $items['hontza_grupos/%/contact'] = array(
    'title' => 'Contact',
    'page callback' => 'hontza_grupos_mi_grupo_contact_form_callback',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access content'),    
  );
  $items['hontza_grupos/usuarios_mas_contacto'] = array(
    'title' => 'List of Users',
    'page callback' => 'hontza_grupos_mi_grupo_usuarios_mas_contacto_callback',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access content'),    
  );
  $items['hontza_grupos/%/user_view'] = array(
    'title' => 'User',
    'page callback' => 'hontza_grupos_mi_grupo_user_view_callback',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('access content'),    
  );
  //
  return $items;
}

/**
 * Form para mostrar grupos
 *
 */
function mis_grupos_form($is_db=1){
    //intelsat-2016
    if(!hontza_grupos_mi_grupo_is_este_servidor()){
        //intelsat-2015    
        if(custom_menu_red_is_activado() && $is_db && custom_menu_red_is_db_request()){
            $form=custom_menu_red_mis_grupos_form_db();
            if(!empty($form)){
                return $form;
            }
        }
    }
    return hontza_grupos_mis_grupos_form(0);        
}    
function hontza_grupos_mis_grupos_form($is_rows=0) {
  global $language;
    $my_lang='';
    if($language->language!='en'){
        $my_lang=$language->language.'/';
    }
    //  
  //intelsat-2015
  //if (user_access('Group selector')) {
  if (user_access('Group selector') || hontza_grupos_mis_grupos_script_access()) {    
  drupal_set_title(t("My Groups"));
  global $user;
  //gemini
  global $base_path,$base_root;
  $my_url_default=$base_root.$base_path;
  //print $my_url.'<BR>';
  //
  $form = array();
    $form['grupos'] = array(
      '#type' => 'fieldset',
      '#title' => t('My Groups'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
  $header = array(
  array('data'=>t('Type'),'field'=>'group_type'),
  array('data'=>t('Server'),'field'=>'server'),    
  array('data' => t('Name'), 'field' => 'node_title'),
  array('data' => t('Channels'), 'field' => 'canales_activados'),     
  array('data' => t('Subject Area'), 'field' => 'subject_area'),    
  //array('data' => t('Type'), 'field' => 'term_data_name'),
  array('data' => t('Users'), 'field' => 'member_count'),
  //array('data' => t('Access'), 'field' => 'enlace'),
  );
  //intelsat-2016
  $header=hontza_grupos_mis_grupos_get_header($header);
$order_by=hontza_grupos_mis_grupos_order_by();
$order_by='';

$kont=0;
/*
if(hontza_is_sareko_id_red(0)){
    $default_array=array('DEFAULT');
    $sareko_id_array=hontza_define_red_sareko_id_array(0);
    $sareko_id_array=array_merge($default_array,$sareko_id_array);
}else{
    $sareko_id_array=array('DEFAULT');
}  
foreach($sareko_id_array as $i=>$sareko_id){
    if(hontza_is_sareko_id($sareko_id)){
        continue;
    }
    $subdomain=strtolower($sareko_id);
    db_set_active($subdomain);
    if($sareko_id=='DEFAULT'){
        $uid=$user->uid;
        $my_url=$my_url_default;
    }else{    
        $uid=red_get_user_uid_by_mail($user->mail);
        $my_url='http://'.$subdomain.'.hontza.es/';
    }*/
    $uid=$user->uid;    
    if(!empty($uid)){
        $rows=hontza_grupos_get_mis_grupos_rows($uid,$order_by,0,0,1);        
    }      
//}
//db_set_active();  
  
  //gemini  
    
  //$my_limit=20;
  //$my_limit=40;
    $my_limit=2000;  
  
    $sort='asc';
    $field='node_title';
    if(isset($_REQUEST['sort']) && !empty($_REQUEST['sort'])){
        $sort=$_REQUEST['sort'];
    }
    $is_numeric=0;
    $is_type_of_group=0;
    if(isset($_REQUEST['order']) && !empty($_REQUEST['order'])){
        $order=$_REQUEST['order'];
        if(in_array($order,array(t('Name'),t('Name')))){
            $field='node_title';
        }else if($order==t('Subject Area')){
            $field='subject_area';
        }else if($order==t('Channels')){
            $field='canales_activados';
        }else if(in_array($order,array(t('Type of Group'),t('Type')))){
            $field='type_of_group';
            $is_type_of_group=1;
        }else if($order==t('Users in the Group')){            
            $field='users_in_group';
            $is_numeric=1;
        }else if($order==t('Server')){
            $field='server';
        }else if($order==t('Thematic Tags')){
            $field='tags';
         }else if($order==t('Geographic Tags')){
            $field='tags_geograficos';
        }
    }
    
    
    //intelsat-2016
    if(!hontza_grupos_mi_grupo_is_este_servidor()){
        $grupos_red_alerta=array();
        if(hontza_is_sareko_user()){    
            $user_login_enviar=  hontza_define_user_login_enviar();
            if(hontza_is_servidor_red_alerta()){
                $grupos_red_alerta=red_servidor_grupo_get_user_grupos_red_alerta_mis_grupos();                
            }else{
                $grupos_red_alerta=red_compartir_grupo_get_user_grupos_red_alerta_mis_grupos();
            }
            $grupos_red_alerta=hontza_grupos_prepare_grupos_red_alerta($grupos_red_alerta,$user_login_enviar);
            $rows=array_merge($rows,$grupos_red_alerta);
        }
    }   
   
      //intelsat-2015
      $rows=hontza_grupos_mi_grupo_prepare_fields($rows);
      $rows=array_ordenatu($rows,$field,$sort,$is_numeric,$is_type_of_group);
      
      /*echo print_r($rows,1);
        exit();*/
      
      $rows=my_set_estrategia_pager($rows,$my_limit);
      
      
      if(!hontza_grupos_hay_congelado($rows)){
          $rows=hontza_grupos_set_title_no_congelados($rows);
      }
     
      $bakup_rows=$rows;
      $rows=hontza_grupos_unset_array($rows,array('node_title'));
      //intelsat-2015
      $rows=hontza_grupos_mi_grupo_unset_fields($rows,$bakup_rows);
      //intelsat-2016
      $rows=hontza_grupos_mi_grupo_get_rows_tags($rows);
      //
    $out = theme('table', $header, $rows);
    $out .= theme( 'pager', NULL, $limit, 0 );
    
    
    $login_red_alerta_formulario_html='';
    //echo print_r($grupos_red_alerta,1);exit();
    if(!empty($grupos_red_alerta)){
        //echo print_r($grupos_red_alerta,1);exit();
        foreach($grupos_red_alerta as $i=>$r){
            $sub='';            
            if(isset($r['subdominio']) && !empty($r['subdominio'])){
                $sub=$r['subdominio'];
                $sub=hontza_set_subdominio_id_name($sub);
            }
            //print 'sub===='.$sub.'<BR>';
            //print $r['login_red_alerta_url'].'<BR>';
            $s=hontza_login_red_alerta_formulario($r['login_red_alerta_url'].'&red_idioma='.trim($my_lang,'/'),$r['my_grupo_nid'],0,$sub,$user_login_enviar);
            $login_red_alerta_formulario_html.=$s;
        }
    }
    variable_set('login_red_alerta_formulario_html',$login_red_alerta_formulario_html);
    
      //intelsat-2015
      if($is_rows){
          return $rows;
      }
      //
    
    $form['grupos']['lista'] = array(
          '#type' => 'item',
          '#value' =>  $out,
    );
    
  return $form;
  }
  else{
  drupal_set_title('No tiene permisos.');
  }
}
//gemini
function my_create_categoria_indefinida($vid){
$term = array(
    'vid' => $vid, // Voacabulary ID
    'name' => 'Categoria indefinida', // Term Name
    'description' => 'Categoria indefinida, para poder importar un rss de una manera simple',
  );

  taxonomy_save_term($term);
}
//gemini
function create_grupo_chat(&$node){
	global $user;
	if(strcmp($node->type,'grupo')==0){
		$grupo_nid=$node->nid;
		//print $grupo_nid;exit();
		$chat_list=my_get_grupo_chat_list($grupo_nid);
		if(empty($chat_list)){
			$my_node=array('type'=>'chat',
			'status'=>1,
			'comment'=>2,
			'promote'=>0,
			'sticky'=>0,
			'uid'=>$user->uid,
			'idle_freq' => 20,
    		'max_users' => 0,
    		'previous_messages_display_count' => 10,
   			'profile_picture' => 1,
			'private'=>1,
			'title'=>'chat '.$node->title,
			);
			//
			$my_node=(object) $my_node;
			node_save($my_node);
			$chat_nid=$my_node->nid;
			//print 'chat_nid='.$chat_nid;exit();
			//funtzio hau sites/default/oportunidad/oportunidad.module-n dago
			insert_chat_my_grupo($chat_nid,$grupo_nid);
			$user_list=my_get_og_grupo_user_list($grupo_nid);
			if(count($user_list)>0){
				foreach($user_list as $i=>$u){
					if($u->uid!=$user->uid){
						//print 'uid='.$u->uid.'<BR>';
						my_insert_chatroom_chat_invite($chat_nid,$user->uid,$u->uid);
						my_insert_chatroom_chat_user($chat_nid,$u->uid);
					}	
				}
			}
			//exit();
		}/*else{
			print 'CREADO';exit();
		}*/
	}
}
//gemini
function my_get_grupo_chat_list($grupo_nid){
	$where=array();
	$where[]="1";
	$where[]="cg.grupo_nid=".$grupo_nid;
	$sql="SELECT * FROM {chat_my_grupo} cg WHERE ".implode(' AND ',$where);
	$res=db_query($sql);
	$result=array();
	while($row=db_fetch_object($res)){
		$result[]=$row;
	}
	return $result;
}
//gemini
function my_insert_chatroom_chat_invite($chat_nid,$inviter_uid,$invitee_uid){
	$sql="INSERT INTO chatroom_chat_invite(nid,inviter_uid,invitee_uid,notified,accepted) 
	VALUES(".$chat_nid.",".$inviter_uid.",".$invitee_uid.",0,0)";
	db_query($sql);
}
//gemini
function my_insert_chatroom_chat_user($chat_nid,$invitee_uid){
	$sql="INSERT INTO chatroom_chat_user(nid,uid) VALUES(".$chat_nid.",".$invitee_uid.")";
	db_query($sql);
}
//gemini
function insert_chat_my_grupo($chat_nid,$grupo_nid){
	$sql="INSERT INTO chat_my_grupo(chat_nid,grupo_nid) VALUES(".$chat_nid.",".$grupo_nid.")";
	db_query($sql);
}
//gemini-2013
function hontza_grupos_get_subject_area_by_node($node){
    if(isset($node->field_tematica) && isset($node->field_tematica[0]) && isset($node->field_tematica[0]['value'])){
        return $node->field_tematica[0]['value'];
    }
    return '';
}
//gemini-2013
function hontza_grupos_mis_grupos_order_by(){
    $sort='asc';
    $field='node_title';
    if(isset($_REQUEST['sort']) && !empty($_REQUEST['sort'])){
        $sort=$_REQUEST['sort'];
    }
    if(isset($_REQUEST['order']) && !empty($_REQUEST['order'])){
        $order=$_REQUEST['order'];
        if($order==t('Name')){
            $field='node_title';
        }
    }
    $result=' ORDER BY '.$field.' '.strtoupper($sort);
    return $result;
}
//gemini-2013
function hontza_grupos_unset_array($rows){
    $result=array();
    if(count($rows)>0){
        foreach($rows as $i=>$r){
            foreach($r as $k=>$v){
                if(is_numeric($k)){
                    $result[$i][$k]=$v;
                }
            }
        }
    }
    return $result;
}
//gemini-2013
function hontza_grupos_publico_reto_form_alter(&$form,&$form_state,$form_id){
    /*$nid=$form['nid']['#value'];
    $is_grupo_publico=0;
    if(!empty($nid)){
        $node=node_load($nid);
        if(estrategia_is_grupo_publico($node)){
            $is_grupo_publico=1;
        }
    }
    //
    $form['grupo_publico_reto_fs']=array(
        '#type'=>'fieldset',
        '#title'=>'Grupo publico',
    );
    $form['grupo_publico_reto_fs']['fecha_reto_propuesta']=array(
        '#value'=>hontza_grupos_create_fecha_reto_propuesta_html('propuesta','Plazo reto propuesta'),        
    );
    $form['grupo_publico_reto_fs']['fecha_reto_comentario']=array(
        '#value'=>hontza_grupos_create_fecha_reto_propuesta_html('comentario','Plazo reto comentario'),        
    );
    $form['grupo_publico_reto_fs']['fecha_reto_evaluacion']=array(
        '#value'=>hontza_grupos_create_fecha_reto_propuesta_html('evaluacion','Plazo reto evaluacion'),        
    );*/ 
}
function hontza_grupos_create_fecha_reto_propuesta_html($type,$label,$ini=0,$end=0){
    $time=time();
    //
    $time_ini=$time;
    $time_end=$time;
    //
    if(!empty($ini)){
        $time_ini=$ini;
    }
    //
    if(!empty($end)){
        $time_end=$end;
    }
    //
    $html=array();
    $my_date=new MyDate('c','fecha_reto_'.$type.'_ini',$time_ini,0,$input_fecha_reto_propuesta_ini);
    $my_date=new MyDate('c','fecha_reto_'.$type.'_end',$time_end,0,$input_fecha_reto_propuesta_end);
    $html[]='<div style="float:left">';
    $html[]='<label><b>'.$label.':</b></label>';
    $html[]='<div><b>Inicio</b>&nbsp;'.$input_fecha_reto_propuesta_ini.'<b>Fin</b>&nbsp;'.$input_fecha_reto_propuesta_end.'</div>';
    $html[]='</div>';
    return implode('',$html);
}
function hontza_grupos_on_presave(&$node,$op){
    if($node->type=='grupo'){
        //if(user_access('root')){
            $type_of_group=hontza_get_type_of_group($node,'hontza_grupos_save',$group_tid);            
            if(!empty($type_of_group) && $type_of_group!='public'){
                $node->og_private=1;
                //$node->space->group->og_private=1;
            }else if($type_of_group=='public'){
                $node->og_private=0;
                //$node->space->group->og_private=0;
            }            
        //}
        //gemini-2014    
        if(isset($node->creator_uid)){
            $node->uid=$node->creator_uid;
        }    
    }
}
function hontza_grupos_on_save(&$node,$op){
    /*if($node->type=='grupo'){
        if(user_access('root')){
            //echo print_r($node,1);exit();
            $type_of_group=hontza_get_type_of_group($node,'',$group_tid);
            if(!empty($type_of_group) && $type_of_group!='public'){
                hontza_grupos_update_og_private($node->nid,1);
            }
        }       
    }*/
}
function hontza_grupos_update_og_private($nid,$private){
    //db_query('UPDATE {og} SET og_private=%d WHERE nid=%d',$private,$nid);     
}
function hontza_grupos_define_active_tabs_options(){
    $result=array();    
    $structure=hontza_grupos_define_active_tabs_structure();
    if(!empty($structure)){
        foreach($structure as $i=>$row){
            $result[$row['value']]=$row['label'];
        }
    }
    return $result;
}
function hontza_grupos_define_active_tabs_default_value(){
    $result=array();
    $options=hontza_grupos_define_active_tabs_options();
    if(!empty($options)){
        $keys=array_keys($options);
        if(!empty($keys)){
            foreach($keys as $i=>$v){
                $result[]=array('value'=>$v);
            }
        }
    }
    return $result;
}
function hontza_grupos_active_access_tab($key){
    if(!hontza_grupos_is_activo_pestana($key)){
        drupal_set_message('The tab not is active in your group','error');
        drupal_access_denied();
        exit();
    }
}
function hontza_grupos_define_active_tabs_structure(){
    $result=array();
    $result[0]['label']=t('Strategy');
    $result[0]['key']='estrategia';
    $result[0]['menu_url']='estrategias/arbol_estrategico';
    $result[0]['value']=1;
    //
    $result[1]['label']=t('Discussion');
    $result[1]['key']='debate';
    $result[1]['menu_url']='area-debate';
    $result[1]['value']=2;
    //
    $result[2]['label']=t('Collaboration');
    $result[2]['key']='wiki';
    $result[2]['menu_url']='area-trabajo';
    $result[2]['value']=3;
    //
    $result[3]['label']=t('Proposals');
    $result[3]['key']='idea';
    $result[3]['menu_url']='ideas';
    $result[3]['value']=4;
    //gemini-2014
    if(hontza_grupos_is_facilitator_activable()){
        $result[4]['label']=t('Experts');
        $result[4]['key']='servicio';
        $result[4]['menu_url']='servicios';
        $result[4]['value']=5;
    }
    //gemini-2014
    if(hontza_is_servidor_red_alerta()){
        $result[5]['label']=t('Docs');
        $result[5]['key']='docs';
        $result[5]['menu_url']='my_doc_list';
        $result[5]['value']=6;
        //
        $result[6]['label']=t('Users');
        $result[6]['key']='users';
        $result[6]['menu_url']='usuarios_acceso/todos';
        $result[6]['value']=6;
    }
    return $result;
}
function hontza_grupos_is_activo_pestana($key,$group_nid_in='',$grupo_node='',$row=''){    
    //return 1;
    //intelsat-2016
    if($key=='fuentes'){
        return 0;
    }
    //intelsat-2015
    if(red_despacho_is_show_custom_activo_pestana($key)){
        return despacho_is_custom_activo_pestana($key);
    }
    if(hontza_grupos_in_shared_menu_keys($key)){
        if(!hontza_grupo_shared_active_tabs_access(1)){
            return 0;
        }
    }
    //intelsat-2015
    $my_grupo='';
    if(isset($grupo_node->nid) && !empty($grupo_node->nid)){
        $my_grupo=$grupo_node;
    }else{
    //    
        if(empty($row) || hontza_grupos_mi_grupo_is_grupo_local($row)){
            if(!empty($group_nid_in)){
                $my_grupo=node_load($group_nid_in);
            }else{
                $my_grupo=og_get_group_context();
            }
        }
    }    
    //intelsat-2015
    //if(!hontza_grupos_mi_grupo_is_grupo_local($row)){
        if(isset($row->is_grupo_red_alerta) && !empty($row->is_grupo_red_alerta) && $row->is_grupo_red_alerta==1){
            /*if(isset($row->activo_tabs) && isset($row->activo_tabs[$key]) && empty($row->activo_tabs[$key])){
                return 0;
            }*/
            return 1;
        }
    //}
    if(!(isset($my_grupo->nid) && !empty($my_grupo->nid))){
        $node=my_get_node();
        $my_grupo=panel_admin_get_node_grupo($node);
    }
    //
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        if(isset($my_grupo->field_group_active_tabs) && !empty($my_grupo->field_group_active_tabs)){
            $pestana_value=hontza_grupos_get_pestana_value($key);
            if(!empty($pestana_value)){
                foreach($my_grupo->field_group_active_tabs as $i=>$row){
                    $value=$row['value'];
                    if(!empty($value)){
                        if($value==$pestana_value){
                            return 1;
                        }
                    }
                }
            }
        }
        //return 0;
    }
    return 0;
    //return 1;
}
function hontza_grupos_get_pestana_value($key){
    $structure=hontza_grupos_define_active_tabs_structure();
    if(!empty($structure)){
        foreach($structure as $i=>$row){
            if($row['key']==$key){
                return $row['value'];
            }
        }
    }
    return '';
}
function hontza_grupos_set_active_menutop($menutop_in){
    global $language;
    $base=base_path();
    $my_grupo=og_get_group_context();
    $purl='';
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $purl=$my_grupo->purl.'/';
    }
    //gemini-2014
    $my_replace='';
    $my_lang='';
    if($language->language!='en'){
        $my_lang=$language->language.'/';
    }
    $my_replace.=$base.$my_lang.$purl;    
    //
    //intelsat-2015
    /*
    $sep='<a href="';
    $is_last=0;
    $my_array=explode($sep,$menutop_in);
    if(!empty($my_array)){
        $num=count($my_array);
        foreach($my_array as $i=>$value){
            if($i<1){
                $html[]=$value;
                continue;
            }
            $pos=strpos($value,'"');
            if($pos===FALSE){
                $html[]=$value;
            }else{
                $url=substr($value,0,$pos);
                $s=str_replace($my_replace,'',$url);
                //print $my_replace.'<BR>';
                //print $s.'<BR>';
                if(!hontza_grupos_is_url_menutop_active($s)){
                    if($i==($num-1)){
                        $is_last=1;
                        $value=hontza_grupos_unset_last_menu($value);
                        $html[]=$value;
                        continue;
                    }else{
                        //continue;
                    }    
                }
                $html[]=$sep.$value;
            }
        }
        
        if($is_last){
            $len=count($html);
            $penultimo=$len-2;
            if($penultimo>=0){
                $html[$penultimo]=hontza_grupos_unset_penultimo_menu($html[$penultimo]);
            }
        }
        
       // return implode($sep,$html);       
       //$result=implode($sep,$html);
       $result=implode('',$html); 
       //print $menutop_in.'====#########################';
       //print $result;exit();
       return $result;
    }
    return $menutop_in;*/
    return hontza_grupos_mi_grupo_set_active_menutop($menutop_in,$my_replace);
}
function hontza_grupos_is_url_menutop_active($s,$group_nid_in=''){
    if(in_array($s,array('fuentes-pipes/todas'))){
        return 0;
    }
    $key=hontza_grupos_get_tab_key($s);
    if(empty($key)){
        return 1;
    }    
    return hontza_grupos_is_activo_pestana($key,$group_nid_in);
}
function hontza_grupos_get_tab_key($s){
    $structure=hontza_grupos_define_active_tabs_structure();
    if(!empty($structure)){
        foreach($structure as $i=>$row){
            if(isset($row['menu_url'])){
                //print $s.'<BR>';
                //$konp=hontza_grupos_prepare_menu_url_konp($s);
                if($row['menu_url']==$s){
                    return $row['key'];
                }
            }    
        }
    }
    return '';
}
//gemini-2014
function hontza_grupos_get_delete_rejected_news_time_value_string($grupo){
    if(module_exists('rejected')){
        $value=rejected_get_delete_rejected_news_time($grupo);
        if(empty($value)){
            $value=2;
        }
        if(!empty($value)){
            if($value>1){
                return $value.' '.t('Months');
            }else{
                return $value.' '.t('Month');
            }
        }    
    }
    return '';
}
function hontza_grupos_define_mis_grupos_sql($order_by, $uid){
    $sql=sprintf("SELECT node.nid AS nid,
                node.title AS node_title,
                term_data.name AS term_data_name,
                term_data.vid AS term_data_vid,
                term_data.tid AS term_data_tid,
                p.value AS enlace,
                (SELECT COUNT(*) FROM og_uid ou INNER JOIN users u ON ou.uid = u.uid WHERE ou.nid = og.nid AND u.status > 0 AND ou.is_active >= 1 AND ou.is_admin >= 0 ) AS member_count
                FROM node node 
                LEFT JOIN term_node term_node ON node.vid = term_node.vid
                LEFT JOIN term_data term_data ON term_node.tid = term_data.tid
                LEFT JOIN og og ON node.nid = og.nid
                LEFT JOIN purl p ON og.nid = p.id
                LEFT JOIN og_uid ug ON og.nid = ug.nid   
                WHERE (node.type in ('grupo')) AND (node.status <> 0) AND ug.uid = %d ".$order_by, $uid);
    return $sql;
}
function hontza_grupos_set_mis_grupos_row($data,$my_url_in,$kont,$hasi_orri='/dashboard',$is_servidor_red_alerta=0,&$rows){
            global $language;
            global $base_url;
            $my_lang='';
            if($language->language!='en'){
                $my_lang=$language->language.'/';
            }
            //gemini-2013
                $node=node_load($data->nid);
                //$rows[] = array(l($data->node_title, $data->enlace .'/dashboard'), $data->term_data_name, $data->member_count, l('Entrar', $data->enlace .'/dashboard'));
                $my_url=$my_url_in;
                $login_red_alerta_url='';
                $subdominio='';
                if($is_servidor_red_alerta){
                    if($is_servidor_red_alerta==1){
                            $my_url=red_compartir_define_redalerta_servidor_url().'/';
                            $my_action='red_servidor/authenticate_red_alerta';
                    }else{
                        $subdominio=$data->subdominio;
                        $my_url='http://'.$subdominio.'/';
                        $my_action='red_compartir/authenticate_local';
                    }                    
                    $subdominio=hontza_set_subdominio_id_name($subdominio);
                            //$my_action='red_compartir/authenticate_red_alerta';
                            $id_a=$subdominio.'login_red_alerta_'.$data->nid;
                            $id_go_a=$subdominio.'login_red_alerta_go_'.$data->nid;
                            $login_red_alerta_url=$my_url.$my_lang.$my_action.'/'.$data->nid;
                            //$my_link='<a id="'.$id_a.'" class="a_login_red_alerta_class" href="'.$login_red_alerta_url.'">'.$row->title.'</a>';
                            //$my_link='<a id="'.$id_a.'" class="a_login_red_alerta_class" href="'.url($my_action.'/'.$row->nid).'">'.$row->title.'</a>';                            
                            //hontza_login_red_alerta_formulario($login_red_alerta_url,$row->nid);
                            $a_class='a_login_red_alerta_class';
                }else{
                    //$url_row=$base_url.base_path().$my_url.$data->enlace.$hasi_orri;
                    $url_row=$base_url.'/'.$my_url.$data->enlace.$hasi_orri;
                    //print $url_row.'<BR>';
                }
                //$rows[] = array(l($data->node_title,$url_row), $data->term_data_name, $data->member_count, l('Entrar', $url_row));
                //gemini-2013
                //$rows[] = array(l($data->node_title,$url_row), $data->term_data_name, get_group_member_count($data), l('Entrar', $url_row));
                if(isset($data->subject_area)){
                    $subject_area=$data->subject_area;                    
                }else{
                    $subject_area=hontza_grupos_get_subject_area_by_node($node);
                }
                $my_term_name=taxonomy_get_term_name_by_language($data->term_data_tid,$data->term_data_name);
                if(isset($data->users_in_group)){
                    $users_in_group=$data->users_in_group;
                }else{
                    $users_in_group=get_group_member_count($data);
                }
                //intelsat-2015
                $icono_privacidad=hontza_grupos_mi_grupo_get_tipo_grupo_icono($data,$data->term_data_tid,$title_popup);
                //
                if($is_servidor_red_alerta){
                    //intelsat-2015
                    $canales_activados=red_funciones_get_subdominio_activado_menu_icono($data,1,1,1,$data->is_grupo_en_subdominio_congelado);
                    //intelsat-2015
                    //$rows[$kont] = array(hontza_get_icono_grupo_congelado($data,1,$is_congelado).hontza_get_icono_grupo_red_alerta($data,1).l($data->node_title,$login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_a,'class'=>$a_class,'title'=>red_funciones_get_grupo_privacidad_name('',$data->term_data_tid)))),$canales_activados,$subject_area,$my_term_name, $users_in_group, l(t('Go'), $login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_go_a,'class'=>$a_class))));
                    //$rows[$kont] = array(hontza_get_icono_grupo_congelado($data,1,$is_congelado).hontza_get_icono_grupo_red_alerta($data,1).l($data->node_title,$login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_a,'class'=>$a_class,'title'=>red_funciones_get_grupo_privacidad_name('',$data->term_data_tid)))),$canales_activados,$subject_area,$icono_privacidad, $users_in_group, l(t('Go'), $login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_go_a,'class'=>$a_class))));                    
                    $rows[$kont] = array(hontza_get_icono_grupo_congelado($data,1,$is_congelado).l($data->node_title,$login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_a,'class'=>$a_class,'title'=>$title_popup,'target'=>'_blank'))),$canales_activados,$subject_area,$icono_privacidad, $users_in_group, l(t('Go'), $login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_go_a,'class'=>$a_class))));                                        
                    //
                    //$rows[$kont]['title_temp']=hontza_get_icono_grupo_red_alerta($data,1).l($data->node_title,$login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_a,'class'=>$a_class)));                                       
                    $rows[$kont]['title_temp']=l($data->node_title,$login_red_alerta_url,array('absolute'=>TRUE,'attributes'=>array('id'=>$id_a,'class'=>$a_class,'title'=>$title_popup,'target'=>'_blank')));                                                                           
                }else{
                    $canales_activados=red_funciones_get_subdominio_activado_menu_icono($data,1,1);
                    //intelsat-2015
                    //$rows[$kont] = array(hontza_get_icono_grupo_congelado($data,1,$is_congelado).hontza_get_icono_grupo_red_alerta($data,1).l($data->node_title,$url_row,array('attributes'=>array('title'=>red_funciones_get_grupo_privacidad_name('',$data->term_data_tid)))),$canales_activados,$subject_area,$my_term_name, $users_in_group, l(t('Go'), $url_row));
                    //$rows[$kont] = array(hontza_get_icono_grupo_congelado($data,1,$is_congelado).hontza_get_icono_grupo_red_alerta($data,1).l($data->node_title,$url_row,array('attributes'=>array('title'=>red_funciones_get_grupo_privacidad_name('',$data->term_data_tid)))),$canales_activados,$subject_area,$icono_privacidad, $users_in_group, l(t('Go'), $url_row));                    
                    $rows[$kont] = array(hontza_get_icono_grupo_congelado($data,1,$is_congelado).l($data->node_title,$url_row,array('attributes'=>array('title'=>$title_popup,'target'=>'_blank'))),$canales_activados,$subject_area,$icono_privacidad, $users_in_group, l(t('Go'), $url_row));                                        
                    //
                    //$rows[$kont]['title_temp']=hontza_get_icono_grupo_red_alerta($data,1).l($data->node_title,$url_row);
                    $rows[$kont]['title_temp']=l($data->node_title,$url_row,array('attributes'=>array('title'=>$title_popup,'target'=>'_blank')));
                }
                //para ordenar
                $rows[$kont]['node_title']=$data->node_title;
                $rows[$kont]['subject_area']=$subject_area;
                $rows[$kont]['type_of_group_tid']=$data->term_data_tid;
                //intelsat-2015
                $rows[$kont]['type_of_group']=$my_term_name;
                //$rows[$kont]['type_of_group']=hontza_grupos_mi_grupo_get_tipo_grupo_icono($data);
                //
                $rows[$kont]['users_in_group']=(int) $users_in_group;
                $rows[$kont]['my_grupo_nid']=$data->nid;
                $rows[$kont]['login_red_alerta_url']=$login_red_alerta_url;
                $rows[$kont]['subdominio']=$subdominio;
                $rows[$kont]['is_congelado']=$is_congelado;
                //intelsat-2015
                $rows[$kont]['canales_activados']=hontza_grupos_set_canales_activados_order_value($canales_activados);               
}
function hontza_grupos_get_mis_grupos_rows($uid,$order_by='',$is_servidor_red_alerta=0,$is_get_content=0,$is_grupo_local=0){
        //$my_url=$my_url_default;
        $consulta= db_query($sql=hontza_grupos_define_mis_grupos_sql($order_by,$uid));
        
          $hasi_orri='/dashboard';
          if(is_user_invitado()){
             $hasi_orri='/ideas';
          }
          $rows=array();
          $kont=0;
          while ($data = db_fetch_object($consulta)) {
                $my_data=clone $data;
                if($is_servidor_red_alerta && $is_get_content){
                    $my_data->is_grupo_red_alerta=1;
                }
                if($is_grupo_local){
                    $my_data->is_grupo_local=1;
                }
                hontza_grupos_set_mis_grupos_row($my_data,'',$kont,$hasi_orri,$is_servidor_red_alerta,$rows);
                $kont++;
                //
          }
    return $rows;      
}
function mis_grupos_callback(){
    $output=drupal_get_form('mis_grupos_form');
    $login_red_alerta_formulario_html=variable_get('login_red_alerta_formulario_html','');
    $output.=$login_red_alerta_formulario_html;
    if(red_crear_usuario_is_activado()){
        //$output.=crear_usuario_grupos_apuntarse_callback(0);
        $output.=crear_usuario_grupos_apuntarse_callback(1);
    }
    return $output;
}
function hontza_grupos_get_subject_area_by_row($row){
    if(isset($row->nid) && !empty($row->nid)){
        $node=node_load($row->nid);
        if(isset($node->nid) && !empty($node->nid)){
            return hontza_grupos_get_subject_area_by_node($node);
        }
    }
    return '';
}
function hontza_grupos_prepare_grupos_red_alerta($grupos_red_alerta,$user_login_enviar){
    $result=$grupos_red_alerta;
    foreach($result as $i=>$row){
        if(isset($result[$i][0]) && !empty($result[$i][0])){
            $result[$i][0]=hontza_grupos_add_user_login_enviar_get_parameter_href($result[$i][0],$user_login_enviar);
            if(isset($result[$i]['title_temp']) && !empty($result[$i]['title_temp'])){
                $result[$i]['title_temp']=$result[$i][0];
            }
        }
        /*if(isset($result[$i][4]) && !empty($result[$i][4])){
            $result[$i][4]=hontza_grupos_add_user_login_enviar_get_parameter_href($result[$i][4],$user_login_enviar,1);              
        }*/
        if(isset($row['type_of_group_tid']) && !empty($row['type_of_group_tid'])){
            //intelsat-2015
            //$my_value=taxonomy_get_term_name_by_language($row['type_of_group_tid'],'',1);
            $my_value=hontza_grupos_mi_grupo_get_tipo_grupo_icono($row,$row['type_of_group_tid'],$title_popup);         
            //
            //$result[$i][2]=$my_value;
            //$result[$i][3]=$my_value;
            $result[$i]['type_of_group']=$my_value;                        
        }
    }    
    return $result;
}
function hontza_grupos_add_user_login_enviar_get_parameter_href($a,$user_login_enviar,$is_go=0){
    global $language;
    $my_lang='';
    if($language->language!='en'){
        $my_lang=$language->language.'/';
    }
    //
    $find='href="';
    $pos=strpos($a,$find);
    if($pos===FALSE){
        return $a;
    }else{            
        $start_pos=$pos+strlen($find);
        $s=substr($a,$start_pos);
        $end_pos=strpos($s,'"');
        if($end_pos===FALSE){
            return $a;
        }else{
            $url=substr($s,0,$end_pos);
            $end_string=substr($s,$end_pos);
            if($is_go){
                $end_string='">'.t('Go').'</a';
            }
            $result=substr($a,0,$start_pos).$url.'?red_idioma='.trim($my_lang,'/').'&user_login_enviar_get='.base64_encode($user_login_enviar).$end_string;
            return $result;
        }
    }    
}
function hontza_grupos_set_admin_grupo_default_by_user_options($user_options,$admin_grupo_default){
    $uid=1;
    if(!empty($admin_grupo_default)){
        if(!empty($user_options)){
            $keys=array_keys($user_options);
            if(in_array($admin_grupo_default,$keys)){
                return $admin_grupo_default;
            }
        }
    }
    return $uid;
}
//gemini-2014
function hontza_grupos_on_delete_grupo(&$node){
    if(isset($node->nid) && !empty($node->nid)){
        $grupo_nid=$node->nid;
        $user_list=hontza_get_usuarios_grupo($grupo_nid);
        if(!empty($user_list)){
            foreach($user_list as $i=>$u){
               if(isset($u->uid) && !empty($u->uid)){
                   if($u->uid!=1){
                           $num_grupos=0; 
                           if(isset($u->og_groups) && !empty($u->og_groups)){
                                $grupo_nid_array=array_keys($u->og_groups);                           
                                $num_grupos=hontza_grupos_get_num_grupos_despues_de_borrar_grupo($grupo_nid,$grupo_nid_array);
                           }
                           if($num_grupos<1){
                               //print $u->name.'=hay que borrar el usuario';
                               hontza_grupos_user_delete($u->uid);
                           }else{
                               /*print '#########################<BR>';
                               print 'num_grupos='.$num_grupos.'<BR>';
                               print $u->name.'=no borrar usuario<BR>';*/
                               continue;
                           }
                       
                   }
               }
            }
        }
    }

}
//gemini-2014
function hontza_grupos_get_num_grupos_despues_de_borrar_grupo($grupo_nid,$grupo_nid_array){
    if(!empty($grupo_nid_array)){
        $result=0;
        foreach($grupo_nid_array as $i=>$v){
            if($grupo_nid!=$v){
                $result++;
            }
        }
        return $result;
    }
    return 0;
}
//gemini-2014
function hontza_grupos_set_creador_en_user_options($grupo_nid,$user_options){
    global $user;
    if(empty($grupo_nid)){
        $result=$user_options;
        $uid_array=array_keys($user_options);
        if(!in_array($user->uid,$uid_array)){
            $result[$user->uid]=$user->name;
        }
        return $result;
    }
    return $user_options;
}
//gemini-2014
function hontza_grupos_get_admin_grupo($node){
    $username='';
    $uid=$node->field_admin_grupo_uid[0]['value'];
    if(empty($uid)){
        $uid=1;
    }
    if(!empty($uid)){
        $my_user=user_load($uid);
        /*if(isset($my_user->uid)){
            $username=$my_user->name;
        }*/
        return $my_user;
    }
    return '';
}
function hontza_grupos_unset_last_menu($value){
    $find='</li>';
    $pos=strpos($value,$find);
    if($pos===FALSE){
        return $value;
    }
    return substr($value,$pos+strlen($find));
}
function hontza_grupos_unset_penultimo_menu($value){
    $find='<li';
    $pos=strpos($value,$find);
    if($pos===FALSE){
        return $value;
    }
    return substr($value,0,$pos);
}
function hontza_grupos_is_facilitator_activable(){
    if(defined('_IS_FACILITADOR_ACTIVABLE') && _IS_FACILITADOR_ACTIVABLE==1){
        return 1;
    }
    return 0;
}
function hontza_grupos_set_local_array($rows){
    if(!empty($rows)){
        foreach($rows as $i=>$row){
            $result[$i]=$row;
            $result[$i]['is_local']=1;
        }
    }
    return $rows;
}
function hontza_grupos_in_shared_menu_keys($key){
    $field_array=array('estrategia','debate','wiki','idea');
    if(in_array($key,$field_array)){
        return 1;
    }
    return 0;
}
function hontza_grupos_user_delete($uid){
    //$edit=(array) $u;
    //user_delete($edit,$uid);
    user_delete(array(),$uid);
}
//gemini-2014
function hontza_grupos_get_delete_unread_news_time_value_string($grupo){
    if(module_exists('rejected')){
        $value=rejected_unread_get_delete_unread_news_time($grupo);
        if(empty($value)){
            $value=6;
        }
        if(!empty($value)){
            if($value>1){
                return $value.' '.t('Months');
            }else{
                return $value.' '.t('Month');
            }
        }    
    }
    return '';
}
//gemini-2014
function hontza_grupos_hay_congelado($rows){
    if(!empty($rows)){
        foreach($rows as $i=>$r){
            if($r['is_congelado']){
                return 1;
            }
        }
    }
    return 0;
}
//gemini-2014
function hontza_grupos_set_title_no_congelados($rows){
    $result=$rows;
    if(!empty($result)){
        foreach($result as $i=>$r){
            $result[$i][0]=$r['title_temp'];
        }
    }
    return $result;
}
//intelsat-2015
function hontza_grupos_set_canales_activados_order_value($canales_activados){
    $find='<img src="';
    $pos=strpos($canales_activados,$find);
    if($pos===FALSE){
        return $canales_activados;
    }else{
        $s=substr($canales_activados,$pos+strlen($find));
        $pos_end=strpos($s,'"');
        if($pos_end===FALSE){
            return $canales_activados;
        }else{
            $result=substr($s,0,$pos_end);
            return basename($result);
        }
    }
    return $canales_activados;
}