<?php
// $Id: opensearch_token.module,v 1.1.2.7 2010/07/13 03:46:34 kiam Exp $

/**
 * @file
 * Implements search tokens that can be used from third-party modules
 * or from opensearch.module.
 */

/**
 * Implements hook_token_list().
 */
function opensearch_token_token_list($type = 'all') {
  $tokens = array();

  if ($type == 'search' || $type == 'all') {
    $tokens['search']['search-keywords'] = t('The keywords of the current search request.');
    $tokens['search']['search-keywords-raw'] = t('The unfiltered keywords of the current search request.');
    $tokens['search']['search-module'] = t('The module handling the search routine.');
    $tokens['search']['search-module-full'] = t('The name of the module handling the search routine, complete of extension.');
    $tokens['search']['search-name'] = t('The title of the search routine.');
    $tokens['search']['search-name-lowercase'] = t('The title of the search routine in lower case characters.');
    $tokens['search']['search-opensearch-url'] = t('The OpenSearch URL for the search page.');
    $tokens['search']['search-url'] = t('The URL of the search page.');
    $tokens['search']['search-url-relative'] = t('The relative URL of the search page.');
  }

  return $tokens;
}

/**
 * Implements hook_token_values().
 *
 * @param $object
 *   The module name of the search routine.
 */
function opensearch_token_token_values($type, $object = NULL, $options = array()) {
  $values = array();

  if ($type == 'search') {
    $name = module_invoke($object, 'search', 'name');
    $relative_url = "search/$object";
    $url = url($relative_url, array('absolute' => TRUE));

    $values['search-keywords-raw'] = trim(search_get_keys());
    $values['search-keywords'] = check_plain($values['search-keywords-raw']);
    $values['search-module'] = $object;
    $values['search-module-full'] = "$object.module";
    $values['search-name'] = $name;
    $values['search-name-lowercase'] = drupal_strtolower($name);
    $values['search-opensearch-url'] = url("opensearch/$object", array('absolute' => TRUE));
    $values['search-url'] = $url;
    $values['search-url-relative'] = $relative_url;
  }

  return $values;
}
