<?php
function copiar_usuarios_perm() {
  return array();
}
function copiar_usuarios_menu() {
  $items=array();
  $items['copiar_usuarios/copiar'] = array(
    'title' => 'Copy Users',
    'page callback' => 'copiar_usuarios_copiar_callback',
    'access callback' => 'copiar_usuarios_custom_access',
  );
  return $items;
}
function copiar_usuarios_copiar_callback(){
  return 'Desactivado';
  //AVISO::::Los user_roles se copian con phmyadmin utilizando copy-paste  
  $users_source_array=copiar_usuarios_get_users_source_array();
  if(!empty($users_source_array)){
    foreach($users_source_array as $i=>$user_row){
        /*echo print_r($user_row,1);
        exit();*/
        $my_user=(array) $user_row;        
        user_save(null,$my_user);
    }
  }
  return date('Y-m-d H:i:s');  
}
function copiar_usuarios_custom_access(){
  if(user_access('root')){
    return TRUE;
  }  
  return FALSE;
}
function copiar_usuarios_get_users_source_array(){
  $result=array();
  $where=array();
  db_set_active('users_source_db');
  $where[]='NOT uid IN(0,1,18)';  
  //$source_db_name=copiar_usuarios_define_source_db_name();
  $res=db_query('SELECT * FROM {users} WHERE '.implode(' AND ',$where));  
  while($row=db_fetch_object($res)){
    $my_user=user_load($row->uid);
    if(isset($my_user->uid) && !empty($my_user->uid)){
        //unset($my_user->uid);
        unset($my_user->og_groups);
        /*echo print_r($my_user,1);
        exit();*/
        $result[]=$my_user;
    }
  }
  db_set_active();
  return $result;
}
function copiar_usuarios_define_source_db_name(){
  $result='';
  $result='backup_hontza_eurecat';
  return $result;  
}