<?php
require_once('hound.update.canal.uid.inc.php');
//intelsat-2016
require_once('hound.enlazar.inc.php');
require_once('hound.noticia.email.inc.php');
require_once('hound.javascript.inc.php');
//
function hound_menu() {
    $items['hound/hound_load_ajax'] = array(
    'title' => 'Ajax Load Hound',
    'page callback' => 'hound_load_ajax_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_api_list'] = array(
    'title' => 'Hound Api List',
    'page callback' => 'hound_api_list_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_get_rss'] = array(
    'title' => 'Hound get rss',
    'page callback' => 'hound_get_rss_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_get_channel'] = array(
    'title' => 'Hound get channel',
    'page callback' => 'hound_get_channel_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_editing_load_ajax'] = array(
    'title' => 'Ajax Load Hound',
    'page callback' => 'hound_editing_load_ajax_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_old_list'] = array(
    'title' => 'Hound Old List',
    'page callback' => 'hound_old_list_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/save_old_hounds'] = array(
    'title' => 'Hound Old List',
    'page callback' => 'hound_save_old_hounds_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/simular_new_hound_ids']= array(
    'title' => 'Simulate new hound ID',
    'page callback' => 'hound_simular_new_hound_ids_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/update_channel_new_hound_ids']= array(
    'title' => 'Simulate new hound ID',
    'page callback' => 'hound_update_channel_new_hound_ids_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_canales_con_varias_fuentes']= array(
    'title' => 'Simulate new hound ID',
    'page callback' => 'hound_canales_con_varias_fuentes_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_api_channel_autocomplete']= array(
    'title' => 'Autocomplete Hound Channel id',
    'page callback' => 'hound_api_channel_autocomplete_callback',
    'access arguments' => array('access content'),
  );
    $items['hound/hound_fix_canal_estrategia']= array(
    'title' => 'Hound fix channel strategy',
    'page callback' => 'hound_fix_canal_estrategia_callback',
    'access arguments' => array('root'),
  );
    $items['hound/update_hound_uid']= array(
    'title' => 'Update hound uid',
    'page callback' => 'hound_update_hound_uid_callback',
    'access arguments' => array('root'),
  );
    $items['hound/settings']= array(
    'title' => 'Hound settings',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('hound_settings_form'),   
    'access callback' => 'hound_settings_access',
  );
    $items['hound/%/reset_hound']= array(
    'title' => 'Autocomplete Hound Channel id',
    'page callback' => 'hound_reset_hound_callback',
    'access callback' => 'hound_admin_grupo_access',
  );
     $items['hound/feed_actualizar']=array(
    'title' => 'Feed',
    'page callback' => 'hound_feed_actualizar_callback',
    'access callback' => TRUE,    
     );     
     $items['hound/noticia/feed_noticia_email_actualizar']=array(
    'title' => 'Feed',
    'page callback' => 'hound_noticia_feed_noticia_email_actualizar_callback',
    'access callback' => TRUE,    
     );
     $items['hound/javascript/simular']=array(
    'title' => 'Hound',
    'page callback' => 'hound_javascript_simular_callback',
    'access arguments' => array('root'),   
     );
     $items['hound/javascript/%/crear/canal']=array(
    'title' => 'Hound',
    'page callback' => 'hound_javascript_crear_canal_callback',
    'access callback' => 'hound_javascript_custom_access',   
     );
      $items['hound/javascript/%/editar/canal']=array(
    'title' => 'Hound',
    'page callback' => 'hound_javascript_crear_canal_callback',
    'access callback' => 'hound_javascript_custom_access',   
     );
    return $items;
}
function hound_add_select_text_input(&$form){     
    if(hound_is_modo_autocomplete()){
            $form['fuentes']['hound1_id'] = array(
               '#type' => 'textfield',
               '#title' => t('Hound Channel Id'),
               '#autocomplete_path' => 'hound/hound_api_channel_autocomplete',
               '#attributes'=>array('autocomplete' => 'on'), 
           );
    }else{
     $form['fuentes']['hound1_id'] = array('#title' => t('Hound Channel Id'),
				'#type' => 'textfield',
                                //'#required'=>TRUE,
     );
    }       
    //        
     $form['fuentes']['hound1_load_btn']=array(
         '#type'=>'button',
         '#default_value'=>t('Load Hound'),
     );
     //intelsat-2016
     hound_enlazar_inc_add_create_edit_form_field($form);
     $form['fuentes']['hound1_result_html']=array(
         '#value'=>'<div id="hound1_result_html" style="padding:10px;"></div>',
     );
     hound_add_text_input_js();
}
function hound_add_text_input_js(){
    
    $js='var hound_is_modo_autocomplete='.hound_is_modo_autocomplete().';
        $(document).ready(function(){
        $("#edit-hound1-load-btn").click(function(){
            call_hound_load_ajax();
            return false;
        });
        if(hound_is_modo_autocomplete==1){
            $("#edit-hound1-id").change(function(){
                call_hound_load_ajax();
                return false;
            });
        }
        function call_hound_load_ajax(){
            var hound_id_val=$("#edit-hound1-id").val();
            jQuery.ajax({
				type: "POST",
				url: "'.$base_url.base_path().'hound/hound_load_ajax?my_time="+new Date().getTime(),
				data: {hound_id:hound_id_val},
				dataType:"json",
				success: function(my_result){
                                    //alert(my_result.content_html);
                                    $("#hound1_result_html").html(my_result.content_html);
				}
			});        
            //return false;
        }    
    });';        
    drupal_add_js($js,'inline');
}
function hound_base_url(){
    $url=hontza_define_hound_url();
    $url=str_replace("/houndRss.php","",$url);
    return $url;
}
function hound_load_ajax_callback(){
    $info=array();
    $hound_id=$_REQUEST['hound_id'];
    $hound_base_url=hound_base_url();
    $url=$hound_base_url;
    //intelsat-2016
    $id_param='';
    if(!hound_enlazar_inc_is_activado()){
        $url.='/index.php';
        $id_param='id/';
    }
    $url.='/channels/getChannel/'.$id_param.urlencode($hound_id);
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $url.='/'.hound_enlazar_inc_get_key();
    }
    $content=file_get_contents($url);
    $result=json_decode($content);
    //echo print_r($result,1);exit();
    //intelsat-2016
    //$result=hound_urldecode_array($result);
    //if(!empty($result)){        
        $info['ok']=1;
        //intelsat-2016
        //$info['content_html']=hound_load_result_html($result,$hound_id);
        $info['content_html']=hound_load_result_html($result,$hound_id,$content);
    /*}else{
        $info['ok']=1;
        $info['content_html']='';
    }*/
    print json_encode($info);
    exit();
}
//intelsat-2016
//function hound_load_result_html($result_in,$hound_id){
function hound_load_result_html($result_in,$hound_id,$content){
    $html=array();
    $result=$result_in;
    $is_empty=0;
    if(hound_is_empty_api_channel($result)){
        $is_empty=1;        
    }
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $html[]='<input type="hidden" name="content_json" value="'.base64_encode($content).'"/>';
        $html[]='<table style="width:75%;">';
        $html[]='<tr>';
        $html[]='<th>'.t('Hound').'</th>';
        $html[]='<th>'.t('Parameter').'</th>';
        $html[]='<th>'.t('Value').'</th>';
        $html[]='</tr>';
    }
    if(!empty($result)){
        foreach($result as $key=>$row){
            //intelsat-2016
            if(hound_enlazar_inc_is_activado()){
                $html[]='<tr style="display:none;">';
            }
            if($is_empty){
                $html[]='<div style="padding:10px;display:none;">';
            }else{
                //intelsat-2016
                if(!hound_enlazar_inc_is_activado()){
                    $html[]='<div style="padding:10px;">';
                }    
            }
            //intelsat-2016
            if(hound_enlazar_inc_is_activado()){
                $html[]='<td>';
            }
            //intelsat-2016
            if(hound_enlazar_inc_is_activado()){
                $html[]='<label><b>'.$key.'</b></label></td>';
            }else{
                $html[]='<label><b>'.t('Hound title').':</b></label>';
            }
            //intelsat-2016
            $my_name='hound1_title';
            $readonly='';
            if(hound_enlazar_inc_is_activado()){
                $my_name='hound1_title['.$key.']';
                $readonly=' readonly="readonly"';
            }
            if(hound_enlazar_inc_is_activado()){
                $html[]='<input type="hidden" id="hound1_title" name="'.$my_name.'" value="'.$key.'"/>';
            }else{    
                $html[]='<input type="text" id="hound1_title" name="'.$my_name.'" value="'.$key.'"'.$readonly.'/>';
            }
            if(!hound_enlazar_inc_is_activado()){
                $html[]='</div>';
            }
            if(hound_enlazar_inc_is_activado()){
                $html[]='<td></td>';
                $html[]='<td></td>';
                 $html[]='</tr>';
            }
            if(empty($row)){
                $row=new stdClass();
                $row->hound_search='';
            }
            //intelsat-2016
            if(hound_enlazar_inc_is_activado()){
                foreach($row as $i=>$row_array){
                    if(empty($row_array)){
                         $html[]='<tr>';
                         if($is_empty){
                            $html[]='<div style="padding:10px;display:none;">';
                         }/*else{    
                            $html[]='<div style="padding:10px;">';
                         }*/
                         $html[]='<td>';
                         $html[]='<label><b>'.$key.'</b></label>';
                         $html[]='</td>';
                         $html[]='<td></td>';
                         $html[]='<td></td>';
                         //$html[]='</div>';
                         $html[]='</tr>';
                         continue;
                    }
                    foreach($row_array as $name=>$value){
                         $html[]='<tr>';
                         if($is_empty){
                            $html[]='<div style="padding:10px;display:none;">';
                         }/*else{    
                            $html[]='<div style="padding:10px;">';
                         }*/
                         $html[]='<td>';
                         $html[]='<label><b>'.$key.'</b></label>';
                         $html[]='</td>';
                         $html[]='<td>';
                         $html[]='<label><b>'.hound_api_param_key_label($name).'</b></label>';
                         $html[]='</td>';
                         $html[]='<td>';
                         if($name=='hound_search'){
                             $html[]='<textarea id="hound1_f_'.$key.'_'.$name.$i.'" name="hound1_f['.$key.']['.$name.']['.$i.']" rows="5" cols="60" readonly="readonly">'.$value.'</textarea>';
                         }else{
                             $html[]='<input type="text" id="hound1_f_'.$key.'_'.$name.$i.'" name="hound1_f['.$key.']['.$name.']['.$i.']" value="'.$value.'" readonly="readonly"/>';
                         }
                         $html[]='</td>';
                         //$html[]='</div>';
                         $html[]='</tr>';
                    }     
                }                
            }else{
                foreach($row as $name=>$value){
                    if($is_empty){
                       $html[]='<div style="padding:10px;display:none;">';
                    }else{    
                       $html[]='<div style="padding:10px;">';
                    }
                    $html[]='<label><b>'.hound_api_param_key_label($name).' ('.$key.'):</b></label>';
                    if($name=='hound_search'){
                        $html[]='<textarea id="hound1_f_'.$key.'_'.$name.'" name="hound1_f['.$key.']['.$name.']" rows="5" cols="60">'.$value.'</textarea>';
                    }else{
                        $html[]='<input type="text" id="hound1_f_'.$key.'_'.$name.'" name="hound1_f['.$key.']['.$name.']" value="'.$value.'"/>';
                    }
                    $html[]='</div>';            
                }
            }    
        }
    }
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $html[]='<table>';
    }
    if($is_empty){
        $html[]='<div style="padding:10px;">';
        $html[]='<label><b>'.t('Hound result').':</b></label>';
        $html[]='<input type="text" id="hound_empty_result" name="hound_empty_result" value="'.t('Hound loaded').'"/>';
        $html[]='</div>';            
    }  
    return implode('',$html);
}
function hound_add_canal_hound_parametros($form_state,&$fuente){    
    //intelsat-2016
    //if(isset($_REQUEST['hound1_f']) && !empty($_REQUEST['hound1_f'])){
    if(hound_enlazar_inc_is_hound_add_canal_hound_parametros()){
        $fuente->canal_hound_parametros='';
        $row=new stdClass();
        $row->hound_id=$form_state['values']['hound1_id'];
        //$row->hound_title=$_REQUEST['hound1_title'];
        //$row->hound_title=hound_get_hound_title_by_request_parametros($_REQUEST['hound1_f']);
        $row->hound_title=hound_get_title_by_hound_id($row->hound_id);
        $row->parametros=serialize($_REQUEST['hound1_f']);
        //intelsat-2016
        hound_enlazar_inc_add_add_canal_hound_parametros($row);
        $row->is_empty=0;
        if(isset($_REQUEST['hound_empty_result']) && !empty($_REQUEST['hound_empty_result'])){
            $row->is_empty=1;
        }
        $fuente->canal_hound_parametros=$row;       
    }
}
function hound_save_canal_hound_parametros($canal){    
    $canal_hound_parametros=hound_get_canal_hound_parametros_row($canal->nid);
    //intelsat-2016
    hound_enlazar_inc_get_canal_hound_parametros_row_hound_title($canal);
    if(isset($canal_hound_parametros->id) && !empty($canal_hound_parametros->id)){
        if(hound_enlazar_inc_is_activado()){
            if(hound_enlazar_inc_is_hound_add_canal_hound_parametros(1)){
                hound_enlazar_inc_add_add_canal_hound_parametros($canal_hound_parametros);
            }
            db_query('UPDATE {canal_hound_parametros} SET hound_id="%s",hound_title="%s",parametros="%s",is_empty=%d,content="%s" WHERE nid=%d AND vid=%d',$canal->canal_hound_parametros->hound_id,$canal->canal_hound_parametros->hound_title,$canal->canal_hound_parametros->parametros,$canal->canal_hound_parametros->is_empty,$canal->canal_hound_parametros->content,$canal->nid,$canal->vid);       
        }else{
            db_query('UPDATE {canal_hound_parametros} SET hound_id="%s",hound_title="%s",parametros="%s",is_empty=%d WHERE nid=%d AND vid=%d',$canal->canal_hound_parametros->hound_id,$canal->canal_hound_parametros->hound_title,$canal->canal_hound_parametros->parametros,$canal->canal_hound_parametros->is_empty,$canal->nid,$canal->vid);
        }            
    }else{
        if(hound_enlazar_inc_is_activado()){
            db_query('INSERT INTO {canal_hound_parametros}(nid,vid,hound_id,hound_title,parametros,is_empty,content) VALUES(%d,%d,"%s","%s","%s",%d,"%s")',$canal->nid,$canal->vid,$canal->canal_hound_parametros->hound_id,$canal->canal_hound_parametros->hound_title,$canal->canal_hound_parametros->parametros,$canal->canal_hound_parametros->is_empty,$canal->canal_hound_parametros->content);                    
        }else{
            db_query('INSERT INTO {canal_hound_parametros}(nid,vid,hound_id,hound_title,parametros,is_empty) VALUES(%d,%d,"%s","%s","%s",%d)',$canal->nid,$canal->vid,$canal->canal_hound_parametros->hound_id,$canal->canal_hound_parametros->hound_title,$canal->canal_hound_parametros->parametros,$canal->canal_hound_parametros->is_empty);            
        }                
    }            
}
function hound_delete_canal_hound_parametros($canal){
    db_query('DELETE FROM {canal_hound_parametros} WHERE vid=%d AND nid=%d',$canal->vid,$canal->nid);
}
//intelsat-2016
//function hound_get_canal_hound_parametros_row($nid){
function hound_get_canal_hound_parametros_row($nid,$node_in=''){
    //intelsat-2016
    if(empty($nid)){
        $node=$node_in;
    }else{
        $node=node_load($nid);
    }
    $where=array();
    $where[]='1';
    $where[]='nid='.$node->nid;
    $where[]='vid='.$node->vid;
    $sql='SELECT * FROM {canal_hound_parametros} WHERE '.implode(' AND ',$where);
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        return $row;
    }
    $my_result=new stdClass();
    return $my_result;
}
function hound_api_list_callback(){
    $output='';
    hound_add_buscar_js();
    $output .= drupal_get_form('hound_search_api_list_form');
    $my_limit=20;
    $hound_base_url=hound_base_url();
    $url=$hound_base_url.'/index.php/channels/apiList';
    $content=file_get_contents($url);
    $result=json_decode($content);
    $result=hound_apply_filter_api_list($result);
    if(!empty($result)){
        $output.=l('Canales con varias fuentes','hound/hound_canales_con_varias_fuentes');
        $kont=0;
        $headers=array('Id',t('Hound Channel Id'),t('Hound Title'),t('Actions'));
        foreach($result as $i=>$r){
            $rows[$kont]=$r;
            $rows[$kont][3]=hound_define_api_list_accciones($r);
            $kont++;
        }
        $rows=my_set_estrategia_pager($rows, $my_limit);
        $output .= theme('table',$headers,$rows);
        $output .= theme('pager', NULL, $my_limit);
    }else{
        $output.= '<div id="first-time">' .t('There are no contents'). '</div>';
    }    
    return $output;
}
function hound_define_api_list_accciones($r){
    $html=array();
    $html[]=l('getChannel','hound/hound_get_channel/'.urlencode($r[1]));
    $html[]=l('getRSS','hound/hound_get_rss/'.urlencode($r[1]),array('attributes'=>array('target'=>'_blank')));
    return implode('&nbsp;',$html);
}
function hound_get_rss_callback(){
    $hound_canal_id=arg(2);
    $hound_base_url=hound_base_url();
    $url=$hound_base_url.'/index.php/channels/getRss/id/'.urlencode($hound_canal_id);
    print $url;exit();
    $content=file_get_contents($url);
    print $content;
    exit();
}
function hound_get_channel_callback(){
    $hound_canal_id=arg(2);
    $hound_base_url=hound_base_url();
    //$hound_canal_id='GSch-Benteler+BMW+Mubea';
    $url=$hound_base_url.'/index.php/channels/getChannel/id/'.urlencode($hound_canal_id);
    //print $url.'<BR>';
    $content=file_get_contents($url);
    $result=json_decode($content);
    if(!empty($result)){
        echo print_r($result,1);
        exit();
    }
    return '';
}
function hound_get_canal_hound_field($canal_hound_row,$field){
    if(isset($canal_hound_row->id) && !empty($canal_hound_row->id)){
        return $canal_hound_row->$field;
    }
    return '';
}
function hound_editing_form_alter(&$form,&$form_state,$form_id,$nid){
        $canal_hound_row='';
        if(hontza_is_hound_text_input()){
            $canal_hound_row=hound_get_canal_hound_parametros_row($nid);
            $hound_title=hound_get_canal_hound_field($canal_hound_row,'hound_title');
        }else{
            $hound_title=hontza_get_hound_title_by_nid($nid);
        }
        $form['field_nombrefuente_canal'][0]['#prefix']='<div style="display:none;">';
        $form['field_nombrefuente_canal'][0]['#suffix']='</div>';
        $form['feeds']['#prefix']='<div style="display:none;">';
        $form['feeds']['#suffix']='</div>';
        $form['hound_title_readonly'] = array(
                '#title' => t('Hound'),
                '#type' => 'textfield',
                '#default_value'=>$hound_title,
                '#attributes'=>array('readonly'=>'readonly'),
                '#maxlength'=>1024,
            );            
        if(hontza_is_hound_text_input()){
            $hound_id_editing=hound_get_canal_hound_field($canal_hound_row,'hound_id');
            if(hound_is_modo_autocomplete()){
                $form['hound_id_editing'] = array(
                    '#type' => 'textfield',
                    '#title' => t('Hound Channel Id'),
                    '#autocomplete_path' => 'hound/hound_api_channel_autocomplete',
                    '#attributes'=>array('autocomplete' => 'on'),
                    '#default_value'=>$hound_id_editing,        
                );   
            }else{
                $form['hound_id_editing'] = array(
                    '#title' => t('Hound Channel Id'),
                    '#type' => 'textfield',
                    '#default_value'=>$hound_id_editing,
                );
            }
            
            $form['hound_editing_load_btn']=array(
                '#type'=>'button',
                '#default_value'=>t('Load Hound'),
            );
            //intelsat-2016
            $form['hound_editing_reset_btn']=array(
                '#type'=>'button',
                '#default_value'=>t('Reset Hound'),
            );            
            hound_enlazar_inc_add_create_edit_form_field($form);
            
            if(!hound_admin_grupo_access()){
                $form['hound_editing_reset_btn']['#prefix']='<div style="display:none">';
                 $form['hound_editing_reset_btn']['#suffix']='</div>';
            }
            $hound_parametros_html=hound_define_editing_parametros_html($canal_hound_row);
            $form['fuentes']['hound1_result_html']=array(
                '#value'=>'<div id="hound1_result_html" style="padding:10px;">'.$hound_parametros_html.'</div>',
            );
            //intelsat-2016
            //hound_add_editing_js();
            //intelsat-2016
            //hound_enlazar_inc_editing_form_alter($form);
            
            hound_add_editing_js($nid);
        }else{
            $hound_search_value=hontza_get_hound_search_value_by_nid($nid);
            $form['hound_search_editing'] = array(
                '#title' => t('Hound search'),
                //'#type' => 'textfield',
                '#type' => 'textarea',
                '#default_value'=>urldecode($hound_search_value),
                '#maxlength'=>1024,
            );
        }
}
function hound_define_editing_parametros_html($canal_hound_row){
    $html=array();
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $html[]=hound_enlazar_inc_define_editing_parametros_html($canal_hound_row);
    }else{
        $parametros_seri=hound_get_canal_hound_field($canal_hound_row,'parametros');
        $parametros=unserialize($parametros_seri);
        if(!empty($parametros)){
            foreach($parametros as $key=>$row){
                foreach($row as $name=>$value){
                    if($canal_hound_row->is_empty){
                        $html[]='<div style="padding:10px;display:none;">';
                    }else{
                        $html[]='<div style="padding:10px;">';
                    }
                    $html[]='<label><b>'.hound_api_param_key_label($name).' ('.$key.')</b>:</label>';
                    if($name=='hound_search'){
                        $html[]='<textarea id="hound1_f_'.$key.'_'.$name.'" name="hound1_f['.$key.']['.$name.']" rows="5" cols="60">'.$value.'</textarea>';
                    }else{
                        $html[]='<input type="text" id="hound1_f_'.$key.'_'.$name.'" name="hound1_f['.$key.']['.$name.']" value="'.$value.'"/>';
                    }
                    $html[]='</div>';
                }
            }
        }
    }
    return implode('',$html);
}
//intelsat-2016
//function hound_add_editing_js(){
function hound_add_editing_js($nid){
    $url_reset_hound=url('hound/'.$nid.'/reset_hound');
    $js='var hound_is_modo_autocomplete='.hound_is_modo_autocomplete().';
        $(document).ready(function(){
        $("#edit-hound-editing-load-btn").click(function(){
            call_hound_editing_load_ajax();  
            return false;
        });
        $("#edit-hound-editing-reset-btn").click(function(){
            window.location.href="'.$url_reset_hound.'";
            return false;
        });
        if(hound_is_modo_autocomplete==1){
            $("#edit-hound-id-editing").change(function(){
                call_hound_editing_load_ajax();  
                return false;
            });
        }
        function call_hound_editing_load_ajax(){
            var hound_id_val=$("#edit-hound-id-editing").val();
            jQuery.ajax({
				type: "POST",
				url: "'.$base_url.base_path().'hound/hound_editing_load_ajax?my_time="+new Date().getTime(),
				data: {hound_id:hound_id_val},
				dataType:"json",
				success: function(my_result){
                                    $("#edit-hound-title-readonly").val(my_result.hound_title);
                                    $("#hound1_result_html").html(my_result.content_html);
				}
			});
        }                
    });';        
    drupal_add_js($js,'inline');
}
function hound_editing_load_ajax_callback(){
    $info=array();
    $hound_id=$_REQUEST['hound_id'];
    $hound_base_url=hound_base_url();
    //intelsat-2016
    $url=$hound_base_url;
    //$url=$hound_base_url.'/index.php/channels/getChannel/id/'.urlencode($hound_id);        
    $id_param='';
    if(!hound_enlazar_inc_is_activado()){
        $url.='/index.php';
        $id_param='id/';
    }
    $url.='/channels/getChannel/'.$id_param.urlencode($hound_id);
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $url.='/'.hound_enlazar_inc_get_key();
    }
    $content=file_get_contents($url);
    $result=json_decode($content);
    //if(!empty($result)){        
        $info['ok']=1;
        //
        //$info['content_html']=hound_editing_load_result_html($result,$hound_id,$hound_title);
        $info['content_html']=hound_editing_load_result_html($result,$hound_id,$hound_title,$content);
        $info['hound_title']=$hound_title;
    /*}else{
        $info['ok']=0;
    }*/
    print json_encode($info);
    exit();
}
function hound_editing_load_result_html($result_in,$hound_id,&$hound_title,$content){
    $result=$result_in;
    $is_empty=0;
    if(hound_is_empty_api_channel($result)){
        $is_empty=1;
    }
    $html=array();
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $html[]='<input type="hidden" name="content_json" value="'.base64_encode($content).'"/>';
    }
    $hound_title=hound_get_hound_title_by_request_parametros($result);
    
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        if(!empty($result)){
            foreach($result as $key=>$row){
                if(empty($row)){
                    $row=new stdClass();
                    $row->hound_search='';
                }
                foreach($row as $i=>$row_array){
                    if(empty($row_array)){
                        continue;
                    }
                    foreach($row_array as $name=>$value){
                         if($is_empty){
                            $html[]='<div style="padding:10px;display:none;">';
                         }else{    
                            $html[]='<div style="padding:10px;">';
                         }
                         $html[]='<label><b>'.hound_api_param_key_label($name).' ('.$key.'):</b></label>';
                         if($name=='hound_search'){
                             $html[]='<textarea id="hound1_f_'.$key.'_'.$name.$i.'" name="hound1_f['.$key.']['.$name.']['.$i.']" rows="5" cols="60" readonly="readonly">'.$value.'</textarea>';
                         }else{
                             $html[]='<input type="text" id="hound1_f_'.$key.'_'.$name.$i.'" name="hound1_f['.$key.']['.$name.']['.$i.']" value="'.$value.'" readonly="readonly"/>';
                         }
                         $html[]='</div>';   
                    }     
                }
            }
        }    
    }else{
        if(!empty($result)){
            foreach($result as $key=>$row){
                if(empty($row)){
                    $row=new stdClass();
                    $row->hound_search='';
                }
                foreach($row as $name=>$value){
                    if($is_empty){
                        $html[]='<div style="padding:10px;display:none;">';
                    }else{    
                        $html[]='<div style="padding:10px;">';
                    }
                    $html[]='<label><b>'.hound_api_param_key_label($name).' ('.$key.'):</b></label>';
                    if($name=='hound_search'){
                        $html[]='<textarea id="hound1_f_'.$key.'_'.$name.'" name="hound1_f['.$key.']['.$name.']" rows="5" cols="60">'.$value.'</textarea>';
                    }else{
                        $html[]='<input class="form-text" type="text" id="hound1_f_'.$name.'" name="hound1_f['.$key.']['.$name.']" value="'.$value.'"/>';
                    }
                    $html[]='</div>';            
                }
            }
        }
    }
    if($is_empty){
        $html[]='<div style="padding:10px;">';
        $html[]='<label><b>'.t('Hound result').':</b></label>';
        $html[]='<input type="text" id="hound_empty_result" name="hound_empty_result" value="'.t('Hound loaded').'"/>';
        $html[]='</div>';            
    }  
    return implode('',$html);
}
function hound_argumentos_canal_hound_presave(&$node){
    if(isset($_REQUEST['hound_id_editing']) && !empty($_REQUEST['hound_id_editing'])){
        $url_hound='';
        $old_hound_canal_id=hound_get_hound_id_by_nid($node->nid);
        hound_add_editing_canal_hound_parametros($node);
        if(isset($node->feeds) && isset($node->feeds['FeedsHTTPFetcher']) && isset($node->feeds['FeedsHTTPFetcher']['source']) && !empty($node->feeds['FeedsHTTPFetcher']['source'])){
            $hound_canal_id='';
            if(isset($node->canal_hound_parametros)){
                $hound_canal_id=$node->canal_hound_parametros->hound_id;
            }
            if($old_hound_canal_id!=$hound_canal_id){
                $hound_base_url=hound_base_url();
                //$url_new=$hound_base_url.'/index.php/channels/getRss/id/'.urlencode($hound_canal_id).'/from/0';
                $url_new=hound_enlazar_inc_get_canal_rss_url($hound_canal_id);
                $node->feeds['FeedsHTTPFetcher']['source']=$url_new;
            }    
        }        
        //hound_delete_canal_hound_parametros($node);
        hound_save_canal_hound_parametros($node);
        hound_api_save_parametros($node);
    }    
}
function hound_add_editing_canal_hound_parametros(&$node){
    $node->canal_hound_parametros='';
    //if(isset($_REQUEST['hound1_f']) && !empty($_REQUEST['hound1_f'])){
    //intelsat-2016
    //if(isset($_REQUEST['hound1_f'])){
    if(hound_enlazar_inc_is_hound_add_canal_hound_parametros(1)){    
        $row=new stdClass();
        $row->hound_id=$_REQUEST['hound_id_editing'];
        //$row->hound_title=$_REQUEST['hound_title_readonly'];
        $row->hound_title=hound_get_title_by_hound_id($row->hound_id);
        $row->parametros=serialize($_REQUEST['hound1_f']);
        //intelsat-2016
        hound_enlazar_inc_add_add_canal_hound_parametros($row);
        $row->is_empty=0;
        if(isset($_REQUEST['hound_empty_result']) && !empty($_REQUEST['hound_empty_result'])){
            $row->is_empty=1;
        }        
        $node->canal_hound_parametros=$row;        
    }    
}
function hound_api_save_parametros($canal){
    //intelsat-2016
    if(!hound_enlazar_inc_is_activado()){
        $canal_hound_parametros=hound_get_canal_hound_parametros_row($canal->nid);
        if(!$canal_hound_parametros->is_empty){
            //http://192.168.110.211/hound/index.php/channels/setChannel/id/H8159/hound_search/{.....json array bat......}
            $hound_base_url=hound_base_url();
            $url=$hound_base_url.'/index.php/channels/setChannel/id/'.urlencode($canal_hound_parametros->hound_id).'/hound_search'.hound_define_api_params($canal_hound_parametros);
            $content=file_get_contents($url);
            //print $content;exit();
        }
    }
}
function hound_define_api_params($canal_hound_parametros){
    $result=array();
    $parametros=unserialize($canal_hound_parametros->parametros);
    if(!empty($parametros)){
        //foreach($parametros as $name=>$value){
            //$my_array=array();
            //$my_array[0]=$value;
            $v=urlencode(base64_encode(json_encode($parametros)));
            $result[]='/'.$v;
        //}
    }
    return implode('',$result);
}
//intelsat-2016
//function hound_get_title_by_nid($nid){
function hound_get_title_by_nid($nid,$is_br=0){
    $canal_hound_parametros=hound_get_canal_hound_parametros_row($nid);
    if(isset($canal_hound_parametros->hound_title)){
        if($is_br){
            $result=$canal_hound_parametros->hound_title;
            $result=explode(',',$result);
            return implode('<br>',$result);
        }else{
            return $canal_hound_parametros->hound_title;     
        }    
    }
    return '';
}
function hound_api_param_key_label($param_key){
    if($param_key=='hound_search'){
        return t('Hound search');
    }
    return $param_key;
}
function hound_is_parametro_text_area($param_key){
    if(in_array($param_key,array('hound_search'))){
        return 1;
    }
    return 0;
}
//intelsat-2016
//function hound_get_hound_id_by_nid($nid){
function hound_get_hound_id_by_nid($nid,$canal=''){
    //intelsat-2016
    //$row=hound_get_canal_hound_parametros_row($nid);
    $row=hound_get_canal_hound_parametros_row($nid,$canal);
    if(isset($row->hound_id) && !empty($row->hound_id)){
        return $row->hound_id;
    }
    return '';
}
function hound_old_list_callback(){
    $my_limit=1000;
    $hound_array=hound_get_all_array();
    $hound_array=hound_old_prepare($hound_array);
    $rows=hound_old_table_rows_prepare($hound_array);
    if(!empty($rows)){
        $kont=0;
        $headers=array('vid','nid','node_title','hound_title','hound_search');       
        $rows=my_set_estrategia_pager($rows, $my_limit);
        //$output.=l(t('Save old hounds'),'hound/save_old_hounds');
        //$output.=l('Simular new_hound_id','hound/simular_new_hound_ids');
        //$output.=l('Update channel new hound id','hound/update_channel_new_hound_ids');
        $output .= theme('table',$headers,$rows);
        $output .= theme('pager', NULL, $my_limit);
    }else{
        $output.= '<div id="first-time">' .t('There are no contents'). '</div>';
    }
    return $output;
}
function hound_get_all_array(){
    $result=array();
    $where=array();
    $where[]='1';
    $where[]='node.type="canal_de_yql"';
    $where[]='c.field_is_hound_value=1';
    $sql='SELECT node.*
    FROM {node} node
    LEFT JOIN {content_type_canal_de_yql} c ON node.vid=c.vid
    WHERE '.implode(' AND ',$where).'
    ORDER BY node.title ASC';
    
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function hound_old_prepare($hound_array){
    $result=array();
    if(!empty($hound_array)){
        foreach($hound_array as $i=>$r){
            $node=node_load($r->nid);
            if(isset($node->nid) && !empty($node->nid)){
                $row=array();
                $row['vid']=$node->vid;
                $row['nid']=$node->nid;
                $row['node_title']=$node->title;
                $row['hound_old_url']=$node->field_nombrefuente_canal[0]['value'];
                $hound_old_title='';
                $parts = parse_url($row['hound_old_url']);
                parse_str($parts['query'], $query);
                if(isset($query['title'])){
                    $hound_old_title=$query['title'];
                }
                $row['hound_old_title']=$hound_old_title;
                $feeds_source=hontza_get_feeds_source($node->nid);
                if(isset($feeds_source->feed_nid) && !empty($feeds_source->feed_nid)){
                    $row['feeds_source_url']=$feeds_source->source;
                    $row['hound_search']=hontza_get_hound_search_value_by_nid($node->nid);
                }    
                $result[]=$row;
            }
        }
    }
    return $result;
}
function hound_old_table_rows_prepare($hound_array){
    $result=array();
    if(!empty($hound_array)){
        $kont=0;
        foreach($hound_array as $i=>$r){
            $result[$kont][0]=$r['vid'];
            $result[$kont][1]=$r['nid'];
            $result[$kont][2]=$r['node_title'];
            $result[$kont][3]=$r['hound_old_title'];
            $result[$kont][4]=$r['hound_search'];
            $kont++;
        }
    }
    return $result;
}
function hound_save_old_hounds_callback(){
    return 'Funcion desactivada';
    hound_delete_all_old_hounds();
    $hound_array=hound_get_all_array();
    $hound_array=hound_old_prepare($hound_array);
    if(!empty($hound_array)){
        foreach($hound_array as $i=>$r){
            db_query('INSERT INTO {old_hounds}(vid,nid,node_title,hound_old_title,hound_search,hound_old_url,feeds_source_url) VALUES(%d,%d,"%s","%s","%s","%s","%s")',$r['vid'],$r['nid'],$r['node_title'],$r['hound_old_title'],$r['hound_search'],$r['hound_old_url'],$r['feeds_source_url']);
        }
    }
    $html=array();
    $html[]='<p>'.t('Old hounds saved').'</p>';
    $html[]=l(t('Return'),'hound/hound_old_list');
    return implode('',$html);
}
function hound_delete_all_old_hounds(){
    $sql='DELETE FROM {old_hounds} WHERE 1';
    db_query($sql);
}
function hound_simular_new_hound_ids_callback(){
    return 'Funcion desactivada';
    $old_array=hound_get_old_hounds_array();
    $hound_base_url=hound_base_url();
    $url=$hound_base_url.'/index.php/channels/apiList';
    $content=file_get_contents($url);
    $result=json_decode($content);    
    if(!empty($result) && !empty($old_array)){
        foreach($old_array as $i=>$row){
            $new_hound_id=$result[0][1];
            if(isset($result[$i][1])){
                $new_hound_id=$result[$i][1];
            }
            db_query('UPDATE {old_hounds} SET new_hound_id="%s" WHERE id="%d"',$new_hound_id,$row->id);
        }
    }
    $html=array();
    $html[]='<p>'.t('Simulated').'</p>';
    $html[]=l(t('Return'),'hound/hound_old_list');
    return implode('',$html);
}
function hound_get_old_hounds_array(){
    $result=array();
    $where=array();
    $where[]='1';
    $sql='SELECT * 
    FROM {old_hounds} 
    WHERE '.implode(' AND ',$where);
    //
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function hound_update_channel_new_hound_ids_callback(){
    return 'Funcion desactivada';
    $old_array=hound_get_old_hounds_array();
    if(!empty($old_array)){
        foreach($old_array as $i=>$row){                        
            $node=node_load($row->nid);
            if(isset($node->nid) && !empty($node->nid)){
                $hound_base_url=hound_base_url();
                //$new_hound_id=$row->new_hound_id;
                $new_hound_id=$row->node_title;
                $url_new=$hound_base_url.'/index.php/channels/getRss/id/'.urlencode($new_hound_id).'/from/0';
                $node->field_nombrefuente_canal[0]['value']=$url_new;
                $node->feeds = array('FeedsHTTPFetcher' => array('source' =>  $url_new));
                $api_channel=hound_api_get_channel($new_hound_id,$url_api_channel);
                if(!hound_is_empty_api_channel($api_channel)){
                    hound_add_canal_hound_parametros_by_api_channel($new_hound_id,$api_channel,$node);
                    node_save($node);
                    //hound_delete_canal_hound_parametros($node);
                    hound_save_canal_hound_parametros($node);                   
                }else{
                    print 'ez===='.$url_api_channel.'<BR>';
                }
            }else{
                 print 'ez===='.$row->nid.'<BR>';
            }
        }
    }
    $html=array();
    $html[]='<p>'.t('Updated').'</p>';
    $html[]=l(t('Return'),'hound/hound_old_list');
    return implode('',$html);
}
function hound_api_get_channel($hound_id,&$url){
    $hound_base_url=hound_base_url();
    //intelsat-2016
    $url=$hound_base_url;    
    //$url=$hound_base_url.'/index.php/channels/getChannel/id/'.urlencode($hound_id);            
    $id_param='';
    if(!hound_enlazar_inc_is_activado()){
        $url.='/index.php';
        $id_param='id/';
    }
    $url.='/channels/getChannel/'.$id_param.urlencode($hound_id);
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $url.='/'.hound_enlazar_inc_get_key();
    }    
    $content=file_get_contents($url);
    $result=json_decode($content);
    if(!empty($result)){  
        return $result;
    }
    $my_result=new stdClass();
    return $my_result;
}
function hound_add_canal_hound_parametros_by_api_channel($hound_id,$api_channel,&$node){
    //foreach($api_channel as $key=>$parametros){    
        $node->canal_hound_parametros='';
        $row=new stdClass();
        $row->hound_id=$hound_id;
        $row->hound_title=hound_get_hound_title_by_request_parametros($api_channel);
        $row->parametros=serialize($api_channel);
        $node->canal_hound_parametros=$row;
    //}    
}
function hound_canales_con_varias_fuentes_callback(){
    $hound_base_url=hound_base_url();
    $url=$hound_base_url.'/index.php/channels/apiList';
    $content=file_get_contents($url);
    $result=json_decode($content);    
    if(!empty($result)){
        foreach($result as $i=>$r){
            $hound_id=$r[1];
            $api_channel=hound_api_get_channel($hound_id,$url_api_channel);
            //echo print_r($api_channel,1);
            $num_fuentes=hound_api_get_num_fuentes($api_channel);
            print 'num_fuentes=='.$num_fuentes.'<BR>';
        }
    }
}
function hound_api_get_num_fuentes($api_channel){
    $result=0;
    foreach($api_channel as $key=>$parametros){
        $result++;
    }
    return $result;
}
function hound_get_hound_title_by_request_parametros($api_channel){
   $result=array();
   foreach($api_channel as $key=>$my_array){
       $result[]=$key;
   }
   return implode(',',$result);
}
function hound_get_title_by_hound_id($hound_id){
    $api_channel=hound_api_get_channel($hound_id,$url_api_channel);
    return hound_get_hound_title_by_request_parametros($api_channel);
}
function hound_is_empty_api_channel($api_channel){
    if(!empty($api_channel)){       
        foreach($api_channel as $key=>$row){
            if(!empty($row)){
                return 0;
            }
        }
    }
    return 1;
}
function hound_search_api_list_form(){
    $form=array();
    $form['hontza_search_api_list_fs']=array('#type'=>'fieldset','#title'=>t('Search'),'#attributes'=>array('id'=>'hontza_search_api_list_fs'));
    $form['hontza_search_api_list_fs']['hound_id']=array('#type'=>'textfield','#title'=>t('Hound Channel Id'),'#default_value'=>hound_api_list_filter_value('hound_id'));
    $form['hontza_search_api_list_fs']['submit']=array('#type'=>'submit','#value'=>t('Search'),'#name'=>'buscar');
    $form['hontza_search_api_list_fs']['reset']=array('#type'=>'submit','#value'=>t('Clean'),'#name'=>'limpiar');
    return $form;
}
function hound_api_list_filter_value($f){
    if(isset($_SESSION['hound_api_list']['filter']) && !empty($_SESSION['hound_api_list']['filter'])){
        if(isset($_SESSION['hound_api_list']['filter'][$f]) && !empty($_SESSION['hound_api_list']['filter'][$f])){
            return $_SESSION['hound_api_list']['filter'][$f];
        }
    }
    return '';
}
function hound_add_buscar_js(){

		$js='
			$(document).ready(function()
			{
			  $("#hontza_search_api_list_fs .fieldset-wrapper").hide();
                          $("#hontza_search_api_list_fs legend").click(function(){
                            if ($("#hontza_search_api_list_fs .fieldset-wrapper").css("display") == "none"){
                                $("#hontza_search_api_list_fs .fieldset-wrapper").show();
                            }else{
                                $("#hontza_search_api_list_fs .fieldset-wrapper").hide();
                            }
                          });
			});';

			drupal_add_js($js,'inline');

}
function hound_search_api_list_form_submit($form_id,&$form){
    if(isset($form['clicked_button']) && !empty($form['clicked_button'])){
        $name=$form['clicked_button']['#name'];
        if(strcmp($name,'limpiar')==0){
            if(isset($_SESSION['hound_api_list']['filter']) && !empty($_SESSION['hound_api_list']['filter'])){
                unset($_SESSION['hound_api_list']['filter']);
            }
        }else{
            $_SESSION['hound_api_list']['filter']=array();
            $fields=array('hound_id');
            if(count($fields)>0){
                foreach($fields as $i=>$f){
                    $v=$form['values'][$f];
                    if(!empty($v)){
                        $_SESSION['hound_api_list']['filter'][$f]=$v;
                    }
                }
            }
        }
    } 
}
function hound_apply_filter_api_list($result_in){
    $result=array();
    if(isset($_SESSION['hound_api_list']['filter']['hound_id']) && !empty($_SESSION['hound_api_list']['filter']['hound_id'])){
        $filter_hound_id=$_SESSION['hound_api_list']['filter']['hound_id'];
        foreach($result_in as $i=>$row){
            $pos=strpos($row[1],$filter_hound_id);
            if($pos===FALSE){
                //
            }else{
                $result[]=$row;
            }
        }
        return $result;
    }
    return $result_in;
}
function hound_api_channel_autocomplete_callback($konp)
{
  $matches = array();
  
    $hound_base_url=hound_base_url();
    $url=$hound_base_url.'/index.php/channels/apiList';
    $content=file_get_contents($url);
    $result=json_decode($content);
    if(!empty($result)){
        foreach($result as $i=>$r){
            $hound_id=$r[1];
            $pos=strpos($hound_id,$konp);
            if($pos===FALSE){
                //
            }else{
                $matches[$hound_id]=$hound_id;
            }    
        }
    }
  
  print drupal_to_js($matches);
}
function hound_is_modo_autocomplete(){
    $result=0;
    //$result=1;
    return $result;
}
function hound_is_updating_channel_new_hound_ids(){
    if(hound_is_arg('update_channel_new_hound_ids')){
        return 1;
    }
    return 0;
}
function hound_is_arg($konp){
    $param0=arg(0);
    if(!empty($param0) && $param0=='hound'){
        $param1=arg(1);
        if(!empty($param1) && $param1==$konp){
            return 1;
        }
    }
    return 0;
}
function hound_fix_canal_estrategia_callback(){
    return 'Funcion desactivada';
    $old_array=hound_get_old_hounds_array();
    if(!empty($old_array)){
        foreach($old_array as $i=>$row){                        
            $node=node_load($row->nid);
            if(isset($node->nid) && !empty($node->nid)){
                $node->estrategia_responde_array=hound_get_old_responde_array($node->nid);
                hontza_canal_save_reto_al_que_responde($node);
            }else{
                 print 'no existe el nodo===='.$row->nid.'<BR>';
            }
        }
    }
    $html=array();
    $html[]='<p>'.t('Updated').' '.date('Y-m-d H:i').'</p>';
    $html[]=l(t('Return'),'hound/hound_old_list');
    return implode('',$html);
}
function hound_get_old_responde_array($nid){
    return hound_get_old_canal_estrategia($nid);
}
function hound_get_old_canal_estrategia($nid){
    $result=array();
    $res=db_query('SELECT * FROM {old_canal_estrategia} ce WHERE ce.nid=%d',$nid);
    while($row=db_fetch_array($res)){
        $r=$row;
        unset($r['id']);
        unset($r['nid']);
        unset($r['vid']);
        $result[]=$r;
    }
    return $result;
}
function hound_settings_access(){
    //simulando
    //return FALSE;
    //if(is_super_admin()){
    if(red_funciones_is_administrador_grupo()){    
        return TRUE;
    }
    return FALSE;
}
function hound_settings_form(){
    drupal_set_title(t('Hound settings'));
    $form=array();
    $hound_is_active=hontza_is_hound_actions();
    if(hound_is_active_access()){
        $form['hound_is_active']=array(
            '#title'=>t('Hound active'),
            '#type'=>'checkbox',
        );
        if($hound_is_active){
            $form['hound_is_active']['#attributes']=array('checked'=>'checked');
        }
    }
    //intelsat-2016
    if(hound_enlazar_inc_is_activado()){
        $hound_key=hound_enlazar_inc_get_key();
        $form['hound_key']=array(
            '#title'=>t('Hound key'),
            '#type'=>'textfield',
            '#default_value'=>$hound_key,
        );
    }
    $form['save_btn']=array(
        '#type'=>'submit',
        '#name'=>'save_btn',
        '#value'=>t('Save'),
    );
    $url_volver='vigilancia/validados';
    /*if(isset($_REQUEST['destination']) && !empty($_REQUEST['destination'])){
        $url_volver=$_REQUEST['destination'];
    }*/
    $form['cancelar_btn']=array(
        '#value'=>l(t('Return'),$url_volver,array('attributes'=>array('class'=>'back_left'))),
    );
    return $form;
}
function hound_settings_form_submit($form, &$form_state){
    if(isset($form_state['clicked_button']) && !empty($form_state['clicked_button'])){
        $name=$form_state['clicked_button']['#name'];
        if(strcmp($name,'save_btn')==0){
            if(hound_is_active_access()){
                $hound_is_active=$form_state['values']['hound_is_active'];
                if(!empty($hound_is_active)){
                    $hound_is_active=1;
                }else{
                    $hound_is_active=0;
                }
                variable_set('hound_is_active',$hound_is_active);
            }
            //intelsat-2016
            hound_enlazar_inc_hound_key_save($form_state);
        }
    }
    //intelsat-2016
    drupal_set_message(t('Hound settings saved'));
    drupal_goto('vigilancia/validados');
}
function hound_is_item_espacenet($link,&$link_ini,&$link_end){
    $link_ini='';
    $link_end='';
    $find='http://worldwide.espacenet.com';
    $pos=strpos($link,$find);
    if($pos===FALSE){
        return 0;
    }else{    
        $find2='&II=';
        $my_array=explode($find2,$link);
        if(count($my_array)>1){
            $pos2=strpos($my_array[1],'&');
            if($pos2===FALSE){
                return 0;
            }else{
                $link_ini=$my_array[0];
                $link_end=substr($my_array[1],$pos2);
                return 1;
            }
        }
    }    
    return 0;
}
//intelsat-2015
function hound_is_new_server_hound(){
    if(defined('_IS_NEW_SERVER_HOUND') && _IS_NEW_SERVER_HOUND==1){
        return 1;
    }
    return 0;
}
//intelsat-2015
function hound_set_ip_url($url){
    $result=$url;
    $is_ip=1;
    //$ip_hound=hontza_define_hound_url($is_ip);
    $hound_base_url=hound_base_url();
    $hound_url=$hound_base_url.'/index.php';
    $ip_hound_array=array('80.32.72.239:8000','192.168.110.211');
        if(!empty($ip_hound_array)){
            foreach($ip_hound_array as $i=>$value){
                $hound_tmp='http://'.$value.'/hound/index.php';
                $result=str_replace($hound_tmp,$hound_url,$result);
                //print 'result='.$result;exit();
            }
        }
    return $result;
}
//intelsat-2016
function hound_reset_hound_callback(){
    $nid=arg(1);
    if(!hontza_is_hound_canal($nid)){
        drupal_access_denied();
        exit();
    }
    $canal_node=node_load($nid);
    //$feeds_source=hontza_get_feeds_source($nid);
    hound_update_canal_last_import_time($canal_node);
    drupal_set_message(t('Hound initialized'));
    drupal_goto('node/'.$nid);
}
//intelsat-2016
function hound_update_canal_last_import_time($canal_node){
    if(db_table_exists('content_field_last_import_time')){
        db_query('UPDATE {content_field_last_import_time} SET field_last_import_time_value=0 WHERE nid=%d AND vid=%d',$canal_node->nid,$canal_node->vid);
        hontza_solr_search_clear_cache_content($canal_node);
    }
}
//intelsat-2016
function hound_admin_grupo_access(){
    if(is_super_admin()){
        return TRUE;
    }
    /*$modo_estrategia=1;
    if(is_administrador_grupo($modo_estrategia)){
        return TRUE;
    }*/
    if(red_crear_usuario_is_rol_administrador_creador_grupo()){
        return TRUE;
    }
    return FALSE;
}
function hound_add_reset_hound_menu_node_link($nid){
   if(hontza_is_hound_text_input() && hontza_is_hound_canal($nid)){
       $result='<li>'.l(t('Reset Hound'),'hound/'.$nid.'/reset_hound',array('query'=>drupal_get_destination())).'</li>';
       return $result;
   }
   return '';
}
//intelsat-2016
function hound_feed_actualizar_callback(){
    return 'Funcion desactivada';
    /*
    $result = db_query('SELECT * FROM {job_schedule} WHERE 1');        
    $kont=0;
    //  
    while ($job = db_fetch_array($result)) {
        if (function_exists($job['callback'])) {
            //$job['callback']($job);
            if($job['callback']=='feeds_source_import'){
                print $job['id'].'<br>';
                feeds_source_import($job);
            }
        }
    }*/
    if(hound_is_feed_actualizar()){
        $hound_array=hound_get_all_array();    
        if(!empty($hound_array)){
            foreach($hound_array as $i=>$row){
                $canal_hound_parametros=hound_get_canal_hound_parametros_row($row->nid);
                //echo print_r($canal_hound_parametros,1);
                //hound_feed_actualizar_canal($row->nid);
            }
        }
    }
    return date('Y-m-d H:i:s');
  //}
}
//intelsat-2016
function hound_is_feed_actualizar(){
    if(defined('_IS_HOUND_FEED_ACTUALIZAR') && _IS_HOUND_FEED_ACTUALIZAR==1){
        return 1;
    }
    return 0;
}
//intelsat-2016
function hound_feed_actualizar_canal($nid){
    $result = db_query('SELECT * FROM {job_schedule} WHERE id="%s"',$nid);        
    $kont=0;
    //  
    while ($job = db_fetch_array($result)) {
        if (function_exists($job['callback'])) {
            //$job['callback']($job);
            if($job['callback']=='feeds_source_import'){
                feeds_source_import($job);
                break;
            }
        }
    }
}
//intelsat-2016
function hound_urldecode_array($result_in){
    $result=$result_in;
    if(!empty($result)){
        foreach($result as $field=>$row){
            foreach($row as $f=>$value){
                $result->$field->$f=urldecode($value);
            }    
        }    
    }
    return $result;
}
//intelsat-2016
function hound_is_active_access(){
    if(is_super_admin()){
        return TRUE;
    }
    return FALSE;
}
//intelsat-2016
function hound_cron(){
    hound_noticia_feed_noticia_email_actualizar();
}
//intelsat-2016-hound-filter
function hound_is_hound_filter_activado(){
  if(defined('_IS_HOUND_FILTER') && _IS_HOUND_FILTER==1){
      return 1;
  }
  return 0;
}
//intelsat-2016-hound-filter
function hound_is_show_filtros_rss($is_hound,$nid){
    if($is_hound){
        $feeds_source=get_feeds_source($nid);
        if(isset($feeds_source->source) && !empty($feeds_source->source)){
            $konp='query.yahooapis.com/v1/public/yql';
            $pos=strpos($feeds_source->source,$konp);
            if($pos===FALSE){
                return 0;
            }else{
                return 1;
            }
        }
        return 0;
    }
    return 1;
}    