<?php
require_once('visualizador.categorias.inc.php');
require_once('visualizador.custom.menu.inc.php');
function visualizador_perm() {
  return array();
}
function visualizador_menu() {
    $items=array();
    $items['visualizador/inicio'] = array(
    'title' => 'Home',
    'page callback' => 'visualizador_inicio_callback',
    //'access arguments'=>array('access content'),
    'access callback'=>'visualizador_anonimo_access',    
  );
    $items['visualizador/project'] = array(
    'title' => 'Home',
    'page callback' => 'visualizador_project_callback',
    //'access arguments'=>array('access content'),
    'access callback'=>'visualizador_anonimo_access',    
  );
    $items['visualizador/aviso_legal'] = array(
    'title' => 'Home',
    'page callback' => 'visualizador_aviso_legal_callback',
    //'access arguments'=>array('access content'),
    'access callback'=>'visualizador_anonimo_access',    
  );
    $items['visualizador/mapa_sitio'] = array(
    'title' => 'Home',
    'page callback' => 'visualizador_mapa_sitio_callback',
    //'access arguments'=>array('access content'),
    'access callback'=>'visualizador_anonimo_access',    
  );
    $items['visualizador/about_project'] = array(
    'title' => 'About Alerta Project',
    'page callback' => 'visualizador_about_project_callback',
    'access callback'=>'visualizador_anonimo_access',    
  );
    $items['visualizador/frontpage'] = array(
    'title' => 'Frontpage',
    'page callback' => 'visualizador_frontpage_callback',
    'access callback'=>'visualizador_anonimo_access',    
  );
  return $items;  
}
function visualizador_inicio_callback(){
    $html=array();
    $html[]=visualizador_inicio_get_texto_html();
    $html[]=visualizador_categorias_get_inicio_categorias_html();        
    $html[]=visualizador_inicio_get_noticias_destacadas_html();
    return implode('',$html);
}
function visualizador_inicio_get_noticias_destacadas_html(){
    $my_limit=3;
    $field_pager='page_noticias_destacadas';
    $noticias_destacadas_array=visualizador_get_noticias_destacadas_array();
    //$noticias_destacadas_array=my_set_estrategia_pager($noticias_destacadas_array, $my_limit);
    $noticias_destacadas_array=my_set_estrategia_pager($noticias_destacadas_array, $my_limit,$field_pager);
    $output = '<h3>'.t('Highlighted News').'</h3>';
  $num_rows = FALSE;
 foreach ($noticias_destacadas_array as $i=>$r){
    $node=node_load($r->nid); 
    $node_view=node_view($node, 1);
    $node_view=visualizador_prepare_node_view($node_view,$node->type);
    $output .=$node_view;      
    $num_rows = TRUE;
  }
  
  if ($num_rows) {
    //$feed_url = url('rss.xml', array('absolute' => TRUE));
    //drupal_add_feed($feed_url, variable_get('site_name', 'Drupal') . ' ' . t('RSS'));
    //$output .= '<div style="float:left;width:100%;padding-top:0px;"'.theme('pager', NULL,$my_limit).'</div>';
    $output .= '<div style="float:left;width:100%;padding-top:0px;"'.theme('pager', NULL,$my_limit,0,array(),9,$field_pager).'</div>';  
  }
  else {
     $output.= '<div id="first-time">' .t('There are no contents'). '</div>';  
  }
    
    
    
    return $output;
}
function visualizador_get_noticias_destacadas_array(){
    $noticias_destacadas_array=array();
    $where=array();
    $where[]='1';
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $where[]='og_ancestry.group_nid='.$my_grupo->nid;
    }
    $where[]='(content_type_item.field_is_carpeta_noticia_destaca_value=1 OR content_type_noticia.field_is_noticia_usuario_destaca_value=1)';
    //    
    $sql='SELECT node.* 
    FROM {node}
    LEFT JOIN {og_ancestry} ON node.nid=og_ancestry.nid 
    LEFT JOIN {content_type_item} ON node.vid=content_type_item.vid 
    LEFT JOIN {content_type_noticia} ON node.vid=content_type_noticia.vid 
    WHERE '.implode(' AND ',$where).'
    ORDER BY node.created DESC';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $noticias_destacadas_array[]=$row;
    }
    return $noticias_destacadas_array;
}
function visualizador_is_visualizador_activado(){
    $sareko_id_array=array('VISUALIZADOR','OBSERVATORIO');
    if(!empty($sareko_id_array)){
        foreach($sareko_id_array as $i=>$sareko_id){
            if(hontza_is_sareko_id($sareko_id)){
                return 1;
            }
        }
    }
    if(defined('_IS_VISUALIZADOR_MODULE') && _IS_VISUALIZADOR_MODULE==1){
        return 1;
    }
    if(hontza_canal_rss_is_visualizador_defined()){
        $is_visualizador=variable_get('is_visualizador',0);
        if($is_visualizador){
            return 1;
        }        
    }
    return 0;
}
function visualizador_prepare_node_view($node_view,$node_type){
    $find='<div class="n-opciones-item">';
    $pos=strpos($node_view,$find);
    if($pos===FALSE){
        return $node_view;
    }else{
        $result='<div style="width:33%;float:left;">';
        $result.=substr($node_view,0,$pos);
        $result.='</div></div>';
        if($node_type!='noticia'){
            $result.='</div>';
        }
        return $result;
    }
    return '';
}
function visualizador_is_show_user_image($type=''){
    //if($type!='inicio'){
        if(visualizador_is_pantalla('inicio')){
            return 0;
        }
    //}
    if(hontza_is_user_anonimo()){
        if($type!='inicio'){
            return 0;
        }   
    }else{
        if($type=='inicio'){
            return 0;
        }
    }
    return 1;
}
function visualizador_is_pantalla($konp=''){
    $param0=arg(0);
    if(!empty($param0) && $param0=='visualizador'){
        if(!empty($konp)){
            $param1=arg(1);        
            if(!empty($param1) && $param1==$konp){
                return 1;
            }
        }else{
            return 1;
        }    
    }
    return 0;
}
function visualizador_get_username_item($my_user_info){
    if(visualizador_is_pantalla('inicio')){
        return t('By ').'<b>'.$my_user_info['username'].'</b> ';
    }
    return '';
}
//intelsat-2015
function visualizador_user_add_grupos_todos($account){
    $grupos=hontza_get_all_nodes(array('grupo'));
    if(!empty($grupos)){
        foreach($grupos as $i=>$grupo_row){
            $og_uid_row=visualizador_get_og_uid_row($account->uid,$grupo_row->nid);
        }
    }
}
//intelsat-2015
function visualizador_get_og_uid_row($uid,$grupo_nid){
    $where=array();
    $where[]='1';
    if(!empty($grupo_nid)){
        $where[]='nid='.$grupo_nid;
    }    
    if(!empty($uid)){
        $where[]='uid='.$uid;
    }
    $sql='SELECT * FROM {og_uid} WHERE '.implode(' AND ',$where);
    print $sql;exit();
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        return $row;
    }
    $result=new stdClass();
    return $result;
}
function visualizador_prepare_menu_menu_primary_links($result_in){
    global $base_url,$language;
    $grupo=visualizador_create_grupo_base_path();
    $result=$result_in;
    $langcode='';
    if($language->language!='en'){
         $langcode='/'.$language->language;
    }
    if(hontza_is_user_anonimo() || visualizador_is_pantalla() || publico_is_pantalla_publico() || publico_alerta_is_pantalla_alerta()){
        $result=array();
        $result['menu-1437']=array();
        $result['menu-1437']['attributes']['title']='';                
        $result['menu-1437']['langcode']=$language->language;
        $result['menu-1437']['href']=url($base_url.$langcode.'/'.$grupo.'/visualizador/inicio',array('absolute'=>true));
        $result['menu-1437']['title']=visualizador_get_inicio_tab_title_lang('Home');
        $result['menu-1234']=array();
        $result['menu-1234']['attributes']['title']='';    
        $result['menu-1234']['langcode']=$language->language;
        $result['menu-1234']['alter']=1;
        $result['menu-1234']['href']=url($base_url.$langcode.'/'.$grupo.'/visualizador/project',array('absolute'=>true));
        $title_project=t('The Project');
        $nid=visualizador_get_project_nid();
        $node=hontza_node_load_by_lang($nid);        
        if(isset($node->nid) && !empty($node->nid)){
            $title_project=$node->title;
        }
        $result['menu-1234']['title']=visualizador_get_inicio_tab_title_lang($title_project);                
        $result['menu-1440']=array();
        $result['menu-1440']['attributes']['title']='';        
        $result['menu-1440']['langcode']=$language->language;
        $result['menu-1440']['alter']=1;
        $result['menu-1440']['href']=url($base_url.$langcode.'/'.$grupo.'/publico/vigilancia/ultimos',array('absolute'=>true));
        $result['menu-1440']['title']=visualizador_get_inicio_tab_title_lang('Latest news');
        /*$result['menu-4444']=array();
        $result['menu-4444']['attributes']['title']='';    
        $result['menu-4444']['langcode']=$language->language;
        $result['menu-4444']['alter']=1;
        $user_register='/user/register';
        //if(!hontza_is_user_anonimo()){
            $user_register='/publico/user/register';
        //}
        $result['menu-4444']['href']=url($base_url.$langcode.'/'.$grupo.$user_register,array('absolute'=>true));
        $result['menu-4444']['title']=visualizador_get_inicio_tab_title_lang('Register');*/        
        $result['menu-2812']=array();
        $result['menu-2812']['attributes']['title']='';    
        $result['menu-2812']['langcode']=$language->language;
        $result['menu-2812']['alter']=1;
        $result['menu-2812']['href']=url($base_url.$langcode.'/'.$grupo.'/publico/alerta_user/mis_boletines_grupo',array('absolute'=>true));
        $result['menu-2812']['title']=visualizador_get_inicio_tab_title_lang('Bulletins');
    }
    return $result;
}
function visualizador_create_grupo_base_path(){
    $grupo=visualizador_get_grupo_default();
    if(isset($grupo->purl) && !empty($grupo->purl)){
        return $grupo->purl;
    }
    return 'test';
}
function visualizador_is_top_item_activado($href,$selected){
    global $base_url,$language;
    $grupo=visualizador_create_grupo_base_path();
    $url_absoluto=$base_url.'/'.$grupo.'/'.$selected;
    if(strcmp($href,$url_absoluto)==0){
        return 1;
    }    
    $langcode='';
    if($language->language!='en'){
         $langcode='/'.$language->language;
    }
    $url_absoluto=$base_url.$langcode.'/'.$grupo.'/'.$selected;
    if(strcmp($href,$url_absoluto)==0){
        return 1;
    }
    return 0;
}
function visualizador_get_node_url($result_in){
    global $base_url;
    $result=$result_in;
    $my_grupo=og_get_group_context();        
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){

    }else{
        $grupo=visualizador_create_grupo_base_path();
        $result=$base_url.'/'.$grupo.'/'.$result;
    }
    return $result;
}
function visualizador_create_top_links(){
    global $base_url;
    $html=array();
    $grupo=visualizador_create_grupo_base_path();
    $result=$result_in;    
    //if(hontza_is_user_anonimo()){
        $result=array();
        $base_url.'/'.$grupo.'/visualizador/inicio';
        $html[]='<li>'.l(t('Home'),$base_url.'/'.$grupo.'/visualizador/inicio',array('absolute'=>TRUE)).'</li>';
        $html[]='<li>'.l(t('Latest news'),$base_url.'/'.$grupo.'/publico/vigilancia/ultimos',array('absolute'=>TRUE)).'</li>';
        $html[]='<li>'.l(t('Bulletins'),$base_url.'/'.$grupo.'/publico/alerta_user/mis_boletines_grupo',array('absolute'=>TRUE)).'</li>';
    //}    
    return implode('&nbsp;|&nbsp;',$html).'|';
}
function visualizador_get_inicio_tab_title_lang($label){
    /*global $language;
    $result=$label;
    if($language->language=='es'){
        if($label=='Home'){
            $result='Inicio';
        }else if($label=='Latest news'){
            $result='Últimas noticias';
        }else if($label=='Register'){
            $result='Regístrese';
        }else if($label=='Bulletins'){
            $result='Boletines';
        }
    }else if($language->language=='eu'){
        if($label=='Home'){
            $result='Hasi';
        }else if($label=='Latest news'){
            $result='Azkeneko berriak';
        }else if($label=='Register'){
            $result='Erregistratu';
        }else if($label=='Bulletins'){
            $result='Buletinak';
        }
    }else if($language->language=='fr'){
        if($label=='Home'){
            $result='Accueil';
        }else if($label=='Latest news'){
            
        }else if($label=='Register'){
            
        }else if($label=='Bulletins'){
            $result='Bulletins';
        }
    }*/
    $result=t($label);
    //intelsat-2015
    $result=strtoupper($result);
    return $result;
}
function visualizador_is_show_categorias_tipos_fuentes_item(){
    if(visualizador_is_pantalla('inicio')){
        return 0;
    }
    return 1;
}
function visualizador_create_busqueda_form_simple(){
    $html=array();
    $search='';
    if(isset($_REQUEST['search']) && !empty($_REQUEST['search'])){
        $search=$_REQUEST['search'];
    }
    $html[]='<input id="id_visualizador_busqueda_text" type="text" value="'.$search.'"/>';
    return implode('',$html);
}
function visualizador_project_callback(){
    //drupal_set_title(t('The project'));            
    $nid=visualizador_get_project_nid();
    //$node=node_load($nid);
    $node=hontza_node_load_by_lang($nid);
    drupal_set_title($node->title);
    $output=node_view($node,FALSE,1);
    $output=visualidador_unset_node_view_links($output);
    return $output;
}
function visualizador_create_busqueda_submit_link(){
    global $base_url;
    $grupo=visualizador_create_grupo_base_path();
    $icono=my_get_icono_action('viewmag',t('Search'),'','').'&nbsp;';
    //$icono
    $url=$base_url.'/'.$grupo.'/publico/vigilancia/busqueda';
    $result=l($icono,$url,array('html'=>true,'attributes'=>array('id'=>'id_a_visualizador_busqueda')));
    visualizador_add_busqueda_submit_js($url);
    return $result;
}
function visualizador_add_busqueda_submit_js($url){
    $js='var visualizador_busqueda_url="'.$url.'"
   $(document).ready(function()
   {
        $("#id_a_visualizador_busqueda").click(function(){
            visualizador_busqueda_buscar();
            return false;
        });
        $("#id_visualizador_busqueda_text").keyup(function (e) {
            if (e.which == 13) {
                visualizador_busqueda_buscar();
            }
        });
        function visualizador_busqueda_buscar(){
            var search=$("#id_visualizador_busqueda_text").val();
            window.location.href=visualizador_busqueda_url+"?search="+search;
        }    
   });';
    drupal_add_js($js,'inline');
}
function visualizador_get_frase_powered(){
    $html=array();
    $background_color=visualizador_get_background_color_logos();
    $margin_top='';
    if(!hontza_is_user_anonimo()){
        $margin_top='margin-top:-10px';
    }
    $html[]='<div style="float:left;width:100%;margin: 0 auto;'.$background_color.$margin_top.'">';
    $style='float:left;width:33%;';
    $sobre_proyecto=visualizador_get_sobre_proyecto_html();
    $alerta_html='';
    $contacta_equipo=visualizador_get_contacta_equipo_html();
    if(visualizador_is_red_alerta()){
        $alerta_html=red_funciones_alerta_financiado_por_html(1);    
    }
    $html[]='<div style="'.$style.'padding-left:5px;">'.$sobre_proyecto.'</div>';
    $html[]='<div style="'.$style.'">'.$contacta_equipo.'</div>';
    $html[]='<div style="'.$style.'">'.$alerta_html.'</div>';
    $html[]='</div>';
    $html[]=visualizador_get_sitio_mapa_html();
    return implode('',$html);
}
function visualizador_get_sobre_proyecto_html(){
    $html=array();
    $nid=visualizador_get_sobre_proyecto_nid();
    $node=hontza_node_load_by_lang($nid);
    //$label=l($node->title,'visualizador/about_project');    
    //$label=t('About Alerta Project');
    $label=$node->title;
    $label=l($label,'visualizador/about_project');
    $html[]='<div class="rt-block">';
    $html[]='<div class="main-title module-title"><div class="module-title2"><div class="module-title3"><h2 class="title" style="visibility: visible;"><span>'.$label.'</span></h2></div></div></div>';
    $html[]='<div class="module-content">';
    $html[]='<div class="customtitle2">';
    $texto=visualizador_get_texto_sobre_proyecto($node);
    $html[]='<p style="color:black;">'.$texto.'</p>';
    $html[]='</div>';    
    $html[]='<div class="clear"></div>';
    $html[]='</div>';
    $html[]='</div>';
    return implode('',$html);
}
function visualizador_get_texto_sobre_proyecto($node){
    $result=visualizador_categorias_get_categoria_description($node->body,290);
    return $result;
}
function visualizador_get_contacta_equipo_html(){
    $html=array();
    $label=t(variable_get('contact_title_text','Contact to the team'));
    $label=l($label,'visualizador/about_project');
    $html[]='<div class="rt-block">';
    $html[]='<div class="main-title module-title"><div class="module-title2"><div class="module-title3"><h2 class="title" style="visibility: visible;"><span>'.$label.'</span></h2></div></div></div>';
    $html[]='<div class="module-content">';
    $html[]='<div class="customtitle2">';
    $content=visualizador_get_contacts_html();
    $html[]=$content;
    $html[]='</div>';
    $html[]='<div class="clear"></div>';
    $html[]='</div>';
    $html[]='</div>';
    return implode('',$html);
}
function visualizador_get_sitio_mapa_html(){
    $html=array();
    $style='color:white;';
    //$margin_top='margin-top:150px;';
    //$margin_top='margin-top:200px;';
    $margin_top='margin-top:165px;';
    if(!hontza_is_user_anonimo()){
        $margin_top='margin-top:155px;';
    }
    //$height='height:20px;';        
    $height='height:10px;';
    $html[]='<div style="width:100%;background-color:black;'.$height.$margin_top.'padding-bottom:10px;">';
    //$copy='&copy; 2015 Proyecto Alerta. Todos los derechos reservados | <u>'.l('Aviso legal','visualizador/aviso_legal',array('attributes'=>array('style'=>$style,'target'=>'_blank'))).'</u>';
    //$copy=t('&copy; 2015 Alerta Project. All rights reserved').' | <u>'.l(t('Legal warning'),'visualizador/aviso_legal',array('attributes'=>array('style'=>$style,'target'=>'_blank'))).'</u>';    
    $title=t('Legal warning');
    $nid=visualizador_get_aviso_legal_nid();
    $node=hontza_node_load_by_lang($nid);
    if(isset($node->nid) && !empty($node->nid)){
        $title=$node->title;
    }
    //$copyright_text=t('&copy; 2015 Alerta Project. All rights reserved');
    $copyright_text=t(variable_get('copyright_text','&copy; 2015 Alerta Project. All rights reserved'));
    $copy=$copyright_text.' | <u>'.l($title,'visualizador/aviso_legal',array('attributes'=>array('style'=>$style))).'</u>';        
    $html[]='<div style="float:left;padding-left:5px;">'.$copy.'</div>';
    //$mapa_sitio=l(t('Site map'),'visualizador/mapa_sitio',array('attributes'=>array('style'=>$style,'target'=>'_blank')));
    //$mapa_sitio=l(t('Site map'),'visualizador/mapa_sitio',array('attributes'=>array('style'=>$style)));
    //$html[]='<div style="float:right;padding-right:100px;"><u>'.$mapa_sitio.'</u></div>';
    $html[]='</div>';
    return implode('',$html);
}
function visualizador_aviso_legal_callback(){
    $nid=visualizador_get_aviso_legal_nid();
    $node=hontza_node_load_by_lang($nid);
    drupal_set_title($node->title);
    $output=node_view($node,FALSE,1);
    $output=visualidador_unset_node_view_links($output);
    return $output;
}
function visualizador_mapa_sitio_callback(){
    drupal_not_found();
    exit();
    $nid=142840;
    $node=hontza_node_load_by_lang($nid);
    drupal_set_title($node->title);
    $output=node_view($node,FALSE,1);
    $output=visualidador_unset_node_view_links($output);
    return $output;
}
function visualidador_unset_node_view_links($result_in){
    $result=hontza_canal_rss_unset_node_view_links($result_in);
    return $result;
}
function visualizador_get_inicio_url($result_in){
    $result=$result_in;
    //if(hontza_is_user_anonimo()){
    if(publico_alerta_is_publico()){
        $result='/visualizador/inicio';
    }
    return $result;
}
function visualizador_get_iconos_redes_sociales(){
    $html=array();
    $facebook_url=variable_get('facebook_url_observatorio','https://www.facebook.com');
    $style=' style="padding:0;"';
    $html[]='<li'.$style.'>'.l(my_get_icono_action('facebook','Facebook','rss_general'),$facebook_url,array('html'=>TRUE,'attributes'=>array('target'=>'_blank'))).'</li>';
    $twitter_url=variable_get('twitter_url_observatorio','https://twitter.com');    
    $html[]='<li'.$style.'>'.l(my_get_icono_action('twitter','Twitter','rss_general'),$twitter_url,array('html'=>TRUE,'attributes'=>array('target'=>'_blank'))).'</li>';            
    $linkedin_url=variable_get('linkedin_url_observatorio','https://www.linkedin.com');
    $html[]='<li'.$style.'>'.l(my_get_icono_action('linkedin','Linkedin','rss_general'),$linkedin_url,array('html'=>TRUE,'attributes'=>array('target'=>'_blank'))).'</li>';    
    $html[]='<li'.$style.'>'.l(my_get_icono_action('global_rss', t('RSS'),'rss_general'),'publico/rss_general',array('html'=>TRUE,'attributes'=>array('target'=>'_blank'))).'</li>';
    return implode('',$html);
}
function visualizador_about_project_callback(){    
    $nid=visualizador_get_sobre_proyecto_nid();
    $node=hontza_node_load_by_lang($nid);
    drupal_set_title($node->title);
    //drupal_set_title(t('About Alerta Project'));
    $output='<div id="id_div_about_project">';
    $output.='<div class="div_about_project">';
    $output.=visualidador_unset_node_view_links(node_view($node,FALSE,1));
    $output.='</div>';
    $output.='<div class="div_contact_about_project">';
    $output.='<h2><b>'.variable_get('contact_title_text','Contact to the team').'</b></h2>';
    $output.=visualizador_get_contacts_html(1);
    $output.='</div>';
    $output.='</div>';
    return $output;
}
function visualizador_get_sobre_proyecto_nid(){
    if(visualizador_is_red_alerta()){
        return 142838;
    }else{
        $visualizador_sobre_proyecto_node=visualizador_get_sobre_proyecto_node();
        if(isset($visualizador_sobre_proyecto_node->nid) && !empty($visualizador_sobre_proyecto_node->nid)){
            return $visualizador_sobre_proyecto_node->nid;
        }        
    }
    return '';
}
function visualizador_help_block(&$vars,$hook){
    $is_online=0;
    $is_block=1;
    if(strcmp($vars['block']->delta,'61')==0){
        $vars['block']->subject=$vars['block']->subject.help_popup_block(143969,$is_block,$is_online);
        return '';
    }
    if(strcmp($vars['block']->delta,'62')==0){
        $vars['block']->subject=$vars['block']->subject.help_popup_block(143970,$is_block,$is_online);
        return '';
    }
    if(strcmp($vars['block']->delta,'63')==0){
        $vars['block']->subject=$vars['block']->subject.help_popup_block(143971,$is_block,$is_online);
        return '';
    }
    if(strcmp($vars['block']->delta,'64')==0){
        $is_block=4;
        $vars['block']->subject=$vars['block']->subject.help_popup_block(143973,$is_block,$is_online);
        return '';
    }
    if(strcmp($vars['block']->delta,'65')==0){
        $vars['block']->subject=$vars['block']->subject.help_popup_block(143979,$is_block,$is_online);
        return '';
    }
}
function visualizador_get_aviso_legal_nid(){
    if(visualizador_is_red_alerta()){
        return 142839;
    }else{
        $visualizador_aviso_legal_node=visualizador_get_aviso_legal_node();
        if(isset($visualizador_aviso_legal_node->nid) && !empty($visualizador_aviso_legal_node->nid)){
            return $visualizador_aviso_legal_node->nid;
        }        
    }
    return '';
}
function visualizador_get_project_nid(){
    if(visualizador_is_red_alerta()){
        return 142836;
    }else{
        $visualizador_proyecto_node=visualizador_get_proyecto_node();
        if(isset($visualizador_proyecto_node->nid) && !empty($visualizador_proyecto_node->nid)){
            return $visualizador_proyecto_node->nid;
        }        
    }
    return '';
}
function visualizador_get_contacts_html($is_about_project=0){
    $html=array();
    $contacts_array=panel_admin_contacts_get_contacts_array();
    if(!empty($contacts_array)){
        if(!$is_about_project){
            $max=3;                
            if(count($contacts_array)>$max){
                $contacts_array=array_slice($contacts_array,0,$max);
            }                
            $html[]='<div id="id_div_contacts">';
        }else{
            $html[]='<div id="id_div_contacts_about_project">';
        }
        foreach($contacts_array as $i=>$my_node){
            $logo=panel_admin_contacts_get_logo($my_node);
            $content='<div class="div_contacts">';
            $url=panel_admin_contacts_get_value_visualizador_contacto_url($my_node);
            $content.='<div class="div_contacts_logo">';
            $content.=l($logo,$url,array('attributes'=>array('target'=>'_blank'),'html'=>true));
            $content.='</div>';
            $content.='<div class="div_contacts_title">';
            $content.='<div>';
            $content.=$my_node->title;
            $content.='</div>';
            $content.='<div>';
            /*$mail='';
            if(isset($my_node->field_contacto_correo[0]['value']) && !empty($my_node->field_contacto_correo[0]['value'])){
                $mail=$my_node->field_contacto_correo[0]['value'];
            }*/
            $mail=panel_admin_contacts_get_value_visualizador_contacto_correo($my_node);
            $content.='<a href="mailto:'.$mail.'">'.$mail.'</a>';
            $content.='</div>';            
            $content.='</div>';
            $content.='</div>';
            $html[]=$content;            
        }
        $html[]='</div>';
    }
    return implode('',$html);
}
function visualizador_get_background_color_logos(){
    $result='#CCCCCC';
    //$result='#808080';
    $result='background-color:'.$result.';';
    return $result;
}
function visualizador_inicio_get_texto_html(){
    $nid=visualizador_inicio_get_texto_nid();
    $node=hontza_node_load_by_lang($nid);
    return $node->body;    
}
function visualizador_inicio_get_texto_nid(){        
    if(visualizador_is_red_alerta()){
        return 144576;
    }else{
        $visualizador_inicio_texto_node=visualizador_get_inicio_texto_node();
        if(isset($visualizador_inicio_texto_node->nid) && !empty($visualizador_inicio_texto_node->nid)){
            return $visualizador_inicio_texto_node->nid;
        }        
    }
    return '';
}
function visualizador_frontpage_callback(){
    global $base_url;
    $my_lang='';
    if(hontza_is_user_anonimo()){
        $my_lang='/es';
    }
    if(visualizador_is_red_alerta()){
        $url=$base_url.$my_lang.'/test/visualizador/inicio';
        drupal_goto($url);
    }else{
        $my_grupo_default=visualizador_get_grupo_default();
        if(isset($my_grupo_default->purl) && !empty($my_grupo_default->purl)){
            $url=$base_url.$my_lang.'/'.$my_grupo_default->purl.'/visualizador/inicio';
            drupal_goto($url);
        }else{
            drupal_goto('node');
        }
    }
    exit();
}
function visualizador_is_red_alerta(){
    $sareko_id_array=array('VISUALIZADOR','OBSERVATORIO');
    if(in_array(_SAREKO_ID,$sareko_id_array)){
        return 1;
    }
    if(defined('_IS_VISUALIZADOR_RED_ALERTA') && _IS_VISUALIZADOR_RED_ALERTA==1){
        return 1;
    }
    return 0;
}
function visualizador_get_proyecto_node(){
    $sql='SELECT * FROM {node} WHERE type="visualizador_proyecto" AND node.language="en" ORDER BY node.nid ASC';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result=node_load($row->nid);
        return $result;
    }
    $my_result=new stdClass();
    return $my_result;
}
function visualizador_get_grupo_nid(){
    $result=140028;
    if(!visualizador_is_red_alerta()){
        $my_grupo=og_get_group_context();
        if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
            $result=$my_grupo->nid;
        }else{
            $my_grupo_nid_default=visualizador_get_grupo_nid_default();
            if(!empty($my_grupo_nid_default)){
                $result=$my_grupo_nid_default;
            }
        }
    }    
    return $result;
}
function visualizador_get_sobre_proyecto_node(){
    $sql='SELECT * FROM {node} WHERE type="visualizador_sobre_proyecto" AND node.language="en" ORDER BY node.nid ASC';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result=node_load($row->nid);
        return $result;
    }
    $my_result=new stdClass();
    return $my_result;
}
function visualizador_get_aviso_legal_node(){
    $sql='SELECT * FROM {node} WHERE type="visualizador_aviso_legal" AND node.language="en" ORDER BY node.nid ASC';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result=node_load($row->nid);
        return $result;
    }
    $my_result=new stdClass();
    return $my_result;
}
function visualizador_get_inicio_texto_node(){
    $sql='SELECT * FROM {node} WHERE type="visualizador_inicio_texto" AND node.language="en" ORDER BY node.nid ASC';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result=node_load($row->nid);
        return $result;
    }
    $my_result=new stdClass();
    return $my_result;
}
function visualizador_get_boletin_texto_node(){
    $sql='SELECT * FROM {node} WHERE type="visualizador_boletin_texto" AND node.language="en" ORDER BY node.nid ASC';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result=node_load($row->nid);
        return $result;
    }
    $my_result=new stdClass();
    return $my_result;
}
function visualizador_is_visualizador_grupos_colaborativos($with_user_anonimo=1){
    if(visualizador_is_visualizador_activado()){
        if(visualizador_is_red_alerta()){
            return 0;
        }
        if($with_user_anonimo){
            if(hontza_is_user_anonimo()){
                return 1;
            }
        }else{
            return 1;
        }
    }
    return 0;
}
function visualizador_get_grupo_default(){
    $my_grupo_nid=visualizador_get_grupo_nid();
    $my_grupo_default=node_load($my_grupo_nid);
    return $my_grupo_default;
}
function visualizador_get_grupo_nid_default(){
    $my_grupos=red_crear_usuario_get_grupos_assoc();
    $my_grupos=array_keys($my_grupos);
    if(isset($my_grupos[0])){
        return $my_grupos[0];
    }
    return '';
}
function visualizador_anonimo_access(){
    return publico_anonimo_access();
}
function visualizador_is_menu_sin_flechas(){
    if(visualizador_is_red_alerta()){
        return 1;
    }
    if(publico_is_pantalla_publico()){
        return 1;
    }
    if(hontza_is_user_anonimo()){
        return 1;
    }
    return 0;    
}
function visualizador_is_show_banner_slider(){
    if(visualizador_is_pantalla('inicio')){
        if(visualizador_is_banners_active()){
            return TRUE;
        }    
    }
    return FALSE;
}
function visualizador_is_banners_active(){
    global $language;
    $res = db_query('SELECT n.nid FROM node n LEFT JOIN content_type_banner cfp ON cfp.vid = n.vid WHERE n.type = "banner" AND cfp.field_banner_activado_value=1 AND language="'.$language->language.'" AND sticky = 1 ORDER BY cfp.field_pisu_value, n.created DESC');
    while($row=db_fetch_object($res)){
        return 1;
    }
    return 0;
}    