<?php
function recuperar_borrados_perm() {
  return array();
}
function recuperar_borrados_menu() {
    $items=array();
    $items['recuperar_borrados/copiar'] = array(
    'title' => 'Channel',
    'page callback' => 'recuperar_borrados_copiar_callback',
    'access arguments'=>array('root'),    
  );    
    return $items;
}
function recuperar_borrados_copiar_callback(){
    //recuperar_borrados_update_title();
    return 'Funcion desactivada';
    db_set_active('borrados');
    $uid=755;
    $node_array=recuperador_borrados_get_user_node_array($uid);
    db_set_active();
    $group_nid_array=array();
    $kont=0;
    $new_kont=0;
    $uid_borrado=769;
    $tid=212169;
    $account=user_load($uid_borrado);
    foreach($node_array as $i=>$row){
        //$node_row=node_load($row->nid);
        $node_row=recuperar_borrados_get_node_row($row->nid);
        if(isset($node_row->nid) && !empty($node_row->nid)){
            //
            print $node_row->nid.'<br>';
            $kont++;
        }else{
            $key_array=array_keys($row->og_groups);
            if(!in_array($key_array[0],$group_nid_array)){
                $group_nid_array[]=$key_array[0];
            }
            $node=$row;
            if(isset($node->title)){
                unset($node->nid);
                unset($node->vid);
                //$canal_nid=211213;
                $node->title.=' (copia)';
                $node->field_item_canal_reference[0]['nid']=$canal_nid;
                //$node->feeds_node_item->feed_nid=$canal_nid;
                //$node->uid=1;
                if($node->uid==$uid){
                    $node->uid=$uid_borrado;
                }
                $created=$node->created;
                $changed=$node->changed;
                node_save($node);
                hontza_delete_flag_content($node);                
                $flag_result = flag('flag','leido_interesante',$node->nid,$account);
                recuperar_borrados_update_flag_content_uid($node->nid,$uid_borrado);
                red_funciones_flag_save_validador_node($node->nid,2,$uid_borrado);
                recuperar_borrados_update_validador_node($node->nid,$uid_borrado);
                recuperar_borrados_update_fechas($node,$created,$changed);
                recuperar_borrados_insert_term_node($node,$tid);
                print 'new_nid='.$node->nid.'='.$node->type.'<BR>';
                $new_kont++;
            }    
        }    
    }
    print 'new_kont='.$new_kont.'<br>';
    echo print_r($group_nid_array,1);exit();
}
function recuperador_borrados_get_user_node_array($uid){
    $result=array();
    $sql='SELECT node.nid
    FROM {node} node
    LEFT JOIN {flag_content} flag_content ON node.nid=flag_content.content_id
    WHERE node.uid='.$uid.' OR flag_content.uid='.$uid;
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=node_load($row->nid);
    }
    return $result;
}
function recuperar_borrados_get_node_row($nid){
    $sql='SELECT node.*
    FROM {node} node
    WHERE node.nid='.$nid;
    //print $sql.'<br>';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        return $row;
    }
    $my_result=new stdClass();
    return $my_result;
}
function recuperar_borrados_update_fechas($node,$created,$changed){
    db_query('UPDATE {node} SET created=%d,changed=%d WHERE nid=%d AND vid=%d',$created,$changed,$node->nid,$node->vid);
}
function recuperar_borrados_update_flag_content_uid($nid,$uid){    
	$sql='UPDATE {flag_content} SET uid= '.$uid.' WHERE content_id='.$nid;	
	db_query($sql);
}
function recuperar_borrados_update_validador_node($nid,$uid){
    $sql='UPDATE {validador_node} SET uid= '.$uid.' WHERE content_id='.$nid;	
    db_query($sql);
}
function recuperar_borrados_insert_term_node($node,$tid){
    db_query('INSERT INTO {term_node}(nid,vid,tid) VALUES(%d,%d,%d)',$node->nid,$node->vid,$tid);
}
function recuperar_borrados_update_title(){
    $uid_borrado=769;
    $flag_content_array=recuperar_borrados_get_flag_content_array($uid_borrado);
    if(!empty($flag_content_array)){
        foreach($flag_content_array as $i=>$row){
            $node=node_load($row->content_id);
            $title=str_replace(' (copia)','',$node->title);
            $res=db_query($sql=sprintf('UPDATE {node} SET title="%s" WHERE nid=%d',$title,$node->nid));
            $res=db_query($sql=sprintf('UPDATE {node_revisions} SET title="%s" WHERE nid=%d',$title,$node->nid));
            //print $sql.'<BR>';
        }
    }
}
function recuperar_borrados_get_flag_content_array($uid){
    $res=db_query('SELECT * FROM {flag_content} WHERE uid=%d',$uid);
    $result=array();
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}    