<?php
require_once('crm_exportar.textos.inc.php');
require_once('crm_exportar.tags.inc.php');
function crm_exportar_perm() {
  return array();
}
function crm_exportar_menu() {
  $items=array();
  //$items['crm_exportar/exportar_noticias/%/%/%']=array(
  $items['crm_exportar/exportar_noticias']=array(
    'title'=>'Home',
    'page callback' => 'crm_exportar_exportar_noticias_callback',
    'access callback' => 'crm_exportar_exportar_custom_access',
  );
  $items['crm_exportar/crear_url']=array(
    'title'=>'Create crm search',
    'page arguments'=>array('crm_exportar_crear_url_form'),  
    'page callback' => 'drupal_get_form',
    'access callback' => 'crm_exportar_crear_url_access',
  );
  $items['crm_exportar/crear_url_post']=array(
    'title'=>'Create crm search',
    'page arguments'=>array('crm_exportar_crear_url_form'),  
    'page callback' => 'drupal_get_form',
    'access callback' => 'crm_exportar_crear_url_access',
  );
  $items['crm_exportar/%/change_link_type']=array(
    'title'=>'Change link type',
    'page callback' => 'crm_exportar_change_link_type_callback',
    'access callback' => 'crm_exportar_change_link_type_access',
  );
  $items['crm_exportar/%/change_link_type_ajax']=array(
    'title'=>'Change link type',
    'page callback' => 'crm_exportar_change_link_type_ajax_callback',
    'access callback' => 'crm_exportar_change_link_type_access',
  );
  /*$items['crm_exportar/get_ip']=array(
    'title'=>'Home',
    'page callback' => 'crm_exportar_get_ip_callback',
    'access callback' => TRUE,
  );*/
  $items['crm_exportar/textos/importar']=array(
    'title'=>'Clients',
    'page arguments' => array('crm_exportar_textos_importar_form'),       
    'page callback' => 'drupal_get_form',       
    'access arguments' => array('root'),
  );
  $items['crm_exportar/textos/links']=array(
    'title'=>'Clients',
    'page callback' => 'crm_exportar_textos_links_callback',
    'access callback' => 'crm_exportar_exportar_custom_access',
  );
  $items['crm_exportar/textos/autocomplete']=array(
    'title'=>'Clients',
    'page callback' => 'crm_exportar_textos_autocomplete_callback',
    'access callback' => 'crm_exportar_exportar_custom_access',
  );
  $items['crm_exportar/textos/exportar_noticias_kont']=array(
    'title'=>'Update results',
    'page callback' => 'crm_exportar_textos_exportar_noticias_kont_callback',
    'access callback' => 'crm_exportar_exportar_custom_access',
  );
  $items['crm_exportar/textos_exportar_todas_noticias']=array(
    'title'=>'Home',
    'page callback' => 'crm_exportar_textos_exportar_todas_noticias_callback',
    //'access callback' => 'crm_exportar_exportar_custom_access',
    'access callback' => 'crm_exportar_crear_url_access',
  );
  $items['crm_exportar/tags/automatic']=array(
    'title'=>'Automatic tags',
    'page callback' => 'crm_exportar_tags_automatic_callback',
    'access arguments' => array('root'),
    //'access callback' => TRUE,  
  );
  $items['crm_exportar/textos_exportar_todas_noticias_automatic_tags']=array(
    'title'=>'Home',
    'page callback' => 'crm_exportar_textos_exportar_todas_noticias_automatic_tags_callback',
    'access arguments' => array('root'),
    //'access callback' => TRUE,
  );
  return $items;
}
function crm_exportar_exportar_custom_access(){
  global $user;
  /*if(is_super_admin()){
      return TRUE;
  }
  return FALSE;*/
  if(crm_exportar_is_crm_exportar_texto()){
    $modo_estrategia=1;
    if(hontza_is_user_anonimo()){
      return FALSE;
    }    
    if(is_super_admin()){
      return TRUE;
    }  
    //if(!red_funciones_is_administrador_grupo()){
    //if(is_administrador_grupo($modo_estrategia)){
    if(isset($user->roles[ADMINISTRADOR_DE_GRUPO])){
      return TRUE;
    }
    return FALSE;      
  }
  return TRUE;  
}
function crm_exportar_exportar_noticias_callback(){
  crm_exportar_ip_access_denied();
  crm_exportar_exportar_noticias();  
}
function crm_exportar_exportar_noticias($crm_in='',$is_kont=0,$is_todas=0,$row_in=''){
  $crm=arg(2);  
  $fecha_ini=crm_exportar_convertir_fecha(arg(3));
  $fecha_fin=crm_exportar_convertir_fecha(arg(4));
  if($is_todas){
    if(empty($fecha_ini) && empty($fecha_fin)){
    //if(empty($crm)){  
      $fecha_ini=crm_exportar_convertir_fecha(strtotime('2016-06-01 00:00:00'));
      $fecha_fin=0;
    }
    $crm=$crm_in;
    if(crm_exportar_is_crm_exportar_tag()){
      $crm=crm_exportar_tags_get_crm_boolean($row_in);
    }      
  }
  if(crm_exportar_is_crm_exportar_texto()){
    if($is_kont){
      $fecha_ini=crm_exportar_convertir_fecha(strtotime('2016-06-01 00:00:00'));
      $fecha_fin=0;
    }
  }
  $param_solr=arg(5);
  $is_post=0;
  if(isset($_POST['tag']) && isset($_POST['fecha_inicio']) && isset($_POST['fecha_fin'])){
      //crm_exportar_authenticate();
      $is_post=1;
      $crm=$_POST['tag'];
      if(is_array($_POST['fecha_inicio']) && is_array($_POST['fecha_fin'])){
          $fecha_ini=my_get_request_fecha_value('fecha_inicio');
          $fecha_fin=my_get_request_fecha_value('fecha_fin');
          $fecha_ini=crm_exportar_convertir_fecha($fecha_ini,$is_post);
          $fecha_fin=crm_exportar_convertir_fecha($fecha_fin,$is_post);
      }else{            
        $fecha_ini=crm_exportar_convertir_fecha($_POST['fecha_inicio']);
        $fecha_fin=crm_exportar_convertir_fecha($_POST['fecha_fin']);
      }
  }
  if($is_kont){
    $crm=$crm_in;
  }
  //$value='my_solr/my_search?f[0]=im_og_gid%3A187709&f[1]=im_field_item_canal_reference%3A253463&solrsort=ds_created desc';
  //$value='my_solr/my_search?f[0]=im_og_gid:188959&f[1]=im_taxonomy_vid_3:211690&solrsort=ds_created desc';
  //intelsat-2016
  //$group_array=hontza_get_all_nodes(array('grupo'),'','',0,'',0);
  $group_array=crm_exportar_get_group_array();
  $crm_texto=crm_exportar_get_crm_texto($crm,$row_in);
  $tid_array=array();
  //if(!crm_exportar_is_crm_exportar_texto()){
    $tid_array=crm_exportar_get_tid_array($crm);
  //}  
  $nid_array=array();
  $texto='';
  $fechas_solr=hontza_solr_get_search_fechas($fecha_ini,$fecha_fin);
  if(!empty($fechas_solr)){
    if(crm_exportar_is_crm_exportar_texto()){
      if(!empty($crm_texto)){
        //$texto='/("'.$crm_texto.'" AND '.$fechas_solr.')';
        //$texto='/('.$crm_texto.' AND '.$fechas_solr.')';
        $texto='/('.$crm_texto.') AND ('.$fechas_solr.')';
        $fechas_solr='/('.$fechas_solr.')';
      }else{
        $fechas_solr='/('.$fechas_solr.')';
      }
    }else{
      $fechas_solr='/('.$fechas_solr.')';    
    }  
  }else{
    if(crm_exportar_is_crm_exportar_texto()){
      if(!empty($crm_texto)){
        //$texto='/"'.$crm_texto.'"';
        $texto='/'.$crm_texto;
      }
    }  
  }
  if(!empty($param_solr)){
    $is_solr=crm_exportar_is_param_solr($param_solr);
  }else{  
    //$is_solr=1;
    $is_solr=0;      
  }
  if(crm_exportar_is_crm_exportar_texto()){
    $is_solr=1;
    if(empty($texto)){
      $texto=$fechas_solr;
    }      
  }  
    if(!empty($tid_array) || crm_exportar_is_crm_exportar_texto()){
      if($is_solr){
          if(!empty($group_array)){
              foreach($group_array as $i=>$row){
                  if(crm_exportar_is_crm_exportar_texto()){
                      $value='my_solr/my_search'.$texto.'?f[0]=im_og_gid:'.$row->nid.'&solrsort=ds_created desc';
                      $result=alerta_solr_get_canal_busqueda_nid_array('',$value);                  
                      /*if(crm_exportar_is_crm_exportar_texto()){
                        //print $row->title.'='.count($result).'<br>';exit();
                        print $value;
                        exit();                                                                         
                      }*/                                 
                      $nid_array=array_merge($nid_array,$result);                      
                  }//else{  
                    foreach($tid_array as $b=>$tid){
                          $value='my_solr/my_search'.$fechas_solr.'?f[0]=im_og_gid:'.$row->nid.'&f[1]=im_taxonomy_vid_3:'.$tid.'&solrsort=ds_created desc';                  
                          $result=alerta_solr_get_canal_busqueda_nid_array('',$value);                  
                          $nid_array=array_merge($nid_array,$result);
                    }
                  //}                      
              }  
          }
      }else{
          if(!crm_exportar_is_crm_exportar_texto()){
            $nid_array=crm_exportar_get_nid_array_mysql($tid_array,$fecha_ini,$fecha_fin,$is_post);
          }  
      }    
    }    
  /*if(crm_exportar_is_crm_exportar_texto()){
    if(count($nid_array)>0){
      echo print_r($nid_array,1);
      exit();
    }
  }*/
  if($is_kont){
    return count($nid_array);
  }else{  
    if($is_todas){
      //return $nid_array;
      $my_result=array();
      $my_result['fecha_ini']=$fecha_ini;
      $my_result['fecha_fin']=$fecha_fin;
      $my_result['nid_array']=$nid_array;
      return $my_result;
    }else{
      $channel=array();
      crm_exportar_node_feed($nid_array,$channel,$crm,$is_post);
    }  
  }
  exit();
}
function crm_exportar_is_exportar_noticias(){    
  $param0=arg(0);  
  if(!empty($param0) && $param0=='crm_exportar'){
      $param1=arg(1);
      if(!empty($param1) && $param1=='exportar_noticias'){
          return 1;
      }
  }
  return 0;
}
function crm_exportar_get_tid_array($crm){
    $result=array();
    $vid=hontza_crm_inc_get_tags_vid();
    $konp=strtolower($crm);
    if(strcmp($konp,'crm:')==0){
        $res=db_query('SELECT * FROM {term_data} WHERE vid=%d AND name LIKE "%s%%"',$vid,$crm);
    }else{
        $res=db_query('SELECT * FROM {term_data} WHERE vid=%d AND name="%s"',$vid,$crm);
    }
    while($row=db_fetch_object($res)){
        $result[]=$row->tid;
    }
    return $result;
}
function crm_exportar_node_feed($nids = FALSE, $channel = array(),$crm,$is_post=0,$is_todas=0,$nid_tag_array=array(),$nid_duplicate_news_array=array()) {
  global $base_url, $language;

  if ($nids === FALSE) {
    $nids = array();
    $result = db_query_range(db_rewrite_sql('SELECT n.nid, n.created FROM {node} n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.created DESC'), 0, variable_get('feed_default_items', 10));
    while ($row = db_fetch_object($result)) {
      $nids[] = $row->nid;
    }
  }

  //intelsat-2016
  //$item_length = variable_get('feed_item_length', 'teaser');
  $item_length ='crm_exportar_item';
  
  $namespaces = array('xmlns:dc' => 'http://purl.org/dc/elements/1.1/');

  $items = '';
  
  //intelsat-2016
  $tag_array=array();
  $crm_id_array=array();
  $nids=crm_exportar_get_nids_by_crm_all($nids,$crm,$node_array,$crm_id_array,$tag_array,$is_todas,$nid_tag_array);    
  //$nid_duplicate_news_array=array();
  //foreach ($nids as $nid) {
  $nid_feed_array=array();
  foreach ($nids as $i=>$nid) {
    // Load the specified node:
    //intelsat-2016
    if(isset($node_array[$nid])){
      $item =$node_array[$nid];  
    }else{
      $item = node_load($nid);
      if(!(isset($item->nid) && !empty($item->nid))){
        continue;
      }
    }
    if(crm_exportar_is_crm_exportar_texto()){
      //if(!crm_exportar_textos_is_nid_duplicate_news($nid,$nid_duplicate_news_array,$i,$nid_tag_array)){
      if(!crm_exportar_textos_is_nid_duplicate_news_feed($nid,$nid_feed_array)){  
        continue;
      }
    }   
    $item->build_mode = NODE_BUILD_RSS;
    $item->link = url("node/$nid", array('absolute' => TRUE));

    if ($item_length != 'title') {
      $teaser = ($item_length == 'teaser') ? TRUE : FALSE;

      // Filter and prepare node teaser
      if (node_hook($item, 'view')) {
        $item = node_invoke($item, 'view', $teaser, FALSE);
      }
      else {
        $item = node_prepare($item, $teaser);
      }

      // Allow modules to change $node->content before the node is rendered.
      node_invoke_nodeapi($item, 'view', $teaser, FALSE);

      // Set the proper node property, then unset unused $node property so that a
      // bad theme can not open a security hole.
      $content = drupal_render($item->content);
      if ($teaser) {
        $item->teaser = $content;
        unset($item->body);
      }
      else {
        $item->body = $content;
        unset($item->teaser);
      }
    
      // Allow modules to modify the fully-built node.
      node_invoke_nodeapi($item, 'alter', $teaser, FALSE);
    }

    // Allow modules to add additional item fields and/or modify $item
    $extra = node_invoke_nodeapi($item, 'rss item');
    $extra = array_merge($extra, array(array('key' => 'pubDate', 'value' => gmdate('r', $item->created)), array('key' => 'dc:creator', 'value' => $item->name), array('key' => 'guid', 'value' => $item->nid .' at '. $base_url, 'attributes' => array('isPermaLink' => 'false'))));
    foreach ($extra as $element) {
      if (isset($element['namespace'])) {
        $namespaces = array_merge($namespaces, $element['namespace']);
      }
    }
   
    // Prepare the item description
    switch ($item_length) {
      case 'fulltext':
        $item_text = $item->body;
        break;
      case 'teaser':
        $item_text = $item->teaser;
        if (!empty($item->readmore)) {
          $item_text .= '<p>'. l(t('read more'), 'node/'. $item->nid, array('absolute' => TRUE, 'attributes' => array('target' => '_blank'))) .'</p>';
        }
        break;
      case 'title':
        $item_text = '';          
        break;
      case 'crm_exportar_item':
        $item_text=crm_exportar_content_resumen($item);
        break;
    }
    $items .= crm_exportar_format_rss_item($item->title, $item->link, $item_text, $extra,$item,$crm,$crm_id_array,$i,$tag_array,$is_todas,$nid_tag_array,$nid_duplicate_news_array);
  }
  $title=variable_get('site_name', 'Drupal');
  if(!empty($crm)){
      $title=$crm;
  }
  $channel_defaults = array(
    'version'     => '2.0',
    'title'       => $title,
    'link'        => $base_url,
    'description' => variable_get('site_mission', ''),
    'language'    => $language->language
  );
  $channel = array_merge($channel_defaults, $channel);

  $output = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
  $output .= "<rss version=\"". $channel["version"] ."\" xml:base=\"". $base_url ."\" ". drupal_attributes($namespaces) .">\n";
  $output .= format_rss_channel($channel['title'], $channel['link'], $channel['description'], $items, $channel['language']);
  $output .= "</rss>\n";

  if($is_post){  
    drupal_set_header('Content-Type: application/xml; charset=utf-8');
  }else{
    drupal_set_header('Content-Type: application/rss+xml; charset=utf-8');
  }
  print $output;
}
function crm_exportar_format_rss_item($title, $link_in, $description, $args = array(),$node,$crm,$crm_id_array,$i,$tag_array,$is_todas=0,$nid_tag_array=array(),$nid_duplicate_news_array=array()) {
  $link=crm_exportar_get_node_url($link_in,$node);  
  $output = "<item>\n";
  $output .= ' <date>'.date('Y-m-d H:i:s',$node->created)."</date>\n";
  $output .= ' <time>'.$node->created."</time>\n";
  $output .= ' <title>'. check_plain($title) ."</title>\n";
  $output .= ' <link>'. check_url($link) ."</link>\n";
  //intelsat-2016
  if(crm_exportar_is_crm_exportar_texto()){
    //$teaser=crm_exportar_textos_get_teaser($description);
    $teaser=node_teaser(strip_tags($description));
    /*$output .= ' <description>'. check_plain($description) ."</description>\n";
    $output .= ' <teaser>'. check_plain($teaser) ."</teaser>\n";*/
    //$output .= ' <description>'. check_plain($teaser) ."</description>\n";
    $output .= ' <description>'. check_plain($description) ."</description>\n";
  }else{
    $output .= ' <description>'. check_plain($description) ."</description>\n";    
  }
  /*if(is_super_admin()){
    $output=crm_exportar_add_tags_rss_item($node,$crm,$output);
  }*/
  //$output .= format_xml_elements($args);
  //$id=crm_exportar_get_node_guid($node);
  $id=$node->nid;
  if(crm_exportar_is_crm_all($crm)){
      $id=$crm_id_array[$i];
      $output .= ' <tag>'. check_plain($tag_array[$i]) ."</tag>\n";  
  }else{    
      $id=crm_exportar_create_crm_id($node->nid,$crm);
      if($is_todas){
        $output.=crm_exportar_textos_get_tags($i,$tag_array,$nid_tag_array,$node->nid,$nid_duplicate_news_array); 
      }else{
        $term_name=crm_exportar_get_term_name_by_crm($node,$crm);
        $output .= ' <tag>'. $term_name ."</tag>\n";
      }  
  }
  $output .= ' <id>'.$id."</id>\n";
  if(is_super_admin() || crm_exportar_is_crm_exportar_texto()){
      $group_title=crm_exportar_get_item_group_title($node);
      $output .= ' <group>'.$group_title."</group>\n";
  }
  $output .= "</item>\n";
  return $output;
}
function crm_exportar_create_guid(){
    $bytes=openssl_random_pseudo_bytes(16,$cstrong);
    $hex   = bin2hex($bytes);
    return $hex;
}
function crm_exportar_get_node_guid($node){
    if(isset($node->field_crm_guid) && isset($node->field_crm_guid[0]) && isset($node->field_crm_guid[0]['value']) && !empty($node->field_crm_guid[0]['value'])){
        return $node->field_crm_guid[0]['value'];
    }else{
        $num=1000;
        for($i=0;$i<$num;$i++){
            $id=crm_exportar_create_guid();
            if(!crm_exportar_existe_guid($id)){
                crm_exportar_save_node_guid($id,$node);
                return $id;
            }
        }
        return $node->nid;
    }    
}
function crm_exportar_existe_guid($id){
    $content_field_crm_guid_array=crm_exportar_get_content_field_crm_guid_array($id);
    if(count($content_field_crm_guid_array)>0){
        return 1;
    }
    return 0;
}
function crm_exportar_get_content_field_crm_guid_array($id){
    $result=array();
    $res=db_query('SELECT * FROM {content_field_crm_guid} WHERE field_crm_guid_value="%s"',$id);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function crm_exportar_save_node_guid($id,$node){
    db_query('UPDATE {content_field_crm_guid} SET field_crm_guid_value="%s" WHERE nid=%d',$id,$node->nid);
    hontza_solr_clear_cache_content($node->nid);
}
function crm_exportar_crear_url_form(){
    global $base_url;
    $form=array();
    crm_exportar_ip_access_denied();
    $type=arg(1);
    $form['#attributes']['target'] = '_blank';
    if(crm_exportar_is_crear_url_post($type)){
        $form['#action'] =$base_url.'/crm_exportar/exportar_noticias';
    }
    $form['file_buscar_fs']=array('#type'=>'fieldset','#title'=>t('Settings'),'#attributes'=>array('id'=>'file_buscar_fs','class'=>$class));
    $form['type']=array(
        '#type'=>'hidden',
        '#default_value'=>$type,
    );
    if(crm_exportar_is_crear_url_post($type)){
        $form['file_buscar_fs']['username']=array(
        '#type'=>'textfield',
        '#title'=>t('Username'),
        );
        $form['file_buscar_fs']['user_key']=array(
        '#type'=>'password',
        '#title'=>t('Password'),
        );
    }
    if(crm_exportar_is_crm_exportar_texto()){
      $form['file_buscar_fs']['tag']=array(
        '#type' => 'textfield',
        '#title' => t('Tag'),
        //'#maxlength' => 128,
        '#autocomplete_path' => 'crm_exportar/textos/autocomplete',
      );
      $form['file_buscar_fs']['tag']['#prefix']='<div style="display:none">';
      $form['file_buscar_fs']['tag']['#suffix']='</div>';
    }else{
      $form['file_buscar_fs']['tag']=array(
          '#type'=>'textfield',
          '#title'=>t('Tag'),
      );
    }
    $duplicate_news_prefix='<div style="padding-left:25px;">';
    if(crm_exportar_is_crm_exportar_texto()){
      $form['file_buscar_fs']['is_tag']=array(
          '#type'=>'checkbox',
          '#title'=>t('Automatic tagging'),
          '#attributes'=>array('checked'=>'checked'),
      );
      $form['file_buscar_fs']['is_export_xml']=array(
          '#type'=>'checkbox',
          '#title'=>t('Export XML'),
          '#attributes'=>array('checked'=>'checked'),
      );
      $form['file_buscar_fs']['is_duplicate_news']=array(
          '#type'=>'checkbox',
          '#title'=>t('One tag per item'),
          '#attributes'=>array('checked'=>'checked'),
          '#prefix'=>$duplicate_news_prefix,
          '#suffix'=>'</div>',
      );      
    }
    $form['file_buscar_fs']['is_time']=array(
        '#type'=>'checkbox',
        '#title'=>t('Unix Time'),        
    );    
    if(crm_exportar_is_crm_exportar_texto()){
        $form['file_buscar_fs']['is_time']['#prefix']=$duplicate_news_prefix;
        $form['file_buscar_fs']['is_time']['#suffix']='</div>';
        $grupo_options=crm_exportar_textos_get_grupo_options();
        if(!hontza_is_user_anonimo()){
            $form['file_buscar_fs']['grupo_nid']=array(
                '#type'=>'select',
                '#title'=>t('Groups'),
                '#options'=>$grupo_options,
                '#multiple'=>TRUE,
                '#default_value'=>crm_exportar_textos_get_grupo_nid_default(),
            );
        }
    }
    /*if(is_super_admin()){
        $form['file_buscar_fs']['is_solr']=array(
            '#type'=>'checkbox',
            '#title'=>t('Is Solr'),
            '#attributes'=>array('checked'=>'checked'),
        );
    }*/
    $form['file_buscar_fs']['fecha_inicio']=array(
			'#type' => 'date_select',
			'#date_format' => 'Y-m-d',
			'#date_label_position' => 'within',
			'#title'=>t('From'));
                        //'#default_value'=>  $fecha_inicio);
    $form['file_buscar_fs']['fecha_fin']=array(
			'#type' => 'date_select',
			'#date_format' => 'Y-m-d',
			'#date_label_position' => 'within',
			'#title'=>t('To'));
			//'#default_value'=>$fecha_fin);    
    $form['file_buscar_fs']['send_btn']=array(
        '#type'=>'submit',
        '#value'=>t('Run'),
        '#prefix'=>'<div style="padding-top:10px;">',
        //'#suffix'=>'</div>',
    );
    if(crm_exportar_is_crm_exportar_texto()){
      $links=crm_exportar_textos_get_links();
      $form['file_buscar_fs']['clientes_btn']=array(
          '#value'=>$links,
          '#suffix'=>'</div>',
      );
    }else{
      $form['file_buscar_fs']['send_btn']['#suffix']='</div>';
    }  
    drupal_set_title(t('Tagging & Export XML'));    
    if(crm_exportar_is_crm_exportar_texto()){
        crm_exportar_textos_crear_url_add_js();
    }
    return $form;
}
function crm_exportar_crear_url_form_submit($form, &$form_state){
    global $base_url;
    $crm=$form_state['values']['tag'];
    /*if(crm_exportar_is_crm_exportar_texto()){
      $crm='CRM:';
    }*/
    $fecha_ini=0;
    $is_time=$form_state['values']['is_time'];
    if(isset($form_state['values']['fecha_inicio'])){
        $fecha_ini=$form_state['values']['fecha_inicio'];
        if($is_time){
            $fecha_ini=strtotime($fecha_ini);
        }
    }
    $fecha_end=0;
    if(isset($form_state['values']['fecha_fin'])){
        $fecha_end=$form_state['values']['fecha_fin'];
        if($is_time){
            $fecha_end=strtotime($fecha_end);
        }
    }
    $type=$form_state['values']['type'];    
    if(!crm_exportar_is_crear_url_post($type)){
        $url=$base_url.'/crm_exportar/exportar_noticias/'.$crm.'/'.$fecha_ini.'/'.$fecha_end;
        /*$is_solr=2;
        if(isset($form_state['values']['is_solr'])){
            if(!empty($form_state['values']['is_solr'])){
                $is_solr=1;
            }
            $url.='/'.$is_solr;
        }*/
        if(crm_exportar_is_crm_exportar_texto()){
          if(empty($crm)){
            $url=$base_url.'/crm_exportar/textos_exportar_todas_noticias/todas/'.$fecha_ini.'/'.$fecha_end;
          }
        }
        //$url.=crm_exportar_textos_add_is_duplicate_news($form_state);  
        $url.=crm_exportar_textos_add_url_fields($form_state);
        drupal_goto($url);        
    }/*else{
        $form_state['rebuild']=TRUE;
    }*/    
}
function crm_exportar_content_resumen($node){
    $result='';
    if(hontza_node_has_body($node)){
        $value=$node->content['body']['#value'];
        return $value;
    }else{
        $result=red_funciones_get_node_description($node,1);
    }
    return $result;
}
function crm_exportar_get_nid_array_mysql($tid_array,$fecha_ini,$fecha_end,$is_post=0){
    $result=array();
    $where=array();
    $where[]='node.type IN("item","noticia")';
    //$field='node.created';
    $field='flag_content.timestamp';
    $where_time=hontza_get_usuarios_acceso_where_time($field,'','','',1,$fecha_ini,$fecha_end);
    if(!empty($where_time)){
        $where[]=$where_time;
    }
    if(!empty($tid_array)){
        $where[]='term_node.tid IN('.implode(',',$tid_array).')';    
    }else{
        return $result;
    }
    $sql='SELECT *
    FROM {node}
    LEFT JOIN {term_node} ON node.vid=term_node.vid
    LEFT JOIN {flag_content} ON node.nid=flag_content.content_id
    WHERE '.implode(' AND ',$where).'
    GROUP BY node.nid     
    ORDER BY node.created DESC';
    $res=db_query($sql);
    /*if($is_post){
        print $sql;
        exit();
    }*/

    while($row=db_fetch_object($res)){
        $result[]=$row->nid;
    }
    return $result;
}
function crm_exportar_node_form_alter(&$form,&$form_state, $form_id){
    if(isset($form['field_crm_guid'])){
        unset($form['field_crm_guid']);
    }
    $modo_estrategia=1;
    $node=$form['#node'];
    $field_item_link_type=crm_exportar_get_item_link_type_default_value($node);
    $form['field_item_link_type']['#default_value'][0]['value']=$field_item_link_type;
    $form['field_item_link_type']['value']['#default_value']=$field_item_link_type;
    //if(!is_administrador_grupo($modo_estrategia)){
    if(!crm_exportar_is_show_field_item_link_type($modo_estrategia,$node)){    
        if(isset($form['field_item_link_type'])){
            unset($form['field_item_link_type']);
        }
    }    
    $form['#after_build'][] = 'crm_exportar_node_after_build';
}
function crm_exportar_get_node_url($link,$node){
    global $base_url;
    $is_url=1;
    $link_platform=$base_url.'/node/'.$node->nid;
    if($node->type=='item'){
        if(crear_crm_exportar_is_node_link_web($node)){
            $result=hontza_item_web_link($node,$is_url);
        }else{
            $result=$link_platform;
        }    
    }else if($node->type=='noticia'){
        if(crear_crm_exportar_is_node_link_web($node)){
            $result=hontza_noticia_usuario_web_link($node,$is_url,1);
        }else{
            $result=$link_platform;
        }    
    }
    if(!empty($result) && $result!='no_existe_enlace_origen'){
        return $result;
    }
    return $link;
}
function crm_exportar_convertir_fecha($fecha,$is_post=0){
    if(!empty($fecha) && is_numeric($fecha)){
        return date('Y-m-d H:i:s',$fecha);
    }
    if(hontza_crm_validate_date($fecha)){
        return $fecha;
    }
    if(hontza_crm_validate_date($fecha,'Y-m-d')){
        return $fecha;
    }
    return 0;
}
function crm_exportar_canal_node_form_alter(&$form,&$form_state, $form_id){
    $node='';
    if(isset($form['#node'])){
        $node=$form['#node'];
    }
    $field_canal_link_type_value=crm_exportar_get_field_canal_link_type_value($node);
    $modo_estrategia=1;
    if(!is_administrador_grupo($modo_estrategia)){
        if(isset($form['field_canal_link_type'])){
            unset($form['field_canal_link_type']);
        }
    }
    $form['#after_build'][] = 'crm_exportar_canal_node_after_build';
}
function crm_exportar_get_item_group_title($node){
    if(isset($node->og_groups_both)){
        $values=array_values($node->og_groups_both);
        if(isset($values[0])){
            return $values[0];
        }
    }
    return '';
}
function crm_exportar_get_field_canal_link_type_value($node){
    if(isset($node->field_canal_link_type) && isset($node->field_canal_link_type[0]) && isset($node->field_canal_link_type[0]['value'])){
        if(!empty($node->field_canal_link_type[0]['value'])){
            return $node->field_canal_link_type[0]['value'];
        }
    }
    return 2;
}
function crm_exportar_canal_node_after_build($form, &$form_state) {
  if(isset($form['field_canal_link_type'])){
    $form['field_canal_link_type']['value']['#options'] = hontza_crm_inc_get_canal_link_type_options();
  }
  return $form;
}
function crm_exportar_crear_url_access(){
    if(crm_exportar_is_crm_exportar_texto()){
        if(crm_exportar_is_crm_exportar_tag()){        
            //return TRUE;
         }else{
            return FALSE;
        }    
    }
    return crm_exportar_exportar_custom_access();    
}
function crm_exportar_is_crear_url_post($type){
  if(!empty($type) && $type=='crear_url_post'){
      return 1;
  }
  return 0;
}
function crm_exportar_authenticate(){    
    $account=user_load(array('name' => $_POST['username'], 'pass' => trim($_POST['user_key']), 'status' => 1));
    if(isset($account->uid) && !empty($account->uid)){
        return 1;
    }else{
        drupal_access_denied();
        exit();
    }
    return 0;
}
function crear_crm_exportar_is_node_link_web($node){
    if(isset($node->field_item_link_type) && isset($node->field_item_link_type[0]) && !empty($node->field_item_link_type[0]['value'])){
        if($node->field_item_link_type[0]['value']==1){
            return 0;
        }
        return 1;
    }
    if(crear_crm_exportar_is_news_canal_link_web($node)){
        return 1;
    }
    return 0;
}
function crm_exportar_get_news_link_type_label($node){
    $value=1;
    //if(crear_crm_exportar_is_node_link_web($node)){
    if(in_array($node->type,array('canal_de_supercanal','canal_de_yql'))){
        if(crear_crm_exportar_is_canal_link_web($node)){
            $value=2;
        }
    }else if(in_array($node->type,array('item','noticia'))){
        //if(crear_crm_exportar_is_news_canal_link_web($node)){
        if(crear_crm_exportar_is_node_link_web($node)){
            $value=2;
        }
    }    
    $result=hontza_crm_inc_get_canal_link_type_options();
    if(isset($result[$value])){
        return $result[$value];
    }
    return '';
}
function crm_exportar_is_param_solr($param_solr){
    if(!empty($param_solr)){
        if($param_solr==1){
            return 1;
        }
    }
    return 0;
}
function crm_exportar_node_after_build($form,&$form_state){
    if(isset($form['field_item_link_type'])){
        $form['field_item_link_type']['value']['#options'] = hontza_crm_inc_get_canal_link_type_options();
        $field_item_link_type=crm_exportar_get_item_link_type_default_value($form['#node']);
        $form['field_item_link_type']['#default_value'][0]['value']=$field_item_link_type;
        $form['field_item_link_type']['value']['#default_value']=$field_item_link_type;
        $form['field_item_link_type']['value']['#defaults_loaded']=0;
    }
  return $form;
}
function crm_exportar_get_item_link_type_default_value($node){
    if(isset($node->field_item_link_type) && isset($node->field_item_link_type[0]) && !empty($node->field_item_link_type[0]['value'])){
        return $node->field_item_link_type[0]['value'];
    }
    if(crear_crm_exportar_is_news_canal_link_web($node)){
        return 2;
    }
    return 1;
}
function crear_crm_exportar_is_news_canal_link_web($node,$canal_in=''){
    if(isset($canal_in->nid) && !empty($canal_in->nid)){
        $canal=$canal_in;
    }else{
        $canal=hontza_crm_get_item_canal($node);
    }
    if(isset($node->type) && in_array($node->type,array('item'))){
        if(isset($canal->field_canal_link_type) && isset($canal->field_canal_link_type[0]) && !empty($canal->field_canal_link_type[0]['value'])){
            if($canal->field_canal_link_type[0]['value']==1){
                return 0;
            }
        }
    }    
    return 1;
}
function crear_crm_exportar_is_canal_link_web($canal){
    return crear_crm_exportar_is_news_canal_link_web('',$canal);
}
function crm_exportar_add_tags_rss_item($node,$crm,$output_in){  
    $output=$output_in;    
    if(isset($node->taxonomy) && !empty($node->taxonomy)){
        $vid=hontza_crm_inc_get_tags_vid();
        $output.='<tags>';                
        foreach($node->taxonomy as $tid=>$term){            
            if($term->vid==$vid){
                if(crm_exportar_is_crm_all($crm)){
                    if(crm_is_crm_term($term)){
                        $output.='<tag>'.$term->name.'</tag>';
                    }
                }
            }            
        }
        $output.="</tags>\n";
    }
    return $output;
}
function crm_exportar_is_crm_all($crm){
    $konp=strtolower($crm);
    if(strcmp($konp,'crm:')==0){
        return 1;
    }
    return 0;
}
function crm_is_crm_term($term){
    $konp='crm:';
    $value=trim(strtolower($term->name));
    $pos=strpos($value,$konp);
    if($pos===FALSE){
        return 0;
    }
    if($pos>0){
        return 0;
    }
    return 1;
}
function crm_exportar_get_nids_by_crm_all($nids,$crm,&$node_array,&$crm_id_array,&$tag_array,$is_todas=0,$nid_tag_array=array()){
    $result=$nids;
    if(crm_exportar_is_crm_exportar_texto()){
      if($is_todas){
        $result=crm_exportar_textos_get_nids_by_crm_all($nids,$crm,$node_array,$crm_id_array,$tag_array,$is_todas,$nid_tag_array);
      }
      return $result;
    }else{
      if(crm_exportar_is_crm_all($crm)){
          $result=array();
          $node_array=array();
          $vid=hontza_crm_inc_get_tags_vid();
          if(!empty($nids)){
              foreach($nids as $i=>$nid){
                  $node=new stdClass();
                  $node=node_load($nid);
                    if(isset($node->taxonomy) && !empty($node->taxonomy)){
                        foreach($node->taxonomy as $tid=>$term){            
                            if($term->vid==$vid){
                                //if(crm_exportar_is_crm_all($crm)){
                                    if(crm_is_crm_term($term) || crm_exportar_is_crm_exportar_texto()){
                                        $result[]=$nid;
                                        $crm_id_array[]=crm_exportar_create_crm_id($node->nid,$term->name);
                                        $node_array[]=$node;
                                        $tag_array[]=$term->name;
                                    }
                                //}
                            }
                        }    
                    }      
              }
          }
      }
    }  
    return $result;
}
function crm_exportar_create_crm_id($nid,$term_name){
    if(crm_exportar_is_crm_exportar_texto()){
      $result=$nid;
    }else{  
      $result=$nid.'_'.$term_name;
    }    
    return $result;        
}
function crm_exportar_get_term_name_by_crm($node,$crm){
    $konp=strtolower($crm);
    $vid=hontza_crm_inc_get_tags_vid();
    if(isset($node->taxonomy) && !empty($node->taxonomy)){
                    foreach($node->taxonomy as $tid=>$term){            
                        if($term->vid==$vid){
                            $term_name=strtolower($term->name);
                                if(crm_is_crm_term($term) && $konp==$term_name){
                                    return $term->name;
                                }
                        }
                    }    
    }
    return $crm;
}
function crm_exportar_link_type_action_class($node,$is_view=0){
    //if(is_super_admin()){
    $modo_estrategia=1;
    if(is_administrador_grupo($modo_estrategia)){
        $result='n-item-link-type-platform';
        if($is_view){
            $result='item-link-type-platform';        
        }
        if(crear_crm_exportar_is_node_link_web($node)){
            $result='n-item-link-type-web';
            if($is_view){
                $result='item-link-type-web';        
            }
        }
        return $result;
    }
    return '';
}
function crm_exportar_web_platform_type_link($node){
    //if(is_super_admin()){
    $modo_estrategia=1;
    if(is_administrador_grupo($modo_estrategia)){
        $attributes['id']='id_change_link_type_'.$node->nid;
        $attributes['class']='a_change_link_type_ajax';
        $result=l('','crm_exportar/'.$node->nid.'/change_link_type',array('query'=>drupal_get_destination(),'attributes'=>$attributes));
        return $result;
    }
    return '';
}
function crm_exportar_change_link_type_access(){
    if(is_super_admin()){
        return TRUE;
    }
    $modo_estrategia=1;
    if(is_administrador_grupo($modo_estrategia)){
        return TRUE;
    }
    return FALSE;
}
function crm_exportar_change_link_type_callback(){
    $url=$_REQUEST['destination'];
    /*$nid=arg(1);
    $node=node_load($nid);
    $value=2;
    if(crear_crm_exportar_is_node_link_web($node)){
        $value=1;
    }
    crm_exportar_update_field_item_link_type($node,$value);
    hontza_solr_search_clear_cache_content($node);*/
    crm_exportar_change_link_type();
    drupal_goto($url);
}
function crm_exportar_update_field_item_link_type($node,$value){
    $res=db_query('UPDATE {content_field_item_link_type} SET field_item_link_type_value=%d WHERE nid=%d AND vid=%d',$value,$node->nid,$node->vid);
}
function crm_exportar_change_link_type_add_js(){
    global $base_url;
    $purl='';
   $my_grupo=og_get_group_context(); 
   if(isset($my_grupo->purl) && !empty($my_grupo->purl)){
       $purl=$my_grupo->purl;
   }
    $js='$(document).ready(function()
   {
            crm_exportar_create_call_change_link_type_ajax_functions();
            function crm_exportar_call_change_link_type_ajax(nid){
             jQuery.ajax({
				//type: "POST",
                                type:"GET",
				url: "'.$base_url.'/'.$purl.'/crm_exportar/"+nid+"/change_link_type_ajax?my_time="+new Date().getTime(),
				dataType:"json",
				success: function(my_result){
                                    crm_exportar_change_link_type_ajax_on_success(my_result);
				}
			});
            }
            /*function crm_exportar_call_no_change_link_type_ajax(nid){
             jQuery.ajax({
				//type: "POST",
                                type:"GET",
				url: "'.$base_url.'/'.$purl.'/crm_exportar/"+nid+"/change_link_type_ajax?my_time="+new Date().getTime(),
				dataType:"json",
				success: function(my_result){
                                    crm_exportar_change_link_type_ajax_on_success(my_result);                                    
				}
			});
            }*/
            function crm_exportar_create_call_change_link_type_ajax_functions(){
                $("a.a_change_link_type_ajax").unbind( "click" );
                $("a.a_change_link_type_ajax").click(function(){
                    var a_id=$(this).attr("id");
                    var nid=a_id.replace("id_change_link_type_","");
                    crm_exportar_call_change_link_type_ajax(nid);
                    return false;
                });
                /*$("a.a_no_change_link_type_ajax").unbind( "click" );
                $("a.a_no_change_link_type_ajax").click(function(){
                    var a_id=$(this).attr("id");
                    var nid=a_id.replace("id_change_link_type_","");
                    crm_exportar_call_no_change_link_type_ajax(nid);
                    return false;
                });*/
            }
            function crm_exportar_change_link_type_ajax_on_success(my_result){
                var my_parent=$("#id_change_link_type_"+my_result.nid).parent();
                var my_class=my_parent.attr("class");
                my_parent.attr("class",set_change_link_type_item_class_ajax(my_class));
                my_parent.html(my_result.a);
                crm_exportar_create_call_change_link_type_ajax_functions();
            }
            function set_change_link_type_item_class_ajax(my_class){
                if(my_class=="n-item-link-type-web"){
                    return "n-item-link-type-platform";
                }
                if(my_class=="n-item-link-type-platform"){
                    return "n-item-link-type-web";
                }
                if(my_class=="item-link-type-web"){
                    return "item-link-type-platform";
                }
                if(my_class=="item-link-type-platform"){
                    return "item-link-type-web";
                }                
            }
   });';
   drupal_add_js($js,'inline');
}
function crm_exportar_change_link_type_ajax_callback(){
    crm_exportar_change_link_type();
    $result=array();
    $result['nid']=arg(1);
    print json_encode($result);
    exit();
}
function  crm_exportar_change_link_type(){
    $nid=arg(1);
    $node=node_load($nid);
    $value=2;
    if(crear_crm_exportar_is_node_link_web($node)){
        $value=1;
    }
    crm_exportar_update_field_item_link_type($node,$value);
    hontza_solr_search_clear_cache_content($node);
}
function crm_exportar_is_show_link_type_action($node=''){
    if(crm_exportar_change_link_type_access()){
        if(isset($node->type) && in_array($node->type,array('noticia'))){
            if(isset($node->field_enlace_noticia) && !empty($node->field_enlace_noticia)){
                if(isset($node->field_enlace_noticia[0]['url']) && !empty($node->field_enlace_noticia[0]['url'])){
                    return 1;           
                }    
            }
            return 0;
        }
        return 1;
    }
    return 0;
}
function crm_exportar_is_show_field_item_link_type($modo_estrategia,$node){
    if(is_administrador_grupo($modo_estrategia)){
        if($node->type=='noticia'){
            if(!crm_exportar_is_show_link_type_action($node)){
                return 0;
            }
        }           
        return 1;
    }    
    return 0;
}
function crm_exportar_ip_access_denied(){
    /*if(crm_exportar_is_crm_exportar_texto()){
        $is_crm_exportar_filtro_ip_activar=variable_get('is_crm_exportar_filtro_ip_activar',0);
        if($is_crm_exportar_filtro_ip_activar){
            $crm_exportar_ip_array=crm_exportar_get_crm_exportar_ip_array($_SERVER['REMOTE_ADDR']);
            if(count($crm_exportar_ip_array)>0){
                return 1;
            }
            print t('Access denied');
            exit();    
            return 0;
        }else{
            return 1;
        }
    }else{*/
        return 1;
    //}    
}
function crm_exportar_get_crm_exportar_ip_array($remote_addr){
    $result=array();
    $res=db_query('SELECT * FROM {crm_exportar_ip} WHERE ip="%s"',$remote_addr);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function crm_exportar_get_ip_callback(){
    print $_SERVER['REMOTE_ADDR'];
    exit();
}
function crm_exportar_is_crm_exportar_texto(){
  if(defined('_IS_CRM_EXPORTAR_TEXTO') && _IS_CRM_EXPORTAR_TEXTO==1){
    return 1;
  }
  return 0;
}
function crm_exportar_get_crm_texto($crm,$row){
  $result=$crm;
  if(crm_exportar_is_crm_exportar_texto()){
    $result=str_ireplace('CRM:','',$result);
    /*if(empty($result)){
      $result='CRM:';
    }*/
    if(!isset($row->booleano) || empty($row->booleano)){
      $result='"'.$result.'"';
    }
    $result='('.$result.' AND (itm_field_item_validate_status:2 OR itm_field_noticia_validate_statu:2))';
  }
  return $result;
}
function crm_exportar_get_group_array(){
  $group_array=array();
  if(crm_exportar_is_crm_exportar_texto()){
    if(isset($_REQUEST['grupo_nid']) && !empty($_REQUEST['grupo_nid'])){
        $grupo_nid_array=explode(',',$_REQUEST['grupo_nid']);
        if(!empty($grupo_nid_array)){
            foreach($grupo_nid_array as $i=>$my_grupo_nid){
                $grupo_node=node_load($my_grupo_nid);
                $group_array[]=$grupo_node;
            }
        }
    }else{
        //Solo hay que exportar en este caso las noticias de este grupo
        $grupo_nid=crm_exportar_textos_get_grupo_nid_default();
        $grupo_node=node_load($grupo_nid);
        $group_array[]=$grupo_node;
    }
  }else{  
    $group_array=hontza_get_all_nodes(array('grupo'),'','',0,'',0);
  }
  return $group_array;
}
function crm_exportar_is_crm_exportar_tag(){
  //$sareko_id_array=array('TAGS','TAGS_OTROALERTA');
  //if(in_array(_SAREKO_ID,$sareko_id_array)){
    if(defined('_IS_CRM_EXPORTAR_TAG') && _IS_CRM_EXPORTAR_TAG==1){
      return 1;
    }
  //}  
  return 0;
}
/*function crm_exportar_cron(){
  if(crm_exportar_is_crm_exportar_tag()){
    crm_exportar_tags_automatic_callback();
  }  
}*/
/*function crm_exportar_init(){
    //$GLOBALS['conf']['cache'] = FALSE;
    if(hontza_is_user_anonimo()){
        $GLOBALS['conf']['cache'] = FALSE;
    }        
}*/