<?php

/**
 * @file
 * This is an example outlining how a module can be used to define a new
 * node type.
 *
 * (Note that custom node types are most often created with CCK in recent
 * versions of Drupal.)
 *
 * Our alerta type will allow users to specify a "color" and a "quantity"
 * for their nodes; some kind of rudimentary inventory-tracking system, perhaps?
 * To store this extra information, we need an auxiliary database table as
 * defined in alerta_schema().
 */

/**
 * @defgroup alerta Example: Node
 * @ingroup examples
 * @{
 * Creating a new content type in a module. (drupal 6)
 *
 * This is an example outlining how a module can be used to define a new
 * node type.
 *
 * (Note that custom node types are most often created with CCK in recent
 * versions of Drupal.)
 *
 * Our alerta type will allow users to specify a "color" and a "quantity"
 * for their nodes; some kind of rudimentary inventory-tracking system, perhaps?
 * To store this extra information, we need an auxiliary database table as
 * defined in alerta_schema().
 *
 * This example is part of the Examples for Developers Project which you can download
 * and experiment with here: http://drupal.org/project/examples
 */
require_once('alerta.fun.php');
require_once('alerta.inc.php');
//intelsat-2015
require_once('alerta.solr.inc.php');
//
/**
 * Implementation of hook_menu().
 */
function alerta_menu() {
  $items['alerta'] = array(
    'title' => 'alert',
    'page callback' => 'alerta_info',
    'access callback' => TRUE,
  );
  $items['alerta_user/%user/my_list'] = array(
    'title' => t('My Alerts'),
    'page callback' => 'alerta_user_callback',
    'page arguments' => array(1),
    'access arguments' => array('Ver alerta_user'),
    //'type' => MENU_LOCAL_TASK,
  );
  $items['alerta_user/add_alerta_canal'] = array(
    'title' => t('Add Alert by Channel'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_canal_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver add_alerta_canal'),
  );
  $items['alerta_user/%/my_edit'] = array(
    'title' => t('Edit alert by channel'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_canal_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver edit_alerta_canal'),
  );
  $items['alerta_user/%/my_delete'] = array(
    'title' => t('Delete Alert by Channel'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('delete_alerta_canal_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver delete_alerta_canal'),
  );
  $items['alerta_user/add_alerta_categoria'] = array(
    'title' => t('Add Alert by Category'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_categoria_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver add_alerta_categoria'),
  );
  $items['alerta_user/%/my_edit_categoria'] = array(
    'title' => t('Edit alert by category'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_categoria_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver edit_alerta_categoria'),
  );
  $items['alerta_user/%/my_delete_categoria'] = array(
    'title' => t('Delete Alert by Category'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('delete_alerta_categoria_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver delete_alerta_categoria'),
  );
   $items['alerta_user/add_alerta_usuario'] = array(
    'title' => t('Add Alert by User'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_usuario_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver add_alerta_categoria'),
  );
  $items['alerta_user/%/my_edit_usuario'] = array(
    'title' => t('edit customised alert'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_usuario_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver edit_alerta_usuario'),
  );
  $items['alerta_user/%/my_delete_usuario'] = array(
    'title' => t('Delete Alert by User'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('delete_alerta_usuario_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver delete_alerta_usuario'),
  );
  $items['alerta/my_execute_cron'] = array(
    'title' => 'my_execute_cron',
    'page callback' => 'my_execute_cron_callback',
    'access arguments' => array('Ver my_execute_cron'),
  );
   $items['alerta_user/%/my_web'] = array(
    'title' => t('See Alert on the web'),
    'page callback' => 'my_web_callback',
    'access arguments' => array('Ver alerta_web'),
  );
  $items['alerta_user/mis_boletines_grupo'] = array(
    'title' => t('Groups Bulletins'),
    'page callback' => 'mis_boletines_grupo_callback',
    'access arguments' => array('Ver mis_boletines_grupo'),
  );
  $items['alerta_user/%/my_desuscribir'] = array(
    'title' => t('Unsubscribe custom alert by channel'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('desuscribir_alerta_canal_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver desuscribir_alerta_canal'),
  );
   $items['alerta_user/add_alerta_invitado'] = array(
    'title' => t('Add Guest alert'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_invitado_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver add_alerta_invitado'),
  );
  $items['alerta_user/%/my_edit_invitado'] = array(
    'title' => t('Edit Guest Alert'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_invitado_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver edit_alerta_invitado'),
  );
  $items['alerta_user/%/my_delete_invitado'] = array(
    'title' => t('Delete Alert by Guest'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('delete_alerta_invitado_form'),
    //'type' => MENU_CALLBACK,
    //'access callback' => TRUE,
    'access arguments' => array('Ver delete_alerta_invitado'),
  );
   $items['alerta/variables'] = array(
    'title' => t('Alert Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_variables_form'),
    //'type' => MENU_CALLBACK,
    'access callback' => 'alerta_variables_access_callback',
    //'access arguments' => array('Editar variables alerta'),
  );
   $items['alerta_user/inicio'] = array(
    'title' => t('Alerts'),
    'page callback' => 'alerta_user_inicio_callback',
    'access arguments' => array('Ver alerta_user'),
  );
   $items['alerta/simular_alerta_solr'] = array(
    'title' => t('Alerts'),
    'page callback' => 'alerta_solr_simular_alerta_solr_callback',
    //'access arguments' => array('root'),
    'access callback' => TRUE,   
  );
   //intelsat-2015
   $items['alerta_user/add_alerta_busqueda'] = array(
    'title' => t('Add Alert by Search'),
    'page callback' => 'drupal_get_form',
    'page arguments'   => array('alerta_solr_busqueda_form'),
    'access callback' => 'alerta_solr_alerta_busqueda_access',
   );
   $items['alerta_user/%/resultado_busqueda'] = array(
    'title' => t('Results'),
    'page callback' => 'alerta_solr_resultado_busqueda_callbak',
    'access callback' => 'alerta_solr_alerta_resultadobusqueda_access',
   );
    $items['alerta_user/%/resultado_canal_busqueda'] = array(
    'title' => t('Results'),
    'page callback' => 'alerta_solr_resultado_canal_busqueda_callbak',
    'access callback' => 'alerta_solr_alerta_resultadobusqueda_access',
   );
   //
  return $items;
}

/**
 * Explain how the module demonstrates a new node type.alerta.test
 */
function alerta_info() {
	return t('The alert type defines a new node, \ alert type 1 \ ", Which can be created at !link."', array('!link' => l(t('node/add/example-node-type-1'), 'node/add/example-node-type-1')));
}
/**
 * Implementation of hook_node_info().
 *
 * This is a required node hook. This function describes the nodes provided by
 * this module.
 *
 * The required attributes are:
 * - "name" provides a human readable name for the node,
 * - "module" tells Drupal how the module's functions map to hooks (i.e. if the
 *   module is alerta_foo then alerta_foo_insert will be called
 *   when inserting the node).
 * - "description" provides a brief description of the node type, which is
 *   shown when a user accesses the "Create content" page for that node type.
 *
 * The other optional, attributes:
 * - "has_title" boolean that indicates whether or not this node type has a
 *   title field.
 * - "title_label": the label for the title field of this content type.
 * - "has_body": boolean that indicates whether or not this node type has a
 *   body field.
 * - "body_label": the label for the body field of this content type.
 * - "min_word_count": the minimum number of words for the body field to be
 *   considered valid for this content type.
 *
 * The key in this example, "example_node_type_1", is the "machine name" of the
 * node type and is stored in {node}.type. The node's type value cannot be
 * changed through the admin interface.
 *
 */
function alerta_node_info() {
  return array(
    'alerta' => array(
      'name' => t('alert type 1'),
      'module' => 'alerta',
      //'description' => t("An alerta type with a few fields."),
      'description' => t("An Alert type with a few fields."),
      'has_title' => TRUE,
      'title_label' => t('Alert Type 1 Title'),
      'has_body' => TRUE,
      'body_label' => t('Alert Type 1 Body'),
    )
  );
}

/**
 * Implementation of hook_access().
 *
 * Node modules may implement node_access() to determine the operations
 * users may perform on nodes. This example uses a very common access pattern.
 */
function alerta_access($op, $node, $account) {
  if ($op == 'create') {
    return user_access('create alerta', $account);
  }

  if ($op == 'update') {
    if (user_access('edit any alerta', $account) || (user_access('edit own alerta', $account) && ($account->uid == $node->uid))) {
      return TRUE;
    }
  }

  if ($op == 'delete') {
    if (user_access('delete any alerta', $account) || (user_access('delete own alerta', $account) && ($account->uid == $node->uid))) {
      return TRUE;
    }
  }
}

/**
 * Implementation of hook_perm().
 *
 * Since we are limiting the ability to create new nodes to certain users,
 * we need to define what those permissions are here. We also define a permission
 * to allow users to edit the nodes they created.
 */
function alerta_perm() {
  return array(
    'create alerta',
    'delete own alerta',
    'delete any alerta',
    'edit own alerta',
    'edit any alerta',
    //gemini
    'Ver alerta_user',
    'Ver add_alerta_canal',
    'Ver edit_alerta_canal',
    'Ver add_alerta_categoria',
    'Ver edit_alerta_categoria',
    'Ver delete_alerta_canal',
    'Ver delete_alerta_categoria',
    'Ver add_alerta_usuario',
    'Ver edit_alerta_usuario',
    'Ver delete_alerta_usuario',
    'Ver alerta_user_limites',
    'Ver my_execute_cron',
    'Ver alerta_web',
    'Ver mis_boletines_grupo',
    'Ver desuscribir_alerta_canal',
    'Ver add_alerta_invitado',
    'Ver edit_alerta_invitado',
    'Ver delete_alerta_invitado',
  );
}

/**
 * Implementation of hook_form().
 *
 * Now it's time to describe the form for collecting the information
 * specific to this node type. This hook requires us to return an array with
 * a sub array containing information for each element in the form.
 */
function alerta_form(&$node, $form_state) {
  // The site admin can decide if this node type has a title and body, and how
  // the fields should be labeled. We need to load these settings so we can
  // build the node form correctly.
  $type = node_get_types('type', $node);

  if ($type->has_title) {
    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => check_plain($type->title_label),
      '#required' => TRUE,
      '#default_value' => $node->title,
      '#weight' => -5
    );
  }

  if ($type->has_body) {
    // In Drupal 6, we use node_body_field() to get the body and filter
    // elements. This replaces the old textarea + filter_form() method of
    // setting this up. It will also ensure the teaser splitter gets set up
    // properly.
    $form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
  }

  // Now we define the form elements specific to our node type.
  $form['color'] = array(
    '#type' => 'textfield',
    '#title' => t('Color'),
    '#default_value' => isset($node->color) ? $node->color : '',
  );
  $form['quantity'] = array(
    '#type' => 'textfield',
    '#title' => t('Quantity'),
    '#default_value' => isset($node->quantity) ? $node->quantity : 0,
    '#size' => 10,
    '#maxlength' => 10
  );

  return $form;
}

/**
 * Implementation of hook_validate().
 *
 * Our "quantity" field requires a number to be entered. This hook lets
 * us ensure that the user entered an appropriate value before we try
 * inserting anything into the database.
 *
 * Errors should be signaled with form_set_error().
 */
function alerta_validate($node, &$form) {
  if ($node->quantity) {
    if (!is_numeric($node->quantity)) {
      form_set_error('quantity', t('The quantity must be a number.'));
    }
  }
}

/**
 * Implementation of hook_insert().
 *
 * As a new node is being inserted into the database, we need to do our own
 * database inserts.
 */
function alerta_insert($node) {
  db_query("INSERT INTO {alerta} (vid, nid, color, quantity) VALUES (%d, %d, '%s', %d)", $node->vid, $node->nid, $node->color, $node->quantity);
}

/**
 * Implementation of hook_update().
 *
 * As an existing node is being updated in the database, we need to do our own
 * database updates.
 */
function alerta_update($node) {
  // if this is a new node or we're adding a new revision,
  if ($node->revision) {
    alerta_insert($node);
  }
  else {
    db_query("UPDATE {alerta} SET color = '%s', quantity = %d WHERE vid = %d", $node->color, $node->quantity, $node->vid);
  }
}

/**
 * Implementation of hook_nodeapi().
 *
 * When a node revision is deleted, we need to remove the corresponding record
 * from our table. The only way to handle revision deletion is by implementing
 * hook_nodeapi().
 */
function alerta_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'delete revision':
      // Notice that we're matching a single revision based on the node's vid.
      db_query('DELETE FROM {alerta} WHERE vid = %d', $node->vid);
      break;
  }
}

/**
 * Implementation of hook_delete().
 *
 * When a node is deleted, we need to remove all related records from our table.
 */
function alerta_delete($node) {
  // Notice that we're matching all revision, by using the node's nid.
  db_query('DELETE FROM {alerta} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 *
 * Now that we've defined how to manage the node data in the database, we
 * need to tell Drupal how to get the node back out. This hook is called
 * every time a node is loaded, and allows us to do some loading of our own.
 */
function alerta_load($node) {
  $additions = db_fetch_object(db_query('SELECT color, quantity FROM {alerta} WHERE vid = %d', $node->vid));
  return $additions;
}

/**
 * Implementation of hook_view().
 *
 * This is a typical implementation that simply runs the node text through
 * the output filters.
 */
function alerta_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);
  $node->content['myfield'] = array(
    '#value' => theme('alerta_order_info', $node),
    '#weight' => 1,
  );

  return $node;
}

/**
 * Implementation of hook_theme().
 *
 * This lets us tell Drupal about our theme functions and their arguments.
 */
function alerta_theme() {
  return array(
    'alerta_order_info' => array(
      'arguments' => array('node'),
    ),
    'alerta_time' => array(
      'arguments' => array('element' => NULL),
    )
  );
}

/**
 * A custom theme function.
 *
 * By using this function to format our node-specific information, themes
 * can override this presentation if they wish. We also wrap the default
 * presentation in a CSS class that is prefixed by the module name. This
 * way, style sheets can modify the output without requiring theme code.
 */
function theme_alerta_order_info($node) {
  $output = '<div class="alerta_order_info">';
  $output .= t('The order is for %quantity %color items.', array('%quantity' => check_plain($node->quantity), '%color' => check_plain($node->color)));
  $output .= '</div>';
  return $output;
}

/**
 * @} End of "defgroup alerta".
 */
function alerta_user_callback(){
    global $user;
    //gemini-2013
    //drupal_add_js('sites/all/libraries/jquery_tablesorter/jquery-latest.js', 'file');
    //drupal_add_js('sites/all/libraries/jquery_tablesorter/jquery.tablesorter.js', 'file');
    
    $uid=arg(1);
    $output='';
    //
    $where=array();
    $where[]='1';
    $where[]='au.uid='.$user->uid;
    //
    if($user->uid!=$uid){
        return t('You can not edit the Personalized alert from other user');
    }
    //$result=drupal_get_form('alerta_user_form');
    
    //
    $my_limit=variable_get('default_nodes_main', 20);
    //
    $sql='SELECT au.*
    FROM {alerta_user} au
    WHERE '.implode(' AND ',$where).'
    ORDER BY au.created ASC';
    $res = db_query($sql);

    /*$headers=array();
    $headers[0]=t('Name');
    $headers[1]=t('Method');
    $headers[2]=t('Frequency');
    $headers[3]=t('Time');
    $headers[4]=t('Created');
    $headers[5]=t('Type');
    $headers[6]=t('Creator');
    $headers[7]=t('Status');
    $headers[8]=t('Actions');*/
    $headers=get_alerta_user_headers();

    $rows=array();
    $output=create_menu_alerta_user();
    $output.=my_create_boton_boletin_cron();
    $kont=0;
    while ($r = db_fetch_object($res)) {
      /*$rows[$kont]=array();
      $rows[$kont][0]=get_alerta_user_nombre($r);
      $rows[$kont][1]=get_metodo_name($r->send_method);
      $rows[$kont][2]=$r->frecuencia;
      $rows[$kont][3]=$r->hora;
      $rows[$kont][4]='';
      if(!empty($r->created)){
        $rows[$kont][4]=date('Y-m-d',$r->created);
      }
      $rows[$kont][5]=$r->tipo;
      $rows[$kont][6]=my_get_username($r->uid);
      $rows[$kont][7]=get_value_alerta_personal_recibir($r->is_recibir);
      $rows[$kont][8]=get_acciones_alerta_user($r);*/
      $rows[$kont]=get_alerta_user_table_row($r);
      $kont++;     
    }
    //gemini-2013
    if(alerta_is_order_name()){
        $rows=alerta_order_by_name($rows);
    }
    
    $rows=my_set_estrategia_pager($rows, $my_limit);


  if (count($rows)>0) {
    /*$feed_url = url('idea_rss.xml', array('absolute' => TRUE));
    drupal_add_feed($feed_url, variable_get('site_name', 'Drupal') . ' ' . t('RSS'));*/
    $output .= theme('table',$headers,$rows,array('id'=>'id_alerta_table'));
    $output .= theme('pager', NULL, $my_limit);
  }
  else {

    $output.= '<div id="first-time">' .t('There are no custom alerts'). '</div>';
  }
  drupal_set_title(t('My Alerts'));  
    
  return $output;
}
function create_menu_alerta_user(){
    //gemini-2014
    return '';
    //
    global $user;
    $html=array();
    $html[]='<div class="tab-wrapper clearfix primary-only" style="margin-top:0;">';
    $html[]='<div class="tabs primary" id="tabs-primary-alerta_user">';
    $html[]='<ul>';
    $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('my_list').'" id="li_gestion_alerta_personalizada">';
    $html[]=l(t('My Alerts'),'alerta_user/'.$user->uid.'/my_list');
    $html[]='</li>';
    if(is_user_invitado()){
        $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('add_alerta_invitado').'" id="li_add_alerta_invitado">';
        $html[]=l(t('Add Guest alert'),'alerta_user/add_alerta_invitado');
        $html[]='</li>';
    }else{
        $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('add_alerta_canal').'" id="li_add_alerta_canal">';
        $html[]=l(t('Add Alert by Channel'),'alerta_user/add_alerta_canal');
        $html[]='</li>';
        $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('add_alerta_categoria').'" id="li_add_alerta_categoria">';
        $html[]=l(t('Add Alert by Category'),'alerta_user/add_alerta_categoria');
        $html[]='</li>';
        $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('add_alerta_usuario').'" id="li_add_alerta_usuario">';
        $html[]=l(t('Add Alert by User'),'alerta_user/add_alerta_usuario');
        $html[]='</li>';
    }
    //
    $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('mis_boletines_grupo').'" id="li_mis_boletines_grupo">';
    //$html[]=l('Groups Bulletins','alerta_user/mis_boletines_grupo',array('query'=>drupal_get_destination()));
    $html[]=l(t('Groups Bulletins'),'alerta_user/mis_boletines_grupo');
    $html[]='</li>';
    //if(boletin_report_is_admin()){
    if(user_access('access boletin report')){
        $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('boletin_report').'" id="li_boletin_report">';
        $html[]=l(t('Customised Bulletins'),'boletin_report/list');
        $html[]='</li>';                
    }
    if(alerta_variables_access()){
        $html[]='<li class="alerta_user_menu_li'.alerta_get_class_active('variables').'" id="li_boletin_report">';
        $html[]=l(t('Alert Settings'),'alerta/variables');
        $html[]='</li>';
    }
    //
    $html[]='</ul>';
    $html[]='</div></div>';
    //
    return implode('',$html);
}
function alerta_canal_form(){
    //gemini-2014
    //intelsat-2015
    $row=get_alerta_user_row(arg(1));    
    $is_busqueda=alerta_solr_is_busqueda_by_row($row);
    if($is_busqueda){
        if(isset($row->id) && !empty($row->id)){
            drupal_set_title(t('Edit alert by search'));
        }
    }else{    
        drupal_set_title(t('Add Alert by Channel'));
    }
    //
    //print $row->tipo.'<BR>';
//echo print_r($row,1);
    if(isset($row->id) && !empty($row->id)){
        $form['my_id']=array(
            '#type'=>'hidden',
            '#default_value' =>$row->id,
        );
    }
    
$form['alerta_user_menu']=array();
$form['alerta_user_menu']['#value']=create_menu_alerta_user();
    //intelsat-2015
    $form['is_busqueda']=array(
            '#type'=>'hidden',
            '#default_value' =>$is_busqueda,
    );
    //
$form['titulo']=array(
    '#type'=>'textfield',
    '#title'=>t('Title'),
    '#default_value'=>$row->titulo,
    '#required'=>TRUE,
);

$form['is_recibir']=create_is_recibir_txek($row);

 // drupal_set_title(t('Añadir alerta canal2'));
  /*$form['canal_nid']=array(
  '#type' => 'select',
  '#title' => t('Seleccionar canal'),
  '#default_value' => $row->canal_nid,
  '#options'=>get_alerta_user_canal_options(),
  '#required' => TRUE
);*/

$form['canales_fs']=array(
  '#type'=>'fieldset',
  '#title'=>t('Select channels'),
  '#collapsible'=>true,
);    
$form['canales_fs']['is_todos_canales']=array(
              '#type'=>'checkbox',
              '#title'=>t('All channels'),
            );
            if(!is_desde_pantalla_canales() && ((isset($row->is_todos_canales) && !empty($row->is_todos_canales)) || !isset($row->is_todos_canales))){
                $form['canales_fs']['is_todos_canales']['#attributes']=array('checked'=>'checked');
            }
//intelsat-2015
if($is_busqueda){
    $form['canales_fs']['#title']=t('Select searches');
    $form['canales_fs']['is_todos_canales']['#title']=t('All searches');
}

//
    
//intelsat-2015
if(!$is_busqueda){
//    
    $form['canales_fs']['is_canales_que_filtro']=array(
              '#type'=>'checkbox',
              '#title'=>t('Channels that I filter'),
    );
            //if(!is_desde_pantalla_canales() && ((isset($row->is_canales_que_filtro) && !empty($row->is_canales_que_filtro)) || !isset($row->is_canales_que_filtro))){
            if(!is_desde_pantalla_canales() && ((isset($row->is_canales_que_filtro) && !empty($row->is_canales_que_filtro)))){                
                $form['canales_fs']['is_canales_que_filtro']['#attributes']=array('checked'=>'checked');
            }            
}

        /*$form['canales_fs']['canales'] = array(
          '#type' => 'select',
          '#title' => t('Channels'),
          '#default_value' => set_default_value_canales($row->canales),
          '#options'=>get_alerta_user_canal_options(),
          '#multiple'=>TRUE,
          '#size'=>20,
          '#required' => FALSE
          );*/
            
          alerta_inc_add_grupos_canales($row,$form,$is_busqueda);  



$form['send_method'] = array(
        '#type' => 'select',
        '#title' => t('Select Sending Method'),
        '#options' => my_get_methods(),
        '#default_value' => $row->send_method,
        '#required' => TRUE,
        //intelsat-2015
        '#prefix'=>'<div style="display:none;">',
        '#suffix'=>'</div>',
        //
      );
$form['frecuencia'] = array(
        '#type' => 'select',
        '#title' => t('Frequency'),
        '#options' => get_frecuencia_options(),
        '#default_value' => $row->frecuencia,
        '#required' => TRUE
      );

$form['hora_array'] = array(
      '#type' => 'alerta_time',
        '#title' => t('Time'),
        '#default_value' => $row->hora,
        '#required' => TRUE
);


//intelsat-2015
//$form=add_form_filtrar_fields($form,$row);
alerta_inc_add_tipo_eventos_form_field($form,$row);
//

$form['my_limite']=array(
    '#type'=>'textfield',
    '#title'=>t('Limit'),
    '#default_value'=>set_alerta_user_my_limite($row->my_limite),
);

 /*$form['limite_resumen']=array(
              '#type'=>'textfield',
              '#title'=>t('Maximum characters of Resume'),
              '#default_value'=>get_alerta_my_limite($row->limite_resumen,alerta_define_max_limite_resumen()),
              '#required' => TRUE
            );*/

$form['limite_resumen']=alerta_limite_resumen_form_field($row);

$form['limite_resumen_comentario']=alerta_limite_resumen_comentario_form_field($row);

$form['alerta_canal_btn_submit']=array(
  '#type' => 'submit',
  '#value' => t('Save'),
  //'#name'=>'alerta_canal_btn_submit',
);

if(isset($row->id)){
    $form['delete_alerta_canal_btn']=array(
      '#value' => '<input type="button" id="my_delete_alerta_btn" name="my_delete_alerta_btn" value="'.t('Delete').'">',
    );
}

//gemini-2013
$my_destination=define_alerta_form_destination();

$form['alerta_canal_volver']=array(
  //'#value' => l(t('Return'),$_REQUEST['destination'],array('attributes'=>array('id'=>'my_volver_alerta_user','class'=>'back_left'))),
  '#value' => l(t('Cancel'),$my_destination),

);

add_js_alerta_delete_btn($row);
alerta_inc_add_canales_checkbox_js();

return $form;
}
function get_alerta_user_row($my_id){
    if(!empty($my_id) && is_numeric($my_id)){
        $alerta_user_list=get_alerta_user_list($my_id);
        if(count($alerta_user_list)>0){
            return $alerta_user_list[0];
        }
    }
    //
    $my_result=array();
    $my_result=(object) $my_result;
    return $my_result;
}
//intelsat-2015
//function get_alerta_user_canal_options($is_anonimo=0,$alerta_user_id='',$is_canales_que_filtro=0,$param_uid_in=''){
function get_alerta_user_canal_options($is_anonimo=0,$alerta_user_id='',$is_canales_que_filtro=0,$param_uid_in='',$tipo=''){
    $result=array();
    //intelsat-2015
    //$canal_list=get_canal_list($is_anonimo,$alerta_user_id,$is_canales_que_filtro,$param_uid_in);
    $canal_list=get_canal_list($is_anonimo,$alerta_user_id,$is_canales_que_filtro,$param_uid_in,$tipo);
    if(count($canal_list)>0){
        foreach($canal_list as $i=>$row){
            $result[$row->nid]=$row->title;
        }
    }
    return $result;
}
//intelsat-2015
//function get_canal_list($is_anonimo=0,$alerta_user_id='',$is_canales_que_filtro=0,$param_uid_in=''){
function get_canal_list($is_anonimo=0,$alerta_user_id='',$is_canales_que_filtro=0,$param_uid_in='',$tipo=''){
    global $user;
    $result=array();
    //
    $param_uid=0;
    if($is_anonimo){
        $group_nid_array=get_group_nid_array_by_anonimo($alerta_user_id,$param_uid);
    }else{
        if(isset($user->og_groups) && !empty($user->og_groups)){
            $group_nid_array=array_keys($user->og_groups);
        }else{
             return $result;
        }
    }
    //
    $where=array();
    $where[]='1';
    //intelsat-2015
    if($tipo=='busqueda'){
        $where[]='n.type IN("canal_busqueda")';
    }else{
        $where[]='n.type IN("canal_de_supercanal","canal_de_yql")';
    }
    if(count($group_nid_array)>0){
        $where[]='ou.nid IN('.implode(',',$group_nid_array).')';
    }
    //gemini-2014
    if($is_canales_que_filtro){
        if(!empty($param_uid_in)){
            $param_uid=$param_uid_in;           
        }
        if(empty($param_uid)){
            $param_uid=alerta_get_param_uid($alerta_user_id);
        }
        $where[]='(node_data_field_responsable_uid.field_responsable_uid_uid = '.$user->uid.' OR node_data_field_responsable_uid2.field_responsable_uid2_uid = '.$user->uid.')';                    
        
    }
    //
    $sql='SELECT n.* 
    FROM {node} n
    LEFT JOIN {og_ancestry} oa ON n.nid=oa.nid
    LEFT JOIN {og_uid} ou ON oa.group_nid=ou.nid
    LEFT JOIN content_field_responsable_uid node_data_field_responsable_uid ON n.nid = node_data_field_responsable_uid.nid
    LEFT JOIN content_field_responsable_uid2 node_data_field_responsable_uid2 ON n.nid = node_data_field_responsable_uid2.nid                    
    WHERE '.implode(' AND ',$where).'
    GROUP BY n.nid 
    ORDER BY n.title ASC';
    //print $sql;exit();
    $res=db_query($sql);
    
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function get_frecuencia_options($is_boletin_grupo=0,$is_manual=0){
    $result=array();
    if($is_manual){
        $result['manual']=t('Manual');
    }
    if(!$is_boletin_grupo){
        $result['diaria']=t('Daily');
    }
    $result['semanal_lunes']=t('Weekly (Monday)');
    $result['semanal_martes']=t('Weekly (Tuesday)');
    $result['semanal_miercoles']=t('Weekly (Wednesday)');
    $result['semanal_jueves']=t('Weekly (Thursday)');
    $result['semanal_viernes']=t('Weekly (Friday)');
    $result['semanal_sabado']=t('Weekly (Saturday)');
    $result['semanal_domingo']=t('Weekly (Sunday)');
    if($is_boletin_grupo){
        $result['diaria']=t('Daily');
    }
    return $result;
}
function alerta_elements() {
  
  $type["alerta_time"] = array(
    "#input"       => true,
    "#process"     => array("alerta_expand_time")
  );

  return $type;
}
function alerta_expand_time($element) {
//echo print_r($element,1);exit();
  $value=$element['#default_value'];
  $my_hour=date('H');
  $my_minute=date('i');
  //
  if(!empty($value)){
      $my_array=explode(':',$value);
      if(count($my_array)>1){
          $my_hour=$my_array[0];
          $my_minute=$my_array[1];
      }
  }
  //
  if (empty($element['#value']) || !is_array($element['#value'])) {
    
    $element['#value'] = array(
      //'hour' => intval(format_date(time(), 'custom', 'H')),
      //'minute' => intval(format_date(time(), 'custom', 'i')),
      //'meridiem' => format_date(time(), 'custom', 'a'),
      'hour' => intval($my_hour),
      'minute' => intval($my_minute),
    );
  }

  $element['#tree'] = TRUE;

  foreach ($element['#value'] as $type => $value) {
    switch ($type) {
      case 'hour':
        //gemini
        //$options = drupal_map_assoc(range(1, 12));
        $options = drupal_map_assoc(range(0, 23));
        //
        break;
      case 'minute':
        $options = drupal_map_assoc(range(0, 59));
        break;
      case 'meridiem':
        $options = drupal_map_assoc(array('am', 'pm'));
        break;
    }

    if ($type == 'hour' || $type == 'minute') {
      foreach ($options as $option) {
        $options[$option] = str_pad($options[$option], 2, '0', STR_PAD_LEFT);
      }
    }
    $parents = $element['#parents'];
    $parents[] = $type;
    $element[$type] = array(
      '#type' => 'select',
      '#default_value' => $element['#value'][$type],
      '#attributes' => $element['#attributes'],
      '#options' => $options,
    );
  }

  return $element;
}
function alerta_canal_form_submit(&$form, &$form_state) {    
    save_alerta_user($form, $form_state,'canal','');
}
function get_alerta_user_nombre($r,$sep_in='<BR>',$with_img=1){
    if(isset($r->titulo) && !empty($r->titulo)){
        return $r->titulo;
    }
    //intelsat-2015
    //if($r->tipo=='canal'){
    if(in_array($r->tipo,array('canal','busqueda'))){
        if($r->is_todos_canales){
            //intelsat-2015
            if($r->tipo=='busqueda'){
                return t('All searches');
            }else{
            //    
                return t('All channels');
            }    
        }
        //gemini-2014
        if($r->is_canales_que_filtro){
            return t('Channels that I filter');
        }
        //
        $canales=get_alerta_user_canal_nid_array($r->id);
        if(count($canales)>0){
            if(count($canales)==1){
                $node=node_load($canales[0]);
                return $node->title;
            }else{
                return set_canales_legible(implode(',',$canales));
            }
        }
        return '';
    }else if($r->tipo=='categoria'){
        return set_categorias_legible($r->categorias_string);
    }else if($r->tipo=='usuario'){
        if($r->is_todos_usuarios){
            return t('All users');
        }
        /*$my_user=user_load($r->alerta_uid);
        if(isset($my_user->uid) && !empty($my_user->uid)){
            return $my_user->name;
        }*/
        $usuarios=get_alerta_user_uid_array($r->id);
        if(count($usuarios)>0){
            if(count($usuarios)==1){
                $my_user=user_load($usuarios[0]);
                if(isset($my_user->uid) && !empty($my_user->uid)){
                    return $my_user->name;
                }
            }else{
                return set_usuarios_legible(implode(',',$usuarios));
            }
        }
    }else if($r->tipo=='invitado'){
        return set_invitados_legible($r->id,$sep_in,$with_img);
    }
    return '';
}
function my_get_username($uid){
    $my_user=user_load($uid);
    if(isset($my_user->uid) && !empty($my_user->uid)){
        return $my_user->name;
    }
    return '';
}
function get_acciones_alerta_user($r){
    $html=array();
    $atzizkia='';
    if(in_array($r->tipo,array('categoria','usuario','invitado'))){
        $atzizkia='_'.$r->tipo;
    }
    $html[]=l(my_get_icono_action('edit', t('Edit')),'alerta_user/'.$r->id.'/my_edit'.$atzizkia,array('html'=>true,'query'=>drupal_get_destination()));
    //intelsat-2015
    //'html'=>true,'query'=>drupal_get_destination())
    $options_view_alerta=red_despacho_boletin_report_get_options_view_alerta();
    $html[]=l(my_get_icono_action('viewmag', t('View')),'alerta_user/'.$r->id.'/my_web',$options_view_alerta);
    $html[]=l(my_get_icono_action('delete', t('Delete')),'alerta_user/'.$r->id.'/my_delete'.$atzizkia,array('html'=>true));
    //intelsat-2015
    if($r->tipo=='busqueda'){
        if(alerta_solr_is_show_resultado_busqueda()){
            $html[]=l(my_get_icono_action('alerta_busqueda','Ver resultado de la busqueda original'),'alerta_user/'.$r->id.'/resultado_busqueda',array('html'=>true,'query'=>drupal_get_destination()));
        }
    }
    //
    return add_div_actions(implode('&nbsp;',$html));
}
function get_alerta_user_list($my_id='',$send_method=''){
    $where=array();
    $where[]='1';
    if(!empty($my_id)){
        $where[]='au.id='.$my_id;
    }
    if(!empty($send_method)){
        $where[]='au.send_method="'.$send_method.'"';
    }
    //
    $result=array();
    $sql='SELECT au.*
    FROM {alerta_user} au
    WHERE '.implode(' AND ',$where).'
    ORDER BY au.created ASC';
    $res = db_query($sql);
    $kont=0;
    while($row=db_fetch_object($res)){
        $result[$kont]=$row;
        $result[$kont]->canales=get_alerta_user_canal_nid_array($row->id);
        $result[$kont]->usuarios=get_alerta_user_uid_array($row->id);
        $kont++;
    }
    return $result;
}
function get_metodo_name($value){
    $options=my_get_methods();
    //echo print_r($options,1);
    if(isset($options[$value]) && !empty($options[$value])){
        return $options[$value];
    }
    return '';
}
function alerta_categoria_form(){
    //gemini-2014
    drupal_set_title(t('Add Alert by Category'));
    //
    $row=get_alerta_user_row(arg(1));
//echo print_r($row,1);
    if(isset($row->id) && !empty($row->id)){
        $form['my_id']=array(
            '#type'=>'hidden',
            '#default_value' =>$row->id,
        );
    }

$form['alerta_user_menu']=array();
$form['alerta_user_menu']['#value']=create_menu_alerta_user();    
    
$form['titulo']=array(
    '#type'=>'textfield',
    '#title'=>t('Title'),
    '#default_value'=>$row->titulo,
    '#required'=>TRUE,
);

//
$form['is_recibir']=create_is_recibir_txek($row);
//
$form=add_grupos_categorias_txek_fieldset($form,$row);
//
$form['send_method'] = array(
        '#type' => 'select',
        '#title' => t('Select Sending Method'),
        '#options' => my_get_methods(),
        '#default_value' => $row->send_method,
        '#required' => TRUE,
         //intelsat-2015
        '#prefix'=>'<div style="display:none;">',
        '#suffix'=>'</div>',
        //
      );
$form['frecuencia'] = array(
        '#type' => 'select',
        '#title' => t('Frequency'),
        '#options' => get_frecuencia_options(),
        '#default_value' => $row->frecuencia,
        '#required' => TRUE
      );

$form['hora_array'] = array(
      '#type' => 'alerta_time',
        '#title' => t('Time'),
        '#default_value' => $row->hora,
        '#required' => TRUE
);

//intelsat-2015
//$form=add_form_filtrar_fields($form,$row);
alerta_inc_add_tipo_eventos_form_field($form,$row);
//
        
$form['my_limite']=array(
    '#type'=>'textfield',
    '#title'=>t('Limit'),
    '#default_value'=>set_alerta_user_my_limite($row->my_limite),
);

$form['limite_resumen']=alerta_limite_resumen_form_field($row);

$form['limite_resumen_comentario']=alerta_limite_resumen_comentario_form_field($row);

$form['alerta_categoria_btn_submit']=array(
  '#type' => 'submit',
  '#value' => t('Save'),
);

if(isset($row->id)){
    $form['delete_alerta_categoria_btn']=array(
      '#value' => '<input type="button" id="my_delete_alerta_btn" name="my_delete_alerta_btn" value="'.t('Delete').'">',
    );
}

//gemini-2013
$my_destination=define_alerta_form_destination();

$form['alerta_canal_volver']=array(
  //'#value' => l(t('Return'),$_REQUEST['destination'],array('attributes'=>array('id'=>'my_volver_alerta_user','class'=>'back_left'))),
  //gemini-2013
  //'#value' => l(t('Cancel'),$_REQUEST['destination']),
  '#value' => l(t('Cancel'),$my_destination),
);


add_js_alerta_delete_btn($row);

return $form;
}
function add_grupos_categorias_txek_fieldset($form_in,$row){
    global $user;
    //
    $form=$form_in;
    $tid_array=explode(',',$row->categorias_string);
    //
    $grupo_list=my_get_og_grupo_list($user->uid,1);
    if(count($grupo_list)>0){
        foreach($grupo_list as $i=>$row){
            $key_fs='categoria_fs_'.$row->nid;
            $form[$key_fs]=array(
                '#type'=>'fieldset',
                '#title'=>$row->title,
                '#collapsible'=>TRUE,
            );
            //
            $id_categoria = db_result(db_query("SELECT og.vid FROM {og_vocab} og WHERE  og.nid=%s", $row->nid));
            //Funcion del modulo taxonomy que dado un el id de una categoria devuelve todos los terminos de la misma
            $categorias=taxonomy_get_tree($id_categoria);
            //echo print_r($categorias,1);
            if(!empty($categorias)){
                  foreach ($categorias as $id => $contenido) {
                      //intelsat-2015
                      //profundidad($contenido->tid);
                      //$pro=variable_get('profundidad_valor', 0);
                      $pro=profundidad($contenido->tid);
                      //
                      $key='my_cat_'.$contenido->tid;
                      //
                      $form[$key_fs][$key] = array(
                        '#required' => TRUE,
                        '#type' => 'checkbox',
                        '#prefix' => '<div class=taxo'. $pro .'>',
                        '#suffix' => '</div>',
                        '#title' => $contenido->name
                      );
                      if(in_array($contenido->tid,$tid_array)){
                         $form[$key_fs][$key]['#attributes']=array('checked' => 'checked');
                       }
                  }
            }
        }
    }
    //
    return $form;
}
function alerta_categoria_form_submit(&$form, &$form_state) {
    global $user;
    //
    $values=$form_state['values'];
    $categorias_string=get_categorias_string_by_values($values);
    //
    save_alerta_user($form, $form_state,'categoria',$categorias_string);
}
function save_alerta_user(&$form, &$form_state,$tipo_in,$categorias_string,$alerta_uid=0){
    global $user;
    $values=$form_state['values'];
    $values['is_antes_filtrar']=0;
    //intelsat-2015
    $tipo=$tipo_in;
    $is_busqueda=0;
    if(isset($values['is_busqueda']) && !empty($values['is_busqueda'])){
        $is_busqueda=1;
    }
    //gemini-2014
    $values['canales']=alerta_inc_get_canales_checkbox_values($values);
    $values['usuarios']=alerta_inc_get_usuarios_checkbox_values($values);
    //
    $hora=str_pad($values['hora_array']['hour'], 2, '0', STR_PAD_LEFT).':'.str_pad($values['hora_array']['minute'], 2, '0', STR_PAD_LEFT);
    $created=time();
    //
    if($tipo=='categoria'){
        $values['canal_nid']=0;
    }
    //
    $is_todos_canales=0;
    if(isset($values['is_todos_canales'])){
        $is_todos_canales=$values['is_todos_canales'];
    }
    //gemini-2014
    $is_canales_que_filtro=0;
    if(isset($values['is_canales_que_filtro'])){
        $is_canales_que_filtro=$values['is_canales_que_filtro'];
    }
    //
    $is_todos_usuarios=0;
    if(isset($values['is_todos_usuarios'])){
        $is_todos_usuarios=$values['is_todos_usuarios'];
    }
    //
    $is_recibir=0;
    if(isset($values['is_recibir'])){
        $is_recibir=$values['is_recibir'];
    }
    //print 'v='.$is_todos_canales;exit();
    $my_limite=set_alerta_user_my_limite($form_state['values']['my_limite']);
    $limite_resumen=0;
    if(isset($values['limite_resumen']) && !empty($values['limite_resumen'])){
        $limite_resumen=$values['limite_resumen'];
    }
    $limite_resumen_comentario=0;
    if(isset($values['limite_resumen_comentario']) && !empty($values['limite_resumen_comentario'])){
        $limite_resumen_comentario=$values['limite_resumen_comentario'];
    }
    //$tipo='canal';
    //intelsat-2015
    if($is_busqueda){
        $tipo='busqueda';
    }
    alerta_inc_set_tipo_eventos_values($is_evento_latest_news,$is_evento_validated_news,$is_evento_rejected_news,$is_evento_edited_news,$values);
    //
    if(isset($values['my_id']) && !empty($values['my_id']) && is_numeric($values['my_id'])){
        $changed=$created;
        $sql=sprintf('UPDATE alerta_user SET titulo="%s",is_todos_canales=%d,send_method="%s",frecuencia="%s",hora="%s",changed=%d,tipo="%s",categorias_string="%s",is_todos_usuarios=%d,my_limite=%d,is_antes_filtrar=%d,is_despues_filtrar=%d,is_recibir=%d,limite_resumen=%d,limite_resumen_comentario=%d,is_canales_que_filtro=%d,is_evento_latest_news=%d,is_evento_validated_news=%d,is_evento_rejected_news=%d,is_evento_edited_news=%d WHERE id=%d',$values['titulo'],$is_todos_canales,$values['send_method'],$values['frecuencia'],$hora,$changed,$tipo,$categorias_string,$is_todos_usuarios,$my_limite,$values['is_antes_filtrar'],$values['is_despues_filtrar'],$values['is_recibir'],$limite_resumen,$limite_resumen_comentario,$is_canales_que_filtro,$is_evento_latest_news,$is_evento_validated_news,$is_evento_rejected_news,$is_evento_edited_news,$values['my_id']);
        db_query($sql);
        $my_id=$values['my_id'];
    }else{
        $sql=sprintf('INSERT INTO alerta_user(titulo,is_todos_canales,send_method,frecuencia,hora,created,tipo,uid,categorias_string,is_todos_usuarios,my_limite,is_antes_filtrar,is_despues_filtrar,is_recibir,limite_resumen,limite_resumen_comentario,is_canales_que_filtro,is_evento_latest_news,is_evento_validated_news,is_evento_rejected_news,is_evento_edited_news) VALUES("%s",%d,"%s","%s","%s",%d,"%s",%d,"%s",%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d)',$values['titulo'],$is_todos_canales,$values['send_method'],$values['frecuencia'],$hora,$created,$tipo,$user->uid,$categorias_string,$is_todos_usuarios,$my_limite,$values['is_antes_filtrar'],$values['is_despues_filtrar'],$values['is_recibir'],$limite_resumen,$limite_resumen_comentario,$is_canales_que_filtro,$is_evento_latest_news,$is_evento_validated_news,$is_evento_rejected_news,$is_evento_edited_news);
        db_query($sql);
        $my_id=db_last_insert_id('alerta_user','id');
    }
    save_alerta_user_canales($my_id,$values['canales']);
    save_alerta_user_usuarios($my_id,$values['usuarios']);
    save_alerta_user_invitados_respuesta($my_id);
    on_alerta_save_goto();
}
function get_categorias_string_by_values($values){
    if(!empty($values)){
        $result=array();
        foreach($values as $f=>$v){
            $tid=str_replace('my_cat_','',$f);
            if(strcmp($f,$tid)==0){
                //
            }else if(is_numeric($tid) && !empty($v)){
                $result[]=$tid;
            }
        }
        //echo print_r($result,1);exit();
        if(count($result)>0){
            return implode(',',$result);
        }
    }
    return '';
}
function delete_alerta_canal_form(){
    /*$form['borrar_msg']=array(
        '#value'=>t('This action cannot be undone.'),
    );
    return $form;*/
    return delete_alerta_form();
}
function delete_alerta_categoria_form(){
    /*$form['borrar_msg']=array(
        '#value'=>t('This action cannot be undone.'),
    );
    return $form;*/
    return delete_alerta_form();
}
function delete_alerta_form(){
    //gemini-2014
    $param2=arg(2);
    $row=get_alerta_user_row(arg(1));
    if(isset($row->titulo) && !empty($row->titulo)){
        drupal_set_title(t('Delete %title',array('%title'=>$row->titulo)));
    }    
    //   
    $form['alerta_user_menu']=array();
    $form['alerta_user_menu']['#value']=create_menu_alerta_user();  
    
        $form['my_id']=array(
            '#type'=>'hidden',
            '#default_value' =>arg(1),
        );
    //
    $form['borrar_msg']=array(
        '#value'=>t('This action cannot be undone.').'<BR>',
    );

    $form['alerta_canal_btn_submit']=array(
  '#type' => 'submit',
  '#value' => t('Delete'),
);
    
//gemini-2013    
$my_destination=define_alerta_form_cancel_destination();    
    

$form['alerta_canal_volver']=array(
  //'#value' => l(t('Return'),$_REQUEST['destination'],array('attributes'=>array('id'=>'my_volver_alerta_user','class'=>'back_left'))),
  //gemini-2013
  //'#value' => l(t('Cancel'),$_REQUEST['destination']),
  '#value' => l(t('Cancel'),$my_destination),  

);

    return $form;
}
function delete_alerta_canal_form_submit(&$form, &$form_state) {
    delete_alerta_form_submit($form, $form_state);
}
function delete_alerta_categoria_form_submit(&$form, &$form_state) {
    delete_alerta_form_submit($form, $form_state);
}
function delete_alerta_form_submit($form, $form_state) {    
    $id=$form_state['values']['my_id'];
    if(!empty($id) && is_numeric($id)){
        delete_alerta_user($id);
    }
    //gemini-2013
    on_alerta_save_goto(1);
    
}
function delete_alerta_user($id){
    $sql='DELETE FROM alerta_user WHERE id='.$id;
    db_query($sql);
    my_delete_alerta_user_canales($id);
    my_delete_alerta_user_usuarios($id);
    call_delete_alerta_user_invitados_respuesta($id);
}
function delete_alerta_usuario_form(){
    return delete_alerta_form();
}
function delete_alerta_usuario_form_submit(&$form, &$form_state) {
    delete_alerta_form_submit($form, $form_state);
}
function alerta_usuario_form(){
    $row=get_alerta_user_row(arg(1));
    //echo print_r($row,1);
    $title=t('Add Alert by User');
    if(isset($row->id) && !empty($row->id)){
        $title=t('Edit alert by user');
        $form['my_id']=array(
            '#type'=>'hidden',
            '#default_value' =>$row->id,
        );
    }    
    drupal_set_title($title);
        
$form['alerta_user_menu']=array();
$form['alerta_user_menu']['#value']=create_menu_alerta_user();    
    
$form['titulo']=array(
    '#type'=>'textfield',
    '#title'=>t('Title'),
    '#default_value'=>$row->titulo,
    '#required'=>TRUE,
);

$form['is_recibir']=create_is_recibir_txek($row);

/*
 // drupal_set_title(t('Añadir alerta canal2'));
  $form['alerta_uid']=array(
  '#type' => 'select',
  '#title' => t('Seleccionar Usuario'),
  '#default_value' => $row->alerta_uid,
  '#options'=>get_alerta_user_usuario_options(),
  '#required' => TRUE
);*/


$form['usuarios_fs']=array(
  '#type'=>'fieldset',
  '#title'=>t('Select Users'),
  '#collapsible'=>true,
);

$form['usuarios_fs']['is_todos_usuarios']=array(
              '#type'=>'checkbox',
              '#title'=>t('All users'),
            );
            if((isset($row->is_todos_usuarios) && !empty($row->is_todos_usuarios)) || !isset($row->is_todos_usuarios)){
                $form['usuarios_fs']['is_todos_usuarios']['#attributes']=array('checked'=>'checked');
            }


        /*$form['usuarios_fs']['usuarios'] = array(
          '#type' => 'select',
          '#title' => t('Users'),
          '#default_value' => $row->usuarios,
          '#options'=>get_alerta_user_usuario_options(),
          '#multiple'=>TRUE,
          '#size'=>20,
          '#required' => FALSE
          );*/
            
           alerta_inc_add_grupos_usuarios($row,$form);


$form['send_method'] = array(
        '#type' => 'select',
        '#title' => t('Select Sending Method'),
        '#options' => my_get_methods(),
        '#default_value' => $row->send_method,
        '#required' => TRUE,
        //intelsat-2015
        '#prefix'=>'<div style="display:none;">',
        '#suffix'=>'</div>',
        //
      );
$form['frecuencia'] = array(
        '#type' => 'select',
        '#title' => t('Frequency'),
        '#options' => get_frecuencia_options(),
        '#default_value' => $row->frecuencia,
        '#required' => TRUE
      );

$form['hora_array'] = array(
      '#type' => 'alerta_time',
        '#title' => t('Time'),
        '#default_value' => $row->hora,
        '#required' => TRUE
);

//intelsat-2015
//$form=add_form_filtrar_fields($form,$row);
alerta_inc_add_tipo_eventos_form_field($form,$row);
//

$form['my_limite']=array(
    '#type'=>'textfield',
    '#title'=>t('Limit'),
    '#default_value'=>set_alerta_user_my_limite($row->my_limite),
);

$form['limite_resumen']=alerta_limite_resumen_form_field($row);

$form['limite_resumen_comentario']=alerta_limite_resumen_comentario_form_field($row);

$form['alerta_usuario_btn_submit']=array(
  '#type' => 'submit',
  '#value' => t('Save'),
);

if(isset($row->id)){
    $form['delete_alerta_usuario_btn']=array(
      '#value' => '<input type="button" id="my_delete_alerta_btn" name="my_delete_alerta_btn" value="'.t('Delete').'">',
    );
}

//gemini-2013
$my_destination=define_alerta_form_destination();

$form['alerta_canal_volver']=array(
  //'#value' => l(t('Return'),$_REQUEST['destination'],array('attributes'=>array('id'=>'my_volver_alerta_user','class'=>'back_left'))),
  //gemini-2013
  //'#value' => l(t('Cancel'),$_REQUEST['destination']),
  '#value' => l(t('Cancel'),$my_destination),  
);

add_js_alerta_delete_btn($row);
alerta_inc_add_usuarios_checkbox_js();

return $form;
}
function alerta_usuario_form_submit(&$form, &$form_state) {
    global $user;
    //
    $values=$form_state['values'];
    $alerta_uid=$values['alerta_uid'];
    //
    save_alerta_user($form, $form_state,'usuario','',$alerta_uid);
}
function get_alerta_user_usuario_options($is_anonimo=0,$alerta_user_id=''){
    $result=array();
    //my_get_og_grupo_list($user_id);
    $user_list=get_user_user_group_list($is_anonimo,$alerta_user_id);
    //echo print_r($user_list,1);
    if(count($user_list)>0){
        foreach($user_list as $i=>$u){
            if(is_invitado_de_mi_subgrupo($u->uid)){
                $result[$u->uid]=$u->name;
            }
        }
    }
    //
    return $result;
}
function get_user_user_group_list($is_anonimo=0,$alerta_user_id=''){
    global $user;
    //
    $result=array();
    //
    if($is_anonimo){
        $group_nid_array=get_group_nid_array_by_anonimo($alerta_user_id,$param_uid);
    }else{
        if(isset($user->og_groups) && !empty($user->og_groups)){
            $group_nid_array=array_keys($user->og_groups);
        }
    }
    //
    if(count($group_nid_array)>0){
        $where=array();
        $where[]='1';
        //gemini-2014
        $where[]='u.status=1';
        $where[]='ou.nid IN('.implode(',',$group_nid_array).')';
        if($is_anonimo){
            $where[]='u.uid!='.$param_uid;
        }else{
            $where[]='u.uid!='.$user->uid;
        }
        //
        $sql='SELECT u.* 
        FROM {users} u
        LEFT JOIN {og_uid} ou ON u.uid=ou.uid
        WHERE '.implode(' AND ',$where).'
        GROUP BY u.uid
        ORDER BY u.name ASC';
        /*if(user_access('root')){
            print $sql;
        }*/
        //
        $res=db_query($sql);
        while($row=db_fetch_object($res)){
            $result[]=$row;
        }
    }
    //gemini-2014
    $result=hontza_unset_usuarios_caducados($result);
    //
    return $result;
}
function set_alerta_user_my_limite($my_limite){
    if(!empty($my_limite) && is_numeric($my_limite)){
        return $my_limite;
    }
    return 10;
}
function add_form_filtrar_fields($form_in,$row){
    $form=$form_in;
    //
    /*$form['is_antes_filtrar']=array(
              '#type'=>'checkbox',
              '#title'=>t('Before filtering'),
            );
            //if((isset($row->is_antes_filtrar) && !empty($row->is_antes_filtrar)) || !isset($row->is_antes_filtrar)){
            if((isset($row->is_antes_filtrar) && !empty($row->is_antes_filtrar))){
                $form['is_antes_filtrar']['#attributes']=array('checked'=>'checked');
            }*/

$form['is_despues_filtrar']=array(
              '#type'=>'checkbox',
              //'#title'=>t('After filtering'),
              '#title'=>t('Only validated items'),
            );
            //if((isset($row->is_despues_filtrar) && !empty($row->is_despues_filtrar)) || !isset($row->is_despues_filtrar)){
            if((isset($row->is_despues_filtrar) && !empty($row->is_despues_filtrar))){
                $form['is_despues_filtrar']['#attributes']=array('checked'=>'checked');
            }
      return $form;
}
function alerta_notif_save(&$node,$my_type='node',$my_action='insert',$cid=0){
    global $user;
    $node_type=$node->type;
    $nid=$node->nid;
    //$cid=0;
    $fecha=time();
    //
    $sql=sprintf('INSERT INTO alerta_notif(my_type,node_type,my_action,nid,cid,uid,fecha) VALUES("%s","%s","%s",%d,%d,%d,%d)',$my_type,$node_type,$my_action,$nid,$cid,$user->uid,$fecha);
    db_query($sql);
}
function alert_notif_flag_save($content_id,$fid,$action){
    $node=node_load($content_id);
    if(strcmp($action,'flag')==0){
        $row=get_flag_row('leido_interesante');
        if($row->fid==$fid){
            alerta_notif_save($node,'node','validado',0);
        }else{
            $row=get_flag_row('leido_no_interesante');
            if($row->fid==$fid){
                alerta_notif_save($node,'node','rechazado',0);
            }
        }
    }else if(strcmp($action,'unflag')==0){
        alerta_notif_save($node,'node','unflag',0);        
    }
}
function my_execute_cron_callback(){
    //intelsat-2015
    drupal_set_title(t('Launch Mail Queue'));
    send_mensaje_despedida_usuario_demo_caducado();
    //gemini_lento: se ha añadido aquí para que se ejecute en el cron
    reset_url_alias_language();
    //
    $dia=date('N');
    $nombre_dia=get_nombre_dia($dia);
    $alerta_user_list=get_alerta_user_list('');
    if(count($alerta_user_list)>0){
        foreach($alerta_user_list as $i=>$row){
            //echo print_r($row,1);exit();
            $my_user=user_load($row->uid);
            if(isset($my_user->uid) && !empty($my_user->uid)){
                $user_mail=$my_user->mail;
                //
                if($row->tipo=='canal'){
                    call_alerta_canal($row,$nombre_dia,$user_mail,1);
                }else if($row->tipo=='categoria'){
                    call_alerta_categoria($row,$nombre_dia,$user_mail,1);
                }else if($row->tipo=='usuario'){
                    call_alerta_autor($row,$nombre_dia,$user_mail,1);
                }else if($row->tipo=='invitado'){
                    call_alerta_invitado($row,$nombre_dia,$user_mail,1);
                //intelsat-2015                    
                }else if($row->tipo=='busqueda'){
                    call_alerta_canal($row,$nombre_dia,$user_mail,1);
                }
            }
        }        
    }
    //
    $boletin_grupo_list=get_boletin_grupo_list('');
    if(count($boletin_grupo_list)>0){
        foreach($boletin_grupo_list as $i=>$bg){
            if(isset($bg->activado) && !empty($bg->activado)){
                call_boletin_grupo($bg,$nombre_dia,1);
            }
        }
    }
    //
    $return_html=array();
    $return_html[]=t('Alerts & Bulletins have been sent');
    $return_html[]=l(t('Return'),'boletin_grupo',array('attributes' => array('class'=>'back_left')));
    return implode('<BR>',$return_html);
}
function get_alerta_canal_list_by_row($param,$nombre_dia,&$my_message){
    $result=array();
    //intelsat-2015
    //if(strcmp($param->tipo,'canal')==0 && is_in_frecuencia($param->frecuencia,$nombre_dia,$param->hora,$param,'alerta_user',$my_message)){
    if(in_array($param->tipo,array('canal','busqueda')) && is_in_frecuencia($param->frecuencia,$nombre_dia,$param->hora,$param,'alerta_user',$my_message)){    
        $canal=node_load($param->canal_nid);
        //intelsat-2015
        if($param->tipo=='busqueda'){
            $canal_nid_list=alerta_solr_get_canal_busqueda_nid_array($canal);
        }else{
        //    
            $canal_nid_list=get_canal_node_nid_list($canal);
        }    
        //print $canal->title.'='.count($canal_nid_list).'<BR>';
        if(count($canal_nid_list)>0){
            //
            $where=array();
            $where[]="1";
            $where[]=get_where_intervalo($param->frecuencia);
            $where[]="an.nid IN (".implode(",",$canal_nid_list).")";
            //intelsat-2015
            if(alerta_inc_is_tipo_evento_activado($param)){
                $where[]=alerta_inc_get_where_tipo_evento($param);
            }else{
                $result=array();
                return $result;
            }
            //
            //$order_by="ORDER BY an.fecha ASC";
            $order_by="ORDER BY votingapi_cache_node_average_value DESC,an.fecha ASC";
            $sql="SELECT an.*,
            votingapi_cache_node_average.value AS votingapi_cache_node_average_value    
            FROM {alerta_notif} an
            LEFT JOIN {node} node ON an.nid=node.nid 
            LEFT JOIN {votingapi_cache} votingapi_cache_node_average ON node.nid = votingapi_cache_node_average.content_id AND (votingapi_cache_node_average.content_type = 'node' AND votingapi_cache_node_average.function = 'average')
            WHERE ".implode(" AND ",$where)."
            ".$order_by;
            //print 'canal_sql='.$sql.'<BR>';exit();
            //
            $res=db_query($sql);
            while($row=db_fetch_object($res)){
                $result[]=$row;
            }
            $result=repasar_filtrado($result,$param);
        }
        //print $canal->title.'='.$param->frecuencia.'='.count($result).'<BR>';
    }
    
    return $result;
}
function is_in_frecuencia($frecuencia,$nombre_dia,$hora,$param,$alert_type,&$my_message){
    $my_message='';

    //AVISO::::por la web para que enseñe siempre
    if(is_my_web()){
        return 1;
    }

    $not_hora=0;

    if(strcmp($frecuencia,'diaria')==0){
        //return 1;
        if(is_in_hora($hora,$param,$alert_type)){
            return 1;
        }else{
            $not_hora=1;
        }
    }
    //
    if(strcmp($frecuencia,'semanal_'.$nombre_dia)==0){
        //return 1;
        if(is_in_hora($hora,$param,$alert_type)){
            return 1;
        }else{
            $not_hora=1;
        }
    }

    if($not_hora){
        $my_message=t('Is not in the time');
    }else{
        $my_message=t('Is not in the frequency');
    }
    
    return 0;
}
function get_nombre_dia($dia){
    $my_array=array('lunes','martes','miercoles','jueves','viernes','sabado','domingo');
    $i=$dia-1;
    if($i>=0){
        return $my_array[$i];
    }
    return '';
}
function get_where_intervalo($frecuencia,$is_comment=0){
    $where='';
    $factor=7;
    if(strcmp($frecuencia,'diaria')==0){
        $factor=1;
    }
    $now=time();
    $ini=$now - ($factor * 24 * 60 * 60);    
    $field='an.fecha';
    if($is_comment){
         $field='c.timestamp';
    }
    $where="(".$field.">=".$ini." AND ".$field."<=".$now.")";
    //
    return $where;
}
function get_canal_node_nid_list($canal){
    $feed_nid_list=get_feed_nid_list($canal->nid);
    //echo print_r($feed_list,1);
    $nid_list=get_canal_nid_list($canal->nid);
    /*echo print_r($nid_list,1);
    print '###############################################<BR>';*/
    if(comparar_array($my_array,$konp_array)){       
       $result=$nid_list;
    }else{       
       $result=my_merge_array($feed_nid_list,$nid_list);
    }
    return $result;
}
function get_feed_nid_list($nid){
    $result=array();
    $sql=sprintf("SELECT f.* FROM {feeds_node_item} f WHERE feed_nid = %d ORDER BY f.nid ASC", $nid);
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row->nid;
    }
    return $result;
}
function get_canal_nid_list($nid,$order_created=0){
    $result=array();
    if($order_created){
        $sql=sprintf("SELECT n.* FROM {node} n LEFT JOIN {content_type_item} c ON n.vid=c.vid WHERE field_item_canal_reference_nid = %d ORDER BY n.created DESC LIMIT 0,1", $nid);
    }else{
        $sql=sprintf("SELECT c.* FROM {content_type_item} c WHERE field_item_canal_reference_nid = %d ORDER BY c.nid ASC", $nid);
    }
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row->nid;
    }
    return $result;
}
function comparar_array($my_array,$konp_array){
    $num=count($my_array);
    $len=count($konp_array);
    if($num==$len){
       if($num>0){
            foreach($my_array as $i=>$v){
                if($v!=$konp_array[$i]){
                    return 0;
                }
            }
       }
       return 1;
    }
    return 0;
}
function my_merge_array($my_array,$my_array2){
    $result=$my_array;
    if(count($my_array2)>0){
        foreach($my_array2 as $i=>$v){
            if(!in_array($v,$my_array2)){
                $result[]=$v;
            }
        }
    }
    return $result;
}
function get_alerta_usuario_list_by_row($param,$nombre_dia,&$my_message){
    $result=array();
   
    if(strcmp($param->tipo,'usuario')==0 && is_in_frecuencia($param->frecuencia,$nombre_dia,$param->hora,$param,'alerta_user',$my_message)){
        
            //
            $where=array();
            $where[]="1";
            $where[]=get_where_intervalo($param->frecuencia);
            $where[]="an.uid=".$param->alerta_uid;
            //intelsat-2015
            if(alerta_inc_is_tipo_evento_activado($param)){
                $where[]=alerta_inc_get_where_tipo_evento($param);
            }else{
                $result=array();
                return $result;
            }
            //  
            //$order_by="ORDER BY an.fecha ASC";
            $order_by="ORDER BY votingapi_cache_node_average_value DESC,an.fecha ASC";
            //
            $sql="SELECT an.*,
            votingapi_cache_node_average.value AS votingapi_cache_node_average_value
            FROM {alerta_notif} an
            LEFT JOIN {node} node ON an.nid=node.nid 
            LEFT JOIN {votingapi_cache} votingapi_cache_node_average ON node.nid = votingapi_cache_node_average.content_id AND (votingapi_cache_node_average.content_type = 'node' AND votingapi_cache_node_average.function = 'average')		
            WHERE ".implode(" AND ",$where)."
            ".$order_by;
            //print $sql;
            //
            $res=db_query($sql);
            while($row=db_fetch_object($res)){
                $result[]=$row;
            }
            
            $result=repasar_filtrado($result,$param);
    }

    return $result;
}
function get_alerta_categoria_list_by_row($param,$nombre_dia,$categoria_canal_nid_list,&$my_message){
    $result=array();
   
    if(strcmp($param->tipo,'categoria')==0 && is_in_frecuencia($param->frecuencia,$nombre_dia,$param->hora,$param,'alerta_user',$my_message)){
            //$categoria_canal_nid_list=get_categoria_canal_nid_list($param->categorias_string);
            if(count($categoria_canal_nid_list)>0){
                $nid_list=get_nid_list_by_canal_list($categoria_canal_nid_list);
                if(count($nid_list)>0){
                    //echo print_r($categoria_canal_nid_list,1);exit();
                    $where=array();
                    $where[]="1";
                    $where[]=get_where_intervalo($param->frecuencia);
                    $where[]="an.nid IN (".implode(",",$nid_list).")";
                    //intelsat-2015
                    if(alerta_inc_is_tipo_evento_activado($param)){
                        $where[]=alerta_inc_get_where_tipo_evento($param);
                    }else{
                        $result=array();
                        return $result;
                    }
                    //              
                    //$order_by="ORDER BY an.fecha ASC";
                    $order_by="ORDER BY votingapi_cache_node_average_value DESC,an.fecha ASC"; 
                    //
                    $sql="SELECT an.*,
                    votingapi_cache_node_average.value AS votingapi_cache_node_average_value    
                    FROM {alerta_notif} an
                    LEFT JOIN {node} node ON an.nid=node.nid 
                    LEFT JOIN {votingapi_cache} votingapi_cache_node_average ON node.nid = votingapi_cache_node_average.content_id AND (votingapi_cache_node_average.content_type = 'node' AND votingapi_cache_node_average.function = 'average')            
                    WHERE ".implode(" AND ",$where)."
                    ".$order_by;
                    //print $sql.'<BR>';
                    //
                    $res=db_query($sql);
                    while($row=db_fetch_object($res)){
                        $result[]=$row;
                    }
                }
                
                $result=repasar_filtrado($result,$param);
            }
    }

    return $result;
}
function get_categoria_canal_nid_list($categorias_string){
    $result=array();
    if(!empty($categorias_string)){
       $where=array();
       $where[]="1";
       $where[]="tn.tid IN (".$categorias_string.")";
       //
       $sql="SELECT tn.*
       FROM {term_node} tn
       WHERE ".implode(" AND ",$where)."
       ORDER BY tn.nid ASC";
       //
       $res=db_query($sql);
       while($row=db_fetch_object($res)){
        $result[]=$row->nid;
        //$node=node_load($row->nid);
        //print $node->type.'<BR>';
       }
    }
    return $result;
}
function get_nid_list_by_canal_list($canal_list){
    $result=array();
    if(count($canal_list)>0){
        foreach($canal_list as $i=>$canal_nid){
            //print 'canal_nid='.$canal_nid.'<BR>';
            $canal=node_load($canal_nid);
            if(isset($canal->nid) && !empty($canal->nid)){
                $nid_list=get_canal_node_nid_list($canal);
            
                $result=array_merge($result,$nid_list);
            }
        }
    }
    //print_r($result);exit();
    return $result;
}
function get_grupo_rows($bg,$current_type='validado'){
    $result=array();
    //echo print_r($bg,1);
    //
    $where=array();
    $where[]="1";
    if(strcmp($current_type,'idea_opor_proy')==0){
        $or=array();
        $or[]="(n.type='idea' AND an.node_type='idea' AND i.grupo_nid=".$bg->grupo_nid.")";
        $or[]="(n.type='oportunidad' AND an.node_type='oportunidad' AND o.grupo_nid=".$bg->grupo_nid.")";
        $or[]="(n.type='proyecto' AND an.node_type='proyecto' AND p.grupo_nid=".$bg->grupo_nid.")";
        $where[]="(".implode(" OR ",$or).")";
    }else{
        $where[]="og_ancestry.group_nid=".$bg->grupo_nid;
    }
    //
    $order_by="ORDER BY an.fecha ASC";
    if(strcmp($current_type,'validado')==0){
        $where[]="an.my_action='validado'";
        $where[]="n.type='item'";
        $order_by="ORDER BY votingapi_cache_node_average_value DESC,an.fecha ASC";
    }else if(strcmp($current_type,'noticia')==0){
        $where[]="n.type='noticia'";
        $where[]="an.my_action IN ('insert','update')";
        $order_by="ORDER BY votingapi_cache_node_average_value DESC,an.fecha ASC";
    }else if(strcmp($current_type,'comment')==0){
        $where[]="an.my_type='comment'";
    }else if(strcmp($current_type,'foros_wikis')==0){
        $where[]="n.type IN('debate','wiki')";
        $where[]="an.my_action IN ('insert','update')";
    }
    $where[]=get_where_alerta_fecha($bg);
    //
    $sql="SELECT an.*,
    votingapi_cache_node_average.value AS votingapi_cache_node_average_value     
    FROM {alerta_notif} an
    LEFT JOIN {node} n ON an.nid=n.nid
    LEFT JOIN {votingapi_cache} votingapi_cache_node_average ON n.nid = votingapi_cache_node_average.content_id AND (votingapi_cache_node_average.content_type = 'node' AND votingapi_cache_node_average.function = 'average')		
    LEFT JOIN {idea} i ON n.nid=i.nid
    LEFT JOIN {oportunidad} o ON n.nid=o.nid
    LEFT JOIN {proyecto} p ON n.nid=p.nid
    LEFT JOIN {og_ancestry} og_ancestry ON an.nid=og_ancestry.nid
    WHERE ".implode(" AND ",$where)."
    GROUP BY an.id 
    ".$order_by;
    //print $sql.'<BR>';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    //echo print_r($result,1);

    if($current_type=='validado'){
        $result=repasar_ahora_son_validados($result);
    }
    return $result;
}
function get_boletin_usuarios_rows($bg,$is_boletin_report=0){
    $result=array();
    $uid_array=array();
    if($bg->is_todos_usuarios){
        $user_list=my_get_og_grupo_user_list($bg->grupo_nid);
        $uid_array=get_array_by_field($user_list,'uid');        
    }else{
        if($is_boletin_report){
            $user_list=boletin_report_get_usuarios_list($bg->id);            
        }else{
            $user_list=get_boletin_usuarios_list($bg->id);            
        }
        $uid_array=get_array_by_field($user_list,'uid');        
    }
    //
    if(count($uid_array)>0){
        foreach($uid_array as $i=>$uid){
            $result[]=user_load($uid);
        }
    }
    return $result;
}
function get_array_by_field($my_list,$f){
    $result=array();
    if(count($my_list)>0){
        foreach($my_list as $i=>$row){
            $result[]=$row->$f;
        }
    }
    return $result;
}
function my_send_mail($mail_to_in,$subject,$body_in,$send_method,$is_recibir,$historico_nid='',$is_mail_externo=0,$br_in='') {
    if($is_recibir){
        $body=$body_in;
        if(strcmp($send_method,'mimemail')==0){
            //intelsat-2015
            if(!red_despacho_is_activado()){
                //gemini-2014            
                if(!empty($historico_nid)){
                   $url_historico=boletin_report_get_url_historico($historico_nid);                              
                   if(!empty($url_historico)){
                        $link_historico=l(t('If this email is not displayed correctly, please click here'),$url_historico,array('absolute'=>TRUE));
                        $body='<p style="text-align:center;font-size:10px;">'.$link_historico.'</p>'.$body;
                   } 
                }
            }
            if(hontza_canal_rss_is_visualizador_activado()){
               if($is_mail_externo){ 
                $body=publico_alerta_get_unsubscribe_link_mail($body,$br_in,$mail_to_in);
               }
            }
            //
            //$body=my_add_css().'<html><body><div id="wrapper"><div id="container" class="layout-region"><div id="main"><div class="main-inner"><div id="content" class="clearfix" style="clear:both;">'.$body.'</div></div></div></div></div></html></body>';
            if(!red_despacho_is_activado()){
                $body=alerta_add_css($body);
            }                
        }
        $mail_to=trim($mail_to_in);
        my_call_send_mail($mail_to, $subject, $body,$send_method,$alert_type);                
    }
}
function my_call_send_mail($mail_to,$subject,$body,$send_method,$alert_type,$is_mensaje_despedida=0) {  
    if(!is_mail_caducado($mail_to,$is_mensaje_despedida)){
          $content_type='text;charset=utf-8';
          if($send_method=='mimemail'){
              $content_type='text/html;charset=utf-8';
          }

          $my_from=variable_get('my_from_default_mail','hontza@hontza.es');
          if(empty($my_from)){
            $my_from='n@webdesignpatterns.org';
          }
          //
          $body=drupal_wrap_mail($body);
          //
          $message = array(
          'to' => $mail_to,
          'subject' => $subject,
          'body' => $body,
          'headers' => array(
                  'From' => $my_from,
                  'MIME-Version' => '1.0',
                  'Content-Type' => $content_type,),
        );
        //intelsat-2015
        //red_despacho_boletin_report_add_logo_attachment($message);        
        /*    
        if(red_despacho_is_activado()){
            $attachments=array();
            $my_headers=array();
            $my_headers=$message['headers'];
            $plaintext=FALSE;
            $my_text = NULL;
            //$my_text =$body;
            $mailkey = '';
            $send = TRUE;
            mimemail($my_from,$mail_to, $subject, $body,$plaintext,$my_headers,$my_text,$attachments,$mailkey,$send);*/
        //}else{
        //intelsat-2016
        //drupal_mail_send($message,1);  
        $is_html=1;
        /*    if(red_copiar_email_html_is_activado()){
                if(empty($alert_type)){
                    $is_html=0;
                }
            }*/
        drupal_mail_send($message,$is_html);
        //}    
    }
/*

$mimeheaders = array();
    foreach ($message['headers'] as $name => $value) {
      $mimeheaders[] = $name .': '. mime_header_encode($value);
    }
    mail(
      $message['to'],
      $message['subject'],
      // Note: e-mail uses CRLF for line-endings, but PHP's API requires LF.
      // They will appear correctly in the actual e-mail that is sent.
      $message['body'],
      // For headers, PHP's API suggests that we use CRLF normally,
      // but some MTAs incorrecly replace LF with CRLF. See #234403.
      join("\n", $mimeheaders)
    );*/
//print $send_method.'<BR>';
}
//intelsat-2015
//function create_boletin_mail_html($my_list_in,$current_type,&$hay_novedades_out,$my_limite_in='',$titulo_mail='',$param_alerta='',$tid_in='',$grupo_nid='',$limite_resumen_in=0,$bg='',$term_name=''){
function create_boletin_mail_html($my_list_in,$current_type,&$hay_novedades_out,$my_limite_in='',$titulo_mail='',$param_alerta='',$tid_in='',$grupo_nid='',$limite_resumen_in=0,$bg='',$term_name='',$tipos_fuente_row=''){
    //gemini-2013
    $hay_novedades_out=0;
    $html=array();
    $user_alerta=alerta_get_user_alerta($param_alerta);
    $my_list=anular_rows($my_list_in,$user_alerta);
    $num_orig=count($my_list);
    $my_limite=get_alerta_my_limite($my_limite_in);
    //print 'aurretik='.count($my_list).'<BR>';
    $my_list=array_slice($my_list,0,$my_limite);
    //print 'my_limite(boletin)='.$my_limite.'<BR>';
    //print 'num='.count($my_list).'<BR>';
    $limite_resumen=$limite_resumen_in;
    if(empty($bg)){
        if(isset($param_alerta->limite_resumen) && !empty($param_alerta->limite_resumen)){
            $limite_resumen=$param_alerta->limite_resumen;            
        }
    }
    //
    $limite_resumen_comentario=0;
    if(empty($bg)){
        if(isset($param_alerta->limite_resumen_comentario) && !empty($param_alerta->limite_resumen_comentario)){
            $limite_resumen_comentario=$param_alerta->limite_resumen_comentario;            
        }
    }
    //
    if(count($my_list)>0){
        //echo print_r($my_list[0],1);exit();
        $html[]='<table class="mail_table" style="width:100%;border:0px;">';
        $th_class=red_despacho_boletin_report_get_th_categoria_title_class($tipos_fuente_row);        
        $html[]='<tr><th colspan="2"'.$th_class.'>'.get_current_type_title($current_type,$titulo_mail,$param_alerta,$term_name,$tipos_fuente_row).'</th></tr>';
        

        /*if(in_array($current_type,array('user_canal','user_autor','user_categoria'))){
            //print $current_type.'<BR>';
            $atzizkia='';
            if(in_array($param_alerta->tipo,array('categoria','usuario'))){
                $atzizkia='_'.$param_alerta->tipo;
            }
            $apuntarse_link='http://'.$_SERVER['HTTP_HOST'].base_path().'alerta_user/'.$param_alerta->id.'/my_edit'.$atzizkia;
            $html[]='<tr><td colspan="2">'.'<a href="'.$apuntarse_link.'">'.t('Subscribe/Unsubscribe to the custom alert').'</a></td></tr>';
        }*/
        $not_empty_kont=0;
        foreach($my_list as $i=>$row){
            $node=node_load($row->nid);
            
            
            $is_mail=1;
            
            $img_style=' style="width:100px;"';
            if(isset($row->my_type) && !empty($row->my_type) && $row->my_type=='comment'){
                $my_user=user_load($node->uid);
                $img=my_get_user_img_src('',$my_user->picture,$my_user->name,$node->uid,$is_mail,$bg);                      
            }else{
                $my_user=user_load($row->uid);
                $img=my_get_user_img_src('',$my_user->picture,$my_user->name,$row->uid,$is_mail,$bg);            
            }
            if(empty($img)){
                $img_style='';
            }
            //intelsat-2014
            //AVISO::::se ha comentado el if
            //if(empty($row->uid)){
                $my_user_info=my_get_user_info($node,1,$bg);
                $img=$my_user_info['img'];
            //}
            //
            $boletin_eskubi_aldea=boletin_eskubi_aldea($row,$node,$current_type,$limite_resumen,$bg,$limite_resumen_comentario,$param_alerta);
            //
            //if(!empty($boletin_eskubi_aldea)){
                $not_empty_kont++;
                //gemini-2013
                $hay_novedades_out=1;
                $html[]='<tr style="vertical-align:top;">';
                //intelsat-2015
                //if(!red_despacho_is_activado()){
                if(!empty($img)){
                    $html[]='<td'.$img_style.'>'.$img.'</td>';
                }    
                $html[]='<td>'.$boletin_eskubi_aldea.'</td>';
                $html[]='</tr>';
            //}
        }
        if($not_empty_kont>0){
            if(is_add_ver_mas_resultados_tr($num_orig,$my_limite)){
                $mas_resultados=add_ver_mas_resultados_tr($param_alerta,$tid_in,$current_type,$grupo_nid);
                if(!empty($mas_resultados)){
                    $html[]=$mas_resultados;
                }
            }
        }else{
            $html[]='<tr style="vertical-align:top;">';
            $html[]='<td>'.t('There are no news').'</td>';
            $html[]='</tr>';
        }
        $html[]='</table>';
    }
    return implode('',$html);
}
//intelsat-2015
//function get_current_type_title($current_type,$titulo_mail,$param_alerta='',$term_name='',$tipos_fuente_row){
function get_current_type_title($current_type,$titulo_mail,$param_alerta='',$term_name='',$tipos_fuente_row=''){    
    //$boletin_txek=array();
    $title='';
    if(strcmp($current_type,'validado')==0){
        //$boletin_txek=get_boletin_txek_field('is_todos_validados');
        //echo print_r($boletin_txek,1);
        $title=t('News');
    }else if(strcmp($current_type,'noticia')==0){
        $title=t('User news');
    }else if(strcmp($current_type,'comment')==0){
        $title=t('Comments');
    }else if(strcmp($current_type,'foros_wikis')==0){
        $boletin_txek=get_boletin_txek_field('is_todos_foros_wikis');
        $title=$boletin_txek['label'];
    }else if(strcmp($current_type,'idea_opor_proy')==0){
        $boletin_txek=get_boletin_txek_field('is_todos_idea_opor_proy');
        $title=$boletin_txek['label'];
    }else if(strcmp($current_type,'item_report')==0){
        $title=t('News');
    }else if(strcmp($current_type,'noticia_report')==0){
        $title=t('User News');
    }else if(strcmp($current_type,'node_report')==0){
        $title=t('Reports');
    }else if(strcmp($current_type,'categorias_report')==0){
        $title=$term_name;
    }
    //if(!empty($boletin_txek)){
    if(!empty($title)){
        //return strtoupper($boletin_txek['label']);
        if(red_despacho_is_activado()){
            $title=red_despacho_boletin_report_get_tipos_fuente_boletin_title($title,$tipos_fuente_row);
        }else{
            $title=my_upper($title);
        }    
        return $title;
    }else{
        if($current_type=='user_categoria'){
            return user_categoria_title_dentro_mail($titulo_mail);            
        }else{
            $img='';
            if($current_type=='invitado'){
                $invitado_node=node_load($param_alerta->alerta_invitado_nid);
                if(isset($invitado_node->nid) && !empty($invitado_node->nid)){
                    $img=get_image_node_type($invitado_node->type);
                }
            }            
            return $img.my_upper($titulo_mail);
        }
    }
    return '';
}
function boletin_eskubi_aldea($row,$node,$current_type,$max_resumen_in=0,$bg='',$limite_resumen_comentario=0,$param_alerta=''){
    $node=node_prepare($node);
    $max_resumen=boletin_grupo_define_max_limite_resumen();
    if(!empty($max_resumen_in)){
        $max_resumen=$max_resumen_in;
    }
    $apply_limite_resumen=0;
    if(empty($bg)){
        $apply_limite_resumen=1;
    }else{
        if(isset($bg->apply_limite_resumen) && !empty($bg->apply_limite_resumen)){
            $apply_limite_resumen=$bg->apply_limite_resumen;
        }
    }
    /*
    //intelsat-2015
    if(boletin_report_pdf_node_is_with_pdf($node)){
        $body=boletin_report_pdf_get_pdf_node_view_link($node);
    }else{
    //
     */    
        if($apply_limite_resumen){        
            //intelsat-2015
            //$strip_tags=strip_tags($node->body);
            $strip_tags=alerta_inc_strip_tags($node->body);
            //
            $len=strlen($strip_tags);
            if(boletin_report_is_apply_limite_resumen($node,$current_type) && ($len>$max_resumen)){                        
                $body=drupal_substr($strip_tags, 0, $max_resumen);        
                $body.=' ...';
            }else{
                $body=$node->body;
            }
        }else{
            $body=$node->body;
            $body=boletin_report_set_img_src_absolutos($body);
        }
    //}    
    $eskubi_aldea=get_node_eskubi_aldea_link($node,$row->nid,$bg);
    //if(!empty($eskubi_aldea)){
        $html=array();
        $html[]='<table class="mail_table_eskubi_aldea" style="border:0px;">';
        if(!red_despacho_is_activado()){
            $html[]='<tr><td>'.date('d-m-Y H:i',$row->fecha).'</td></tr>';
        }
        $html[]='<tr><td><b>'.$eskubi_aldea.'</b></td></tr>';
        $etiquetas=alerta_inc_etiquetas($node);
        if(!red_despacho_is_activado()){    
            if(!empty($etiquetas)){
                $html[]='<tr><td>'.$etiquetas.'</td></tr>';
            }
        }    
        //intelsat-2015
        //if(!red_despacho_is_activado()){
        if(red_despacho_boletin_report_is_show_resumen($bg,$param_alerta)){
            $html[]='<tr><td>'.$body.'</td></tr>';
        }
        //intelsat-2015
        if(!red_despacho_is_activado()){        
            if(in_array($current_type,array('noticia','comment','foros_wikis','idea_opor_proy','user_canal','user_categoria','user_autor','invitado'))){
                $html[]='<tr><td><i>'.t($row->my_action).'</i></td></tr>';
                //$html[]='<tr><td>'.get_notif_actions_date_html($row->action_date_list).'</td></tr>';
                //$html[]='<tr><td>'.get_notif_actions_html($row->action_list).'</td></tr>';
            }
        }
        //intelsat-2015
        //echo print_r($bg,1);
        //if(!red_despacho_is_activado()){    
        if(red_despacho_boletin_report_is_show_comments($bg,$param_alerta)){    
            $html[]=alerta_node_comments_html($node,$bg,$limite_resumen_comentario,$param_alerta);
        }
        if(!red_despacho_is_activado()){        
            $html[]=boletin_report_get_enlaces_html($node);
        }
        $html[]='</table>';
        return implode('',$html);
    //}
    return '';
}
function get_alerta_my_limite($my_limite,$my_default=10){
    if(is_numeric($my_limite) && !empty($my_limite) && $my_limite>0){
        return $my_limite;
    }
    return $my_default;
}
function get_alerta_categorias_seleccionadas_html($categorias_string){
    $html=array();
    //$html[]=$categorias_string;
    $term_list=get_alerta_categorias_term_list($categorias_string);
    if(count($term_list)>0){
        $html[]='<table style="width:100%;">';
        $html[]='<tr><th>'.t('Selected Categories').'</th></tr>';
        foreach($term_list as $i=>$term_data){
            $html[]='<tr><td>'.$term_data->name.'</td></tr>';
        }
        $html[]='</table>';
    }
    return implode('',$html);   
}
function get_alerta_categorias_term_list($categorias_string){
    $result=array();
    if(!empty($categorias_string)){
        
        //
        $where=array();
        $where[]="1";
        $where[]="td.tid IN(".$categorias_string.")";
        $sql="SELECT td.* FROM {term_data} td WHERE ".implode(" AND ",$where)." ORDER BY td.name ASC";
        $res=db_query($sql);
        while($row=db_fetch_object($res)){
            $result[]=$row;
        }

    }
    return $result;
}
function get_node_eskubi_aldea_link($node,$my_nid='',$bg=''){
    //intelsat-2015
    global $base_url;
    $node_title=estrategia_set_title_max_len(htmlkarakter($node->title));
    if(isset($node->nid) && !empty($node->nid)){
        $html=l($node_title,'node/'.$node->nid);
        //
        $group_nid='';
        if(isset($node->og_groups) && !empty($node->og_groups)){
            $values=array_keys($node->og_groups);
            $group_nid=$values[0];
        }else{
            if(isset($node->grupo_nid)){
                $group_nid=$node->grupo_nid;
            }
        }
        //intelsat-2015
        $html_pdf='';
        if(boletin_report_pdf_node_is_with_pdf($node)){
            $html_pdf=boletin_report_pdf_get_pdf_node_view_link($node);
        }    
        if(!empty($html_pdf)){
            $html=$html_pdf;
        }else{
        //    
            if(!empty($group_nid)){    
                $group=node_load($group_nid);
                //intelsat-2015
                //$url='http://'.$_SERVER['HTTP_HOST'].base_path().$group->purl.'/node/'.$node->nid;
                $url=$base_url.'/'.$group->purl.'/node/'.$node->nid;
                $html='<a href="'.$url.'">'.$node_title.'</a>';            
            }else{
                //intelsat-2015
                //$url='http://'.$_SERVER['HTTP_HOST'].base_path().'node/'.$node->nid;
                $url=$base_url.'/node/'.$node->nid;
                $html='<a href="'.$url.'">'.$node_title.'</a>';
            }
        }    
    }else{
        return t('News deleted with this identifier').': '.$my_nid;
        //return '';
    }
    if(!empty($bg) && isset($bg->is_boletin_report) && !empty($bg->is_boletin_report)){
        if(!empty($bg->tipo_link) && $bg->tipo_link==2){
            if(isset($node->field_enlace_noticia) && isset($node->field_enlace_noticia[0]) && isset($node->field_enlace_noticia[0]['url'])){
                $url=$node->field_enlace_noticia[0]['url'];
                $html='<a href="'.$url.'">'.$node_title.'</a>';
            }else{
                if(isset($node->feeds_node_item->url) && !empty($node->feeds_node_item->url)){
                    $url=$node->feeds_node_item->url;
                    $html='<a href="'.$url.'">'.$node_title.'</a>';
                }else{
                    if(isset($node->feeds_node_item->guid) && !empty($node->feeds_node_item->guid)){
                        $url=$node->feeds_node_item->guid;
                        $html='<a href="'.$url.'">'.$node_title.'</a>';
                    }
                }            	            	
            }
        }
    }
    if(in_array($node->type,array('idea','oportunidad','proyecto'))){
        $img=get_image_node_type($node->type);
        $html=$img.$html;
    }
    return $html;
}
function repasar_filtrado($my_list,$param){
    if(isset($param->is_antes_filtrar) && isset($param->is_despues_filtrar)){        
        if($param->is_antes_filtrar==$param->is_despues_filtrar){
            return $my_list;
        }
        //
        
        $result=array();
        if(count($my_list)>0){
            foreach($my_list as $i=>$row){               
                if(is_node_alerta_filtrada($row->nid,$param)){
                    $result[]=$row;
                }
            }
        }

        return $result;
    }
    return $my_list;
}
function get_is_node_filtrado($nid){
    $flag=my_get_flag_content($nid);
    if(isset($flag->content_id) && !empty($flag->content_id)){
        return 1;
    }
    return 0;
}
function is_node_alerta_filtrada($nid,$param){
    $result=0;
    //
    $is_node_filtrado=get_is_node_filtrado($nid);
    if($param->is_antes_filtrar){
        if(!$is_node_filtrado){
            $result=1;
        }
    }else{
        //print 'nid='.$nid.'='.$is_node_filtrado.'<BR>';
        if($is_node_filtrado){
            $result=1;
        }
    }
    //
    return $result;
}
function my_get_methods(){
    $options=_notifications_send_methods();
    unset($options['mail']);
    //intelsat-2015
    unset($options['simple']);
    //
    /*$options['mimemail']=t('HTML Email');
    $options['simple']=t('Website');*/
    return $options;
}
function my_web_callback(){
    $dia=date('N');
    $nombre_dia=get_nombre_dia($dia);
    $my_id=arg(1);
    $row_list=get_alerta_user_list($my_id,'');
    $row=$row_list[0];
    $my_user=user_load($row->uid);
    //
    $content='';
    if(isset($my_user->uid) && !empty($my_user->uid)){    
        $por_correo=0;
        if($row->tipo=='canal'){            
            $content=call_alerta_canal($row,$nombre_dia,$my_user->mail,$por_correo);
        }else if($row->tipo=='categoria'){
            $content=call_alerta_categoria($row,$nombre_dia,$my_user->mail,$por_correo);
        }else if($row->tipo=='usuario'){
            $content=call_alerta_autor($row,$nombre_dia,$my_user->mail,$por_correo);
        }else if($row->tipo=='invitado'){
            $content=call_alerta_invitado($row,$nombre_dia,$my_user->mail,$por_correo);
        //intelsat-2015    
        }else if($row->tipo=='busqueda'){            
            $content=call_alerta_canal($row,$nombre_dia,$my_user->mail,$por_correo);
        }
        //
    }
    if(red_despacho_is_activado()){
        print $content;
        exit();
    }
    /*$volver=l(t('Return'),$_REQUEST['destination'],array('attributes'=>array('class'=>'back_left')));
    //
    $content=$volver.$content;*/
    $menu=create_menu_alerta_user();
    $content=$menu.$content;
    return $content;
}
function call_alerta_canal($row_in,$nombre_dia,$user_mail,$por_correo=1){
    $content='';
    $current_type='user_canal';
    $row=$row_in;
    //intelsat-2015
    //$canales=get_alerta_user_canal_nid_array($row->id,$row->is_todos_canales,$row->is_canales_que_filtro);
    $canales=get_alerta_user_canal_nid_array($row->id,$row->is_todos_canales,$row->is_canales_que_filtro,$row->tipo);
    $my_message='';
    $hay_novedades=0;
    if(count($canales)>0){
        foreach($canales as $k=>$canal_nid){
            $row->canal_nid=$canal_nid;
                $alerta_canal_list=get_alerta_canal_list_by_row($row,$nombre_dia,$my_message);
                 $canal_title='';
                   $canal_node=node_load($row->canal_nid);
                   if(isset($canal_node->nid) && !empty($canal_node->nid)){
                       //intelsat-2015
                       if(empty($canal_node->title)){
                           continue;
                       }
                       //
                       $canal_title=': '.$canal_node->title;
                   }else{
                       //intelsat-2015
                       continue;
                   }
                   //$titulo_mail=t('Alerta personalizada del canal').$canal_title;
                   $titulo_mail=str_replace(':','',$canal_title);
                if(count($alerta_canal_list)>0){
                   //print $row->my_limite.'<BR>';
                   $my_limite=get_alerta_my_limite($row->my_limite);
                   //$alerta_canal_list=array_slice($alerta_canal_list,0,$my_limite);                   
                   //gemini-2013
                   $content.=create_boletin_mail_html($alerta_canal_list,$current_type,$hay_novedades_out,$my_limite,$titulo_mail,$row);
                   if($hay_novedades_out){
                       $hay_novedades=1;
                   }
                   /*if($por_correo){
                       if(in_array($row->send_method,array('mail','mimemail'))){
                          
                            my_send_mail($user_mail,$titulo_mail, $content,$row->send_method);
                       }
                   }*/
                }else{                    
                    //intelsat-2015
                    if(!red_despacho_is_activado()){    
                        $content.=no_hay_novedades_html($current_type, $titulo_mail,$my_message);
                    }    
                }
        }
    }

    //$subject=t('Customised alert by channels').': '.get_alerta_user_nombre($row);
       $alerta_user_title=get_alerta_user_nombre($row);
       if(!empty($alerta_user_title)){
           $subject=$alerta_user_title;
       }else{
           $subject=t('Customised alert by channels');
       }
    //print $subject.'<BR>';
    $content=add_introduccion_despedida_html($content,'',$row->uid,$subject,$row);
    //intelsat-2015
    $content=red_despacho_boletin_report_get_current_content($content, $subject,'');
                
     if(!empty($content) && $por_correo){
        if(in_array($row->send_method,array('mail','mimemail'))){
            //gemini-2013
            if($hay_novedades){
                my_send_mail($user_mail,$subject, $content,$row->send_method,$row->is_recibir);
            }    
        }
     }else{
        $content=get_content_by_my_message($content, $por_correo, $my_message);
     }
     //if(strcmp($row->tipo,'canal')==0){
     if(in_array($row->tipo,array('canal','busqueda'))){
        //print $message.'<BR>';
        save_aviso_procesado($row,$por_correo,$my_message,'alerta_user');
     }

     return $content;
}
function call_alerta_categoria($row,$nombre_dia,$user_mail,$por_correo=1){
    $content='';
    $current_type='user_categoria';
    $categorias_array=explode(",",$row->categorias_string);
    $my_message='';
    //gemini-2013
    $hay_novedades=0;
    if(count($categorias_array)>0){
        //$content.=add_grupos_categorias_read_fieldset($row);
        foreach($categorias_array as $i=>$tid){
            $categoria_title='';
            /*$term=taxonomy_get_term($tid);
            if(isset($term->tid) && !empty($term->tid)){
                $categoria_title=$term->name;*/
            $categoria_title=set_categoria_title_con_flechas($tid);
            //}
            //$categoria_canal_nid_list=get_categoria_canal_nid_list($row->categorias_string);
            $categoria_canal_nid_list=get_categoria_canal_nid_list($tid);
            $grupo=get_grupo_by_tid($tid);
            $titulo_mail=$grupo->title.': '.$categoria_title;
            if(count($categoria_canal_nid_list)>0){
                /*if(user_access('root')){
                    echo print_r($categoria_canal_nid_list,1);
                }*/    
                        $alerta_categoria_list=get_alerta_categoria_list_by_row($row,$nombre_dia,$categoria_canal_nid_list,$my_message);
                        //echo print_r($alerta_categoria_list,1);
                        if(count($alerta_categoria_list)>0){                            
                            $my_limite=get_alerta_my_limite($row->my_limite);
                            //$titulo_mail=t('Alerta personalizada de categoría').': '.$categoria_title;
                            //gemini-2013
                            $content.=create_boletin_mail_html($alerta_categoria_list,$current_type,$hay_novedades_out,$my_limite,$titulo_mail,$row,$tid);
                            if($hay_novedades_out){
                                $hay_novedades=1;
                            }
                        }else{
                            //intelsat-2015
                            if(!red_despacho_is_activado()){
                                $content.=no_hay_novedades_html($current_type,$titulo_mail,$my_message);
                            }    
                        }
            }else{
                //intelsat-2015
                if(!red_despacho_is_activado()){
                    $content.=no_hay_novedades_html($current_type,$titulo_mail,'');
                }    
            }
        }
        //
        /*if(!empty($content)){
            $content=add_grupos_categorias_read_fieldset($row).$content;
        }*/

       //$subject=t('Customised alert by categories').': '.get_alerta_user_nombre($row);
       $alerta_user_title=get_alerta_user_nombre($row);
       if(!empty($alerta_user_title)){
           $subject=$alerta_user_title;
       }else{
           $subject=t('Customised alert by categories');
       }
       //print $row->nid.$subject.'<BR>';
       $content=add_introduccion_despedida_html($content,'',$row->uid,$subject,$row);
       //intelsat-2015
       $content=red_despacho_boletin_report_get_current_content($content, $subject,'');

        if(!empty($content) && $por_correo){
                                if(in_array($row->send_method,array('mail','mimemail'))){
                                    //gemini-2013
                                    if($hay_novedades){
                                        my_send_mail($user_mail,$subject, $content,$row->send_method,$row->is_recibir);
                                    }
                                }
        }else{
            $content=get_content_by_my_message($content, $por_correo, $my_message);
        }


    }
    if(strcmp($row->tipo,'categoria')==0){
        save_aviso_procesado($row, $por_correo, $my_message, 'alerta_user');
    }
    return $content;
}
function call_alerta_autor($row_in,$nombre_dia,$user_mail,$por_correo=1){
    $content='';
    $current_type='user_autor';
    $row=$row_in;
    $usuarios=get_alerta_user_uid_array($row->id,$row->is_todos_usuarios);
    //echo print_r($usuarios,1);
    $my_message='';
    //gemini-2013
    $hay_novedades=0;
    if(count($usuarios)>0){
        foreach($usuarios as $k=>$alerta_uid){
            $row->alerta_uid=$alerta_uid;
            //print $row->alerta_uid.'<BR>';
            $autor_title='';
            $autor_user=user_Load($row->alerta_uid);
            if(isset($autor_user->uid) && !empty($autor_user->uid)){
                $autor_title=': '.$autor_user->name;
            }
            //$titulo_mail=t('Alerta personalizada del autor').$autor_title;
            $titulo_mail=str_replace(':','',$autor_title);
            //
                $alerta_usuario_list=get_alerta_usuario_list_by_row($row,$nombre_dia,$my_message);
                if(count($alerta_usuario_list)>0){
                    $my_limite=get_alerta_my_limite($row->my_limite);
                    //$alerta_usuario_list=array_slice($alerta_usuario_list,0,$my_limite);
                    //gemini-2013
                    $content.=create_boletin_mail_html($alerta_usuario_list,$current_type,$hay_novedades_out,$my_limite,$titulo_mail,$row);
                    if($hay_novedades_out){
                        $hay_novedades=1;
                    }
                    /*if($por_correo){
                        if(in_array($row->send_method,array('mail','mimemail'))){
                            my_send_mail($user_mail,$titulo_mail, $content,$row->send_method);
                        }
                    }*/
                }else{
                    //intelsat-2015
                    if(!red_despacho_is_activado()){
                        $content.=no_hay_novedades_html($current_type, $titulo_mail,$my_message);
                    }    
                }
        }
    }

    $alerta_user_title=get_alerta_user_nombre($row);
    //$subject=t('Customised alert by users').': '.$alerta_user_title;
    if(!empty($alerta_user_title)){
        $subject=$alerta_user_title;
    }else{
        $subject=t('Customised alert by users');
    }
    //    
    $content=add_introduccion_despedida_html($content,'',$row->uid,$subject,$row);
    //intelsat-2015
    $content=red_despacho_boletin_report_get_current_content($content, $subject,'');

    if(!empty($content) && $por_correo){
        if(in_array($row->send_method,array('mail','mimemail'))){
            //gemini-2013
            if($hay_novedades){
                my_send_mail($user_mail,$subject, $content,$row->send_method,$row->is_recibir);
            }    

        }
    }else{
        $content=get_content_by_my_message($content,$por_correo,$my_message);
    }
    if(strcmp($row->tipo,'usuario')==0){
        save_aviso_procesado($row, $por_correo, $my_message, 'alerta_user');
    }
    return $content;
}
function call_boletin_grupo($bg,$nombre_dia,$por_correo=1){
    global $user;
    $content='';
    $my_message='';
    if(is_in_frecuencia($bg->frecuencia,$nombre_dia,$bg->hora,$bg,'boletin_grupo',$my_message)){
                $grupo=node_load($bg->grupo_nid);
                $grupo_title='';
                if(isset($grupo->nid) && !empty($grupo->nid)){
                    $grupo_title=': '.$grupo->title;
                    //$grupo_title=$grupo->title;
                }
                $subject=t('Group Bulletin').$grupo_title;
                /*if(!empty($grupo_title)){
                    $subject=$grupo_title;
                }else{
                    $subject=t('Group Bulletin');
                }*/
                //
                $html_body=array();
                //print 'bg_id='.$bg->id.'<BR>';
                $usuarios=get_boletin_usuarios_rows($bg);
                //echo print_r($usuarios,1);exit();
                //
                $hay_todos_validados=0;
                $hay_todos_noticias_usuario=0;
                $hay_todos_comentarios=0;
                $hay_todos_foros_wikis=0;
                $hay_todos_idea_opor_proy=0;
                //
                if($bg->is_todos_validados){
                    $validados=get_grupo_rows($bg,'validado');
                    //print 'limite_todos_validados='.$bg->limite_todos_validados;exit();
                    //gemini-2013
                    $content=create_boletin_mail_html($validados,'validado',$hay_novedades_out,$bg->limite_todos_validados, '', '', '',$bg->grupo_nid,$bg->limite_resumen,$bg);
                    
                    if(!empty($content) && $hay_novedades_out){
                        $html_body[]=$content;
                        $hay_todos_validados=1;
                    }else{
                        //intelsat-2015
                        if(!red_despacho_is_activado()){
                            $html_body[]=no_hay_novedades_html('validado', '',$my_message);
                        }    
                    }
                }
                //
                if($bg->is_todos_noticias_usuario){
                    $noticias_usuario=get_grupo_rows($bg,'noticia');
                    //echo print_r($noticias_usuario,1);
                    $hay_novedades_out=0;
                    $content=create_boletin_mail_html($noticias_usuario,'noticia',$hay_novedades_out,$bg->limite_todos_noticias_usuario, '', '', '',$bg->grupo_nid,$bg->limite_resumen,$bg);
                    if(!empty($content) && $hay_novedades_out){
                        $html_body[]=$content;
                        $hay_todos_noticias_usuario=1;
                    }else{
                        //intelsat-2015
                        if(!red_despacho_is_activado()){
                            $html_body[]=no_hay_novedades_html('noticia', '',$my_message);
                        }
                    }
                }
                //
                //intelsat-2015
                if(!red_despacho_is_activado()){
                    if($bg->is_todos_comentarios){
                        $comentarios=get_grupo_rows($bg,'comment');
                        //echo print_r($comentarios,1);
                        $hay_novedades_out=0;
                        $content=create_boletin_mail_html($comentarios,'comment',$hay_novedades_out,$bg->limite_todos_comentarios, '', '', '',$bg->grupo_nid,$bg->limite_resumen,$bg);
                        if(!empty($content) && $hay_novedades_out){
                            $html_body[]=$content;
                            $hay_todos_comentarios=1;
                        }else{
                            $html_body[]=no_hay_novedades_html('comment', '',$my_message);
                        }
                    }
                    //
                    if($bg->is_todos_foros_wikis){
                        $foros_wikis=get_grupo_rows($bg,'foros_wikis');
                        //echo print_r($foros_wikis,1);
                        $hay_novedades_out=0;
                        $content=create_boletin_mail_html($foros_wikis,'foros_wikis',$hay_novedades_out,$bg->limite_todos_foros_wikis, '', '', '',$bg->grupo_nid,$bg->limite_resumen,$bg);
                        if(!empty($content) && $hay_novedades_out){
                            $html_body[]=$content;
                            $hay_todos_foros_wikis=1;
                        }else{
                            $html_body[]=no_hay_novedades_html('foros_wikis', '',$my_message);
                        }
                    }
                    //
                    if($bg->is_todos_idea_opor_proy){
                        /*$idea_opor_proys=get_grupo_rows($bg,'idea_opor_proy');
                        //echo print_r($idea_opor_proys,1);
                        $content=create_boletin_mail_html($idea_opor_proys,'idea_opor_proy',$bg->limite_todos_idea_opor_proy, '', '', '',$bg->grupo_nid);
                        if(!empty($content)){
                            $html_body[]=$content;
                            $respuesta_content=$content;
                        }else{
                            $no_hay=no_hay_novedades_html('idea_opor_proy', '',$my_message);
                            $html_body[]=$no_hay;
                            $respuesta_content=$no_hay;
                        }*/
                        //gemini-2013
                        $is_no_hay=0;
                        $content=get_invitado_respuesta_content($bg,$my_message,$is_no_hay,'');
                        if(!$is_no_hay){
                            $hay_todos_idea_opor_proy=1;
                        }
                        //
                        $html_body[]=$content;
                        $respuesta_content=$content;
                    }
                }
                if(count($html_body)>0){
                    $content=implode('',$html_body);

                    //$content=add_introduccion_despedida_html($content,$grupo,'',$subject);


                    //print implode('',$html_body);exit();
                    //
                    if(count($usuarios)>0){
                        $my_kont=0;
                        foreach($usuarios as $z=>$u){
                            //print $bg->grupo_nid.'='.$u->uid.'<BR>';
                            $is_activo=is_activo_boletin_grupo_user($bg->grupo_nid, $u->uid);

                            if(!$is_activo){
                                continue;
                            }

                            $user_mail=$u->mail;
                            //print $user_mail.'<BR>';
                            //
                            //if($my_kont<1){
                                if($por_correo){
                                    if(is_user_invitado($u)){
                                        $respuesta_content=get_invitado_respuesta_content($bg,$my_message,$is_no_hay,$u);
                                        $current_content=add_introduccion_despedida_html($respuesta_content,$grupo,$u->uid,$subject);
                                    }else{
                                        $current_content=add_introduccion_despedida_html($content,$grupo,$u->uid,$subject);
                                    }
                                    //intelsat-2015
                                    if(red_despacho_is_activado()){
                                        $current_content=red_despacho_boletin_report_get_current_content($current_content,$subject,'');
                                    }
                                    //gemini-2013
                                    if(hay_novedades_en_el_boletin_de_grupo($hay_todos_validados,$hay_todos_noticias_usuario,$hay_todos_comentarios,$hay_todos_foros_wikis,$hay_todos_idea_opor_proy)){
                                    //    
                                        my_send_mail($user_mail,$subject, $current_content,$bg->send_method,$is_activo);
                                    }                                        
                                }
                            //}
                            $my_kont++;
                        }
                        
                    }
                }
            }

     if(is_user_invitado()){
        $respuesta_content=get_invitado_respuesta_content($bg,$my_message,$is_no_hay,$user);
        $content=$respuesta_content;
     }

     if(!empty($content)){
         $content=add_introduccion_despedida_html($content,$grupo,$user->uid,$subject);
     }


     if(empty($content) && !$por_correo){
        $content=get_content_by_my_message($content, $por_correo, $my_message,1);
     }
     //intelsat-2015
     $content=red_despacho_boletin_report_get_current_content($content,$subject,'');
                                    
     //intelsat-2015
     //save_aviso_procesado($bg, $por_correo, $my_message, 'boletin_grupo');
     save_aviso_procesado($bg, $por_correo, $my_message, 'boletin_grupo',$content);
     return $content;
}
function anular_rows($my_list,$user_alerta=''){
    $result=array();
    $my_array=$my_list;
    if(count($my_array)>0){
        $my_array=array_reverse($my_array);
        foreach($my_array as $i=>$row){
            $node=node_load($row->nid);
            if(isset($node->nid) && !empty($node->nid) && alerta_in_user_grupo($user_alerta,$node)){
                if(!isset($result[$row->nid])){
                    $result[$row->nid]=$row;
                    $result[$row->nid]->action_list=array();
                    $result[$row->nid]->action_list[]=$row->my_action;
                    //
                    $result[$row->nid]->action_date_list=array();
                    $result[$row->nid]->action_date_list[]=add_action_date_info($row);
                }else{
                    if(!in_array($row->my_action,$result[$row->nid]->action_list)){
                        $result[$row->nid]->action_list[]=$row->my_action;
                    }
                    $result[$row->nid]->action_date_list[]=add_action_date_info($row);
                }
            }
        }
    }
    $result=array_values($result);
    $result=array_reverse($result);
    //return $my_list;
    return $result;
}
function add_action_date_info($row){
    $result=$row->my_action.' ('.date('d-m-Y H:i',$row->fecha).')';
    return $result;
}
function get_notif_actions_date_html($action_list_in){
    $action_list=array_reverse($action_list_in);
    if(count($action_list)>0){
        return '<i>'.implode('</i><BR><i>',$action_list).'</i>';
    }
    return '';
}
function get_notif_actions_html($action_list_in){
    $action_list=array_reverse($action_list_in);
    if(count($action_list)>0){
        return '<i>'.implode(',',$action_list).'</i>';
    }
    return '';
}
function repasar_ahora_son_validados($my_list){
    $result=array();
    if(count($my_list)>0){
        $flag_row=get_flag_row('leido_interesante');
        foreach($my_list as $i=>$row){
            if(is_content_validado($row->nid,$flag_row)){
                $result[]=$row;
            }
        }
    }
    return $result;
}
function is_content_validado($nid,$flag_row){
    $c=my_get_flag_content($nid);
    if(isset($c->fid) && !empty($c->fid) && $c->fid==$flag_row->fid){
        return 1;
    }
    return 0;
}
function save_alerta_user_canales($id,$canales){
        my_delete_alerta_user_canales($id);
	if(count($canales)>0){
            foreach($canales as $canal_nid=>$v){
                insert_alerta_user_canales($id,$canal_nid);
            }
    	}
}
function my_delete_alerta_user_canales($id,$canal_nid=''){
        $where=array();
        if(!empty($id)){
            $where[]='alerta_user_id='.$id;
	}
        if(!empty($canal_nid)){
            $where[]='canal_nid='.$canal_nid;
	}
        $sql='DELETE FROM {alerta_user_canales} WHERE '.implode(' AND ',$where);
	db_query($sql);
}
function insert_alerta_user_canales($id,$canal_nid){
	$sql='INSERT INTO alerta_user_canales(alerta_user_id,canal_nid) VALUES('.$id.','.$canal_nid.')';
        db_query($sql);
}
//intelsat-2015
//function get_alerta_user_canal_nid_array($id,$is_todos_canales=0,$is_canales_que_filtro=0){
function get_alerta_user_canal_nid_array($id,$is_todos_canales=0,$is_canales_que_filtro=0,$tipo=''){
    if($is_todos_canales){
        //intelsat-2015
        //$options=get_alerta_user_canal_options(1,$id);
        $options=get_alerta_user_canal_options(1,$id,0,'',$tipo);
        $keys=array_keys($options);
        return $keys;
    }
    $result=array();
    $where=array();
    $where[]='1';
    $where[]='c.alerta_user_id='.$id;
    $order_by='ORDER BY c.id ASC';
    $sql='SELECT c.* FROM {alerta_user_canales} c WHERE '.implode(' AND ',$where).' '.$order_by;
    //print $sql;
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row->canal_nid;
    }
    //gemini-2014
    if($is_canales_que_filtro){
        $canales_filtro_nid_array=alerta_get_canales_que_filtro_nid_array($id);        
        $result=array_unique(array_merge($result,$canales_filtro_nid_array));
        $result=alerta_order_nid_array_by_title($result);
    }    
    return $result;
}
function save_alerta_user_usuarios($id,$usuarios){
        my_delete_alerta_user_usuarios($id);
	if(count($usuarios)>0){
            foreach($usuarios as $uid=>$v){
                insert_alerta_user_usuarios($id,$uid);
            }
    	}
}
function my_delete_alerta_user_usuarios($id){
	$sql='DELETE FROM {alerta_user_usuarios} WHERE alerta_user_id='.$id;
	db_query($sql);
}
function insert_alerta_user_usuarios($id,$uid){
	$sql='INSERT INTO alerta_user_usuarios(alerta_user_id,alerta_uid) VALUES('.$id.','.$uid.')';
        db_query($sql);
}
function get_alerta_user_uid_array($id,$is_todos_usuarios=0){
    if($is_todos_usuarios){
        $options=get_alerta_user_usuario_options(1,$id);        
        $keys=array_keys($options);
        return $keys;
    }
    $result=array();
    $where=array();
    $where[]='1';
    $where[]='u.alerta_user_id='.$id;
    $sql='SELECT u.* FROM {alerta_user_usuarios} u WHERE '.implode(' AND ',$where).' ORDER BY u.id ASC';
    //print $sql;
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row->alerta_uid;
    }
    $result=hontza_unset_usuarios_caducados($result,1);
    return $result;
}
function add_grupos_categorias_read_fieldset($row){
    //drupal_add_js('misc/collapse.js', 'file');
    //
    $html=array();
    global $user;
    //
    $tid_array=explode(',',$row->categorias_string);
    //
    $href_add_alerta_categoria='http://'.$_SERVER['HTTP_HOST'].base_path().'alerta_user/add_alerta_categoria?destination=alerta_user/'.$row->uid.'/my_list';
    //
    //$grupo_list=my_get_og_grupo_list($user->uid,1);
    $grupo_list=my_get_og_grupo_list($row->uid,1);
    if(count($grupo_list)>0){
        foreach($grupo_list as $i=>$gr){
            //echo print_r($gr,1);exit();
            //$href_add_alerta_categoria='http://'.$_SERVER['HTTP_HOST'].base_path().$gr->value.'/alerta_user/add_alerta_categoria?destination=alerta_user/'.$row->uid.'/my_list';
    
            $id_categoria = db_result(db_query("SELECT og.vid FROM {og_vocab} og WHERE  og.nid=%s", $gr->nid));
            //Funcion del modulo taxonomy que dado un el id de una categoria devuelve todos los terminos de la misma
            $categorias=taxonomy_get_tree($id_categoria);
            //echo print_r($categorias,1);
            if(!empty($categorias) && is_grupo_alerta_categoria_selected($categorias,$tid_array)){


                $html[]='<fieldset class=" collapsible">';
                $html[]='<legend class="collapse-processed"><a href="'.$href_add_alerta_categoria.'">'.$gr->title.'</a></legend>';
                $html[]='<div class="fieldset-wrapper">';
                $html[]='<div class="fieldset-wrapper">';
                
           
                  
                  foreach ($categorias as $id => $contenido) {
                    profundidad($contenido->tid);
                      $pro=variable_get('profundidad_valor', 0);
                      $txeked='';
                      if(in_array($contenido->tid,$tid_array)){
                         $txeked=' checked="checked"';
                       }else{
                         if(!is_txeked_parent($categorias,$contenido->tid,$tid_array)){
                             continue;
                         }
                       }
                        //$html[]='<div class="taxo'.$pro.'">';
                        $padding_left=$pro*25;
                        $html[]='<div style="padding: 0px 0px 5px '.$padding_left.'px;">';
                        //$html[]='<div id="edit-my-cat-'.$contenido->tid.'-wrapper" class="form-item form-item-checkbox form-item-required">';
                        $html[]='<div id="edit-my-cat-'.$contenido->tid.'-wrapper" style="margin: 1em 0 0.5em;">';

                        $html[]='<label for="edit-my-cat-'.$contenido->tid.'" class="option">';
                        $html[]=set_categoria_alerta_value_html($contenido,$txeked);
                        $html[]='</label>';
                        $html[]='</div>';
                        $html[]='</div>';
                  }
            
           
           
                $html[]='</div>';
                $html[]='</div>';
                $html[]='</fieldset>';
            }
        }
    }
    return implode('',$html);
}
function is_txeked_parent($categorias,$tid,$selected_array){
    if(count($categorias)>0){
        foreach($categorias as $i=>$contenido){
            if(in_array($tid,$contenido->parents) && in_array($contenido->tid,$selected_array)){
                return 1;
            }
        }
    }
    return 0;
}
function set_categoria_alerta_value_html($contenido,$txeked){
    $html=array();
    //$html[]='<input type="checkbox" class="form-checkbox required" value="1" id="edit-my-cat-'.$contenido->tid.'" name="my_cat_'.$contenido->tid.'"'.$txeked.'>'.$contenido->name;
    //$html[]='<div id="edit-my-cat-'.$contenido->tid.'">';
    $icon_name='selected';
    if(empty($txeked)){
       $icon_name='ledgreen';
    }
    $src='http://'.$_SERVER['HTTP_HOST'].base_path().'sites/all/themes/buho/images/icons/'.$icon_name.'.png';
    $html[]='<img src="'.$src.'" alt="'.$contenido->name.'" title="'.$contenido->name.'"/>';
    $html[]=$contenido->name;
    //$html[]='</div>';
    return implode('',$html);
}
function is_grupo_alerta_categoria_selected($categorias,$tid_array){
    if(!empty($categorias)){
        foreach($categorias as $i=>$contenido){
            if(in_array($contenido->tid,$tid_array)){
                return 1;
            }
        }
    }
    return 0;
}
function my_add_css($is_download=0){
    //intelsat-2015
    global $base_url;    
    $html=array();
    if(!red_despacho_boletin_report_is_my_add_css()){
        return '';
    }
    //$hasi_url='http://'.$_SERVER['HTTP_HOST'].base_path();
    $hasi_url=$base_url.'/';
    $is_pdf=boletin_report_pdf_is_pdf();
    if($is_download || $is_pdf){
        $html[]='<meta http-equiv="Content-Type" content="text/html; charset=utf-8">';
    }
    if(!red_despacho_boletin_report_is_styles_inline()){
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/default/modules/admin_menu/admin_menu.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/help_popup/jq_modal.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'modules/node/node.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'modules/system/defaults.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'modules/system/system.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'modules/user/user.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/cck/theme/content-module.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/ctools/css/ctools.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/date/date.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/date/date_popup/themes/datepicker.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/date/date_popup/themes/jquery.timeentry.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/filefield/filefield.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/fivestar/css/fivestar.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/og/theme/og.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/tagadelic/tagadelic.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/cck/modules/fieldgroup/fieldgroup.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/views/css/views.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/modules/context/plugins/context_reaction_block.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/themes/buho/css/layout.css?3" />';
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/default/files/buho/custom.css?3" />';
    }
    //
    $style_name='style';
    if($is_pdf){
        $style_name='style_pdf';            
    }
    //intelsat-2016
    $sareko_id=strtolower(_SAREKO_ID);        
    //if(hontza_is_sareko_id('GESTION_CLAVES')){             
    if(red_is_claves_activado()){    
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/'._SUBDOMINIO_SITES.'/themes/'.strtolower(_SAREKO_ID).'-buho/'.$style_name.'.css?3" />';    
    }else if(red_is_rojo()){
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/'.$sareko_id.'.hontza.es/themes/'.$sareko_id.'-buho/'.$style_name.'.css?3" />';    
    }else if(red_despacho_is_activado()){
        //intelsat-2015
        //$html=array();
        //$url_layout=$hasi_url.'sites/all/themes/buho/css/layout.css?3';
        //intelsat-2016
        $url_style=$hasi_url.'sites/'.$sareko_id.'.hontza.es/themes/'.$sareko_id.'-buho/'.$style_name;
        $html=array();
        $html[]=red_despacho_boletin_report_get_styles_inline($url_layout,$url_style,$hasi_url);
    }else{
        $html[]='<link type="text/css" rel="stylesheet" media="all" href="'.$hasi_url.'sites/all/themes/buho/'.$style_name.'.css?3" />';       
    }
    return implode('',$html);
}
function alerta_cron(){
    my_execute_cron_callback();
}
//gemini-2013
function hay_novedades_en_el_boletin_de_grupo($hay_todos_validados,$hay_todos_noticias_usuario,$hay_todos_comentarios,$hay_todos_foros_wikis,$hay_todos_idea_opor_proy){
    if($hay_todos_validados || $hay_todos_noticias_usuario || $hay_todos_comentarios || $hay_todos_foros_wikis || $hay_todos_idea_opor_proy){
        return 1;
    }
    return 0;
}
//gemini-2013
function on_alerta_save_goto($is_force=0){
    global $user;
    if(!$is_force && isset($_REQUEST['destination']) && !empty($_REQUEST['destination'])){
        //
    }else{
        drupal_goto('alerta_user/'.$user->uid.'/my_list');
    }
}