<?php
require_once('despacho.vigilancia.inc.php');
require_once('despacho.boletin_report.inc.php');
require_once('despacho.boletin_report.word.inc.php');
function despacho_perm() {
  return array();
}
function despacho_menu() {
  $items=array();
  $items['despacho/canales/tipos_fuente/%'] = array(
    'title' => 'Monitoring',
    'page callback' => 'despacho_vigilancia_canales_tipos_fuente_callback',
    'access callback'=>'despacho_vigilancia_canales_tipos_fuente_access',    
  );
  $items['despacho/%/categorizar']=array(
    'title' => 'Categorize',
    'page arguments' => array('despacho_vigilancia_categorizar_form'),  
    'page callback' => 'drupal_get_form',
    'access callback'=>'despacho_vigilancia_categorizar_access',    
  );
  $items['despacho/%/on_categorizar/popup']=array(
    'title' => 'Categorize',
    'page callback' => 'despacho_vigilancia_on_categorizar_popup_callback',  
    'access callback'=>'despacho_vigilancia_categorizar_access',    
  );
  $items['despacho/%/reclasificar_tipo_fuente']=array(
    'title' => 'Types of Sources',
    'page arguments' => array('despacho_vigilancia_reclasificar_tipo_fuente_form'),  
    'page callback' => 'drupal_get_form',
    'access callback'=>'despacho_vigilancia_categorizar_access',    
  );
  $items['despacho/%/on_reclasificar_tipo_fuente/popup']=array(
    'title' => 'Categorize',
    'page callback' => 'despacho_vigilancia_on_reclasificar_tipo_fuente_popup_callback',  
    'access callback'=>'despacho_vigilancia_categorizar_access',    
  );
  return $items;
}
function despacho_is_show_custom_activo_pestana($key){
  if(despacho_is_show_custom_activo_pestana_activado()){
    $my_array=array('debate','wiki','idea','estrategia');
    if(red_dashboard_is_activado()){
        $dashboard_array=array('grupo');
        $my_array=array_merge($my_array,$dashboard_array);
    }
    if(in_array($key,$my_array)){
        return 1;
    }
  }  
  return 0;
}
function despacho_is_custom_activo_pestana($key){
    if(despacho_is_show_custom_activo_pestana($key)){
        return 0;
    }
    return 1;
}
function despacho_is_show_lo_mas_comentado(){
    return 0;
}
function despacho_is_show_boletin_report_link(){
    //if(is_super_admin()){
        return 1;
    /*}
    return 0;*/
}
function despacho_is_show_comment_link(){
    if(defined('_IS_DESPACHO_SHOW_COMMENT_LINK')){
      if(_IS_DESPACHO_SHOW_COMMENT_LINK==1){
        return 1;
      }
    }
    return 0;
}
function despacho_is_show_categorizar_link(){
    return 1;
}
function despacho_is_show_custom_activo_pestana_activado(){
  if(defined('_IS_DESPACHO_SHOW_CUSTOM_ACTIVO_TAB')){
    if(_IS_DESPACHO_SHOW_CUSTOM_ACTIVO_TAB==1){
      return 1;
    }
    return 0;
  }
  return 1;
}