<?php
require_once('red_compartir.canal.inc.php');
require_once('red_compartir.facilitador.inc.php');
require_once('red_compartir.grupo.inc.php');
require_once('red_compartir.login.inc.php');
require_once('red_compartir.user.view.inc.php');
require_once('red_compartir.fuente.multiple.inc.php');
require_once('red_compartir.canal.multiple.inc.php');
require_once('red_compartir.facilitador.multiple.inc.php');
//intelsat-2015
//require_once('red_compartir.validar_usuario.network.inc.php');
//intelsat-2016
require_once('red_compartir.registrar.grupo.inc.php');
function red_compartir_perm() {
    return array('access red_compartir');
}
function red_compartir_menu() {
    $items=array(); 
    $items['red_compartir/compartir_fuente_hoja/%'] = array(
        'title' => 'Share Source',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_fuente_hoja_form'),
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_guardar_en_local_compartir_fuente_hoja_enviado']=array(
        'title' => 'Share Source',
        'page callback'=>'red_compartir_guardar_en_local_compartir_fuente_hoja_enviado_callback',    
        'access arguments' => array('access red_compartir'),    
    );
    $items['red_compartir/red_compartir_copiar_fuentes_servidor'] = array(
        'title' => 'Shared Sources',
        'page callback'=>'red_compartir_copiar_fuentes_servidor_form_callback',
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/compartir_canal_hoja/%'] = array(
        'title' => 'Share Channel',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_canal_hoja_form'),
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_guardar_en_local_compartir_canal_hoja_enviado']=array(
        'title' => 'Share Channel',
        'page callback'=>'red_compartir_guardar_en_local_compartir_canal_hoja_enviado_callback',    
        'access arguments' => array('access red_compartir'),    
    );
    $items['red_compartir/red_compartir_copiar_canales_servidor'] = array(
        'title' => 'Shared Channels',
        //'page callback'=>'drupal_get_form',    
        //'page arguments' => array('red_compartir_copiar_canales_servidor_form'),
        'page callback' => 'red_compartir_copiar_canales_servidor_form_callback',
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/compartir_facilitador_hoja/%'] = array(
        'title' => 'Share Facilitator',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_facilitador_hoja_form'),
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_guardar_en_local_compartir_facilitador_hoja_enviado']=array(
        'title' => 'Share Facilitator',
        'page callback'=>'red_compartir_guardar_en_local_compartir_facilitador_hoja_enviado_callback',    
        'access arguments' => array('access red_compartir'),    
    );
    $items['red_compartir/red_compartir_copiar_facilitadores_servidor'] = array(
        'title' => 'Copy facilitators from Network server',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_copiar_facilitadores_servidor_form'),
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/compartir_grupo_hoja/%'] = array(
        'title' => 'Connect to Network',
        'page callback'=>'red_compartir_grupo_hoja_callback',    
        'access arguments' => array('access red_compartir'),
    );    
    $items['red_compartir/red_compartir_grupo_guardar_en_local_compartir_grupo_hoja_enviado']=array(
        'title' => 'Connect to Network',
        'page callback'=>'red_compartir_grupo_guardar_en_local_compartir_grupo_hoja_enviado_callback',    
        'access arguments' => array('access red_compartir'),    
    );
    $items['red_compartir/red_compartir_grupo_get_user_grupos_subdominio_get_contents']=array(
        'title'=>'My Groups Network',
        'page callback'=>'red_compartir_grupo_get_user_grupos_subdominio_get_contents_callback',    
        'access callback' => TRUE,
    );
    $items['red_compartir/authenticate_local/%']=array(
        'title'=>'Login network user',
        'page callback'=>'red_compartir_login_authenticate_local_callback',    
        'access callback' => TRUE,
    );
    $items['red_compartir/user_change']=array(
        'title'=>'User Network change',
        'page callback'=>'red_compartir_grupo_user_change_callback',    
        'access callback' => TRUE,
    );
    $items['red_compartir/red_compartir_fuente_get_user_local_get_contents/%']=array(
        'title'=>'Source user local',
        'page callback'=>'red_compartir_fuente_get_user_local_get_contents_callback',    
        'access callback' => TRUE,
    );
     $items['red_compartir/red_compartir_fuente_get_numero_de_descargas_get_contents/%']=array(
        'title'=>'Source',
        'page callback'=>'red_compartir_fuente_get_numero_de_descargas_get_contents_callback',    
        'access callback' => TRUE,
    );
    $items['red_compartir/red_compartir_view_fuente_servidor/%'] = array(
        'title' => 'View Source',
        'page callback'=>'red_compartir_view_fuente_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_view_user_fuente_servidor/%'] = array(
        'title' => 'View Source',
        'page callback'=>'red_compartir_view_user_fuente_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_view_canal_servidor/%'] = array(
        'title' => 'View Channel',
        'page callback'=>'red_compartir_view_canal_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
     $items['red_compartir/red_compartir_canal_get_numero_de_descargas_get_contents/%']=array(
        'title'=>'Source',
        'page callback'=>'red_compartir_canal_get_numero_de_descargas_get_contents_callback',    
        'access callback' => TRUE,
    );
     $items['red_compartir/red_compartir_view_user_canal_servidor/%'] = array(
        'title' => 'View Source',
        'page callback'=>'red_compartir_view_user_canal_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
     $items['red_compartir/user_compartir_autocomplete'] = array(
        'title' => 'User',
        'page callback'=>'red_compartir_user_compartir_autocomplete_callback',    
        'access arguments' => array('access red_compartir'),
    );
     $items['red_compartir/no_compartir_grupo_hoja/%'] = array(
        'title' => 'Disconnect from Network',
        'page callback'=>'red_compartir_grupo_no_compartir_grupo_hoja_callback',    
        'access arguments' => array('access red_compartir'),
    );     
    $items['red_compartir/red_compartir_grupo_guardar_en_local_no_compartir_grupo_hoja_enviado']=array(
        'title' => 'Share Source',
        'page callback'=>'red_compartir_grupo_guardar_en_local_no_compartir_grupo_hoja_enviado_callback',    
        'access arguments' => array('access red_compartir'),    
    );
    $items['red_compartir/red_compartir_get_user_local_by_uid_get_contents/%']=array(
        'title' => 'User',
        'page callback'=>'red_compartir_get_user_local_by_uid_get_contents_callback',    
        'access callback' => TRUE,    
    );
    $items['red_compartir/compartir_fuente_hoja_multiple'] = array(
        'title' => 'Sharing Sources',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_fuente_hoja_multiple_form'),
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_guardar_en_local_compartir_fuente_hoja_multiple_enviado']=array(
        'title' => 'Share Sources',
        'page callback'=>'red_compartir_guardar_en_local_compartir_fuente_hoja_enviado_multiple_callback',    
        'access arguments' => array('access red_compartir'),    
    );
    $items['red_compartir/compartir_canal_hoja_multiple'] = array(
        'title' => 'Share Channels',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_canal_hoja_multiple_form'),
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_guardar_en_local_compartir_canal_hoja_multiple_enviado']=array(
        'title' => 'Share Channels',
        'page callback'=>'red_compartir_guardar_en_local_compartir_canal_hoja_enviado_multiple_callback',    
        'access arguments' => array('access red_compartir'),    
    );
    $items['red_compartir/%/red_compartir_copiar_fuente_del_servidor'] = array(
        'title' => 'Download Source',
        'page callback'=>'red_compartir_copiar_fuente_del_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/%/red_compartir_copiar_canal_del_servidor'] = array(
        'title' => 'Download Channel',
        'page callback'=>'red_compartir_copiar_canal_del_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_view_facilitador_servidor/%'] = array(
        'title' => 'View Facilitator',
        'page callback'=>'red_compartir_view_facilitador_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
     $items['red_compartir/%/red_compartir_copiar_facilitador_del_servidor'] = array(
        'title' => 'Download Facilitator',
        'page callback'=>'red_compartir_copiar_facilitador_del_servidor_callback',    
        'access arguments' => array('access red_compartir'),
    );
     $items['red_compartir/compartir_facilitador_hoja_multiple'] = array(
        'title' => 'Share Facilitators',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_facilitador_hoja_multiple_form'),
        'access arguments' => array('access red_compartir'),
    );
     $items['red_compartir/red_compartir_guardar_en_local_compartir_facilitador_hoja_multiple_enviado']=array(
        'title' => 'Share Facilitators',
        'page callback'=>'red_compartir_guardar_en_local_compartir_facilitador_hoja_enviado_multiple_callback',    
        'access arguments' => array('access red_compartir'),    
    );
     $items['red_compartir/borrarme_del_servidor'] = array(
        'title' => 'Delete',
        'page callback'=>'drupal_get_form',    
        'page arguments' => array('red_compartir_borrarme_del_servidor_form'),
        'access arguments' => array('access content'),
    );
    //intelsat-2015
    $items['red_compartir/red_compartir_view_fuente_local/%'] = array(
        'title' => 'View Source',
        'page callback'=>'red_compartir_view_fuente_local_callback',    
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_view_canal_local/%'] = array(
        'title' => 'View Channel',
        'page callback'=>'red_compartir_canal_view_canal_local_callback',    
        'access arguments' => array('access red_compartir'),
    );
    $items['red_compartir/red_compartir_view_facilitador_local/%'] = array(
        'title' => 'View Channel',
        'page callback'=>'red_compartir_facilitador_view_facilitador_local_callback',    
        'access arguments' => array('access red_compartir'),
    );
    //intelsat-2016
    $items['red_compartir/compartir_grupo_hoja_registrar/%'] = array(
        'title' => 'Connect to Network',
        'page arguments'=>array('red_compartir_registrar_grupo_hoja_registrar_form'), 
        'page callback'=>'drupal_get_form',    
        'access arguments' => array('access red_compartir'),
    ); 
    //
    return $items;
}
function red_compartir_fuente_hoja_form(){
    global $user;
    red_compartir_grupo_is_grupo_red_alerta_access_denied();
    $form=array();
    $nid=arg(2);
    $node=node_load($nid);    
    $existe=red_compartir_fuente_existe_en_el_servidor($node);
    if(!empty($existe)){
        $msg='';
        if($existe==1){
            $msg=t('The Yahoo Pipes ID is already shared in the Server');        
        }else if($existe==2){
            $msg=t('The source title already exists in the Server, please change it');        
        }
        //    
        $form['msg_existe']['#value']='<p>'.$msg.'</p>';
        $form['cancelar_btn']=array(
            '#value'=>l(t('Return'),'node/'.$nid),
        );
        return $form;
    }
    $form['#action']=red_compartir_define_url_fuente_servidor();
    $form['#attributes']=array('target'=>'_blank');
    $node->sareko_id=_SAREKO_ID;
    $node->user_local=red_compartir_prepare_user_enviar($user);
    $node->subdominio=red_compartir_grupo_get_subdominio();
    $fuente_enviar=red_compartir_prepare_fuente_enviar($node);
    $form['fuente_enviar']=array(
        '#type'=>'hidden',
        '#default_value'=>$fuente_enviar,
    );    
    $form['source_name']=array(
        '#value'=>'<p><b>'.$node->title.'</b></p>',
    );
    $form['share_btn']=array(
        '#type'=>'submit',
        '#default_value'=>t('Share'),
    );
    $form['cancelar_btn']=array(
        '#value'=>l(t('Return'),'node/'.$nid),
    );
    red_compartir_add_fuente_hoja_js();
    return $form;
}
function red_compartir_define_url_fuente_servidor(){
    $redalerta_servidor_url=red_compartir_define_redalerta_servidor_url();
    return url($redalerta_servidor_url.'/red_servidor/guardar_fuente_hoja',array('absolute'=>TRUE));
}
function red_compartir_define_redalerta_servidor_url(){
    //simulando
    //return 'http://localhost/hontza3';
    //
    return red_get_servidor_central_url();
}
function red_compartir_add_fuente_hoja_js(){ 
    $js='
        $(document).ready(function(){
        $("#edit-share-btn").click(function(){
            call_red_compartir_fuente_hoja_ajax();
            //return false;
        });
        function call_red_compartir_fuente_hoja_ajax(){ 
            var d=new Date();
            var n=d.getTime();
            var fuente_enviar_val=$("#edit-fuente-enviar").val();
            jQuery.ajax({
				type: "POST",
				url: "'.url('red_compartir/red_compartir_guardar_en_local_compartir_fuente_hoja_enviado',array('absolute'=>TRUE)).'?my_time="+n,
				data: {fuente_enviar:fuente_enviar_val},
				dataType:"json",
				success: function(my_result){
                                  window.location.href="'.url('red/fuentes-pipes/todas').'";
				}
			});          
        }          
    });';        
    drupal_add_js($js,'inline');
}
function red_compartir_prepare_fuente_enviar($node){
    return base64_encode(serialize($node));
}
function red_compartir_guardar_en_local_compartir_fuente_hoja_enviado_callback(){
    $result=array();
    $result['ok']=1;
    if(isset($_POST['fuente_enviar']) && !empty($_POST['fuente_enviar'])){
        $node=unserialize(base64_decode(($_POST['fuente_enviar'])));
        red_compartir_save_red_compartir_fuente($node);
    }
    print json_encode($result);
    exit();
} 
function red_compartir_save_red_compartir_fuente($node){
    global $user;
    $row=red_compartir_get_red_compartir_fuente_row($node);
    $nid=$node->nid;
    $vid=$node->vid;
    $uid=$user->uid;
    $group_nid=0;
    $my_grupo=og_get_group_context();
    if(isset($my_grupo->nid) && !empty($my_grupo->nid)){
        $group_nid=$my_grupo->nid;
    }
    $fecha=time();
    if(isset($row->id) && !empty($row->id)){
        db_query($sql=sprintf('UPDATE {red_compartir_fuente} SET uid=%d,group_nid=%d,fecha=%d WHERE nid=%d AND vid=%d',$uid,$group_nid,$fecha,$nid,$vid));
    }else{
        db_query($sql=sprintf('INSERT INTO {red_compartir_fuente}(nid,vid,uid,group_nid,fecha) VALUES(%d,%d,%d,%d,%d)',$nid,$vid,$uid,$group_nid,$fecha));
    }
    drupal_set_message(t('Source %fuente_title shared',array('%fuente_title'=>$node->title)));
}
function red_compartir_get_red_compartir_fuente_row($node){
    $red_compartir_fuente_array=red_compartir_get_red_compartir_fuente_array($node->vid,$node->nid);
    if(count($red_compartir_fuente_array)>0){
        return $red_compartir_fuente_array[0];
    }
    $my_result=new stdClass();
    return $my_result;
}
function red_compartir_get_red_compartir_fuente_array($vid,$nid){
    $result=array();
    $where=array();
    $where[]='1';
    if(!empty($vid)){
        $where[]='vid='.$vid;
    }
    if(!empty($nid)){
        $where[]='nid='.$nid;
    }
    $sql='SELECT * FROM {red_compartir_fuente} WHERE '.implode(' AND ',$where);
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function red_compartir_copiar_fuentes_servidor_form(){
    //drupal_set_title(t('Shared Sources'));
    boletin_report_no_group_selected_denied();
    $form=array();
        $fuente_list=red_compartir_get_fuentes_servidor_list();
        //echo print_r($fuente_list,1);exit();
        $prefix='<div class="n-opciones-item">';
        $form_return_btn=array(
            '#value'=>red_compartir_copiar_fuentes_servidor_volver_link(),
            '#prefix'=>$prefix,                             
        );        
        if(!empty($fuente_list)){
             $form['copiar_fuente_table']=array(
                 '#value'=>red_compartir_get_copiar_fuente_table_html($fuente_list),
             );
             //intelsat-2015
             $form['return_btn']=$form_return_btn;
             $form['my_submit']=array(
                 //intelsat-2015
                 //'#type'=>'submit',
                 '#type'=>'image_button',
                 '#name'=>'my_submit',
                 '#value'=>t('Download'),
                 //'#prefix'=>'<div style="float:left;">',                 
                 '#suffix'=>'</div>',
                 '#src'=>red_compartir_fuente_descargar_path(),
                 );
             //
        }else{
            $form['my_msg']=array(
                '#value'=>'<p>'.t('There are no contents').'</p>',
            );
            //intelsat-2015
            $form['return_btn']=$form_return_btn;
            $form['return_btn']['#suffix']='</div>';
            //            
        }            
    return $form;
}
function red_compartir_get_fuentes_servidor_list(){
    $result=array();
    $url=red_compartir_define_redalerta_servidor_url();
    $url.='/red_servidor/red_servidor_fuentes_get_contents';
    $filtro_get_contents=red_compartir_fuentes_set_copy_filtro_get_contents();    
    if(!empty($filtro_get_contents)){
        $url.='?red_alerta_filtro='.$filtro_get_contents;
    }
    /*if(user_access('root')){
        print $url;exit();
    }*/
    $content=file_get_contents($url);
    //$fuentes_servidor=unserialize($content);
    $content_array=unserialize($content);
    $fuentes_servidor=$content_array['fuentes_array'];
    $_SESSION['user_autocomplete_fuentes']['user_autocomplete_options']=$content_array['user_autocomplete_options'];
    //
    if(!empty($fuentes_servidor)){
        foreach($fuentes_servidor as $i=>$row){
            //if($row->sareko_id!=_SAREKO_ID){
                $result[]=$row;
            //}
        }
    }    
    return $result;
}
function red_compartir_copiar_fuentes_servidor_volver_link($is_canal=0,$url_in=''){
    if(empty($url_in)){
        if($is_canal){
            $url='vigilancia/validados';
        }else{
            $url='fuentes-pipes/todas';
        }
        if(isset($_REQUEST['destination']) && !empty($_REQUEST['destination'])){
            $url=$_REQUEST['destination'];
        }
    }else{
        //intelsat-2015
        $url=$url_in;
        //
    }       
    //intelsat-2015
    //return l(t('Return'),$url,array('attributes'=>array('class'=>'back_left')));
    return l(my_get_icono_action('back',t('Return'),'',array(),' style="padding-top:2px;float:left;"'),$url,array('html'=>true)).'&nbsp;';
}
function red_compartir_copiar_fuentes_servidor_form_submit(&$form, &$form_state){
    if(isset($form_state['clicked_button']) && !empty($form_state['clicked_button']) && $form_state['clicked_button']['#name']=='my_submit'){
        /*
        $values=$form_state['values'];
        if(isset($values['copiar_fuente']) && !empty($values['copiar_fuente'])){
            $my_array=$values['copiar_fuente'];*/
            $my_array=array();
            if(isset($_REQUEST['copiar_fuente'])){
                $my_array=$_REQUEST['copiar_fuente'];
            }
            if(!empty($my_array)){
                $fuentes_servidor=red_compartir_get_fuentes_servidor_list();
                foreach($my_array as $nid=>$v){
                    if(!empty($v)){
                        if(!red_compartir_is_copiado_del_servidor($nid)){
                            $fuente_servidor=red_compartir_get_fuente_servidor($nid,$fuentes_servidor);
                            //AVISO:::: $fuente es un parametro out
                            red_compartir_save_fuente_descargados($fuente_servidor,$fuente);
                            //intelsat-2015
                            //red_compartir_fuente_contar_descargado($fuente_servidor);
                            //
                            drupal_set_message(t('Source %fuente_title downloaded',array('%fuente_title'=>$fuente->title)));
                        }  
                    }
                }
            }
        //}
    }
    //drupal_goto('fuentes-pipes/todas');
    drupal_goto('red_compartir/red_compartir_copiar_fuentes_servidor');
}
function red_compartir_is_copiado_del_servidor($nid){
    $fuente=red_compartir_get_fuente_descargados_row($nid);
    if(isset($fuente->id) && !empty($fuente->id)){
       $node=node_load($fuente->nid);
       if(isset($node->nid) && !empty($node->nid)){     
            return 1;
       } 
    }
    return 0;
}
function red_compartir_get_fuente_descargados_row($nid){
    $fuente_array=red_compartir_get_fuente_descargados_array($nid);
    if(count($fuente_array)>0){
        return $fuente_array[0];
    }
    //
    $my_result=new stdClass();
    return $my_result;
}
function red_compartir_get_fuente_descargados_array($nid=''){
    $where=array();
    $where[]='1';
    if(!empty($nid)){
        $where[]='servidor_nid='.$nid;
    }
    $sql='SELECT * FROM {red_compartir_fuente_descargados} WHERE '.implode(' AND ',$where);
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=$row;
    }
    return $result;
}
function red_compartir_get_fuente_servidor($nid,$fuentes_servidor){
    if(!empty($fuentes_servidor)){
        foreach($fuentes_servidor as $i=>$row){
           if($nid==$row->nid){
               return $row;
           }
        }
    }
    $my_result=new stdClass();
    return $my_result;
}
function red_compartir_save_fuente_descargados($fuente_servidor,&$node){
    if(isset($fuente_servidor->node)){
        $node=$fuente_servidor->node;
        //
            $servidor_nid=$node->nid; 
            $servidor_vid=$node->vid; 
            $servidor_uid=$node->uid;
            $servidor_group_nid=$fuente_servidor->group_nid;
            $fecha=time();
            $servidor_sareko_id=$fuente_servidor->sareko_id;
            $node=red_compartir_local_preparar_fuente($node,$grupo_local);
            node_save($node);
            $vid=$node->vid;
            $nid=$node->nid;
            $uid=$node->uid;
            $group_nid=$grupo_local->nid;
            $sql=sprintf('INSERT INTO {red_compartir_fuente_descargados}(servidor_nid,servidor_vid,servidor_uid,servidor_group_nid,fecha,servidor_sareko_id,vid,nid,uid,group_nid) VALUES(%d,%d,%d,%d,%d,"%s",%d,%d,%d,%d)',$servidor_nid,$servidor_vid,$servidor_uid,$servidor_group_nid,$fecha,$servidor_sareko_id,$vid,$nid,$uid,$group_nid);
            db_query($sql);
    }    
}
function red_compartir_local_preparar_fuente($node_in,&$grupo_local){
    global $user;
    $node=$node_in;
    unset($node->nid);
    unset($node->vid);
    unset($node->created);
    unset($node->changed);
    $node->uid=$user->uid;
    unset($node->sareko_id);
    $grupo_local=og_get_group_context();
    $new_body=hontza_content_full_text($node,1);
    $node->body=$new_body;
    //    
    if(isset($node->og_groups)){
        unset($node->og_groups);
    }
    if(isset($node->og_groups_both)){
        unset($node->og_groups_both);
    }
    if(isset($grupo_local->nid) && !empty($grupo_local->nid)){
        $$grupo_local_nid=$grupo_local->nid;
        $node->og_groups[$grupo_local_nid]=$grupo_local_nid;
        $node->og_groups_both[$grupo_localr_nid]=$grupo_local->title;
    }
    return $node;
}
function red_compartir_get_copiar_fuente_table_html($fuente_list_in){
    $fuente_list=$fuente_list_in;
    $sort='asc';
    $is_numeric=0;
    $field='fuente_title';
    if(isset($_REQUEST['sort']) && !empty($_REQUEST['sort'])){
        $sort=$_REQUEST['sort'];
    }    
    if(isset($_REQUEST['order']) && !empty($_REQUEST['order'])){
        $order=$_REQUEST['order'];
        if($order==t('Region')){
            $field='fuente_region';
        }else if($order==t('Rating')){
            $is_numeric=1;
            $field='fuente_rating_suma';            
        }else if($order==t('User')){
            $field='user_local_name';            
        }else if($order==t('Downloads')){
            $field='numero_de_descargas';            
        }             
    }    
    $fuente_list=array_ordenatu($fuente_list,$field,$sort,$is_numeric);    
    /*if(user_access('root')){
        echo print_r($fuente_list,1);
        exit();
    }*/    
    //$filter_fields=red_compartir_fuentes_copy_filter_fields();
    //
    $my_limit=25;
    //
    $headers=array();
    $headers[0]='';
    //$headers[1]=t('Title');
    $headers[1]=array('data'=>t('Description'),'field'=>'fuente_title');
    //$headers[2]=t('Origin');
    //$headers[2]=t('Type');		
    //$headers[4]=t('Subdomain');
    $headers[2]=array('data'=>t('Region'),'field'=>'fuente_region');
    $headers[3]=array('data'=>t('Rating'),'field'=>'fuente_rating_suma');
    //$headers[3]=t('Quality');
    //$headers[4]=t('Coverage');
    //$headers[5]=t('Update');
    $headers[4]=array('data'=>t('Downloads'),'field'=>'numero_de_descargas');
    $headers[5]=array('data'=>t('User'),'field'=>'user_local_name');
    //$headers[8]='A';
    //$headers[9]='O';
    //$headers[10]='F';
    $kont=0;
    $rows=array();
    $_SESSION['red_compartir_copiar_fuentes_servidor']=array();    
    if(!empty($fuente_list)){
        foreach($fuente_list as $i=>$r){
            if(isset($r->node)){
                $node=$r->node;
                //print $r->node_view;exit();
                //echo print_r($r,1);
                $_SESSION['red_compartir_copiar_fuentes_servidor'][$r->id]=$r;
                if(isset($node->nid) && !empty($node->nid)){
                    $rows[$kont]=array();
                    $rows[$kont][0]='<div style="white-space:nowrap;float:right;">';
                    if($r->sareko_id==_SAREKO_ID){
                        $rows[$kont][0].='<div style="margin-top:-18px;">&nbsp;</div>';
                    }else{    
                        $rows[$kont][0].='<input type="checkbox" id="copiar_fuente_'.$r->nid.'" name="copiar_fuente['.$r->nid.']" value="1"/>&nbsp;';
                    }
                    //intelsat-2015
                    //se ha comentado esto
                    //$rows[$kont][0].='&nbsp;'.l(my_get_icono_action('viewmag', t('View')),'red_compartir/red_compartir_view_fuente_servidor/'.$r->id,array('html'=>true,'query'=>drupal_get_destination()));
                    $rows[$kont][0].='</div>';
                    //$rows[$kont][1]=$node->title;
                    $rows[$kont][1]=red_compartir_fuente_get_description($node,'red_compartir/red_compartir_view_fuente_servidor/'.$r->id);
                    $rows[$kont][2]=red_regiones_get_region_decode_value(red_compartir_fuente_get_region($node));
                    //$rows[$kont][2]=red_compartir_fuente_get_origin($node->type);
                    //$rows[$kont][2]=red_compartir_get_fuente_type($node);
                    //$rows[$kont][4]=$r->sareko_id_label;
                    //$rows[$kont][3]=hontza_get_fuente_stars_value($node,'calidad',1);
                    //$rows[$kont][4]=hontza_get_fuente_stars_value($node,'exhaustividad',1);
                    //$rows[$kont][5]=hontza_get_fuente_stars_value($node,'actualizacion',1);
                    $rows[$kont][3]=array('data'=>red_compartir_fuente_get_rating_en_filas($node),'style'=>'width:190px;');
                    $rows[$kont][4]=$r->numero_de_descargas;
                    $rows[$kont][5]=red_compartir_fuente_get_user_name($r);
                    //$rows[$kont][8]=my_get_source_view_api_icon($node,'alchemy');
                    //$rows[$kont][9]=my_get_source_view_api_icon($node,'opencalais');
                    //$rows[$kont][10]=my_get_source_view_api_icon($node,'full_text_rss');
                    $kont++;
                }
            }
        }        
    }
    /*
        if(user_access('root')){
            echo print_r($_SESSION['red_compartir_copiar_fuentes_servidor'],1);
            exit();
        }
    */    
    //exit();
    $rows=my_set_estrategia_pager($rows, $my_limit);
    
    if (count($rows)>0) {
        $output .= theme('table',$headers,$rows,array('class'=>'table_gestion_usuarios'));
        $output .= theme('pager', NULL, $my_limit);    
    }else {
        $output.= '<div id="first-time">' .t('There are no contents'). '</div>';
    }
    return $output;
}
function red_compartir_fuente_get_origin($node_type){
    if($node_type=='supercanal'){
        return 'Yahoo Pipes';
    }
    return 'Dapper';
}
function red_compartir_get_fuente_type($node){
    $html=array();
    if(isset($node->taxonomy) && !empty($node->taxonomy)){
        foreach($node->taxonomy as $tid=>$servidor_term){
            $term=taxonomy_get_term_by_language($tid);
            if(isset($term->name) && !empty($term->name)){
                $html[]=$term->name;
            }else{
                $html[]=$servidor_term->name;            
            }
        }
    }
    return implode('<BR>',$html);
}
function red_compartir_fuentes_copy_filter_fields(){
    //$filter_fields=array('fuente_title','node_type','clasificacion','sareko_id','calidad','exhaustividad','actualizacion');
    $filter_fields=array('fuente_title','fuente_description','region','calidad','exhaustividad','actualizacion','numero_de_descargas','user_local_name');
    return $filter_fields;
}
function red_compartir_fuentes_copy_header(){
    $html=array();
    $html[]=red_compartir_navegar_menu();
    $html[]=red_compartir_fuentes_copy_filtro();
    return implode('',$html);
}
function red_compartir_fuentes_copy_filtro(){
    my_add_buscar_js();
    return drupal_get_form('red_compartir_fuentes_copy_filtro_form');
}
function red_compartir_fuentes_copy_filtro_form(){
    $form=array();
    $fs_title=t('Search');
    if(!red_compartir_fuentes_copy_is_filter_activated()){
        $fs_title=t('Filter');
        $class='file_buscar_fs_vigilancia_class';
    }else{
        $fs_title=t('Filter Activated');
        $class='file_buscar_fs_vigilancia_class fs_search_activated';
    }
    //    
    $form['file_buscar_fs']=array('#type'=>'fieldset','#title'=>$fs_title,'#attributes'=>array('id'=>'file_buscar_fs','class'=>$class));
    $form['file_buscar_fs']['fuente_title']=
        array('#type'=>'textfield',
        '#title'=>t('Title'),
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('fuente_title'));
    $form['file_buscar_fs']['fuente_description']=
        array('#type'=>'textfield',
        '#title'=>t('Description'),
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('fuente_description'));
    /*$form['file_buscar_fs']['region']=
        array('#type'=>'textfield',
        '#title'=>t('Region'),
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('region'));*/
    /*
    $form['file_buscar_fs']['region']=
        array('#type'=>'select',
        '#title'=>t('Region'),
        '#options'=>red_regiones_define_regiones_options(1),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('region'));*/
    
    
    $form['file_buscar_fs']['region_fs']=red_regiones_define_fieldset('',red_compartir_fuentes_copy_get_filter_value('region'));
    
    
    // 
    /*$form['file_buscar_fs']['node_type']=
        array('#type'=>'select',
        '#title'=>t('Origin'),
        '#options'=>red_compartir_fuentes_copy_define_origin_options(),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('node_type'));
    //
    $form['file_buscar_fs']['clasificacion']=
        array('#type'=>'select',
        '#title'=>t('Type'),
        '#options'=>hontza_define_clasificaciones_fuente(1),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('clasificacion'));
    // 
    $form['file_buscar_fs']['sareko_id']=
        array('#type'=>'select',
        '#title'=>t('Sudomain'),
        '#options'=>red_compartir_fuentes_copy_define_subdomain_options(),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('sareko_id'));*/
     $form['file_buscar_fs']['calidad']=
        array('#type'=>'select',
        '#title'=>t('Quality'),
        '#options'=>my_get_star_texto_options('calidad',0),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('calidad'));
     $form['file_buscar_fs']['exhaustividad']=
        array('#type'=>'select',
        '#title'=>t('Coverage'),
        '#options'=>my_get_star_texto_options('exahustivo',0),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('exhaustividad'));
     $form['file_buscar_fs']['actualizacion']=
        array('#type'=>'select',
        '#title'=>t('Update'),
        '#options'=>my_get_star_texto_options('actualizacion',0),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('actualizacion'));     
     /*$form['file_buscar_fs']['numero_de_descargas']=
        array('#type'=>'textfield',
        '#title'=>t('Downloads'),
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('numero_de_descargas'));*/
     
      $form['file_buscar_fs']['numero_de_descargas']=
        array('#type'=>'select',
        '#title'=>t('Downloads'),
        '#options'=>red_compartir_fuentes_copy_define_numero_de_descargas_options(),    
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('numero_de_descargas'));
     
     
     /*$form['file_buscar_fs']['user_local_name']=
        array('#type'=>'textfield',
        '#title'=>t('User'),
        "#default_value"=>red_compartir_fuentes_copy_get_filter_value('user_local_name'));*/
      
      $form['file_buscar_fs']['user_local_name']= array(
	  '#title' => t('User'),
	  '#type' => 'textfield',
	  '#maxlength' => 255,
	  '#autocomplete_path' => 'red_compartir/user_compartir_autocomplete',
	  '#default_value' => red_compartir_fuentes_copy_get_filter_value('user_local_name')
	);
      
    //
    $form['file_buscar_fs']['submit']=array('#type'=>'submit','#value'=>t('Search'),'#name'=>'buscar','#prefix'=>'<div id="red_red_fuentes_filtro_botones">');
    $form['file_buscar_fs']['reset']=array('#type'=>'submit','#value'=>t('Clean'),'#name'=>'limpiar','#suffix'=>'</div>');
    return $form;
}
function red_compartir_fuentes_copy_get_filter_value($f){
    return hontza_get_gestion_usuarios_filter_value($f,'red_compartir_fuentes_copy');
}
function red_compartir_fuentes_copy_filtro_form_submit(&$form, &$form_state){
    if(isset($form_state['clicked_button']) && !empty($form_state['clicked_button'])){
        $name=$form_state['clicked_button']['#name'];
        if(strcmp($name,'limpiar')==0){
            if(isset($_SESSION['red_compartir_fuentes_copy']['filter']) && !empty($_SESSION['red_compartir_fuentes_copy']['filter'])){
                unset($_SESSION['red_compartir_fuentes_copy']['filter']);
            }
        }else{
            $_SESSION['red_compartir_fuentes_copy']['filter']=array();
            $fields=red_compartir_fuentes_copy_filter_fields();
            if(count($fields)>0){
                foreach($fields as $i=>$f){
                    if($f=='region'){
                        $v=red_regiones_get_region_post_value();
                    }else{
                        $v=$form_state['values'][$f];
                    }
                    //
                    if(!empty($v)){
                        $_SESSION['red_compartir_fuentes_copy']['filter'][$f]=$v;
                    }
                }
            }
        }
    } 
}
function red_compartir_copiar_fuentes_servidor_form_callback(){
    drupal_set_title(t('Download Sources'));
    drupal_access_denied();
    exit();
    red_compartir_grupo_is_grupo_red_alerta_access_denied();    
    $output=red_compartir_fuentes_copy_header().drupal_get_form('red_compartir_copiar_fuentes_servidor_form');
    return $output;
}
function red_compartir_fuentes_set_copy_filtro_get_contents(){
    $result=array();        
            $fields=red_compartir_fuentes_copy_filter_fields();
            if(count($fields)>0){
                foreach($fields as $i=>$f){
                    $v=red_compartir_fuentes_copy_get_filter_value($f);
                    if(!empty($v)){
                        $result[$f]=$v;
                    }
                }
            }
    if(!empty($result)){
        return base64_encode(serialize($result));
    }
    return '';
}
function red_compartir_fuentes_copy_define_origin_options(){
    return my_get_tipo_fuente_options(0);
}
function red_compartir_fuentes_copy_define_subdomain_options(){
    if(isset($_SESSION['red_alerta_subdomain_options']) && !empty($_SESSION['red_alerta_subdomain_options'])){
        return $_SESSION['red_alerta_subdomain_options'];
    }else{
        $result=array();
        $url=red_compartir_define_redalerta_servidor_url();
        $url.='/red_servidor/red_servidor_subdomain_options_get_contents';
        $content=file_get_contents($url);
        $subdomain_options=unserialize($content);
        $_SESSION['red_alerta_subdomain_options']=$subdomain_options;
        return $subdomain_options;
    }     
}
function red_compartir_fuentes_copy_is_filter_activated(){
    $filter_fields=red_compartir_fuentes_copy_filter_fields();
    if(!empty($filter_fields)){
        foreach($filter_fields as $i=>$f){
            $v=red_compartir_fuentes_copy_get_filter_value($f);
            if(!empty($v)){
                return 1;
            }
        }    
    }
    return 0;
}
function red_compartir_fuente_get_user_local_get_contents_callback(){
    $output='';    
    $uid=arg(2);
    if(!empty($uid)){
        $user_local=user_load($uid);
        if(isset($user_local->uid) && !empty($user_local->uid)){
            require_once('sites/all/modules/user/user.pages.inc');
            $user_local->user_html=red_compartir_user_view($user_local);
            $user_local->user_html=base64_encode($user_local->user_html);
            unset($user_local->pass);
            $output=serialize($user_local);
            $output=base64_encode($output);
            $output=red_compartir_grupo_encrypt_text($output);
        }
    }
    print $output;
    exit();
}
function red_compartir_fuente_get_user_name($r,$is_canal=0){
    if(isset($r->user_local) && isset($r->user_local->name)){
        //return $r->user_local->name;
        if($is_canal){
            $url='red_compartir/red_compartir_view_user_canal_servidor/'.$r->id;
        }else{
            $url='red_compartir/red_compartir_view_user_fuente_servidor/'.$r->id;
        }
        return l($r->user_local->name,$url);
    }
    return '';
}
function red_compartir_fuente_get_rating_en_filas($node){
    return red_fuente_get_rating_en_filas($node);
}
function red_compartir_fuente_get_description($node,$url=''){
    return red_fuente_get_description($node,0,1,$url);
}
function red_compartir_fuente_get_resumen($node,$len=150){
      return red_fuente_get_resumen($node,$len);
}
function red_compartir_fuente_get_numero_de_descargas_get_contents_callback(){
    $nid=arg(2);
    //print $nid;
    $fuente_descargados_array=red_compartir_get_fuente_descargados_array($nid);
    print count($fuente_descargados_array);
    exit();
}
function red_compartir_view_fuente_servidor_callback(){
    $id=arg(2);
    if(isset($_SESSION['red_compartir_copiar_fuentes_servidor'][$id])){
            $row=$_SESSION['red_compartir_copiar_fuentes_servidor'][$id];
            drupal_set_title($row->fuente_title);
            $node_view=$row->node_view;
            //print $node_view;exit();
            $node_view=red_compartir_disable_node_view_link($node_view,$row);
            $node_view=red_compartir_translate_view_fuente_servidor($node_view,$row);
            $output=$node_view;            
            $destination='red_compartir/red_compartir_copiar_fuentes_servidor';            
            $output.=l(t('Return'),$destination);
            return $output;
    }
    return '';
}
function red_compartir_view_user_fuente_servidor_callback(){
    $id=arg(2);    
    if(isset($_SESSION['red_compartir_copiar_fuentes_servidor'][$id])){            
            $user_html=$_SESSION['red_compartir_copiar_fuentes_servidor'][$id]->user_local->user_html;
            drupal_set_title($_SESSION['red_compartir_copiar_fuentes_servidor'][$id]->user_local->name);
            $user_html=base64_decode($user_html);
            $output=$user_html;            
            //$output=red_compartir_get_user_html_compartidor_de_la_fuente($_SESSION['red_compartir_copiar_fuentes_servidor'][$id]);
            $destination='red_compartir/red_compartir_copiar_fuentes_servidor';            
            $output.=l(t('Return'),$destination);
            return $output;
    }
    drupal_set_title('User');
    return '';
}
function red_compartir_fuente_get_region($node){
    if(isset($node->field_fuente_region) && isset($node->field_fuente_region[0]) && isset($node->field_fuente_region[0]['value'])){
        return $node->field_fuente_region[0]['value'];
    }
    return '';
}
function red_compartir_disable_node_view_link($node_view,$row=''){
    $result=$node_view;
    $pos=strpos($result,'<h2><a');
    if($pos===FALSE){
        return $result;
    }else{
        $find_end='</a></h2>';
        $pos_end=strpos($result,$find_end);
        $len=($pos_end-$pos)+strlen($find_end);
        $s=substr($result,$pos,$len);
        $s=strip_tags($s);
        //$result=substr($result,0,$pos).'<h2><b>'.$s.'</b></h2>'.substr($result,$pos_end+strlen($find_end));
        $result=substr($result,0,$pos).substr($result,$pos_end+strlen($find_end));
    }
    $replace='<div class="n-opciones-item" style="display:none;">';
    $result=str_replace('<div class="n-opciones-item">',$replace,$result);
    $pos_opciones=strpos($result,$replace);
    if($pos_opciones===FALSE){
        return $result;
    }else{
        $pre=substr($result,0,$pos_opciones);
        $result=$pre.'<div class="n-opciones-item">'.red_compartir_define_servidor_fuentes_opciones_item($row).'</div>'.substr($result,$pos_opciones);
    }
    return $result;
}
function red_compartir_fuente_is_con_datos_rellenados($node){
        $params=array();
        $texto=hontza_content_full_text($node);
        $texto=trim(strip_tags($texto));
        if(empty($texto)){
            return 0;
        }
        $region=red_compartir_fuente_get_region($node);
        if(empty($region)){
            return 0;
        }
        return 1;
}
function red_compartir_fuente_supercanal_form_alter(&$form,&$form_state,$form_id){
    /*$param3=arg(3);
    if(!empty($param3) && $param3=='no_se_puede_compartir'){
        form_set_error('generico','No puedes compartir la fuente, porque tienes datos sin rellenar');
        $texto=hontza_content_full_text($node);
        $texto=trim(strip_tags($texto));
        if(empty($texto)){
            form_set_error('body','body:sin rellenar');
        }
    }*/
}
function red_compartir_get_user_html_compartidor_de_la_fuente($row){
    $user_local=red_compartir_fuente_get_user_local($row);
    if($user_local->user_html){
        return base64_decode($user_local->user_html);
    }
    return '';
}
function red_compartir_fuente_get_user_local($row){
    if(isset($row->id) && !empty($row->id)){
        $subdominio=red_get_subdominio_by_sareko_id($row->sareko_id);
        if(!empty($subdominio)){
            $url='http://'.$subdominio.'/red_compartir/red_compartir_fuente_get_user_local_get_contents/'.$row->local_uid;
            $content=file_get_contents($url);
            if(!empty($content)){
                $content=red_compartir_grupo_decrypt_text($content);
                $content=base64_decode($content);
                $user_local=unserialize($content);
                return $user_local;
            }
        }
    }
    $my_result=new stdClass();
    return $my_result;
}
function red_compartir_fuentes_copy_define_numero_de_descargas_options(){
    return red_define_numero_de_descargas_options();
}
function red_compartir_user_compartir_autocomplete_callback(){
    $matches==array();
    $find=arg(2);
    if(!empty($find)){
        if(isset($_SESSION['user_autocomplete_fuentes']['user_autocomplete_options'])){
            $options=$_SESSION['user_autocomplete_fuentes']['user_autocomplete_options'];        
            if(!empty($options)){
                foreach($options as $key=>$user_name){
                    $pos=strpos($user_name,$find);
                    if($pos===FALSE){
                        continue;
                    }else{
                        $matches[$key]=$user_name;
                    }
                }
            }
        }
    }    
    drupal_json($matches);
}
function red_compartir_get_grupo_fuentes(){
    $grupos=red_compartir_get_grupos();
    if(count($grupos)>0){
        foreach($grupos as $i=>$r){
            if($r->nid==RED_ALERTA_GRUPO_SHARED_NID){
                return $r;
            }
        }
        foreach($grupos as $i=>$r){
            if($r->purl=='test'){
                return $r;
            }
        }
        //simulando
        if(hontza_is_sareko_id('LOKALA')){
            if($r->purl=='pr'){
                return $r;
            }
        }
        return $grupos[0];
    }
    return '';
}
function red_compartir_get_grupos(){
    $result=array();
    $sql='SELECT * FROM {node} n WHERE n.type="grupo"';
    $res=db_query($sql);
    while($row=db_fetch_object($res)){
        $result[]=node_load($row->nid);
    }
    return $result;
}
function red_compartir_get_user_local_by_uid_get_contents_callback(){
    $uid=arg(2);
    $my_user=user_load($uid);
    $content=red_compartir_prepare_user_enviar($my_user);
    print $content;
    exit();
}
function red_compartir_prepare_user_enviar($my_user){
    if(isset($my_user->uid) && !empty($my_user->uid)){
        $user_enviar=new stdClass();
        $user_enviar->uid=$my_user->uid;
        $user_enviar->name=$my_user->name;
        $user_enviar->mail=$my_user->mail;
        //
        $result=base64_encode(serialize($user_enviar));
        $result=red_compartir_grupo_encrypt_text($result);
        $result=base64_encode($result);
        return $result;
    }
    return '';
}
function red_compartir_fuente_contar_descargado($fuente_servidor){
    global $user;
    $result=array();
    $result['fuente_servidor']=new stdClass();
    $result['fuente_servidor']->nid=$fuente_servidor->nid;
    $result['fuente_servidor']->vid=$fuente_servidor->vid;
    //
    $result['user_local']=red_compartir_prepare_user_enviar($user);
    $result_post=base64_encode(serialize($result));
    $result_post=red_compartir_grupo_encrypt_text($result_post);
    $result_post=base64_encode($result_post);
    $postdata=array();
    $postdata['fuente_contar_numero_de_descargas']=$result_post;
    $url=red_compartir_define_redalerta_servidor_url();
    $url.='/red_servidor/contar_fuente_numero_de_descargas';
    red_compartir_fuente_contar_numero_de_descargas_postapi($url,$postdata);
}
function red_compartir_fuente_contar_numero_de_descargas_postapi($url,$postdata)
{
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_RETURNTRANSFER,TRUE);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_POST, 1);
    curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query( $postdata ) );
    $data=curl_exec($curl);
    $result=unserialize(trim($data));
    curl_close($curl);    
    if(isset($result['ok']) && !empty($result['ok']) && $result['ok']=='ok'){
        return 'ok';
    }else{
        echo print_r($result,1);
        exit();
    }
    return '';
}
function red_compartir_fuente_existe_en_el_servidor($node){
   if($node->type=='supercanal'){
        $result=array();
        $result['fuente']=new stdClass();
        $result['fuente']->local_nid=$node->nid;
        $result['fuente']->type=$node->type;
        $result['fuente']->title=$node->title;
        $result['fuente']->yahoo_pipe_id='';
        if(isset($node->field_supercanal_fuente[0]['value'])){
            $result['fuente']->yahoo_pipe_id=$node->field_supercanal_fuente[0]['value'];
        }
        $result_post=base64_encode(serialize($result));
        $result_post=red_compartir_grupo_encrypt_text($result_post);
        $result_post=base64_encode($result_post);
        $postdata=array();
        $postdata['fuente']=$result_post;
        $url=red_compartir_define_redalerta_servidor_url();
        $url.='/red_servidor/fuente_existe_en_el_servidor';
        $existe=red_compartir_fuente_existe_en_el_servidor_postapi($url,$postdata);
        return $existe;
   }
   return 0;
}
function red_compartir_fuente_existe_en_el_servidor_postapi($url,$postdata)
{
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_RETURNTRANSFER,TRUE);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_POST, 1);
    curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query( $postdata ) );
    $data=curl_exec($curl);
    $result=unserialize(trim($data));
    curl_close($curl);
    /*echo print_r($result,1);
    exit();*/        
    if(isset($result['ok']) && !empty($result['ok'])){
        return $result['existe'];
    }else{
        /*echo print_r($result,1);
        exit();*/
        return 0;
    }
    return 0;
}
function red_compartir_delete_red_compartir_fuente(&$node){
    if(in_array($node->type,array('supercanal','fuentedapper'))){
        db_query('DELETE FROM {red_compartir_fuente} WHERE nid=%d',$node->nid);        
    }
}
function red_compartir_delete_red_compartir_canal(&$node){
    if(in_array($node->type,array('canal_de_supercanal','canal_de_yql'))){
        db_query('DELETE FROM {red_compartir_canal} WHERE nid=%d',$node->nid);        
    }
}
function red_compartir_define_servidor_fuentes_opciones_item($row){
    $html=array();
    if($row->sareko_id!=_SAREKO_ID){
        $html[]='<div class="item-descargar-fuente">';
        $label=t('Download');
        $html[]=l('','red_compartir/'.$row->id.'/red_compartir_copiar_fuente_del_servidor',array('attributes'=>array('title'=>$label)));
        $html[]='</div>';
    }
    return implode($html,'');
}
function red_compartir_copiar_fuente_del_servidor_callback(){
    $id=arg(1);
    if(isset($_SESSION['red_compartir_copiar_fuentes_servidor'][$id])){    
        $row=$_SESSION['red_compartir_copiar_fuentes_servidor'][$id];
        if(isset($row->nid) && !empty($row->nid)){    
            $form=array();
            $form_state=array();
            $form_state['clicked_button']=array();
            $form_state['clicked_button']['#name']='my_submit';
            $_REQUEST['copiar_fuente']=array();
            $_REQUEST['copiar_fuente'][$row->nid]=1;
            red_compartir_copiar_fuentes_servidor_form_submit($form,$form_state);
        }    
    }
    return '';
}
function red_compartir_navegar_menu(){
    return '';
    global $user;
    $html=array();
    $html[]='<div class="tab-wrapper clearfix primary-only">';
    $html[]='<div id="tabs-primary" class="tabs primary">';
    $html[]='<ul>';
    $html[]='<li class="red_publica_menu_li'.red_compartir_get_menu_class_active('red_compartir/red_compartir_copiar_fuentes_servidor').'"'.'>'.l(t('Download Sources'),'red_compartir/red_compartir_copiar_fuentes_servidor').'</li>';
    $html[]='<li class="red_publica_menu_li'.red_compartir_get_menu_class_active('red_compartir/red_compartir_copiar_canales_servidor').'"'.'>'.l(t('Download Channels'),'red_compartir/red_compartir_copiar_canales_servidor').'</li>';
    $html[]='<li class="red_publica_menu_li'.red_compartir_get_menu_class_active('red_compartir/red_compartir_copiar_facilitadores_servidor').'"'.'>'.l(t('Download Facilitators'),'red_compartir/red_compartir_copiar_facilitadores_servidor').'</li>';
    
    $html[]='<li class="red_publica_menu_li'.red_compartir_get_menu_class_active('red/fuentes-pipes/todas').'"'.'>'.l(t('Share Sources'),'red/fuentes-pipes/todas').'</li>';
    $html[]='<li class="red_publica_menu_li'.red_compartir_get_menu_class_active('red/canales/todas').'"'.'>'.l(t('Share Channels'),'red/canales/todas').'</li>';
    $html[]='<li class="red_publica_menu_li'.red_compartir_get_menu_class_active('red/facilitadores/todas').'"'.'>'.l(t('Share Facilitators'),'red/facilitadores/todas').'</li>';
    
    $html[]='</ul>';
    $html[]='</div>';
    $html[]='</div>';
    //
    $output=implode('',$html);
    return $output;
}
function red_compartir_get_menu_class_active($konp){
    $ok=0;
    $param0=arg(0);
    if(!empty($param0)){
        $my_array=explode('/',$konp);
        if(isset($my_array[0]) && !empty($my_array[0])){
            if($param0==$my_array[0]){
                $param1=arg(1);
                if(!empty($param1)){
                    if(isset($my_array[1]) && !empty($my_array[1])){
                        if($param1==$my_array[1]){
                            $param2=arg(2);
                            if(!empty($param2)){
                                if(isset($my_array[2]) && !empty($my_array[2])){
                                    if($param2==$my_array[2]){
                                        $ok=1;
                                    }
                                }
                            }else{
                                $ok=1;
                            }
                        }    
                    }
                }
            }
        }
    }    
    if($ok){
        return ' active';
    }    
    return '';
}
function red_compartir_borrarme_del_servidor_form(){
    drupal_set_title(t('Are you sure?'));
    $form=array();
    $form['my_msg']=array(
        '#value'=>red_compartir_define_borrarme_del_servidor_msg(),
    );
    $form['delete_btn']=array(
        '#name'=>'borrarme_del_servidor_btn',
        '#type'=>'submit',
        '#value'=>t('Delete'),
    );
    $url_volver='';
    $form['volver_btn']['#value']=l(t('Cancel'),$url_volver,array('attributes'=>'back_left'));
    return $form;
}
function red_compartir_define_borrarme_del_servidor_msg(){
    $html=array();
    $html[]='<p>'.t('You will not have access to the server or any of their groups').'.</p>';
    return implode('',$html);
}
function red_compartir_borrarme_del_servidor_form_submit(&$form, &$form_state){
    if(isset($form_state['clicked_button']) && !empty($form_state['clicked_button']) && $form_state['clicked_button']['#name']=='borrarme_del_servidor_btn'){
        red_compartir_borrarme_del_servidor();
        drupal_set_message('Te has borrado del servidor');
    }
    drupal_goto('');
}
function red_compartir_borrarme_del_servidor(){
    global $user;
    $my_user=clone $user;
    if(hontza_is_sareko_user(1,$my_user)){
            $url='';
            $user_array=array();
            $user_array[0]=$my_user;
            $user_array=red_compartir_grupo_prepare_user_enviar_array($user_array,0);
            $user_enviar=serialize($user_array[0]);            
            $user_enviar=red_compartir_grupo_encrypt_text($user_enviar);
            $postdata=array();
            $postdata['user_enviar']=$user_enviar;
            //$postdata=http_build_query($postdata);
            //
        if(hontza_is_red_hoja()){    
            $url=red_compartir_define_redalerta_servidor_url().'/red_servidor/borrarme_del_servidor';
            $content=red_compartir_grupo_postapi($url,$postdata,1);            
            drupal_set_message(t('User %username has been deleted from the server',array('%username'=>$my_user->name)));
            drupal_goto('user');
        }//else if(hontza_is_servidor_red_alerta()){
            /*if(hontza_is_servidor_red_alerta()){
                $subdominio_array=red_servidor_grupo_get_subdominio_array($my_user);   
            }else{
                $subdominio_array=red_compartir_grupo_get_subdominio_array($my_user);            
            }            
            if(!empty($subdominio_array)){
                foreach($subdominio_array as $i=>$subdominio){
                    if(red_compartir_grupo_is_apply_user_change($subdominio)){
                        $url='http://'.$subdominio.'/red_compartir/user_change';
                        $content=red_compartir_grupo_postapi($url,$postdata);
                    }
                }
            }*/
        //}        
    }
}
function red_compartir_translate_view_fuente_servidor($node_view,$row){
    //if(user_access('root')){
        $my_array=array('Creation Date','Classifications','Summary','Source','Arguments','Description of parameters','Quality','Coverage','Update','Apply Alchemy', 
        'Apply OpenCalais','Apply FulltextRSSFeed','Languages','Update frequency','Main Language','URL Address','Country or Region','Groups'); 
        //
        $result=$node_view;
        if(!empty($my_array)){
            foreach($my_array as $i=>$f){
                $result=str_replace($f.':',t($f).':',$result);
            }
        }
        /*if(user_access('root')){
            $result=red_compartir_translate_clasificaciones_view_fuente_servidor($result,$row);
        }*/
        return $result;
    //}
    //return $node_view;
}
function red_compartir_translate_clasificaciones_view_fuente_servidor($result_in,$row){
    global $language;
    $result=$result_in;
    $sep='<div class="field field-type-text field-field-supercanal-clasificaciones" style="float:left;clear:both;">';
    $pos=strpos($result,$sep);
    $end=substr($result,$pos+strlen($sep));
    $sep_end='</ul></div>';
    $pos_end=strpos($end,$sep_end);
    $string=substr($end,0,$pos_end);
    //
    if(isset($row->taxonomy_lang[$language->language])){
        $html=array();
        $html[]='<div class="field-items">';			
        $html[]='<div class="field-item odd">';			
	$html[]='<div class="field-label-inline-first" style="float:left;">';
	//intelsat-2015
        //$html[]=t('Classifications').'&nbsp;';
	$html[]=t('Type').'&nbsp;';        
        $html[]='</div>';					
	$html[]='<div class="terms terms-inline" style="margin-top:0px;"><ul>';
        //        
        $term_array=$row->taxonomy_lang[$language->language];
        if(!empty($term_array)){
            foreach($term_array as $i=>$term){
                //$html[]='<li class="taxonomy_term_">';
            }
        }
    }
    return $result;
}
//intelsat-2015
function red_compartir_fuente_descargar_path($file_name_in='descargar_fuente'){
    return 'sites/all/themes/buho/images/icons/'.$file_name_in.'.png';
}
//intelsat-2015
function red_compartir_view_fuente_local_callback(){
    $nid=arg(2);
    $node=node_load($nid);
    drupal_set_title(hontza_get_title_fuente_simbolo_img().$node->title);
    return node_view($node);
}